const { query } = require('../config/database');

async function seedJftModelPaper07() {
  try {
    const title = 'JFT-Basic Official Model Paper 07 (60 Minutes)';
    const existingExam = await query.get("SELECT id FROM exams WHERE title = ?", [title]);
    let examId;

    if (existingExam) {
      examId = existingExam.id;
      console.log(`Seeding JFT Model Paper 07 (Exam ID: ${examId})...`);
      await query.run(`
        UPDATE exams 
        SET description = 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper 07 (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [examId]);
      await query.run("DELETE FROM questions WHERE exam_id = ?", [examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (1, ?, 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper 07 (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.', 60, 200, 1)
      `, [title]);
      examId = res.id;
      console.log(`Created JFT Model Paper 07 (Exam ID: ${examId})`);
    }

    const questions = [
      // ==========================================
      // SECTION 1: Script & Vocabulary (文字・語彙 - Q01 to Q15)
      // ==========================================
      {
        order_num: 1,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q01.jpg',
        audio_url: null,
        option_a: 'トンネル',
        option_b: 'トラック',
        option_c: 'トラク',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'トラック (Truck / ලොරිය/ට්‍රක් රථය).'
      },
      {
        order_num: 2,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q02.jpg',
        audio_url: null,
        option_a: 'けっこんします',
        option_b: 'けんかします',
        option_c: 'あんないします',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'けっこんします (To get married / විවාහ වෙනවා).'
      },
      {
        order_num: 3,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q03.jpg',
        audio_url: null,
        option_a: 'いぬ',
        option_b: 'りす',
        option_c: 'ねこ',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ねこ (Cat / පූසා).'
      },
      {
        order_num: 4,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q04.jpg',
        audio_url: null,
        option_a: 'せんたくします',
        option_b: 'そうだんします',
        option_c: 'そうじします',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'そうじします (To clean / පිරිසිදු කරනවා).'
      },
      {
        order_num: 5,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q05.jpg',
        audio_url: null,
        option_a: 'テレビ',
        option_b: 'れいぞうこ',
        option_c: 'せんたっき',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'テレビ (Television / රූපවාහිනිය).'
      },
      {
        order_num: 6,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the phrase that fits the blank the most.)\n\nとしょかんは＿＿＿＿たてものです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'これ',
        option_b: 'この',
        option_c: 'ここ',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'このたてもの (This building / මේ ගොඩනැගිල්ල. 連体詞「この」+ 名詞).'
      },
      {
        order_num: 7,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\nあなたはネクタイが＿＿＿＿ありますか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q07.jpg',
        audio_url: null,
        option_a: 'なんまい',
        option_b: 'なんだい',
        option_c: 'なんさつ',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'なんまい (How many thin/flat items like neckties / නෙක්ටයි ගණන් කිරීමේදී 枚 [まい] භාවිතා වේ).'
      },
      {
        order_num: 8,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\nテストはあまり＿＿＿＿です。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q08.jpg',
        audio_url: null,
        option_a: 'やさしかった',
        option_b: 'かんたん',
        option_c: 'やさしくなかった',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'あまり + 否定 -> あまりやさしくなかったです (Was not very easy / එතරම් පහසු වූයේ නැත).'
      },
      {
        order_num: 9,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\nデパートで買い物を＿＿＿＿。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q09.jpg',
        audio_url: null,
        option_a: 'とりました',
        option_b: 'すわりました',
        option_c: '買いました',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'デパートで買い物を買いました/しました (Did shopping / සාප්පු සවාරි කළා).'
      },
      {
        order_num: 10,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\n＿＿＿＿テレビを見ました。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q10.jpg',
        audio_url: null,
        option_a: '1時間半時間',
        option_b: '1時半時間',
        option_c: '1時間半',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '1時間半 (1 and a half hours / පැය එකහමාරක්).'
      },
      {
        order_num: 11,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined kanji word in hiragana.? Choose the correct one.\n\nお【誕生日】はいつですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'たんじょうび',
        option_b: 'おいくつ',
        option_c: 'たんじょび',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '誕生日 (たんじょうび - Birthday / උපන්දිනය).'
      },
      {
        order_num: 12,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined kanji word in hiragana.? Choose the correct one.\n\n毎朝【七時】におきます。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'はちじ',
        option_b: 'しちじ',
        option_c: 'ななじ',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '七時 (しちじ - 7 o\'clock / හතයි).'
      },
      {
        order_num: 13,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined kanji word in hiragana.? Choose the correct one.\n\n【姉】はなま魚がきらいです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'あに',
        option_b: 'いもうと',
        option_c: 'あね',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '姉 (あね - Elder sister / අක්කා).'
      },
      {
        order_num: 14,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined kanji word in hiragana.? Choose the correct one.\n\n先生は【親切】な人です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'やさしい',
        option_b: 'しんせつな',
        option_c: 'たいせつな',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '親切 (しんせつ - Kind / කාරුණික).'
      },
      {
        order_num: 15,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined kanji word in hiragana.? Choose the correct one.\n\n来週のかようびともだちと【旅行】へ行きます。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'りょこう',
        option_b: 'りょこ',
        option_c: 'りょうこう',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '旅行 (りょこう - Trip / Travel / සංචාරය).'
      },

      // ==========================================
      // SECTION 2: Conversation & Expression (会話・表現 - Q16 to Q30)
      // ==========================================
      {
        order_num: 16,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\nリーさんは家族＿＿＿＿シンガポールへ行きました。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q16.jpg',
        audio_url: null,
        option_a: 'といっしょに',
        option_b: 'にいしょに',
        option_c: 'がいっしょに',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '家族といっしょに (Together with family / පවුලේ අය සමඟ එකට).'
      },
      {
        order_num: 17,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\n明日はプレゼントを＿＿＿＿にデパートへ行きます。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '買う',
        option_b: '買い',
        option_c: '買え',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '動詞マス形＋に行きます -> 買いに行きます (Go to buy / මිලදී ගැනීමට යනවා).'
      },
      {
        order_num: 18,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\n去年の冬休みはあまり＿＿＿＿です。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q18.jpg',
        audio_url: null,
        option_a: 'ながく',
        option_b: 'ながくなかった',
        option_c: 'ながい',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'あまり + 過去否定 -> ながくなかったです (Was not very long / එතරම් දිගු වූයේ නැත).'
      },
      {
        order_num: 19,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\n田中さんはコーヒーを飲みません。お茶＿＿飲みません。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'は',
        option_b: 'も',
        option_c: 'が',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'お茶も飲みません (Does not drink tea either / තේ ද බොන්නේ නැත).'
      },
      {
        order_num: 20,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\n東京からおおさかまで＿＿＿＿です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '3時ぐらい',
        option_b: '3時ごろ',
        option_c: '3時間ぐらい',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '3時間ぐらい (About 3 hours duration / පැය 3ක් පමණ කාලයක්).'
      },
      {
        order_num: 21,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the phrase that fits the most.)\n\nA: ピアノがお上手ですね。れんしゅうはいつごろはじめたんですか。\nB: 去年の 2月＿＿＿＿はじめました。まだへたです。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q21.jpg',
        audio_url: null,
        option_a: 'うしろ',
        option_b: 'あと',
        option_c: 'まえ',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'まえ (Ago / පෙර).'
      },
      {
        order_num: 22,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the phrase that fits the most.)\n\nA: 明日、パーティー行く？\nB: うん。行くよ。\nA: マリアさんは来るかな。\nB: いそがしいと言っていたから＿＿＿＿と思うよ。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '来ます',
        option_b: '来ない',
        option_c: '来ました',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '普通形 + と思う -> 来ないと思うよ (I think she will not come / ඇය එන්නේ නැති වෙයි කියා සිතනවා).'
      },
      {
        order_num: 23,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the phrase that fits the most.)\n\nA: 今日はかさをもっていったほうがいいですよ。\nB: どうして。\nA: 雨が＿＿＿＿です。テレビで見ました。\nB: わかりました。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q23.jpg',
        audio_url: null,
        option_a: 'ふります',
        option_b: 'ふるそう',
        option_c: 'ふらない',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '伝聞の「〜そう」-> ふるそうです (I heard it will rain / වැස්ස වසිනු ඇතැයි ආරංචියි/පැවසේ).'
      },
      {
        order_num: 24,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the phrase that fits the most.)\n\nA: 私が＿＿＿＿料理です。\nB: わぁ、おいしそうですね。いただきます。\nA: どうですか。\nB: とてもおいしいです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'つくった',
        option_b: 'つくりました',
        option_c: 'つくります',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '名詞修飾 -> 私がつくった料理 (The dish that I made / මම හදපු කෑම).'
      },
      {
        order_num: 25,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the phrase that fits the most.)\n\nA: 昨日シャツを買いました。\nB: なんまい買いましたか。\nA: 2まい買いました。\nB: ＿＿＿＿＿＿＿＿。\nA: 2まいで 5000円でした。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q25.jpg',
        audio_url: null,
        option_a: 'いつでしたか',
        option_b: 'いくらになりましたか',
        option_c: 'なんまいでしたか',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'いくらになりましたか (How much was it? / කීයක් වුණාද?).'
      },
      {
        order_num: 26,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄 (26) に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the best phrase for 26.)\n\nたなか: はるこさん、これは日本のおかしです。(26)＿＿＿＿。\nはるこ: どうもうありがとう。ああ、おいしいですね。\nたなか: やまださんも、どうぞ。\nやまだ: いえ、私は(27)＿＿＿＿。私はおかしを食べません。\nたなか: そうですか。では、やまださん、これを飲みますか。\nやまだ: それは日本のお酒ですね。\nたなか: ええ、どうぞ。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q26_27.jpg',
        audio_url: null,
        option_a: 'どうもうありがとう',
        option_b: 'どうぞ',
        option_c: 'あげましょう',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'どうぞ (Please have some / මෙන්න ගන්න/කන්න).'
      },
      {
        order_num: 27,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄 (27) に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the best phrase for 27.)\n\nたなか: はるこさん、これは日本のおかしです。(26)どうぞ。\nはるこ: どうもうありがとう。ああ、おいしいですね。\nたなか: やまださんも、どうぞ。\nやまだ: いえ、私は(27)＿＿＿＿。私はおかしを食べません。\nたなか: そうですか。では、やまださん、これを飲みますか。\nやまだ: それは日本のお酒ですね。\nたなか: ええ、どうぞ。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q26_27.jpg',
        audio_url: null,
        option_a: 'けっこうです',
        option_b: 'いいですね',
        option_c: '食べましょう',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'いえ、私はけっこうです (No thank you, I am fine / නැහැ මට කමක් නෑ/එපා).'
      },
      {
        order_num: 28,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄 (28) に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the best phrase for 28.)\n\nきゃく: (28)＿＿＿＿。\nウェートレス: はい。\nきゃく: ご飯とスープをおねがいします。それは、何のスープですか。\nウェートレス: これは、魚のスープです。これは、とりにくのスープです。\nきゃく: 魚のスープは(29)＿＿＿＿。\nウェートレス: ええ、おいしいです。\nきゃく: では、魚のスープをください。\nウェートレス: (30)＿＿＿＿。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q28_30.jpg',
        audio_url: null,
        option_a: 'はじめまして',
        option_b: 'いらっしゃいませ',
        option_c: 'すみません',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'すみません (Excuse me / වේටර්වරිය කැඳවීමේදී පවසන ආචාර වචනය).'
      },
      {
        order_num: 29,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄 (29) に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the best phrase for 29.)\n\nきゃく: (28)すみません。\nウェートレス: はい。\nきゃく: ご飯とスープをおねがいします。それは、何のスープですか。\nウェートレス: これは、魚のスープです。これは、とりにくのスープです。\nきゃく: 魚のスープは(29)＿＿＿＿。\nウェートレス: ええ、おいしいです。\nきゃく: では、魚のスープをください。\nウェートレス: (30)＿＿＿＿。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q28_30.jpg',
        audio_url: null,
        option_a: 'おいしいですか',
        option_b: 'おいしくないですか',
        option_c: 'おもしろいですか',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'おいしいですか (Is it delicious? / රසවත්ද?).'
      },
      {
        order_num: 30,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄 (30) に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the best phrase for 30.)\n\nきゃく: (28)すみません。\nウェートレス: はい。\nきゃく: ご飯とスープをおねがいします。それは、何のスープですか。\nウェートレス: これは、魚のスープです。これは、とりにくのスープです。\nきゃく: 魚のスープは(29)おいしいですか。\nウェートレス: ええ、おいしいです。\nきゃく: では、魚のスープをください。\nウェートレス: (30)＿＿＿＿。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q28_30.jpg',
        audio_url: null,
        option_a: 'どうもうありがとう',
        option_b: 'かしこまりました',
        option_c: 'またあした',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'かしこまりました (Certainly / Very well / ඇණවුම භාරගැනීමේදී පවසන වචනය).'
      },

      // ==========================================
      // SECTION 3: LISTENING COMPREHENSION (聴解 - Choukai - Q31 to Q45)
      // ==========================================
      {
        order_num: 31,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、イラストの記号 (a, b, c) から正しいものを選んでください。\n\nWhere do they go on day off?\n(休みの日に二人はどこへ行きますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q31.jpg',
        audio_url: '/uploads/audio/jft07_q31.mp3',
        option_a: 'a (公園 / Park)',
        option_b: 'b (ジム / Gym)',
        option_c: 'c (モール / Mall)',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '音声の会話で決定した目的地（c）を選びます。'
      },
      {
        order_num: 32,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、イラストの記号 (a, b, c) から正しいものを選んでください。\n\nHow is the weather today?\n(今日の天気はどうですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q32.jpg',
        audio_url: '/uploads/audio/jft07_q32.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c (雨 / Rain)',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '今日の天気に該当するイラスト（c）を選びます。'
      },
      {
        order_num: 33,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、郵便局の場所を地図 (a, b, c, d) から選んでください。\n\nWhere is the post office located?\n(郵便局はどこにありますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q33.jpg',
        audio_url: '/uploads/audio/jft07_q33.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '道案内で示された郵便局の位置を選びます。'
      },
      {
        order_num: 34,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、イラストの記号 (a, b, c) から正しいものを選んでください。\n\nWhere are they going?\n(二人はどこへ行きますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q34.jpg',
        audio_url: '/uploads/audio/jft07_q34.mp3',
        option_a: 'a (会社 / Company)',
        option_b: 'b (受付 / Reception)',
        option_c: 'c (改札口 / Ticket gate)',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '二人が向かう場所（c: 改札口）を選びます。'
      },
      {
        order_num: 35,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題 - 35/36共通】音声を聞いて、正しい時間を選んでください。\n\nWhat time will they meet?\n(二人は何時に会いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q35_36.jpg',
        audio_url: '/uploads/audio/jft07_q35.mp3',
        option_a: '7.00',
        option_b: '6.00',
        option_c: '6.30',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '約束の待ち合わせ時間は「6時30分（6.30）」です。'
      },
      {
        order_num: 36,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題 - 35/36共通】音声を聞いて、正しい場所を選んでください。\n\nWhere did they decide to meet?\n(二人はどこで会うことに決めましたか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q35_36.jpg',
        audio_url: '/uploads/audio/jft07_q36.mp3',
        option_a: 'えき',
        option_b: 'えきのかいさつで',
        option_c: 'いえ',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '待ち合わせ場所に決めた「駅の改札（えきのかいさつで）」が正解です。'
      },
      {
        order_num: 37,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題 - 37/38共通】音声を聞いて、日本語を勉強した場所を選んでください。\n\nWhere did they learn Japanese?\n(日本語をどこで勉強しましたか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q37_38.jpg',
        audio_url: '/uploads/audio/jft07_q37.mp3',
        option_a: 'a (独学 / Self-study)',
        option_b: 'b (教室 / Classroom)',
        option_c: 'c (オンライン / Online)',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '日本語を学んだ方法・場所（b: 教室）を選びます。'
      },
      {
        order_num: 38,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題 - 37/38共通】音声を聞いて、勉強した期間を選んでください。\n\nHow long have you been studying?\n(どのくらい勉強していますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q37_38.jpg',
        audio_url: '/uploads/audio/jft07_q38.mp3',
        option_a: 'いちねん (1年)',
        option_b: 'よねん (4年)',
        option_c: 'にねん (2年)',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '勉強期間は「2年（にねん）」です。'
      },
      {
        order_num: 39,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、二人が話している話題を選んでください。\n\nWhat are they talking about?\n(二人は何について話していますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q39.jpg',
        audio_url: '/uploads/audio/jft07_q39.mp3',
        option_a: 'a (レスリング / Wrestling)',
        option_b: 'b (映画 / Movie)',
        option_c: 'c (動物園のパンダ / Panda)',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '話題になっている内容（b: 映画）を選びます。'
      },
      {
        order_num: 40,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、Joseさんの症状を選んでください。\n\nWhat is Jose\'s health problem?\n(ホセさんの体調はどうですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q40.jpg',
        audio_url: '/uploads/audio/jft07_q40.mp3',
        option_a: 'a (二日酔い / Hangover)',
        option_b: 'b (頭痛 / Headache)',
        option_c: 'c (胃痛・腹痛 / Stomachache)',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ホセさんの訴えている症状（b: 頭痛）を選びます。'
      },
      {
        order_num: 41,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、アドバイスされた内容を選んでください。\n\nWhat was the advice?\n(どのようなアドバイスを受けましたか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q41.jpg',
        audio_url: '/uploads/audio/jft07_q41.mp3',
        option_a: 'a (お風呂に入る / Hot bath)',
        option_b: 'b (温かいお茶を飲む / Hot tea)',
        option_c: 'c (薬・栄養剤を飲む / Medicine drink)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '音声内でアドバイスされた行動（a）を選びます。'
      },
      {
        order_num: 42,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、女性がこれからする行動を選んでください。\n\nWhat will the woman do?\n(女性は何をしますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q42.jpg',
        audio_url: '/uploads/audio/jft07_q42.mp3',
        option_a: 'a (家に帰る / Go home)',
        option_b: 'b (病院に行く / Hospital)',
        option_c: 'c (腰痛の様子を見る / Back pain)',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '女性が取る行動（b: 病院に行く）を選びます。'
      },
      {
        order_num: 43,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、Xuさんが紛失したスマホケースを選んでください。\n\nWhich of the following describes Xu\'s lost smartphone?\n(シュウさんが無くしたスマホはどれですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q43.jpg',
        audio_url: '/uploads/audio/jft07_q43.mp3',
        option_a: 'a (赤いケース・犬)',
        option_b: 'b (茶・グレーケース・犬)',
        option_c: 'c (赤いケース・猫)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '特徴に合致するスマホケース（a: 赤いケースに犬の絵）を選びます。'
      },
      {
        order_num: 44,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、男性が授業を受ける日を選んでください。\n\nWhen will the man take class?\n(男性はいつ授業を受けますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q44.jpg',
        audio_url: '/uploads/audio/jft07_q44.mp3',
        option_a: 'a (7月3日)',
        option_b: 'b (7月17日)',
        option_c: 'c (7月24日)',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'カレンダーで指定された受講日（b: 17日）を選びます。'
      },
      {
        order_num: 45,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、加藤さん (Kato) は誰か選んでください。\n\nWhich person is Kato?\n(加藤さんはどの人ですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q45.jpg',
        audio_url: '/uploads/audio/jft07_q45.mp3',
        option_a: 'a (本棚の前の女性)',
        option_b: 'b (コピー機前の男性)',
        option_c: 'c (机でメモを取る男性)',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '加藤さんの特徴に合致する人物（b）を選びます。'
      },

      // ==========================================
      // SECTION 4: READING COMPREHENSION (読解 - Dokkai - Q46 to Q60)
      // ==========================================
      {
        order_num: 46,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【46/47/48 共通問題】\n私は水曜日に「英語で話す会話」に行っています。この会話は日本人と外国人が 10 人ぐらいいますが、先生はいません。会話のみなさんは英語がじょうずですが、もっとじょうずになりたいと言います。ですから、みんなでいろいろなことを英語を使って言います。今まで、ニュースや旅行の話、お金の話などをしました。歌を歌ったり、スピーチをしたりしたこともあります。私は英語があまりじょうずではありませんが、みなさんがとてもやさしいので、学校で勉強するより、このクラスで英語を話すほうがたのしいです。\n\nこのクラスにどんな人が来ていますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft07_passage_46_48.png',
        audio_url: null,
        option_a: '英語がもっとじょうずになりたい人',
        option_b: '英語がじょうずではない人',
        option_c: '学校で勉強したくない人',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '「会話のみなさんは英語がじょうずですが、もっとじょうずになりたいと言います」とあります。(People who want to become better at English / ඉංග්‍රීසි වඩාත් හොඳින් ඉගෙන ගැනීමට කැමති අය).'
      },
      {
        order_num: 47,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '私はどうして「英語で話し会話」と言うクラスへ行っていますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft07_passage_46_48.png',
        audio_url: null,
        option_a: 'クラスでみんなしんせつでたのしいから',
        option_b: 'クラスはお金ははらわないから',
        option_c: 'クラスでみんな英語をおしえるから',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '「みなさんがとてもやさしいので、学校で勉強するより、このクラスで英語を話すほうがたのしいです」とあります。(Because everyone is kind and fun / සියලු දෙනා කාරුණික හා විනෝදජනක නිසා).'
      },
      {
        order_num: 48,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'ここにあっているものはどれか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft07_passage_46_48.png',
        audio_url: null,
        option_a: '私は英語がじょうずで、みんなとじょうずに英語を話しています',
        option_b: 'このクラスでは先生がおしえています',
        option_c: '人が10人このクラスにいます',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '「日本人と外国人が10人ぐらいいますが、先生はいません」とあります。(There are about 10 people in this class / පුද්ගලයින් 10 දෙනෙක් පමණ සිටිති).'
      },
      {
        order_num: 49,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【49/50/51 共通問題】\n3 か月の前、あたらしい家にひっこしました。1 かいにはだいどころとトイレと私とつまがいっしょに使う部屋があります。2 かいには、子供の部屋が二つあります。今子供は 1 人しかいませんが、来年あかちゃんが生まれます。子供が少ないので、まだ 2 かいの部屋は使っていません。ひっこす前は、父と母と住んでいました。父と母は毎日、子供といっしょにあそびました。子供はよく「おじいさん、おばあさんあそびたい」と言います。それで休みの日はたいてい、子供と父と母に会いに行きます。明日、つまは仕事に、私は父と母の家に行きます。\n\nこの人は今、子供が何人いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft07_passage_49_51.png',
        audio_url: null,
        option_a: '3',
        option_b: '2',
        option_c: '1',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '「今子供は 1 人しかいませんが」とあるため、現在は1人です。(Currently has 1 child / දැනට දරුවන් 1 අයෙක් සිටී).'
      },
      {
        order_num: 50,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'この人は新しい家にひっこす前にどこに住んでいましたか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft07_passage_49_51.png',
        audio_url: null,
        option_a: '男の人の両親と',
        option_b: '女の人の両親と',
        option_c: 'ホテル',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '「ひっこす前は、父と母と住んでいました（私＝語り手の両親）」とあります。(With the man\'s parents / පිරිමියාගේ දෙමව්පියන් සමඟ).'
      },
      {
        order_num: 51,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'どうして明日父と母の家に行きますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft07_passage_49_51.png',
        audio_url: null,
        option_a: '子供は父と母に会いたいからです',
        option_b: 'つまが仕事に行くからです',
        option_c: '父と母は「明日来てください」と言ったからです',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '「明日、つまは仕事に、私は父と母の家に行きます」とあり、妻が仕事に行くため子供を連れて実家に行きます。(Because the wife is going to work / බිරිඳ රැකියාවට යන නිසා).'
      },
      {
        order_num: 52,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【52/53/54 共通問題】\n私はきょうだいがありません。でもいとこがいます。母の妹の子供です。いとこといっしょにいると、知らない人はよく「きょうだいですね」と言います。母とおばは顔がちがいましたが、私といとこはにています。それはおもしろいです。\nおととい、頭がいたかったので、友達とえいがに行きませんでした。友達へのメールに「ごめんなさい」と書きました。でも、昨日友達から「えいがかんいませんでしたか」と言う電話がありました。友達は少しおこっていました。たぶん、それは私のいとこです。私と友達は二人でわらいました。\n\nこの人のおばは母の誰ですか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft07_passage_52_54.png',
        audio_url: null,
        option_a: '母の姉です',
        option_b: '母の妹です',
        option_c: '母のいとこです',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '「母の妹の子供です」とおばは母の妹であることがわかります。(Mother\'s younger sister / මවගේ නංගී).'
      },
      {
        order_num: 53,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '私は何がおもしろいですか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft07_passage_52_54.png',
        audio_url: null,
        option_a: '自分がきょうだいがいないが、母にはきょうだいがいること',
        option_b: '母とおばはにていないが、私といとこはにていること',
        option_c: 'いとこはおばにはにていないが、自分ににていること',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '「母とおばは顔がちがいましたが、私といとこはにています。それはおもしろいです」とあります。(Mother and aunt don\'t look alike, but the cousins look alike / අම්මයි පුංචියි සමාන නැති වුණත් මමයි ඥාති සහෝදරියයි සමාන වීම).'
      },
      {
        order_num: 54,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '友達はどうして私に電話をしましたか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft07_passage_52_54.png',
        audio_url: null,
        option_a: '頭がいたい私が、えいがかんにいたと思ったからです',
        option_b: 'えいがかんの時間をわすれたので、私に聞きたかったからです',
        option_c: '私からのメールを読まなかったからです',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '映画館で私にそっくりないとこを見かけて、私だと勘違いしたため電話してきました。(Saw the look-alike cousin at the cinema and thought it was me / සිනමාහලේදී මම වගේම කෙනෙක්ව දැකලා මම කියලා හිතපු නිසා).'
      },
      {
        order_num: 55,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【55/56/57 共通問題】\n小さいときは、田舎に住んでいました。学校がとおくて大変でしたが、よく学校から帰るとくに、友達とのはらをはしったり、川で泳いだりしました。家におそく帰って来るので、母はおこりましたが、あのころはとてもたのしかったです。\n今、大きな町の会社で働いています。のはらや川がありませんが、お店がたくさんあります。買い物は便利です。母が病気になったので、来月からいっしょに住みます。ここは病院は近いですから、母にも便利です。でも、私はまたのはらや川であそびたいです。\n\n私は小さいころよく何をしましたか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft07_passage_55_57.png',
        audio_url: null,
        option_a: '友達といっしょに行きました',
        option_b: '友達とのはらや川であそびました',
        option_c: '友達の家に行きました',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '「友達とのはらをはしったり、川で泳いだりしました」とあります。(Played in fields and river with friends / යහළුවන් සමඟ කෙත්වතු සහ ගංගාවල සෙල්ලම් කළා).'
      },
      {
        order_num: 56,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '母はどうして大きな町で住みますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft07_passage_55_57.png',
        audio_url: null,
        option_a: '病院は近いからです',
        option_b: '買い物が便利からです',
        option_c: '子供といっしょに住みたいからです',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '「母が病気になったので、来月からいっしょに住みます。ここは病院は近いですから、母にも便利です」とあります。(Because the hospital is close by / රෝහල ආසන්නයේ ඇති නිසා).'
      },
      {
        order_num: 57,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'ここにあっているものはどれか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft07_passage_55_57.png',
        audio_url: null,
        option_a: 'この人は小さいとき、町に住んでいました',
        option_b: '今、この人は小さな田舎の会社で働いています',
        option_c: '小さいとき、学校から家まで帰るとおそくなるので母はおこりました',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '「家におそく帰って来るので、母はおこりましたが」と一致します。(When young, mother got angry when returning home late / කුඩා කාලයේ නිවසට ඒම ප්‍රමාද වූ විට මව කේන්ති ගත්තා).'
      },
      {
        order_num: 58,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【58/59/60 共通問題】\n今日は私の家にいる犬のことを話します。\n黒い犬で名前はノアと言います。ノアは小さいとき、誰かがうちの前においていった犬です。大きいですが、そのときはまだ目が開いていなくて「クーン、クーン」と泣いていました。私はすぐにあたたかい部屋に入れました。はじめは、げんきがありませんでしたが、1 週間ぐらいでとてもげんきになりました。\n小さいときはよく泣きましたが、今は泣きません。\nでも、はしるのが早くて、さんぽのときは大変です。\n\n「ノア」は今どんな犬ですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q58_60.jpg',
        audio_url: null,
        option_a: '黒くて、いつも泣いている犬',
        option_b: '白くて、げんきな犬',
        option_c: '黒くて、げんきな犬',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '「黒い犬で名前はノア... 1週間ぐらいでとてもげんきになりました。今は泣きません」とあります。(Black, energetic dog / කළු, නිරෝගී ක්‍රියාශීලී බල්ලෙක්).'
      },
      {
        order_num: 59,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '「ノア」ははじめてうちに来たときどうでしたか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q58_60.jpg',
        audio_url: null,
        option_a: 'はしるのが大変早かったです',
        option_b: '目が開いていませんでした',
        option_c: 'よく泣いてとてもげんきでした',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '「そのときはまだ目が開いていなくて」とあります。(Its eyes were not open yet / ඒ කාලයේ ඇස් ඇරී තිබුණේ නැත).'
      },
      {
        order_num: 60,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '今ノアとさんぽのとき、大変になるのはどれか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft07_q58_60.jpg',
        audio_url: null,
        option_a: 'ノアはいつも泣いていること',
        option_b: 'ノアははしるのが早いこと',
        option_c: 'ノアは目が開いていないこと',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '「でも、はしるのが早くて、さんぽのときは大変です」とあります。(Because it runs very fast / ඌ ඉතා වේගයෙන් දුවන නිසා).'
      }
    ];

    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, order_num, section_name, question_text, question_type, 
          image_url, audio_url, option_a, option_b, option_c, option_d, 
          correct_option, marks, explanation
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId, q.order_num, q.section_name, q.question_text, q.question_type,
        q.image_url, q.audio_url, q.option_a, q.option_b, q.option_c, q.option_d,
        q.correct_option, q.marks, q.explanation
      ]);
    }

    console.log(`Successfully inserted all 60 questions for JFT Model Paper 07 (Exam ID: ${examId})`);
  } catch (err) {
    console.error('seedJftModelPaper07 error:', err);
  }
}

module.exports = { seedJftModelPaper07 };
