const { query } = require('../config/database');

async function seedJftModelPaper01() {
  try {
    const title = 'JFT-Basic Official Model Paper 01 (60 Minutes)';
    const exam = await query.get("SELECT id FROM exams WHERE id = 1 OR title = ?", [title]);
    
    let examId = 1;
    if (exam) {
      examId = exam.id;
      const countRes = await query.get("SELECT COUNT(*) as count FROM questions WHERE exam_id = ?", [examId]);
      if (countRes && countRes.count >= 60) {
        // Already fully seeded
        return;
      }
      console.log('Seeding full 60 questions for JFT Model Paper 01...');
      await query.run(`
        UPDATE exams 
        SET title = ?,
            description = 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [title, examId]);
      await query.run("DELETE FROM questions WHERE exam_id = ?", [examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (id, course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (1, 1, ?, 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.', 60, 200, 1)
      `, [title]);
      examId = res.id;
    }

    const questions = [
      // Section 1: Script & Vocabulary (文字・語彙 - Q01 to Q15)
      {
        order_num: 1,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q01.jpg',
        audio_url: null,
        option_a: 'いらっしゃる',
        option_b: 'あいさつする',
        option_c: 'プレゼントをあげる',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'あいさつする (To greet / ආචාර කරනවා).'
      },
      {
        order_num: 2,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q02.jpg',
        audio_url: null,
        option_a: 'バス',
        option_b: 'じどうしゃ',
        option_c: 'じてんしゃ',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'じてんしゃ (Bicycle / බයිසිකලය).'
      },
      {
        order_num: 3,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q03.jpg',
        audio_url: null,
        option_a: '書いています',
        option_b: '話しています',
        option_c: 'およいでいます',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '話しています (はなしています - Talking / Speaking).'
      },
      {
        order_num: 4,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q04.jpg',
        audio_url: null,
        option_a: 'こっき',
        option_b: 'こくさい',
        option_c: 'こくせき',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'こっき (国旗 - National Flag / ජාතික කොඩිය).'
      },
      {
        order_num: 5,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q05.jpg',
        audio_url: null,
        option_a: 'たばこをすっています',
        option_b: 'おふろにはいっています',
        option_c: 'おんがくを聞いています',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'おふろにはいっています (Taking a bath / නාන තටාකයේ නාමින් සිටියි).'
      },
      {
        order_num: 6,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q06.jpg',
        audio_url: null,
        option_a: 'あやまります',
        option_b: 'わらいます',
        option_c: 'がんばります',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'あやまります (To apologize / සමාව අයදිනවා).'
      },
      {
        order_num: 7,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q07.jpg',
        audio_url: null,
        option_a: 'しゃしんをとります',
        option_b: 'りょうりを作ります',
        option_c: 'あそびます',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'しゃしんをとります (Take a photo / ඡායාරූපයක් ගන්නවා).'
      },
      {
        order_num: 8,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '帽子（ぼうし）を________。\nイラストを見て正しい動詞を選んでください。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q08.jpg',
        audio_url: null,
        option_a: 'します',
        option_b: 'かぶります',
        option_c: 'きます',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '帽子をかぶります (Wear a hat / තොප්පියක් දමනවා).'
      },
      {
        order_num: 9,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q09.jpg',
        audio_url: null,
        option_a: 'あんないします',
        option_b: 'けいかくします',
        option_c: 'けんかをします',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'けんかをします (Quarrel / Fight / රණ්ඩු වෙනවා).'
      },
      {
        order_num: 10,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined kanji word in hiragana? Choose the correct one.\n\n私の<u>両親</u>はおおさかに住んでいます。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'りょしん',
        option_b: 'りょうしん',
        option_c: 'りようしん',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '両親 (りょうしん - Parents / දෙමාපියන්).'
      },
      {
        order_num: 11,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined kanji word in hiragana? Choose the correct one.\n\n母は<u>買い物</u>が大好きです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'かいだん',
        option_b: 'かうもの',
        option_c: 'かいもの',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '買い物 (かいもの - Shopping / බඩු මිලදී ගැනීම).'
      },
      {
        order_num: 12,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined hiragana word in kanji? Choose the correct one.\n\n明日サッカーの<u>しあい</u>を見に行きませんか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '試験',
        option_b: '試姶',
        option_c: '試合',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'しあい = 試合 (Match / Game / තරගය).'
      },
      {
        order_num: 13,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'Read the sentence and choose the word that fits in blank the most.\n\nすみませんが、<u>　（　）　</u>をあけてください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'マッチ',
        option_b: 'でんき',
        option_c: 'まど',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'まど (窓 - Window / ජනේලය).'
      },
      {
        order_num: 14,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'Read the sentence and choose the word that fits in blank the most.\n\nスリランカではコロンボがいちばん<u>　（　）　</u>町です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ひまな',
        option_b: 'にぎやかな',
        option_c: 'ふるい',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'にぎやかな (Lively / Bustling / වඩාත්ම කාර්යබහුල, ජනාකීර්ණ).'
      },
      {
        order_num: 15,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'Read the sentence and choose the word that fits in blank the most.\n\n私は<u>　（　）　</u>をすいます。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'タバコ',
        option_b: '水',
        option_c: 'お酒',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'タバコをすいます (Smoke cigarettes / දුම්වැටි බොනවා).'
      },

      // Section 2: Conversation & Expression (会話・表現 - Q16 to Q30)
      {
        order_num: 16,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'ご飯を食べる<u>　（　）　</u>には、「いただきます」と言います。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q16.jpg',
        audio_url: null,
        option_a: 'こと',
        option_b: 'もの',
        option_c: 'とき',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '食べる「とき」 (When eating / ආහාර ගන්නා විට).'
      },
      {
        order_num: 17,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '私の部屋にベッドやコンピューターやほんだながあります。ねこが<u>　（　）　</u>。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q17.jpg',
        audio_url: null,
        option_a: 'ありません',
        option_b: 'いません',
        option_c: 'います',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'සතුන්/ජීවීන් නොමැති බව දැක්වීමට 「いません」 යොදයි.'
      },
      {
        order_num: 18,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '山田：<u>　（　）　</u>ですね。おげんきですか。\n田中：ええ、おかげさまで。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q18.jpg',
        audio_url: null,
        option_a: 'はじめまして',
        option_b: 'しつれいします',
        option_c: 'ひさしぶり',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ひさしぶりですね (Long time no see / ගොඩ කාලෙකින් නේද).'
      },
      {
        order_num: 19,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'Read the dialog and choose the phrase that fits the most.\n\nシン：ヤンさんのうちはえきからとおいですか。\nリン：いいえ、ちかいです。\nヤン：ヤンさんのへやはひろいですか。\nヤン：いいえ、<u>　（　）　</u>。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ひろいではありません',
        option_b: 'ひろくないです',
        option_c: 'ひろくてありません',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ひろくないです (ඉඩකඩ සහිත නැත).'
      },
      {
        order_num: 20,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'ヤン：シンさん、このケーキを食べますか。\nシン：わあっ、おいしいですね。このケーキはどこで買いましたか。\nヤン：私が<u>　（　）　</u>。\nシン：そうですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q20.jpg',
        audio_url: null,
        option_a: '作りました',
        option_b: 'しました',
        option_c: '使いました',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '作りました (つくりました - I made it / මම හැදුවා).'
      },
      {
        order_num: 21,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'コウ：ヤンさんは毎日何時に学校へ来ますか。\nヤン：９時に来ます。\nコウ：何で来ますか。\nヤン：<u>　（　）　</u>。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'でんしゃがきます',
        option_b: 'でんしゃできます',
        option_c: 'でんしゃにきます',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'でんしゃで きます (I come by train / කෝච්චියෙන් එනවා).'
      },
      {
        order_num: 22,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '学生１：日本の人はどうやってしょくじをしますか。\n学生２：はしとちゃわんでしょくじをします。\n学生１：ちゃわんは手で<u>　（　）　</u>。\n学生２：はい、手でもちます。ナイフやフォークなどもつかいます。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q22.jpg',
        audio_url: null,
        option_a: 'まちます',
        option_b: 'もちます',
        option_c: 'めします',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'もちます (手で持ちます - Hold in hand / අතින් අල්ලාගන්නවා).'
      },
      {
        order_num: 23,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'さとう：ミラーさん。\nミラー：何でしょうか。\nさとう：明日友達とお花見をします。ミラーさんも来ますか。\nミラー：いいですね。どこへ行きますか。\nさとう：おおさかじょうこうえんです。\nミラー：何時ですか。\nさとう：３時ごろです。おおさかじょうこうえんえきで<u>　（　）　</u>。\nミラー：わかりました。\nさとう：じゃ、またあした。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q23.jpg',
        audio_url: null,
        option_a: 'あいます',
        option_b: 'あいましょう',
        option_c: 'あうます',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'あいましょう (Let\'s meet / හමුවෙමු).'
      },
      {
        order_num: 24,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'シン：昨日、デパートでサリさんに<u>　（　）　</u>よ。\nパク：どこのデパートですか。\nシン：ぎんざのデパートです。きれいな女の人といっしょにいました。\nパク：こいびとですか。\nシン：さあ、わかりません。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q24.jpg',
        audio_url: null,
        option_a: 'みました',
        option_b: 'あんないしました',
        option_c: 'あいました',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'サリさんに会いました (Met Sari / සාරිව හමුවුණා).'
      },
      {
        order_num: 25,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'ヤン：ブラウンさんはおすしを食べますか。\nブラウン：いいえ、食べません。\nヤン：どうしてですか。\nブラウン：さかなが<u>　（　）　</u>から。\nヤン：じゃ、さしみも食べませんね。\nブラウン：ええ、食べません。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q25.jpg',
        audio_url: null,
        option_a: 'きらいです',
        option_b: 'へたです',
        option_c: 'すきです',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'さかながきらいですから (Because I dislike fish / මාලු වලට අකමැති නිසා).'
      },
      {
        order_num: 26,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'リン：サリさん、おかえりなさい。\nサリ：<u>　（　）　</u>。これ、おみやげです。\nリン：ありがとうございます。きょうとはどうでしたか。\nサリ：とてもきれいでした。でも、人がおおぜいいました。あまりしずかではありませんでした。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ただいま',
        option_b: 'さようなら',
        option_c: 'またあした',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ただいま (I\'m back / මම ආවා).'
      },
      {
        order_num: 27,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'てんいん：<u>　（　）　</u>。\nきゃく：すみません、サンドイッチをください。\nてんいん：サンドイッチをひとつですね。\nきゃく：はい。あ、それから、コーヒーもお願いします。\nてんいん：コーヒーはホットですか、アイスですか。\nきゃく：ホットをください。\nてんいん：はい、ぜんぶで720円です。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q27.jpg',
        audio_url: null,
        option_a: 'いらっしゃいません',
        option_b: 'いらっしゃいませんか',
        option_c: 'いらっしゃいませ',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'いらっしゃいませ (Welcome to our store / සාදරයෙන් පිළිගනිමු).'
      },
      {
        order_num: 28,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '学生１：きれいな店ですね。\n学生２：ええ、この店は、<u>　（　）　</u>おいしいです。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q28.jpg',
        audio_url: null,
        option_a: 'やすい',
        option_b: 'やすくて',
        option_c: 'やすいで',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'やすくて (Cheap and... / ලාභදායී මෙන්ම රසවත්).'
      },
      {
        order_num: 29,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'リン：パクさんはお酒をよく飲みますか。\nパク：私はお酒があまりすきではありませんが、ときどき飲みますよ。あなたはどうですか。\nリン：私の家族は、みんなお酒がすきですから、たくさん飲みます。でも、私はぜんぜん<u>　（　）　</u>。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q29.jpg',
        audio_url: null,
        option_a: 'のみました',
        option_b: 'のみません',
        option_c: 'のみます',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ぜんぜん のみません (Do not drink at all / කොහෙත්ම බොන්නේ නැත).'
      },
      {
        order_num: 30,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '田中：ただいま。\n山田：<u>　（　）　</u>。\n田中：これ、きょうとのおみやげです。\n山田：どうもありがとうございます。ぎおん祭りはどうでしたか。\n田中：とてもおもしろかったです。外国人も多かったですよ。\n山田：そうですか。\n田中：ええ。でもちょっとつかれました。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q30.jpg',
        audio_url: null,
        option_a: 'またあいましょう',
        option_b: 'おじゃまします',
        option_c: 'おかえりなさい',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'おかえりなさい (Welcome home / ආපසු පැමිණීම සාදරයෙන් පිළිගනිමු).'
      },

      // Section 3: Listening Comprehension (聴解 - Choukai - Q31 to Q45)
      {
        order_num: 31,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA woman is asking a store clerk something at a book store. Which book does the woman want to see?\n(女の人が本屋で店員に聞いています。女の人はどの本を見たいですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q31.jpg',
        audio_url: '/uploads/audio/jft01_q31_bookstore.mp3',
        option_a: 'A (車の本)',
        option_b: 'B (電車の本)',
        option_c: 'C (船の本)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'A (Car book / කාර් පිලිබඳ පොත).'
      },
      {
        order_num: 32,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA man and a woman are looking over a menu at a restaurant. What\'s the man going to order?\n(男の人と女の人がレストランでメニューを見ています。男の人は何を注文しますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q32.jpg',
        audio_url: '/uploads/audio/jft01_q32_restaurant_order.mp3',
        option_a: 'A (ピザ / Pizza)',
        option_b: 'B (ハンバーガー / Hamburger)',
        option_c: 'C (スパゲッティ / Spaghetti)',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'B (Hamburger / බර්ගර්).'
      },
      {
        order_num: 33,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA man is calling the doctor\'s office. What time does he need to be at the doctor\'s office by?\n(男の人が病院に電話しています。何時までに病院へ行かなければなりませんか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q33.jpg',
        audio_url: '/uploads/audio/jft01_q33_doctor_time.mp3',
        option_a: 'A (9:00)',
        option_b: 'B (1:00)',
        option_c: 'C (5:30 / 6:00)',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'C (5:30 / 6:00 Blue clock).'
      },
      {
        order_num: 34,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA boy is reading from his journal. What was the first thing the boy did today?\n(男の子が日記を読んでいます。今日、はじめに何をしに行きましたか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q34.jpg',
        audio_url: '/uploads/audio/jft01_q34_boy_journal.mp3',
        option_a: 'A (水泳 - およぐ)',
        option_b: 'B (テレビを見る)',
        option_c: 'C (勉強する)',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'C (Studying at desk / මේසයේ වාඩිවී පාඩම් කිරීම).'
      },
      {
        order_num: 35,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA woman and a man are looking at a photograph. Which photo are they looking at?\n(女の人と男の人が写真を見ています。どの写真を見ていますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q35.jpg',
        audio_url: '/uploads/audio/jft01_q35_photograph.mp3',
        option_a: 'A (テニスチーム)',
        option_b: 'B (サッカーチーム全員同色)',
        option_c: 'C (キーパーが違う色のサッカーチーム)',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'C (Soccer team with goalkeeper in distinct uniform).'
      },
      {
        order_num: 36,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA man and a woman are talking. When are they going to see a movie?\n(男の人と女の人が話しています。二人は何時に映画を見に行きますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q36.jpg',
        audio_url: '/uploads/audio/jft01_q36_movie_time.mp3',
        option_a: 'A (4:00)',
        option_b: 'B (2:00)',
        option_c: 'C (12:00)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'A (4:00 - Yellow clock).'
      },
      {
        order_num: 37,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA man is talking with a shop clerk. Which shirt is he going to buy?\n(男の人が店員と話しています。どのシャツを買いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q37.jpg',
        audio_url: '/uploads/audio/jft01_q37_shirt_color.mp3',
        option_a: 'A (青いシャツ / Blue)',
        option_b: 'B (白いシャツ / White)',
        option_c: 'C (赤いシャツ / Red)',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'B (White shirt / සුදු පැහැති කමිසය).'
      },
      {
        order_num: 38,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA man is at a hamburger shop. Which set is he going to order?\n(男の人がハンバーガー屋にいます。どのセットを注文しますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q38.jpg',
        audio_url: '/uploads/audio/jft01_q38_burger_set.mp3',
        option_a: 'A (バーガー＋サラダ＋ポテト)',
        option_b: 'B (バーガー＋ポテト＋ジュース)',
        option_c: 'C (バーガー＋サラダ＋ジュース)',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'C (Burger + Salad + Drink set).'
      },
      {
        order_num: 39,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA teacher is cooking a cake. What did the teacher put in it?\n(先生がケーキを作っています。何を入れましたか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q39.jpg',
        audio_url: '/uploads/audio/jft01_q39_cake_ingredients.mp3',
        option_a: 'A (バター、チョコ、卵1個、牛乳)',
        option_b: 'B (バター、チョコ、卵2個、小麦粉)',
        option_c: 'C (バター、チョコ、卵1個、小麦粉)',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'B (Butter, Chocolate, 2 Eggs, and Flour).'
      },
      {
        order_num: 40,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA man and a woman are talking. What are they going to do first?\n(男の人と女の人が話しています。二人ははじめに何をしますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q40.jpg',
        audio_url: '/uploads/audio/jft01_q40_cinema_shopping.mp3',
        option_a: 'A (映画館で映画を見る)',
        option_b: 'B (デパートで買い物をする)',
        option_c: 'C (家でテレビを見る)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'A (Watch movie at cinema first / මුලින්ම සිනමාහලේ චිත්‍රපටය නැරඹීම).'
      },
      {
        order_num: 41,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA teacher and a student are talking. When will the student go to the teacher\'s office?\n(先生と学生が話しています。学生は何時に先生の部屋へ行きますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q41.jpg',
        audio_url: '/uploads/audio/jft01_q41_teacher_office.mp3',
        option_a: 'A (1:00)',
        option_b: 'B (4:00)',
        option_c: 'C (12:00)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'A (1:00 - Blue clock).'
      },
      {
        order_num: 42,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA woman is having lunch at a restaurant. What is she going to order?\n(女の人がレストランで昼ご飯を食べています。何を注文しますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q42.jpg',
        audio_url: '/uploads/audio/jft01_q42_coffee_sugar.mp3',
        option_a: 'A (ブラックコーヒーのみ)',
        option_b: 'B (コーヒーとミルクのみ)',
        option_c: 'C (コーヒーとミルクと砂糖)',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'B (Coffee with milk only / සීනි නැතිව කිරි පමණක් දැමූ කෝපි).'
      },
      {
        order_num: 43,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA woman is waiting for a man. Where will the woman wait?\n(女の人が男の人を待っています。女の人はどこで待ちますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q43.jpg',
        audio_url: '/uploads/audio/jft01_q43_waiting_location.mp3',
        option_a: '1 (カフェの前)',
        option_b: '2 (交差点の角)',
        option_c: '3 (バス停の前)',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'C (Location 3 - Near the bus stop / බස් නැවතුම අසල 3 ස්ථානය).'
      },
      {
        order_num: 44,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA man and a woman are talking about summer vacation. What is the woman going to do during summer vacation?\n(男の人と女の人が夏休みについて話しています。女の人は夏休みに何をしますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q44.jpg',
        audio_url: '/uploads/audio/jft01_q44_summer_vacation.mp3',
        option_a: 'A (海へ行く)',
        option_b: 'B (山でキャンプする)',
        option_c: 'C (自転車に乗る)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'A (Go to the sea / මුහුදු වෙරළට යාම).'
      },
      {
        order_num: 45,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA man and a woman are talking. What did the woman eat this morning?\n(男の人と女の人が話しています。女の人は今朝何を食べましたか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q45.jpg',
        audio_url: '/uploads/audio/jft01_q45_morning_breakfast.mp3',
        option_a: 'A (パンとスープとコーヒー)',
        option_b: 'B (パンとバナナとコーヒー)',
        option_c: 'C (パンとスープとバナナとコーヒー)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'A (Bread, Soup/Yogurt, and Coffee).'
      },

      // Section 4: Reading Comprehension (読解 - Dokkai - Q46 to Q60)
      {
        order_num: 46,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、正しい答えを選んでください。\n\n【ミラーさんの毎日】\nミラーさんは毎日６時におきます。朝ご飯はいつもパンとコーヒーです。でんしゃでかいしゃへ行きます。かいしゃは９時から５時までです。７時にうちへかえります。７時半に夕ご飯を食べます。それからテレビを見ます。えいごのしんぶんもよみます。夜１２時にねます。\n土曜日と日曜日ははたらきません。土曜日は朝としょかんへ行きます。午後テニスをします。日曜日はどこも行きません。やすみます。\n\n質問：ミラーさんのやすみの日はいつですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '月曜日と土曜日',
        option_b: '土曜日と日曜日',
        option_c: '日曜日と金曜日',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '土曜日と日曜日 (Saturday and Sunday / සෙනසුරාදා සහ ඉරිදා).'
      },
      {
        order_num: 47,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、正しい答えを選んでください。\n\n今はてんきがよかったので、いつもの道をとおらないで、こうえんをさんぽしながらがっこうに行きました。私のうちからがっこうまで、いつもはあるいて１５分ですが、今日は３０分かかりました。でも、きもちがよかったです。\n\n質問：私は今日どうしましたか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'こうえんをとおってがっこうに行きました',
        option_b: 'がっこうからいつもの道でこうえんに行きました',
        option_c: 'いつもの道をゆっくりあるいて、がっこうに行きました',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'こうえんをとおってがっこうに行きました (Walked through the park to school).'
      },
      {
        order_num: 48,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、正しい答えを選んでください。\n\n私の家族は父と母と兄と妹です。父はこうこうでえいごをおしえています。母はぎんこういんです。兄はかいしゃではたらいています。私はだいがくせいで妹はちゅうがくせいです。\n\n質問：私の家族は何人ですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '2人',
        option_b: '6人',
        option_c: '5人',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '5人 (Father, Mother, Brother, Sister, and "I" = 5 people / පවුලේ 5 දෙනෙකි).'
      },
      {
        order_num: 49,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【前問の文章】\n私の家族は父と母と兄と妹です。父はこうこうでえいごをおしえています。母はぎんこういんです。兄はかいしゃではたらいています。私はだいがくせいで妹はちゅうがくせいです。\n\n質問：誰がかいしゃにはたらいていますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '父',
        option_b: '兄',
        option_c: '母',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '兄 (あに - Elder brother / 兄は会社で働いています).'
      },
      {
        order_num: 50,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'ポスターを見て質問に答えてください。\n\n【絵のてんらんかい案内】\n・日時（A）：2022年08月22日（月） 06.00時〜\n・場所（B）：CBCホール\n・チケット（C）：1000円\n\n質問：てんらんかいはいつですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q50.jpg',
        audio_url: null,
        option_a: 'A (日時: 2022年08月22日)',
        option_b: 'B (場所: CBCホール)',
        option_c: 'C (チケット: 1000円)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'A (日時: 2022年08月22日（月） 06.00時〜).'
      },
      {
        order_num: 51,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【絵のてんらんかい案内】\n・日時（A）：2022年08月22日（月） 06.00時〜\n・場所（B）：CBCホール\n・チケット（C）：1000円\n\n質問：私は友達といっしょにてんらんかいへ行きたいです。２まいのきっぷはいくらになりますか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q50.jpg',
        audio_url: null,
        option_a: '4000円',
        option_b: '2000円',
        option_c: '2500円',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '2000円 (1000円 × 2枚 = 2000円).'
      },
      {
        order_num: 52,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '山田さんの週間予定表を見て答えてください。\n\n【山田さんの予定表】\n・1日（月）：漢字テスト\n・2日（火）：文法テスト\n・3日（水）：11時〜 田中さんの会社\n・4日（木）：誕生日カードをデパートで買います\n・5日（金）：17時〜 木村さんの誕生日パーティー\n・6日（土）：（休み）\n・7日（日）：10時〜 映画\n\n質問：いつ田中さんの会社へ行きますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '3日の水曜日',
        option_b: '4日の水曜日',
        option_c: '4日の木曜日',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '3日の水曜日 (11時〜 田中さんの会社).'
      },
      {
        order_num: 53,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【山田さんの予定表】\n・1日（月）：漢字テスト\n・2日（火）：文法テスト\n・3日（水）：11時〜 田中さんの会社\n・4日（木）：誕生日カードをデパートで買います\n・5日（金）：17時〜 木村さんの誕生日パーティー\n・6日（土）：（休み）\n・7日（日）：10時〜 映画\n\n質問：木曜日に何をしますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '学校の漢字テストです',
        option_b: 'きむらさんの誕生日パーティーへ行きます',
        option_c: '誕生日カードを買うためにデパートへ行きます',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '誕生日カードを買うためにデパートへ行きます (4日木曜日).'
      },
      {
        order_num: 54,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【国際郵便料金表（絵はがき・手紙）】\n・封書（10gまで）：アジア 80円 / 北中米 100円 / ヨーロッパ 120円\n・封書（20gまで）：アジア 140円 / 北中米 170円 / ヨーロッパ 220円\n・封書（30gまで）：アジア 200円 / 北中米 240円 / ヨーロッパ 320円\n・封書（40gまで）：アジア 260円 / 北中米 310円 / ヨーロッパ 420円\n・はがき（絵葉書）：全世界一律 70円（アジア 70円 / 北中米 70円 / ヨーロッパ 70円）\n\n質問：フランスに絵はがきを出したいです。いくらになりますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '70円',
        option_b: '80円',
        option_c: '120円',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '70円 (はがき/絵葉書は全世界一律70円です).'
      },
      {
        order_num: 55,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、正しい答えを選んでください。\n\n【私のうち】\n私の新しいうちはしずかなところにあります。うちのとなりにきれいなこうえんがあります。こうえんの前によみものときっさてんがあります。私はとしょかんで本をかります。そして、こうえんでよみます。ときどききっさてんのコーヒーはおいしいです。うちの近くにゆうびんきょくとぎんこうがあります。ゆうびんきょくとぎんこうの間にスーパーがあります。スーパーの中にはなややおいしいパンやがあります。とてもべんりです。\n\n質問：はなやはどこにありますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'スーパーの前に',
        option_b: 'スーパーのよこに',
        option_c: 'スーパーの中に',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'スーパーの中に (Inside the supermarket / 「スーパーの中にはなややおいしいパンやがあります」).'
      },
      {
        order_num: 56,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'スマートフォンのメッセージとイラストを見て答えてください。\n\n【メッセージ】\n「すみません。今、としょかんで べんきょうしているの でちょっとあとで でんわをして くださいませんか。」\n\n質問：なぜ彼はでんわにでられないのですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q56.jpg',
        audio_url: null,
        option_a: 'A (犬と散歩しているから)',
        option_b: 'B (図書館で勉強しているから)',
        option_c: 'C (道路が混んでいるから)',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'B (図書館で勉強しているから / Studying at the library).'
      },
      {
        order_num: 57,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、正しい答えを選んでください。\n\nアヌポンさんは午後２時半になりたくうこうにつきました。タイから日本まで６時間ぐらいかかりました。くうこうからとうきょうのホテルまでリムジンバスでは２時間ぐらいかかります。しかし、どうろがこんでいるときは、もっと時間がかかります。とっきゅうでんしゃでもうえのまで１時間ぐらいです。うえのからホテルまではちかてつやタクシーで行きます。リムジンバスのりょうきん2800円で、でんしゃは1700円です。でんしゃはうえののえきまで行きますが、バスはホテルの前まで行きます。アヌポンさんはかばんを３つもっています。おおきくておもいです。ですから、リムジンバスのほうがたかいですが、バスで行きます。バスの前には人がたくさんいます。みんなのかばんもおおきいです。\n\n質問：アヌポンさんはどうしてリムジンバスでホテルへ行きますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'やすいからです',
        option_b: 'はやいからです',
        option_c: 'にもつがおおいからです',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'にもつがおおいからです (Because he has a lot of heavy luggage / බඩු බාහිරාදිය 3ක් ඇති නිසා).'
      },
      {
        order_num: 58,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'メモを読んで、質問に答えてください。\n\n【もりさんへ】\nクラスでつかう本をなかがわ先生にかりました。\nページを２まいコピーしてください。\nコピーははやしさんにわたしてください。\n本は明日私がかえしますから、私のつくえの上においてください。\n―― やまぐち\n\n質問：やまぐち先生のメモによると、もりさんは本をコピーしたあと本に何をしたらいいですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'クラスでつかいます',
        option_b: 'なかがわ先生にわたします',
        option_c: 'やまぐち先生のつくえの上におきます',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'やまぐち先生のつくえの上におきます (「私のつくえの上においてください」).'
      },
      {
        order_num: 59,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章とイラストを見て質問に答えてください。\n\n日曜日は私のやすみの日です。朝きっさてんで友達にあって、友達といっしょにプールへおよぎに行きました。とてもたのしかったです。\n\n・イラストA：きっさてんで友達にあう\n・イラストB：街を歩いて買い物する\n・イラストC：プールでおよぐ\n\n質問：かのじょはどのようにやすみの日をすごしましたか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft01_q59.jpg',
        audio_url: null,
        option_a: 'AとB',
        option_b: 'AとC',
        option_c: 'BとC',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'AとC (Cafe A + Pool C / කැෆේ එකේදී යෙහෙළිය හමුවී පිහිනුම් තටාකයට යාම).'
      },
      {
        order_num: 60,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'メモを読んで、質問に答えてください。\n\n【みちこさんへ】\n10時ごろにゆうびんきょくの人がこのにもつをとりに来ますから、にもつとお金をわたしてください。お金は田中さんにもっています。ゆうびんきょくの人は来る前にもらいに行ってください。\nよろしくおねがいします。\n―― あべ（11月09日 09:30）\n\n質問：メモをよんだ後、みちこさんははじめに何をしますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '田中さんにお金をもらいます',
        option_b: '田中さんににもつとお金をわたします',
        option_c: 'ゆうびんきょくの人ににもつをもらいます',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '田中さんにお金をもらいます (「郵便局の人が来る前にもらいに行ってください」).'
      }
    ];

    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, section_name, question_text, question_type,
          image_url, audio_url,
          option_a, option_b, option_c, option_d,
          correct_option, marks, explanation, order_num
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId,
        q.section_name,
        q.question_text,
        q.question_type,
        q.image_url,
        q.audio_url,
        q.option_a,
        q.option_b,
        q.option_c,
        q.option_d || '',
        q.correct_option,
        q.marks,
        q.explanation || '',
        q.order_num
      ]);
    }
    console.log('✅ Auto-seeded JFT Model Paper 01 with 60 questions successfully.');
  } catch (err) {
    console.error('seedJftModelPaper01 error:', err);
  }
}

module.exports = { seedJftModelPaper01 };
