const { query } = require('../config/database');

async function seedJLPTN5Paper03() {
  try {
    console.log('====================================================');
    console.log('Seeding JLPT N5 Official Examination - 2010-2011 (Paper 03)...');
    console.log('====================================================');

    const course = await query.get("SELECT id, code, name FROM courses WHERE id = 2 OR code = 'JLPT-N5'");
    if (!course) {
      throw new Error("Course JLPT-N5 (ID: 2) not found in database.");
    }
    const courseId = course.id;
    console.log(`Target Course: ${course.name} (ID: ${courseId})`);

    const title = 'JLPT N5 Official Examination - 2010-2011 (Paper 03)';
    const description = 'Official JLPT N5 Examination from 2010-2011 (Paper 03). Features all 3 sections: Language Knowledge (Vocabulary), Language Knowledge (Grammar) & Reading, and Listening Comprehension with authentic audio and high-resolution diagrams.';

    // Check if exam record already exists
    let exam = await query.get("SELECT * FROM exams WHERE course_id = ? AND title = ?", [courseId, title]);

    let examId;
    if (exam) {
      examId = exam.id;
      console.log(`Found existing Exam record with ID: ${examId}`);
      await query.run(`
        UPDATE exams
        SET title = ?,
            course_id = ?,
            duration_minutes = 105,
            passing_score = 50,
            total_marks = 180,
            description = ?,
            category = 'JLPT-N5',
            is_active = 1
        WHERE id = ?
      `, [title, courseId, description, examId]);
    } else {
      console.log('Creating new Exam record for Paper 03...');
      const insertResult = await query.run(`
        INSERT INTO exams (course_id, title, duration_minutes, passing_score, total_marks, description, category, is_active)
        VALUES (?, ?, 105, 50, 180, ?, 'JLPT-N5', 1)
      `, [courseId, title, description]);
      examId = insertResult.id;
      console.log(`Created Exam record with ID: ${examId}`);
    }

    const audioTrackUrl = '/audio/n5_paper3_listening.m4a';

    const questionsData = [
      // =========================================================================
      // SECTION 1: 言語知識（文字・語彙） (Q01 to Q33, 1 mark each = 33 marks)
      // =========================================================================
      // 問題１ (Q1-Q10) 漢字読み
      {
        order_num: 1,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題１　＿＿＿の　ことばは　どう　よみますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n先週 デパートに かいものに いきました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'せんしゅ',
        option_b: 'せんしゅう',
        option_c: 'ぜんしゅ',
        option_d: 'ぜんしゅう',
        correct_option: 'B',
        marks: 1,
        explanation: '「先週」の読み方は「せんしゅう」です。「先週 デパートに かいものに いきました。」（I went shopping at the department store last week.）',
        explanation_sin: '「先週」කියවන්නේ「せんしゅう」(සෙන්ශූ - ගිය සතිය) ලෙසයි. ගිය සතියේ දෙපාර්තමේන්තු සාප්පුවට බඩු ගැනීමට ගියෙමි.'
      },
      {
        order_num: 2,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題１　＿＿＿の　ことばは　どう　よみますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nごはんの 後で さんぽ します。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'つぎ',
        option_b: 'うしろ',
        option_c: 'まえ',
        option_d: 'あと',
        correct_option: 'D',
        marks: 1,
        explanation: '「後で」の読み方は「あとで」です。「ごはんの 後で さんぽ します。」（I will take a walk after the meal.）',
        explanation_sin: '「後で」කියවන්නේ「あとで」(අතොදෙ - පසුව) ලෙසයි. කෑමෙන් පසු ඇවිදින්නට යන්නෙමි.'
      },
      {
        order_num: 3,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題１　＿＿＿の　ことばは　どう　よみますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nもう いちど 言って ください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'いって',
        option_b: 'きって',
        option_c: 'まって',
        option_d: 'たって',
        correct_option: 'A',
        marks: 1,
        explanation: '「言って」の読み方は「いって」です。「言う」のて形です。「もう いちど 言って ください。」（Please say it once more.）',
        explanation_sin: '「言って」කියවන්නේ「いって」(ඉත්තෙ - කියන්න) ලෙසයි. 「言う」(කියනවා) හි තෙ-ආකාරයයි. නැවත වරක් කියන්න.'
      },
      {
        order_num: 4,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題１　＿＿＿の　ことばは　どう　よみますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nちかくに 山が あります。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'かわ',
        option_b: 'やま',
        option_c: 'いけ',
        option_d: 'うみ',
        correct_option: 'B',
        marks: 1,
        explanation: '「山」の読み方は「やま」です。「ちかくに 山が あります。」（There is a mountain nearby.）',
        explanation_sin: '「山」කියවන්නේ「やま」(යම - කන්ද) ලෙසයි. ආසන්නයේ කන්දක් ඇත.'
      },
      {
        order_num: 5,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題１　＿＿＿の　ことばは　どう　よみますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nこの ホテルは へやが 多いです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'すくない',
        option_b: 'おおい',
        option_c: 'せまい',
        option_d: 'ひろい',
        correct_option: 'B',
        marks: 1,
        explanation: '「多い」の読み方は「おおい」です。「この ホテルは へやが 多いです。」（This hotel has many rooms.）',
        explanation_sin: '「多い」කියවන්නේ「おおい」(ඕයි - ගොඩක්/බොහෝ) ලෙසයි. මෙම හෝටලයේ කාමර බොහෝ ප්‍රමාණයක් ඇත.'
      },
      {
        order_num: 6,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題１　＿＿＿の　ことばは　どう　よみますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nともだちと いっしょに 学校に いきます。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'がこう',
        option_b: 'がこお',
        option_c: 'がっこう',
        option_d: 'がっこお',
        correct_option: 'C',
        marks: 1,
        explanation: '「学校」の読み方は「がっこう」です。「ともだちと いっしょに 学校に いきます。」（I go to school together with my friend.）',
        explanation_sin: '「学校」කියවන්නේ「がっこう」(ගක්කෝ - පාසල) ලෙසයි. මිතුරා සමග එක්ව පාසල් යමි.'
      },
      {
        order_num: 7,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題１　＿＿＿の　ことばは　どう　よみますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nえんぴつが 六本 あります。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ろくぼん',
        option_b: 'ろくぽん',
        option_c: 'ろっぼん',
        option_d: 'ろっぽん',
        correct_option: 'D',
        marks: 1,
        explanation: '細長いものを数える助数詞「本」がつくと「六本」は促音化して「ろっぽん」と読みます。',
        explanation_sin: 'සිහින් දිගටි දෑ ගණනය කිරීමේ ඒකකය 「本」සමග 6 යෙදෙන විට「ろっぽん」(රොප්පොන් - පැන්සල් හයක්) ලෙස ශබ්ද වේ.'
      },
      {
        order_num: 8,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題１　＿＿＿の　ことばは　どう　よみますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nこの 新聞は いくらですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'しんむん',
        option_b: 'しんぶん',
        option_c: 'しむん',
        option_d: 'しぶん',
        correct_option: 'B',
        marks: 1,
        explanation: '「新聞」の読み方は「しんぶん」です。「この 新聞は いくらですか。」（How much is this newspaper?）',
        explanation_sin: '「新聞」කියවන්නේ「しんぶん」(ශින්බුන් - පුවත්පත) ලෙසයි. මෙම පුවත්පත කීයද?'
      },
      {
        order_num: 9,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題１　＿＿＿の　ことばは　どう　よみますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nこの カメラは 安いです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'たかい',
        option_b: 'やすい',
        option_c: 'おもい',
        option_d: 'かるい',
        correct_option: 'B',
        marks: 1,
        explanation: '「安い」の読み方は「やすい」です。「この カメラは 安いです。」（This camera is cheap / inexpensive.）',
        explanation_sin: '「安い」කියවන්නේ「やすい」(යසුයි - ලාභදායී) ලෙසයි. මෙම කැමරාව ලාභයි.'
      },
      {
        order_num: 10,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題１　＿＿＿の　ことばは　どう　よみますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nかさは 外に あります。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'いえ',
        option_b: 'なか',
        option_c: 'そと',
        option_d: 'にわ',
        correct_option: 'C',
        marks: 1,
        explanation: '「外」の読み方は「そと」です。「かさは 外に あります。」（The umbrella is outside.）',
        explanation_sin: '「外」කියවන්නේ「そと」(සොතො - පිටත) ලෙසයි. කුඩය පිටත ඇත.'
      },

      // 問題２ (Q11-Q18) 表記・漢字
      {
        order_num: 11,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題２　＿＿＿の　ことばは　どう　かきますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nけさ しゃわーを あびました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'シャワー',
        option_b: 'シャウー',
        option_c: 'ツァワー',
        option_d: 'ツァウー',
        correct_option: 'A',
        marks: 1,
        explanation: 'カタカナ表記で「シャワー」です。「けさ シャワーを あびました。」（I took a shower this morning.）',
        explanation_sin: 'කටකනා අකුරින්「シャワー」(ශවර් - නෑම) ලෙස ලියනු ලැබේ. අද උදෑසන ෂවර් එකෙන් නෑවෙමි.'
      },
      {
        order_num: 12,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題２　＿＿＿の　ことばは　どう　かきますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nコーヒーを のみました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '飯みました',
        option_b: '飲みました',
        option_c: '飮みました',
        option_d: '食みました',
        correct_option: 'B',
        marks: 1,
        explanation: '「のみました」の漢字表記は「飲みました」です。「飲む」は「飲」の漢字を使います。',
        explanation_sin: '「のみました」හි නිවැරදි කන්ජි අකුර「飲みました」(බිව්වා) වේ.'
      },
      {
        order_num: 13,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題２　＿＿＿の　ことばは　どう　かきますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nあたらしい くるまを かいました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '卓',
        option_b: '早',
        option_c: '車',
        option_d: '真',
        correct_option: 'C',
        marks: 1,
        explanation: '「くるま」の漢字表記は「車」です。「あたらしい 車を かいました。」（I bought a new car.）',
        explanation_sin: '「くるま」හි නිවැරදි කන්ජි අකුර「車」(මෝටර් රථය) වේ. අලුත් මෝටර් රථයක් මිලදී ගත්තෙමි.'
      },
      {
        order_num: 14,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題２　＿＿＿の　ことばは　どう　かきますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nこの ぼうしは 1000 えんです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '1000 内',
        option_b: '1000 用',
        option_c: '1000 冊',
        option_d: '1000 円',
        correct_option: 'D',
        marks: 1,
        explanation: '通貨単位「えん」の漢字表記は「円」です。「1000円」（1,000 yen）。',
        explanation_sin: 'මුදල් ඒකකය වන「えん」(යෙන්) හි නිවැරදි කන්ජි අකුර「円」වේ. මෙම තොප්පිය යෙන් 1000 කි.'
      },
      {
        order_num: 15,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題２　＿＿＿の　ことばは　どう　かきますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nしゅくだいが はんぶん おわりました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '羊分',
        option_b: '平分',
        option_c: '伴分',
        option_d: '半分',
        correct_option: 'D',
        marks: 1,
        explanation: '「はんぶん」の漢字表記は「半分」です。「半分」（half）。',
        explanation_sin: '「はんぶん」හි නිවැරදි කන්ජි අකුර「半分」(අඩක්/බාගයක්) වේ. ගෙදර වැඩවලින් අඩක් අවසන් විය.'
      },
      {
        order_num: 16,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題２　＿＿＿の　ことばは　どう　かきますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nわたしの うちに きませんか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '来ませんか',
        option_b: '采ませんか',
        option_c: '木ませんか',
        option_d: '未ませんか',
        correct_option: 'A',
        marks: 1,
        explanation: '「きます（来る）」の漢字表記は「来」です。「わたしの うちに 来ませんか。」（Won\'t you come to my house?）',
        explanation_sin: '「きませんか」හි「き（来る - එනවා）」හි නිවැරදි කන්ජි අකුර「来」වේ. මාගේ නිවසට එන්නේ නැද්ද?'
      },
      {
        order_num: 17,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題２　＿＿＿の　ことばは　どう　かきますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nきのう たなかさんと あいました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '見いました',
        option_b: '書いました',
        option_c: '会いました',
        option_d: '話いました',
        correct_option: 'C',
        marks: 1,
        explanation: '人に「あう（会う）」の漢字表記は「会」です。「きのう たなかさんと 会いました。」（I met Mr. Tanaka yesterday.）',
        explanation_sin: 'මිනිසුන් හමුවීම「あう」සඳහා යොදන නිවැරදි කන්ජි අකුර「会」වේ (会いました - හමුවුණා).'
      },
      {
        order_num: 18,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題２　＿＿＿の　ことばは　どう　かきますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nいもうとと おなじ ふくを かいました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '同じ',
        option_b: '回じ',
        option_c: '哃じ',
        option_d: '固じ',
        correct_option: 'A',
        marks: 1,
        explanation: '「おなじ」の漢字表記は「同じ」です。「いもうとと 同じ ふくを かいました。」（I bought the same clothes as my younger sister.）',
        explanation_sin: '「おなじ」හි නිවැරදි කන්ජි අකුර「同じ」(සමාන/එකම) වේ. නංගීගේ වැනිම ඇඳුමක් ගත්තෙමි.'
      },

      // 問題３ (Q19-Q28) 文脈規定
      {
        order_num: 19,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題３　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nわたしの へやは この ( )の 2かいです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'エレベーター',
        option_b: 'プール',
        option_c: 'エアコン',
        option_d: 'アパート',
        correct_option: 'D',
        marks: 1,
        explanation: '部屋がある建物として文脈に合うのは「アパート」（apartment）です。「この アパートの 2かいです。」',
        explanation_sin: 'කාමරයක් පිහිටි ගොඩනැගිල්ලක් විස්තර කිරීමට ගැළපෙන්නේ「アパート」(ඇපාර්ට්මන්ට්/මහල් නිවාසය) යන්නයි.'
      },
      {
        order_num: 20,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題３　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nさとうさんは ギターを じょうずに ( )。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'うたいます',
        option_b: 'ききます',
        option_c: 'ひきます',
        option_d: 'あそびます',
        correct_option: 'C',
        marks: 1,
        explanation: 'ギターやピアノなど弦楽器・鍵盤楽器を演奏するときは動詞「ひく（弾く）」を使います。「ギターを ひきます。」',
        explanation_sin: 'ගිටාර් හෝ පියානෝ වාදනය කිරීමේදී යොදන ක්‍රියාපදය වන්නේ「ひきます」(වාදනය කරනවා) යන්නයි.'
      },
      {
        order_num: 21,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題３　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nテーブルに おさらと はしを ( ) ください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ならべて',
        option_b: 'とって',
        option_c: 'たべて',
        option_d: 'あらって',
        correct_option: 'A',
        marks: 1,
        explanation: 'テーブルの上にお皿や箸を整えて置くときは「ならべる（並べる）」を使います。「ならべて ください。」（Please arrange the plates and chopsticks.）',
        explanation_sin: 'මේසය මත පිඟන් සහ චොප්ස්ටික් පිළිවෙළට තැබීමට「ならべて」(පිළිවෙළට තබන්න) යන්න යෙදේ.'
      },
      {
        order_num: 22,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題３　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nけさ そうじを したから へやは ( )です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'きれい',
        option_b: 'きたない',
        option_c: 'あかるい',
        option_d: 'くらい',
        correct_option: 'A',
        marks: 1,
        explanation: '「そうじを したから」（掃除をしたので）部屋は清潔で美しい状態になるため、「きれい」が適切です。',
        explanation_sin: 'උදෑසන පිරිසිදු කළ බැවින් කාමරය「きれい」(පිරිසිදු/ලස්සන) වී ඇත.'
      },
      {
        order_num: 23,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題３　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nきょうは 500( ) およぎました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ど',
        option_b: 'ばん',
        option_c: 'メートル',
        option_d: 'グラム',
        correct_option: 'C',
        marks: 1,
        explanation: '水泳の泳いだ距離を表す単位は「メートル」（meters）です。「500メートル およぎました。」',
        explanation_sin: 'පිහිනූ දුර ප්‍රමාණය මැනීමට ගැළපෙන ඒකකය「メートル」(මීටර්) වේ. අද මීටර් 500ක් පිහිනුවෙමි.'
      },
      {
        order_num: 24,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題３　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nえきから たいしかんまでの ( )を かいて ください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'しゃしん',
        option_b: 'ちず',
        option_c: 'てがみ',
        option_d: 'きっぷ',
        correct_option: 'B',
        marks: 1,
        explanation: '駅から大使館までの道順・案内を「かく」ものとして「ちず（地図）」が適切です。「ちずを かいて ください。」（Please draw a map.）',
        explanation_sin: 'දුම්රියපොළේ සිට තානාපති කාර්යාලය දක්වා මාර්ගය ඇඳ පෙන්වීමට「ちず」(සිතියම) යන්න යෙදේ.'
      },
      {
        order_num: 25,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題３　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nうるさいから テレビを( ) ください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'けして',
        option_b: 'つけて',
        option_c: 'しめて',
        option_d: 'あけて',
        correct_option: 'A',
        marks: 1,
        explanation: '「うるさいから」（うるさいので）電気製品のテレビの電源を切る動詞は「けす（消す）」です。「テレビを けして ください。」（Please turn off the TV.）',
        explanation_sin: 'ශබ්දය වැඩි බැවින් රූපවාහිනිය නිවා දැමීමට「けして」(නිවා දමන්න) යන්න ගැළපේ.'
      },
      {
        order_num: 26,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題３　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nきょうは ( )が ふって います。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'くもり',
        option_b: 'はれ',
        option_c: 'かぜ',
        option_d: 'ゆき',
        correct_option: 'D',
        marks: 1,
        explanation: '「〜が ふる（降る）」と結びつく天候の言葉は「雨」や「ゆき（雪）」です。「ゆきが ふって います。」（Snow is falling.）',
        explanation_sin: 'වැටෙනවා/ඇදහැලෙනවා「ふる」සමග යෙදෙන කාලගුණ පදය වන්නේ「ゆき」(හිම) වේ. අද හිම ඇදහැලෙමින් පවතී.'
      },
      {
        order_num: 27,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題３　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nはこに りんごが ( ) あります。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper3/vocab_q27_apples.jpg',
        audio_url: null,
        option_a: 'よっつ',
        option_b: 'いつつ',
        option_c: 'むっつ',
        option_d: 'ななつ',
        correct_option: 'B',
        marks: 1,
        explanation: '絵を見ると、箱の中にりんごが5個入っています。5個は和数詞で「いつつ」と数えます。',
        explanation_sin: 'පින්තූරයේ පෙට්ටිය තුළ ඇපල් ගෙඩි 5ක් ඇත. ජපන් ක්‍රමයට 5 ගණන් කරන්නේ「いつつ」(පහක්) ලෙසයි.'
      },
      {
        order_num: 28,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題３　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nめがねは つくえの ( )に あります。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper3/vocab_q28_desk.jpg',
        audio_url: null,
        option_a: 'そば',
        option_b: 'よこ',
        option_c: 'した',
        option_d: 'うえ',
        correct_option: 'D',
        marks: 1,
        explanation: '絵を見ると、メガネは机の天板の上（うえ）に置かれています。「つくえの うえに あります。」',
        explanation_sin: 'පින්තූරය අනුව කණ්ණාඩි කුට්ටම මේසය උඩ ඇත. එබැවින්「うえ」(උඩ) යන්න නිවැරදිය.'
      },

      // 問題４ (Q29-Q33) 言い換え類義
      {
        order_num: 29,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題４　＿＿＿の　ぶんと　だいたい　おなじ　いみの　ぶんが　あります。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nまいばん くにの かぞくに でんわします。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'よるは ときどき くにの かぞくに でんわします。',
        option_b: 'あさは ときどき くにの かぞくに でんわします。',
        option_c: 'よるは いつも くにの かぞくに でんわします。',
        option_d: 'あさは いつも くにの かぞくに でんわします。',
        correct_option: 'C',
        marks: 1,
        explanation: '「まいばん（毎晩）」は「よるは いつも（every night）」と同じ意味です。',
        explanation_sin: '「まいばん」(සෑම රාත්‍රියකම) යන්න「よるは いつも」(රාත්‍රියට සැමවිටම) යන්නට සමාන අර්ථයක් ලබාදෙයි.'
      },
      {
        order_num: 30,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題４　＿＿＿の　ぶんと　だいたい　おなじ　いみの　ぶんが　あります。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nこの まちには ゆうめいな たてものが あります。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'この まちには ゆうめいな ビルが あります。',
        option_b: 'この まちには ゆうめいな おちゃが あります。',
        option_c: 'この まちには ゆうめいな ケーキが あります。',
        option_d: 'この まちには ゆうめいな こうえんが あります。',
        correct_option: 'A',
        marks: 1,
        explanation: '「たてもの（建物）」を具体的に言い換えた言葉は「ビル（building）」です。',
        explanation_sin: '「たてもの」(ගොඩනැගිල්ල) යන්නට සමාන වචනය වන්නේ「ビル」(බිල්ඩිම) වේ.'
      },
      {
        order_num: 31,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題４　＿＿＿の　ぶんと　だいたい　おなじ　いみの　ぶんが　あります。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nその えいがは おもしろくなかったです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'その えいがは たのしかったです。',
        option_b: 'その えいがは つまらなかったです。',
        option_c: 'その えいがは みじかかったです。',
        option_d: 'その えいがは ながかったです。',
        correct_option: 'B',
        marks: 1,
        explanation: '「おもしろくなかった（not interesting）」は「つまらなかった（boring）」と同じ意味です。',
        explanation_sin: '「おもしろくなかった」(සිත්ගන්නාසුළු නොවීය) යන්න「つまらなかった」(කම්මැලි සහගත විය) යන්නට සමාන වේ.'
      },
      {
        order_num: 32,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題４　＿＿＿の　ぶんと　だいたい　おなじ　いみの　ぶんが　あります。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nたんじょうびは 6がつ 15にちです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '6がつ 15にちに けっこんしました。',
        option_b: '6がつ 15にちに テストが はじまりました。',
        option_c: '6がつ 15にちに うまれました。',
        option_d: '6がつ 15にちに くにへ かえりました。',
        correct_option: 'C',
        marks: 1,
        explanation: '「たんじょうび（誕生日）」は生まれた日なので、「6がつ 15にちに うまれました。（I was born on June 15th）」と同じ意味です。',
        explanation_sin: '「たんじょうび」(උපන් දිනය) යනු උපන් දිනය බැවින්「6がつ 15にちに うまれました」(ජූනි 15 වන දින උපත ලැබුවා) යන්න නිවැරදිය.'
      },
      {
        order_num: 33,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題４　＿＿＿の　ぶんと　だいたい　おなじ　いみの　ぶんが　あります。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nにねんまえに きょうとへ いきました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'きのう きょうとへ いきました。',
        option_b: 'おととい きょうとへ いきました。',
        option_c: 'きょねん きょうとへ いきました。',
        option_d: 'おととし きょうとへ いきました。',
        correct_option: 'D',
        marks: 1,
        explanation: '「にねんまえ（2年前）」は「おととし（the year before last）」と同じ意味です。',
        explanation_sin: '「にねんまえ」(වසර 2කට පෙර) යනු「おととし」(පෙරේදා අවුරුද්ද/ගිය වසරට කලින් වසර) යන්නට සමාන වේ.'
      },

      // =========================================================================
      // SECTION 2: 言語知識（文法）・読解 (Q34 to Q65, 2 marks each = 64 marks)
      // =========================================================================
      // 文法 問題１ (Q34-Q49) 助詞・文法形式
      {
        order_num: 34,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n日本( )ラーメンは おいしいです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'に',
        option_b: 'の',
        option_c: 'を',
        option_d: 'へ',
        correct_option: 'B',
        marks: 2,
        explanation: '名詞と名詞を結びつけ、産地や所属を表す助詞「の」が適切です。「日本の ラーメン」（Japanese ramen）。',
        explanation_sin: 'නාම පද දෙකක් එකතු කරමින් රට/ස්ථානය සම්බන්ධ කිරීමට「の」නිපාතය යෙදේ. ජපානයේ රාමෙන් රසවත්ය.'
      },
      {
        order_num: 35,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nわたしには きょうだいが 二人います。弟( )妹です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'は',
        option_b: 'も',
        option_c: 'と',
        option_d: 'か',
        correct_option: 'C',
        marks: 2,
        explanation: '2人のきょうだいを並列して列挙する助詞「と」（and）が適切です。「弟と 妹」（Younger brother and younger sister）。',
        explanation_sin: 'සහෝදරයන් දෙදෙනා ලැයිස්තුගත කිරීමට සම්බන්ධක නිපාතයක් ලෙස「と」(සහ/හා) යොදාගනී.'
      },
      {
        order_num: 36,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n山下「田中さん( ) きのう どこかに 出かけましたか。」\n田中「いいえ、いえに いました。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'で',
        option_b: 'は',
        option_c: 'を',
        option_d: 'に',
        correct_option: 'B',
        marks: 2,
        explanation: '相手の行動について話題として取り上げる主題提示の助詞「は」が適切です。「田中さんは〜」',
        explanation_sin: 'තනකා මහතා මාතෘකාව ලෙස ගෙන ප්‍රශ්න කිරීමට මාතෘකා නිපාතය වන「は」යෙදේ.'
      },
      {
        order_num: 37,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n（タクシーで）\nA「つぎの かどを 右( ) まがって ください。」\nB「わかりました。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'が',
        option_b: 'や',
        option_c: 'か',
        option_d: 'に',
        correct_option: 'D',
        marks: 2,
        explanation: '曲がる方向を表すときは助詞「に」または「へ」を使います。「右に まがって ください」（Please turn right）。',
        explanation_sin: 'හැරෙන දිශාව දැක්වීමට「に」(වෙත/දෙසට) නිපාතය යොදාගනී. දකුණට හැරෙන්න.'
      },
      {
        order_num: 38,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nきのう、わたしは ひとり( ) えいがを 見に 行きました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'が',
        option_b: 'を',
        option_c: 'で',
        option_d: 'は',
        correct_option: 'C',
        marks: 2,
        explanation: '行動する人数の状態・限定を表す助詞「で」を使います。「ひとりで」（by oneself / alone）。',
        explanation_sin: 'තනිවම ක්‍රියාවක් කරන බව දැක්වීමට「ひとりで」(තනිවම) ලෙස「で」නිපාතය යෙදේ.'
      },
      {
        order_num: 39,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n山下「今日 パーティーが ありますから、田中さん( ) 来て ください。」\n田中「ありがとうございます。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'に',
        option_b: 'も',
        option_c: 'や',
        option_d: 'で',
        correct_option: 'B',
        marks: 2,
        explanation: '「ほかの人も来ますが、田中さんもぜひ」という追加・強調を表す助詞「も」（also）が適切です。',
        explanation_sin: 'අනෙක් අය මෙන්ම තනකා මහතාටත් ආරාධනා කිරීමට「も」(ද/පවා) නිපාතය යෙදේ.'
      },
      {
        order_num: 40,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n田中「この ぼうしは 山田さん( ) ですか。」\n山田「はい。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'や',
        option_b: 'は',
        option_c: 'の',
        option_d: 'か',
        correct_option: 'C',
        marks: 2,
        explanation: '所有を表す助詞「の」（「山田さんのぼうし」の略）が適切です。「山田さんの ですか。」（Is this Yamada\'s?）',
        explanation_sin: 'අයිතිය දැක්වීමට「の」(ගේ) නිපාතය යෙදේ. මෙම තොප්පිය යමදා මහතාගේද?'
      },
      {
        order_num: 41,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n駅まで タクシーで 1000円( ) です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ぐらい',
        option_b: 'など',
        option_c: 'ごろ',
        option_d: 'も',
        correct_option: 'A',
        marks: 2,
        explanation: '金額や数量のおおよその程度を表すときは「ぐらい」（approximately / about）を使います。「ごろ」は時刻の時点に使います。',
        explanation_sin: 'මුදලක හෝ ප්‍රමාණයක ආසන්න අගය දැක්වීමට「ぐらい」(පමණ) යොදාගනී. යෙන් 1000ක් පමණ වේ.'
      },
      {
        order_num: 42,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nA「さようなら。」\nB「さようなら。また( )。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'おととい',
        option_b: '今日',
        option_c: '来週',
        option_d: '今月',
        correct_option: 'C',
        marks: 2,
        explanation: '別れの挨拶「また〜」には未来の再会時期が入ります。選択肢の中で自然なのは「来週」（See you next week）です。',
        explanation_sin: 'සමුගැනීමේදී අනාගතයේ නැවත හමුවන දිනයක් දැක්වීමට「また 来週」(නැවත ලබන සතියේ හමුවෙමු) යන්න යෙදේ.'
      },
      {
        order_num: 43,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nわたしの 母は 50さいです。父は 55さいです。母は 父( )5さい わかいです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'から',
        option_b: 'まで',
        option_c: 'より',
        option_d: 'のほうが',
        correct_option: 'C',
        marks: 2,
        explanation: '比較の基準を表す助詞「より」（than）を使います。「母は 父より 5さい わかいです。」（Mother is 5 years younger than father.）',
        explanation_sin: 'සංසන්දනය කිරීමේදී「より」(වඩා) නිපාතය යොදාගනී. මව පියාට වඩා අවුරුදු 5ක් බාලයි.'
      },
      {
        order_num: 44,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n子ども「いただきます。」\n母「あ、食べる( ) 手を あらいましょう。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'まえに',
        option_b: 'のまえに',
        option_c: 'あとに',
        option_d: 'のあとに',
        correct_option: 'A',
        marks: 2,
        explanation: '動詞辞書形＋「まえに」（before doing）の文型です。「食べる まえに」（Before eating）。名詞の場合は「名詞＋のまえに」となります。',
        explanation_sin: 'ක්‍රියාපදයක මූලික ස්වරූපය සමග「まえに」(කලින්) යෙදේ.「食べる まえに」(කෑමට පෙර) අත් සෝදමු.'
      },
      {
        order_num: 45,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nA「東京でも 雪が ふりますか。」\nB「ええ、ふりますよ。でも、きょねんは あまり ( )。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ふりませんでした',
        option_b: 'ふりません',
        option_c: 'ふりました',
        option_d: 'ふります',
        correct_option: 'A',
        marks: 2,
        explanation: '「きょねん（去年）」という過去のこと＋「あまり」は否定形と呼応するため、過去否定形の「ふりませんでした」（didn\'t fall much）になります。',
        explanation_sin: '「きょねん」(ගිය වසර) සහ「あまり」(වැඩිය නැත) සමග අතීත සෘණාත්මක ක්‍රියාපදය වන「ふりませんでした」(වැටුණේ නැත) යෙදේ.'
      },
      {
        order_num: 46,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n(川で)\nA「見て ください。小さな 魚が たくさん( )よ。」\nB「ほんとうですね。30 ぴきくらい いますね。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'およぎます',
        option_b: 'およぎません',
        option_c: 'およぎました',
        option_d: 'およんで います',
        correct_option: 'D',
        marks: 2,
        explanation: '目の前で魚が泳いでいる現在の進行状態を表すため、「〜て います」形の「およんで います」が適切です。',
        explanation_sin: 'ඇස් ඉදිරිපිට මාළු පිහිනමින් සිටින සිදුවීම විස්තර කිරීමට「およんで います」(පිහිනමින් සිටී) යෙදේ.'
      },
      {
        order_num: 47,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n中川「山田さんの その カメラは いいですね。どこで かいましたか。」\n山田「いえ、これは 兄に ( )。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'あげました',
        option_b: 'もらいました',
        option_c: 'うりました',
        option_d: 'かいました',
        correct_option: 'B',
        marks: 2,
        explanation: '兄から自分が受け取ったことを表す授受動詞は「〜に もらいました」（received from brother）です。自分が兄にあげたのではありません。',
        explanation_sin: 'අයියාගෙන් තමාට ලැබුණු බව දැක්වීමට「兄に もらいました」(අයියාගෙන් ලැබුණා) යන්න නිවැරදිය.'
      },
      {
        order_num: 48,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nたまごりょうりの じょうずな 作りかたを ( ) 読みました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '何に',
        option_b: '何も',
        option_c: '何かへ',
        option_d: '何かで',
        correct_option: 'D',
        marks: 2,
        explanation: '本や雑誌、インターネットなど特定の手段・媒体で読んだことを不特定の手段として表す「何かで（in something / through something）」が適切です。',
        explanation_sin: 'පොතකින් හෝ යම් මාධ්‍යයකින් කියවූ බව දැක්වීමට「何かで」(මොකකින් හරි) යන්න යෙදේ.'
      },
      {
        order_num: 49,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　(　)に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n(電話で)\n本田「はい、本田です。」\n北山「あ、北山花子です。すみません、( )。」\n本田「はい。ちょっと まって くださいね。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ひろこさんを おねがいします',
        option_b: 'ひろこさんを ください',
        option_c: 'ひろこさんと 話しますか',
        option_d: 'ひろこさんと 話しませんか',
        correct_option: 'A',
        marks: 2,
        explanation: '電話で他の人への取次ぎをお願いするときの定番表現は「〜さんを おねがいします」（May I speak to ... please?）です。',
        explanation_sin: 'දුරකථන ඇමතුමකදී වෙනත් අයෙකු ඉල්ලා සිටින සම්මත ප්‍රකාශනය වන්නේ「〜さんを おねがいします」(කරුණාකර ... මහත්මියට සම්බන්ධ කරන්න) යන්නයි.'
      },

      // 文法 問題２ (Q50-Q54) 星並べ替え
      {
        order_num: 50,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題２　★に　はいる　ものは　どれですか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n(店で)\n田中「すみません。くだもの ＿＿ ＿＿ ★ ＿＿ か」\n店の人「こちらです。」\n\n1. どこ　2. あります　3. は　4. に',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'どこ',
        option_b: 'あります',
        option_c: 'は',
        option_d: 'に',
        correct_option: 'D',
        marks: 2,
        explanation: '文の組み立て：「くだものは(3) どこ(1) に(4:★) あります(2) か」。★に入るのは「4. に」です。',
        explanation_sin: 'නිවැරදි වාක්‍ය සැකසුම:「くだものは(3) どこ(1) に(4:★) あります(2) か」. ★ සලකුණ ඇති ස්ථානයට එන්නේ「4. に」වේ.'
      },
      {
        order_num: 51,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題２　★に　はいる　ものは　どれですか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nA「山下さんは？」\nB「となりの へやで ＿＿ ＿＿ ★ ＿＿ しています。」\n\n1. れんしゅう　2. の　3. ギター　4. を',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'れんしゅう',
        option_b: 'の',
        option_c: 'ギター',
        option_d: 'を',
        correct_option: 'A',
        marks: 2,
        explanation: '文の組み立て：「となりの へやで ギター(3) の(2) れんしゅう(1:★) を(4) しています。」★に入るのは「1. れんしゅう」です。',
        explanation_sin: 'නිවැරදි වාක්‍ය සැකසුම:「ギター(3) の(2) れんしゅう(1:★) を(4) しています」. ★ ස්ථානයට එන්නේ「1. れんしゅう」වේ.'
      },
      {
        order_num: 52,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題２　★に　はいる　ものは　どれですか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nA「会社 ＿＿ ＿＿ ★ ＿＿ 行って いますか。」\nB「わたしは あるいて 行って います。」\n\n1. で　2. は　3. へ　4. 何',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'で',
        option_b: 'は',
        option_c: 'へ',
        option_d: '何',
        correct_option: 'D',
        marks: 2,
        explanation: '文の組み立て：「会社 へ(3) は(2) 何(4:★) で(1) 行って いますか。」交通手段を尋ねる疑問文です。★に入るのは「4. 何」です。',
        explanation_sin: 'නිවැරදි වාක්‍ය සැකසුම:「会社 へ(3) は(2) 何(4:★) で(1) 行って いますか」. ★ ස්ථානයට එන්නේ「4. 何」වේ.'
      },
      {
        order_num: 53,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題２　★に　はいる　ものは　どれですか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n山田「ジョンさん、しゅくだいは ぜんぶ おわりましたか。」\nジョン「いいえ、まだです。ここ ＿＿ ＿＿ ★ ＿＿、さいごの もんだいが むずかしいです。」\n\n1. は　2. かんたんでした　3. が　4. まで',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'は',
        option_b: 'かんたんでした',
        option_c: 'が',
        option_d: 'まで',
        correct_option: 'B',
        marks: 2,
        explanation: '文の組み立て：「ここ まで(4) は(1) かんたんでした(2:★) が(3)、さいごの もんだいが むずかしいです。」★に入るのは「2. かんたんでした」です。',
        explanation_sin: 'නිවැරදි වාක්‍ය සැකසුම:「ここ まで(4) は(1) かんたんでした(2:★) が(3)」. ★ ස්ථානයට එන්නේ「2. かんたんでした」වේ.'
      },
      {
        order_num: 54,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題２　★に　はいる　ものは　どれですか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n(本屋で)\nヤン「わたしは この 本を 買います。アンナさんは どんな 本が いいですか。」\nアンナ「わたしは もう 少し ＿＿ ＿＿ ★ ＿＿ が いいです。」\n\n1. 本　2. かんたんな　3. の　4. 日本語',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '本',
        option_b: 'かんたんな',
        option_c: 'の',
        option_d: '日本語',
        correct_option: 'B',
        marks: 2,
        explanation: '文の組み立て：「もう 少し 日本語(4) の(3) かんたんな(2:★) 本(1) が いいです。」★に入るのは「2. かんたんな」です。',
        explanation_sin: 'නිවැරදි වාක්‍ය සැකසුම:「日本語(4) の(3) かんたんな(2:★) 本(1)」. ★ ස්ථානයට එන්නේ「2. かんたんな」වේ.'
      },

      // 文法 問題３ (Q55-Q59) 文章の文法（空欄補充）
      {
        order_num: 55,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題３　[ 22 ] に なにを 入れますか。\n\n（文章１）\nわたしは すしが すきです。日本には たくさん すし屋が ありますね。わたしの 国には すし屋が ありませんから、今 とても うれしいです。日本に [ 22 ] いろいろな 店で 食べました。学校の 前の 店は 安くて おいしいです。すしが すきな 人は、いっしょに [ 23 ]。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '行くから',
        option_b: '行ってから',
        option_c: '来るから',
        option_d: '来てから',
        correct_option: 'D',
        marks: 2,
        explanation: '話者は現在日本に滞在しているので「日本に来る」を用います。また「日本に来た後で（after coming to Japan）」という継起を表す「〜てから」の形になるため「来てから」が適切です。',
        explanation_sin: 'කථකයා දැන් සිටින්නේ ජපානයේ බැවින්「日本に来る」යෙදෙන අතර, පැමිණි පසු අර්ථයෙන්「〜てから」සමග「来てから」(පැමිණියාට පසු) යන්න නිවැරදිය.'
      },
      {
        order_num: 56,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題３　[ 23 ] に なにを 入れますか。\n\n（文章１）\nわたしは すしが すきです。日本には たくさん すし屋が ありますね。わたしの 国には すし屋が ありませんから、今 とても うれしいです。日本に [ 22 ] いろいろな 店で 食べました。学校の 前の 店は 安くて おいしいです。すしが すきな 人は、いっしょに [ 23 ]。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '行きましたか',
        option_b: '行きませんか',
        option_c: '行って いましたか',
        option_d: '行って いませんか',
        correct_option: 'B',
        marks: 2,
        explanation: '読者に「いっしょに〜（一緒に行きませんか）」と勧誘・誘いかけをしている文脈なので、「行きませんか」（Won\'t you go together?）が適切です。',
        explanation_sin: 'පාඨකයන්ට「いっしょに」(එක්ව) යමුදැයි ආරාධනා කරන බැවින්「行きませんか」(යමුද?) යන්න නිවැරදිය.'
      },
      {
        order_num: 57,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題３　[ 24 ] に なにを 入れますか。\n\n（文章２）\nわたしは えきの ちかくの 本屋が すきです。えきの ちかくの 本屋 [ 24 ] 大きい お店です。外国の 本も 売って います。わたしの 国のもの [ 25 ]。そして、わたしが すきな りょうりの 本も 多いです。[ 26 ]、本は いつも えきの ちかくの 本屋で 買います。みなさんは すきな 本屋が ありますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'か',
        option_b: 'と',
        option_c: 'の',
        option_d: 'は',
        correct_option: 'D',
        marks: 2,
        explanation: '「えきの ちかくの 本屋は 大きい お店です」と、その本屋について説明する主題の助詞「は」が適切です。',
        explanation_sin: 'දුම්රියපොළ අසල පොත්සාප්පුව ගැන විස්තර ඉදිරිපත් කිරීමේදී මාතෘකා නිපාතය වන「は」යෙදේ.'
      },
      {
        order_num: 58,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題３　[ 25 ] に なにを 入れますか。\n\n（文章２）\nわたしは えきの ちかくの 本屋が すきです。えきの ちかくの 本屋 [ 24 ] 大きい お店です。外国の 本も 売って います。わたしの 国のもの [ 25 ]。そして、わたしが すきな りょうりの 本も 多いです。[ 26 ]、本は いつも えきの ちかくの 本屋で 買います。みなさんは すきな 本屋が ありますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'います',
        option_b: '読みます',
        option_c: 'あります',
        option_d: 'します',
        correct_option: 'C',
        marks: 2,
        explanation: '「わたしの 国のもの（＝外国の本）」は無生物なので、存在を表す動詞は「あります」（there are/exist）です。',
        explanation_sin: 'පොත් යනු අජීවී ද්‍රව්‍ය බැවින් ඒවා තිබෙන බව දැක්වීමට「あります」(තිබෙනවා) යන්න යෙදේ.'
      },
      {
        order_num: 59,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題３　[ 26 ] に なにを 入れますか。\n\n（文章２）\nわたしは えきの ちかくの 本屋が すきです。えきの ちかくの 本屋 [ 24 ] 大きい お店です。外国の 本も 売って います。わたしの 国のもの [ 25 ]。そして、わたしが すきな りょうりの 本も 多いです。[ 26 ]、本は いつも えきの ちかくの 本屋で 買います。みなさんは すきな 本屋が ありますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'だから',
        option_b: 'では',
        option_c: 'それから',
        option_d: 'でも',
        correct_option: 'A',
        marks: 2,
        explanation: '前文でその本屋が好きな理由（大きく、外国の本やりょうりの本が多い）を述べた後、結論としてそこで買うと述べているので順接の接続詞「だから」（Therefore / That is why）が適切です。',
        explanation_sin: 'ඉහතින් පොත්සාප්පුව හොඳ වීමට හේතු දක්වා, එමනිසා එහි යන්නේ යැයි පැවසීමට හේතු දැක්වීමේ සම්බන්ධකය වන「だから」(එබැවින්) යෙදේ.'
      },

      // 読解 問題４ (Q60-Q62) 短文読解
      {
        order_num: 60,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題４　つぎの　ぶんしょうを　よんで、しつもんに　こたえて　ください。こたえは、１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nわたしは、今日、友だちと 買い物に 行きました。3か月前に 見た えいがの DVDが ほしかったからです。買った DVDは、友だちや 姉と いっしょに 見ます。\n\n【しつもん】「わたし」は 今日、何を しましたか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '友だちと えいがを 見に 行きました。',
        option_b: '友だちと DVDを 買いに 行きました。',
        option_c: '姉と えいがを 見に 行きました。',
        option_d: '姉と DVDを 買いに 行きました。',
        correct_option: 'B',
        marks: 2,
        explanation: '本文に「今日、友だちと 買い物に 行きました。3か月前に 見た えいがの DVDが ほしかったからです」とあるので、友だちとDVDを買いに行きました。',
        explanation_sin: 'ජේදයේ පැහැදිලිව සඳහන් වන්නේ මිතුරා සමග DVD එකක් මිලදී ගැනීමට ගිය බවයි (友だちと DVDを 買いに 行きました).'
      },
      {
        order_num: 61,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題４　つぎの　ぶんしょうを　よんで、しつもんに　こたえて　ください。こたえは、１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nわたしの へやには、テーブルが 一つと いすが 二つと 本だな が 一つ あります。本が たくさん ありますから、もっと 大きい 本だな が ほしいです。\n\n【しつもん】今の へやは どれですか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper3/reading_q28_rooms.jpg',
        audio_url: null,
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'C',
        marks: 2,
        explanation: '条件は「テーブルが一つ、いすが二つ、本だな（本棚）が一つ」です。イラスト3がテーブル1つ、いす2つ、本棚1つを正確に表しています。',
        explanation_sin: 'කාමරයේ කොන්දේසි: මේස 1ක්, පුටු 2ක් සහ පොත් රාක්ක 1ක්. මේවා නිවැරදිව පෙන්වන්නේ රූප සටහන් 3 මගිනි.'
      },
      {
        order_num: 62,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題４　つぎの　ぶんしょうを　よんで、しつもんに　こたえて　ください。こたえは、１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n森さんの 机の 上に、山口先生の メモと 本が あります。\n\n【メモ】\n森さん\nクラスで 使う 本を 中川先生に かりました。５ページを 25枚 コピーして ください。コピーは 南さんに わたして ください。本は、わたしが あした かえしますから、わたしの 机の 上に おいて ください。\n山口\n\n【しつもん】森さんは コピーを した あとで、本を どうしますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'クラスで 使います。',
        option_b: '南さんに わたします。',
        option_c: '中川先生に かえします。',
        option_d: '山口先生の 机の 上に おきます。',
        correct_option: 'D',
        marks: 2,
        explanation: 'メモの最後に「本は、わたしが あした かえしますから、わたしの 机の 上に おいて ください。山口」とあるので、山口先生の机の上に置きます。',
        explanation_sin: 'සටහනේ අවසානයේ「わたしの 机の 上に おいて ください。山口」(යමගුචි ගුරුතුමාගේ මේසය උඩ තබන්න) ලෙස පැහැදිලිව සඳහන් වේ.'
      },

      // 読解 問題５ (Q63-Q64) 中文読解
      {
        order_num: 63,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題５　つぎの　ぶんしょうを　よんで、しつもんに　こたえて　ください。こたえは、１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nきのうの 夜は おそくまで しごとを しました。とても つかれました。しごとの あと、電車で 帰りました。家の 近くの 駅で 電車を おりました。外は 雨でしたが、わたしは かさが ありませんでした。とても こまりました。駅の 人が わたしを 見て、「あの はこの 中の かさを 使って ください。」と 言いました。はこの 中には かさが ３本 ありました。わたしは「えっ、いいんですか。」と 聞きました。駅の 人は「あれは みなの かさです。お金は いりません。あした、あの はこに かえして ください。」と 言いました。わたしは「わかりました。ありがとうございます。」と 言って、かさを かりて 帰りました。\n\n【しつもん１】どうして こまりましたか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'おそい 時間に 駅に 着いたから',
        option_b: 'しごとが たくさん あったから',
        option_c: 'とても つかれたから',
        option_d: 'かさが なかったから',
        correct_option: 'D',
        marks: 2,
        explanation: '本文に「外は 雨でしたが、わたしは かさが ありませんでした。とても こまりました」とあるので、雨が降っているのに傘を持っていなかったからです。',
        explanation_sin: 'ජේදයේ සඳහන් වන්නේ පිටත වැසි වැටුණත් කුඩයක් නොතිබූ නිසා අපහසුතාවයට පත් වූ බවයි (かさが なかったから).'
      },
      {
        order_num: 64,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題５　つぎの　ぶんしょうを　よんで、しつもんに　こたえて　ください。こたえは、１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n（文章は前の問題と同じ）\nきのうの 夜は おそくまで しごとを しました。とても つかれました。しごとの あと、電車で 帰りました。家の 近くの 駅で 電車を おりました。外は 雨でしたが、わたしは かさが ありませんでした。とても こまりました。駅の 人が わたしを 見て、「あの はこの 中の かさを 使って ください。」と 言いました。はこの 中には かさが ３本 ありました。わたしは「えっ、いいんですか。」と 聞きました。駅の 人は「あれは みなの かさです。お金は いりません。あした、あの はこに かえして ください。」と 言いました。わたしは「わかりました。ありがとうございます。」と 言って、かさを かりて 帰りました。\n\n【しつもん２】「わたし」は あした どうしますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'お金を はこの 中に 入れます。',
        option_b: 'お金を 駅の 人に わたします。',
        option_c: 'かさを はこの 中に 入れます。',
        option_d: 'かさを 駅の 人に わたします。',
        correct_option: 'C',
        marks: 2,
        explanation: '駅の人が「あした、あの はこに かえして ください」と言ったので、明日傘をその箱の中に返します（入れます）。',
        explanation_sin: 'දුම්රියපොළේ නිලධාරියා පැවසූ පරිදි හෙට දිනයේදී කුඩය නැවත එම පෙට්ටියට දැමිය යුතුය (かさを はこの 中に 入れます).'
      },

      // 読解 問題６ (Q65) 情報検索
      {
        order_num: 65,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題６　右のページの　チラシを　見て、しつもんに　こたえて　ください。こたえは、１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nあきらやで トイレットペーパーと にくと やさいを 同じ 日に 買いたいです。いつが 安いですか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper3/reading_q32_flyer.jpg',
        audio_url: null,
        option_a: '6月 17日(日)と 18日(月)',
        option_b: '6月 13日(水)と 14日(木)',
        option_c: '6月 15日(金)と 16日(土)',
        option_d: '6月 11日(月)と 12日(火)',
        correct_option: 'B',
        marks: 2,
        explanation: 'チラシを確認すると、トイレットペーパーの安売り日は6月13日(水)・14日(木)です。また、6月13日・14日は「野菜・肉」の割引日にも該当するため、同じ日に両方安く買えるのは「6月 13日(水)と 14日(木)」です。',
        explanation_sin: 'වෙළඳ දැන්වීම පත්‍රිකාව අනුව ටොයිලට් පේපර් සහ මස්/එළවළු යන දෙවර්ගයම එකම දිනක ලාභදායී මිලකට ගත හැක්කේ ජූනි 13 සහ 14 යන දිනවලදීය.'
      },

      // =========================================================================
      // SECTION 3: 聴解 (Q66 to Q89, 2 marks each = 48 marks)
      // =========================================================================
      // 聴解 問題１ (Q66-Q72) 課題理解
      {
        order_num: 66,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題１　問題１では、まず しつもんを きいて ください。それから はなしを きいて、問題用紙の １から４の なかから、いちばん いい ものを ひとつ えらんで ください。\n\n１番：男の人と 女の人が 話して います。女の人は どの スカートを 履きますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper3/listening_m1_q1.jpg',
        audio_url: audioTrackUrl,
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'B',
        marks: 2,
        explanation: '音声会話の指示：女性は白無地の長いスカート（2番）を選びます。',
        explanation_sin: 'ශ්‍රව්‍ය දෙබසට අනුව කාන්තාව තෝරාගන්නේ දිගු, රටා නැති සුදු සායයි (2).'
      },
      {
        order_num: 67,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題１\n\n２番：男の人と 女の人が 話して います。男の人は 何階へ 行きますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '1かい',
        option_b: '2かい',
        option_c: '3かい',
        option_d: '4かい',
        correct_option: 'B',
        marks: 2,
        explanation: '男の人が行く階は2階です。正解は2（2かい）です。',
        explanation_sin: 'පිරිමි පුද්ගලයා යා යුත්තේ 2 වන මහලටයි (2かい).'
      },
      {
        order_num: 68,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題１\n\n３番：男の人と 女の人が 話して います。男の人は どれを 取りますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper3/listening_m1_q3.jpg',
        audio_url: audioTrackUrl,
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'C',
        marks: 2,
        explanation: '指示されたカップの特徴に合致するのは3番です。',
        explanation_sin: 'දෙබසේ විස්තරයට ගැළපෙන කෝප්පය වන්නේ 3 වන රූපයයි.'
      },
      {
        order_num: 69,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題１\n\n４番：男の人と 女の人が 話して います。女の人は どの 鞄を 買いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper3/listening_m1_q4.jpg',
        audio_url: audioTrackUrl,
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'C',
        marks: 2,
        explanation: '女性が選んだ鞄の特徴（丸型・デザイン等）に合致するのは3番です。',
        explanation_sin: 'කාන්තාව මිලදී ගැනීමට තීරණය කරන බෑගය වන්නේ 3 වන රූපයයි.'
      },
      {
        order_num: 70,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題１\n\n５番：男の人と 女の人が ホテルで 話して います。二人は これから まず どこへ 行きますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'レストランへ 行きます',
        option_b: '部屋へ 行きます',
        option_c: '買い物を します',
        option_d: 'テレビを 見ます',
        correct_option: 'A',
        marks: 2,
        explanation: '二人はまず食事のためにレストランへ行きます。',
        explanation_sin: 'දෙදෙනා පළමුවෙන්ම කෑම ගැනීම සඳහා අවන්හලට යනු ඇත (レストランへ 行きます).'
      },
      {
        order_num: 71,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題１\n\n６番：学校で 先生が 話して います。学生は あした 何を 持って 行きますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'おにぎり',
        option_b: 'お菓子',
        option_c: '飲み物',
        option_d: '何も 持っていかない',
        correct_option: 'D',
        marks: 2,
        explanation: '必要なものはすべて用意されているため、学生は何も持って行かなくてよいことになります（4. 何も 持っていかない）。',
        explanation_sin: 'සියලු දෑ සපයන බැවින් සිසුන්ට කිසිවක් රැගෙන ඒමට අවශ්‍ය නැත (何も 持っていかない).'
      },
      {
        order_num: 72,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題１\n\n７番：駅で 男の人と 女の人が 話して います。男の人は 何番の バスに 乗りますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '1番のバス',
        option_b: '3番のバス',
        option_c: '5番のバス',
        option_d: '7番のバス',
        correct_option: 'D',
        marks: 2,
        explanation: '会話で案内されたバスの番号は7番です。',
        explanation_sin: 'දෙබසේ උපදෙස් අනුව පිරිමි පුද්ගලයා ගමන් කළ යුත්තේ අංක 7 බස් රථයෙනි (7番のバス).'
      },

      // 聴解 問題２ (Q73-Q78) ポイント理解
      {
        order_num: 73,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題２　問題２では、まず しつもんを きいて ください。そのあと、問題用紙の せんたくしを よんで ください。よむ じかんが あります。それから はなしを きいて、問題用紙の １から４の なかから、いちばん いい ものを ひとつ えらんで ください。\n\n１番：男の人と 女の人が 話して います。女の人は きのう 何時間 勉強しましたか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '1時間',
        option_b: '2時間',
        option_c: '3時間',
        option_d: '4時間',
        correct_option: 'D',
        marks: 2,
        explanation: '女性が昨日勉強した合計時間は4時間です。',
        explanation_sin: 'කාන්තාව ඊයේ පාඩම් කළ මුළු කාලය පැය 4 කි (4時間).'
      },
      {
        order_num: 74,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題２\n\n２番：男の人と 女の人が 電話で 話して います。田中さんの 電話番号は 何番ですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '512-7734',
        option_b: '512-7744',
        option_c: '512-7743',
        option_d: '512-7733',
        correct_option: 'C',
        marks: 2,
        explanation: '田中さんの正しい電話番号は「512-7743」です。',
        explanation_sin: 'තනකා මහතාගේ නිවැරදි දුරකථන අංකය 512-7743 වේ.'
      },
      {
        order_num: 75,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題２\n\n３番：男の人と 女の人が 話して います。女の人は だれと 日本へ 来ましたか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '両親',
        option_b: '姉',
        option_c: '弟',
        option_d: '姉と弟',
        correct_option: 'B',
        marks: 2,
        explanation: '女性が一緒に日本へ来たのはお姉さん（姉）です。',
        explanation_sin: 'කාන්තාව ජපානයට පැමිණියේ ඇයගේ අක්කා (姉) සමගය.'
      },
      {
        order_num: 76,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題２\n\n４番：男の人と 女の人が 話して います。二人は どこで 昼ごはんを 食べますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '食堂',
        option_b: '喫茶店',
        option_c: 'パン屋',
        option_d: '教室',
        correct_option: 'D',
        marks: 2,
        explanation: '食堂等が混んでいるなどの理由で、二人はパンを買って教室（教室）で食べることになりました。',
        explanation_sin: 'දෙදෙනා දිවා ආහාරය ගැනීමට තීරණය කරන්නේ පන්ති කාමරයේදීය (教室).'
      },
      {
        order_num: 77,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題２\n\n５番：男の人と 女の人が 話して います。テストでは 何で 書きますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '黒のボールペン',
        option_b: '赤のボールペン',
        option_c: '鉛筆',
        option_d: '万年筆',
        correct_option: 'A',
        marks: 2,
        explanation: 'テストの記入用具として指定されたのは「黒のボールペン」（黒のボールペン）です。',
        explanation_sin: 'විභාගය ලිවීම සඳහා භාවිත කළ යුතු බවට උපදෙස් ලැබෙන්නේ කළු බෝල්පොයින්ට් පෑනයි (黒のボールペン).'
      },
      {
        order_num: 78,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題２\n\n６番：男の人と 女の人が 話して います。二人は どこで 会いますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'レストラン',
        option_b: 'サッカー場',
        option_c: '駅の前の喫茶店',
        option_d: '駅',
        correct_option: 'C',
        marks: 2,
        explanation: '待ち合わせ場所として決まったのは「駅の前の喫茶店」です。',
        explanation_sin: 'දෙදෙනා හමුවීමට තීරණය කළ ස්ථානය දුම්රියපොළ ඉදිරිපිට කැෆේ එකයි (駅の前の喫茶店).'
      },

      // 聴解 問題３ (Q79-Q83) 発話表現 (3 options; option_d = "")
      {
        order_num: 79,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題３　問題３では、えを みながら しつもんを きいて ください。やじるし（➡）の ひとは なんと いいますか。１から３の なかから、いちばん いい ものを ひとつ えらんで ください。\n\n１番：ご飯を 食べ終わりました。何と 言いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper3/listening_m3_q1.jpg',
        audio_url: audioTrackUrl,
        option_a: 'ごちそうさまでした',
        option_b: 'いただきます',
        option_c: 'どういたしまして',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '食事を食べ終わったあとの挨拶は「ごちそうさまでした」です。',
        explanation_sin: 'කෑම කා අවසන් වූ පසු කියන සම්මත ආචාර වචනය「ごちそうさまでした」(ගොචිසෝසමාදෙශිතා) වේ.'
      },
      {
        order_num: 80,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題３\n\n２番：電車の中で 席を ゆずります。何と 言いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper3/listening_m3_q2.jpg',
        audio_url: audioTrackUrl,
        option_a: 'どうもありがとう',
        option_b: 'はじめまして',
        option_c: 'ここ、どうぞ',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '電車で席を譲るときは「ここ、どうぞ」（Please, take this seat）と言います。',
        explanation_sin: 'දුම්රියේදී අසුනක් පරිත්‍යාග කිරීමේදී「ここ、どうぞ」(මෙතනින් වාඩිවෙන්න) යන්න පැවසිය යුතුය.'
      },
      {
        order_num: 81,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題３\n\n３番：友だちと 別れます。何と 言いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper3/listening_m3_q3.jpg',
        audio_url: audioTrackUrl,
        option_a: '行ってきます',
        option_b: 'じゃ、また',
        option_c: 'ただいま',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '友人と別れるときの気軽な挨拶は「じゃ、また」（See you later）です。',
        explanation_sin: 'මිතුරෙකුගෙන් සමුගන්නා විට පවසන්නේ「じゃ、また」(එහෙනම් නැවත හමුවෙමු) යන්නයි.'
      },
      {
        order_num: 82,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題３\n\n４番：郵便局で 切手を 買いたいです。何と 言いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper3/listening_m3_q4.jpg',
        audio_url: audioTrackUrl,
        option_a: '切手をかいませんか',
        option_b: '切手をどうぞ',
        option_c: '切手をください',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '郵便局の窓口で切手を求めるときは「切手をください」（Stamps, please）と言います。',
        explanation_sin: 'තැපැල් කාර්යාලයෙන් මුද්දර ඉල්ලීමේදී「切手をください」(මුද්දර ලබා දෙන්න) යන්න යෙදේ.'
      },
      {
        order_num: 83,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題３\n\n５番：友だちに 鉛筆を 貸します。何と 言いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper3/listening_m3_q5.jpg',
        audio_url: audioTrackUrl,
        option_a: 'えんぴつ、借りましょうか',
        option_b: 'えんぴつ、使いますか',
        option_c: 'えんぴつ、貸してください',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '友人に鉛筆を貸してあげようと勧めるときは「えんぴつ、使いますか」（Would you like to use this pencil?）と言います。',
        explanation_sin: 'මිතුරෙකුට පැන්සලක් දීමට යෝජනා කිරීමේදී「えんぴつ、使いますか」(පැන්සලක් පාවිච්චි කරනවද?) යන්න යෙදේ.'
      },

      // 聴解 問題４ (Q84-Q89) 即時応答 (3 options; option_d = "")
      {
        order_num: 84,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題４　問題４では、えなどが ありません。ぶんを きいて、１から３の なかから、いちばん いい ものを ひとつ えらんで ください。\n\n１番：日本へ 来てから どのくらいに なりますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '三日です',
        option_b: '三週間です',
        option_c: '3時です',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '期間を尋ねる質問（どのくらいになりますか）に対し、期間を表す「三日です」（It has been three days）が適切です。',
        explanation_sin: 'ගත වූ කාලය විමසන ප්‍රශ්නයට පිළිතුරක් ලෙස「三日です」(දින තුනකි) යන්න ගැළපේ.'
      },
      {
        order_num: 85,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題４\n\n２番：図書館は どこですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'あそこです',
        option_b: '6時までです',
        option_c: '本を借ります',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '場所を尋ねる「どこですか」に対し、場所を指し示す「あそこです」（It is over there）が適切です。',
        explanation_sin: 'ස්ථානය විමසන බැවින් ස්ථානයක් පෙන්වා දෙන「あそこです」(අර එතනයි) යන්න නිවැරදිය.'
      },
      {
        order_num: 86,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題４\n\n３番：会議は 何時からですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'バスできます',
        option_b: '9時半です',
        option_c: '六人です',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '開始時刻を尋ねる「何時からですか」に対し、時刻を答える「9時半です」（It is from 9:30）が適切です。',
        explanation_sin: 'ආරම්භක වේලාව විමසන බැවින් වේලාවක් දක්වන「9時半です」(9:30 ට) යන්න නිවැරදිය.'
      },
      {
        order_num: 87,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題４\n\n４番：荷物を 持ちましょうか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'どういたしまして',
        option_b: '持ちませんでした',
        option_c: 'ありがとうございます',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '手伝いの申し出（〜ましょうか）に対して感謝を伝える「ありがとうございます」（Thank you very much）が適切です。',
        explanation_sin: 'උදව් කිරීමට ඉදිරිපත් වන විට කෘතඥතාව පළ කිරීමට「ありがとうございます」(බොහොම ස්තූතියි) යන්න ගැළපේ.'
      },
      {
        order_num: 88,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題４\n\n５番：あした、いっしょに 映画を 見に 行きませんか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '日曜日です',
        option_b: 'お元気ですか',
        option_c: 'そうしましょう',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '誘い（〜ませんか）に対する同意表現として「そうしましょう」（Let\'s do so）が適切です。',
        explanation_sin: 'ආරාධනයක් පිළිගැනීමේදී「そうしましょう」(එසේ කරමු) යන්න පැවසිය යුතුය.'
      },
      {
        order_num: 89,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題４\n\n６番：それは 何の本ですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '料理の本です',
        option_b: '私の本です',
        option_c: 'はい、そうです',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '本の内容・種類を尋ねる「何の本ですか」に対し、内容を答える「料理の本です」（It is a cooking book）が適切です。',
        explanation_sin: 'පොතේ අන්තර්ගතය කුමක්දැයි විමසන බැවින්「料理の本です」(ඉවුම් පිහුම් පොතකි) යන්න නිවැරදිය.'
      }
    ];

    console.log(`Prepared ${questionsData.length} questions for Paper 03.`);

    // Delete existing questions for this exam to ensure fresh, idempotent state
    await query.run("DELETE FROM questions WHERE exam_id = ?", [examId]);
    console.log(`Cleared existing questions for exam ID ${examId}.`);

    // Insert all 89 questions
    for (const q of questionsData) {
      await query.run(`
        INSERT INTO questions (
          exam_id, section_name, question_text, question_type,
          image_url, audio_url,
          option_a, option_b, option_c, option_d,
          correct_option, marks, explanation, explanation_sin, order_num, difficulty_level
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId,
        q.section_name,
        q.question_text,
        q.question_type,
        q.image_url,
        q.audio_url,
        q.option_a,
        q.option_b,
        q.option_c,
        q.option_d,
        q.correct_option,
        q.marks,
        q.explanation,
        q.explanation_sin,
        q.order_num,
        'N5'
      ]);
    }

    console.log(`✅ Successfully seeded all ${questionsData.length} questions for "${title}" (Exam ID: ${examId})!`);

    // Verification check
    const countCheck = await query.get("SELECT COUNT(*) as count FROM questions WHERE exam_id = ?", [examId]);
    console.log(`Verification: Exam ID ${examId} now has ${countCheck.count} questions.`);

    // Check Exam ID 2 intact
    const exam2Check = await query.get("SELECT COUNT(*) as count FROM questions WHERE exam_id = 2");
    console.log(`Safety Check: Original Mock Exam ID 2 question count = ${exam2Check.count} (Must be exactly 8).`);

    // Check Exam ID 184 intact
    const exam184Check = await query.get("SELECT COUNT(*) as count FROM questions WHERE exam_id = 184");
    console.log(`Safety Check: Paper 02 Exam ID 184 question count = ${exam184Check.count} (Must be exactly 67).`);

    return { examId, totalQuestions: countCheck.count };
  } catch (err) {
    console.error('Error in seedJLPTN5Paper03:', err);
    throw err;
  }
}

module.exports = { seedJLPTN5Paper03 };

if (require.main === module) {
  seedJLPTN5Paper03()
    .then((result) => {
      console.log('Seeding completed successfully:', result);
      process.exit(0);
    })
    .catch((err) => {
      console.error('Seeding failed:', err);
      process.exit(1);
    });
}
