const { query } = require('../config/database');

async function seedJftModelPaper16() {
  console.log('Seeding JFT-Basic Official Model Paper 16 (60 Questions, 250 Marks, Pass 200)...');
  const title = 'JFT-Basic Official Model Paper 16 (60 Minutes)';

  try {
    let exam = await query.get("SELECT id FROM exams WHERE title = ? OR title LIKE '%Paper 16%'", [title]);
    let examId;

    if (exam) {
      examId = exam.id;
      console.log(`Found existing Exam ID: ${examId}, resetting questions...`);
      await query.run('DELETE FROM questions WHERE exam_id = ?', [examId]);
      await query.run(`
        UPDATE exams 
        SET course_id = 1,
            title = ?,
            description = 'Official JFT-Basic Prometric Computer-Based Examination Paper 16 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Listening Audio Tracks and Sinhala Explanations)',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [title, examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (
          1,
          ?,
          'Official JFT-Basic Prometric Computer-Based Examination Paper 16 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Listening Audio Tracks and Sinhala Explanations)',
          60,
          200,
          1
        )
      `, [title]);
      examId = res.id;
      console.log(`Created new Exam ID: ${examId}`);
    }

    const questions = [
      // ================= SECTION 1: Script & Vocabulary (文字・語彙 - Q01 to Q15) =================
      {
        order_num: 1,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft16/jft16_img_1.jpg',
        audio_url: null,
        option_a: 'ひこうき',
        option_b: 'くうこう',
        option_c: '駅',
        option_d: '',
        correct_option: 'B',
        marks: 1,
        explanation: 'くうこう (空港) = ගුවන්තොටුපළ / Airport. ひこうき = ගුවන් යානය. えき = දුම්රිය ස්ථානය.'
      },
      {
        order_num: 2,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft16/jft16_img_2.jpg',
        audio_url: null,
        option_a: 'くうこう',
        option_b: 'ひこうき',
        option_c: '駅',
        option_d: '',
        correct_option: 'C',
        marks: 1,
        explanation: 'えき (駅) = දුම්රිය ස්ථානය / Railway Station.'
      },
      {
        order_num: 3,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft16/jft16_img_3.jpg',
        audio_url: null,
        option_a: 'バス',
        option_b: 'バスてい',
        option_c: '駅',
        option_d: '',
        correct_option: 'B',
        marks: 1,
        explanation: 'バスてい (バス停) = බස් නැවතුම්පොළ / Bus stop.'
      },
      {
        order_num: 4,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft16/jft16_img_4.jpg',
        audio_url: null,
        option_a: '病気',
        option_b: '病院',
        option_c: 'ホテル',
        option_d: '',
        correct_option: 'B',
        marks: 1,
        explanation: 'びょういん (病院) = රෝහල / Hospital. びょうき = රෝගය.'
      },
      {
        order_num: 5,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft16/jft16_img_5.jpg',
        audio_url: null,
        option_a: '学校',
        option_b: '庭',
        option_c: '公園',
        option_d: '',
        correct_option: 'C',
        marks: 1,
        explanation: 'こうえん (公園) = උද්‍යානය / Public park playground.'
      },
      {
        order_num: 6,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\n友達（　　）やくそく（　　）しました。',
        image_url: null,
        audio_url: null,
        option_a: 'が・が',
        option_b: 'と・と',
        option_c: 'と・を',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: 'මිතුරෙකු සමග පොරොන්දුවක් වීම: 「友達と 約束を しました」。'
      },
      {
        order_num: 7,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\nこの料理は味（　　）うすいですから、もっとしお（　　）入れてください。',
        image_url: null,
        audio_url: null,
        option_a: 'が・に',
        option_b: 'が・が',
        option_c: 'が・を',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: 'රස අඩු බැවින් ලුණු දමන්න: 「味が うすいですから、しおを 入れてください」。'
      },
      {
        order_num: 8,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\nあの歌手はとても人気（　　）あります。',
        image_url: null,
        audio_url: null,
        option_a: 'に',
        option_b: 'が',
        option_c: 'を',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: 'ජනප්‍රියයි: 「人気が あります」。'
      },
      {
        order_num: 9,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\n子供は公園の中（　　）走りまわっています。',
        image_url: null,
        audio_url: null,
        option_a: 'に',
        option_b: 'を',
        option_c: 'が',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: 'චලනය වන අවකාශය දැක්වීමට 「〜を 走りまわっています」.'
      },
      {
        order_num: 10,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\n母（　　）作ったケーキ（　　）これです。',
        image_url: null,
        audio_url: null,
        option_a: 'の・を',
        option_b: 'が・は',
        option_c: 'の・も',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: 'නාම විශේෂණ වාක්‍ය ඛණ්ඩයක කර්තෘ 「が」සහ ප්‍රධාන වාක්‍යයේ මාතෘකාව 「は」: 「母が作ったケーキはこれです」。'
      },
      {
        order_num: 11,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）の漢字のひらがなはどう書きますか。\n私は【西洋】の文学が好きです。',
        image_url: null,
        audio_url: null,
        option_a: 'せいゆう',
        option_b: 'とうよう',
        option_c: 'せいよう',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '西洋 = せいよう (බටහිර රටවල් / Western world).'
      },
      {
        order_num: 12,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）の漢字のひらがなはどう書きますか。\n妹の【代わり】に手紙を書きました。',
        image_url: null,
        audio_url: null,
        option_a: 'わかり',
        option_b: 'かわり',
        option_c: 'まわり',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '代わり = かわり (වෙනුවට / Instead of).'
      },
      {
        order_num: 13,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）の漢字のひらがなはどう書きますか。\n妹の代わりに【手紙】を書きました。',
        image_url: null,
        audio_url: null,
        option_a: 'てがみ',
        option_b: 'はがき',
        option_c: 'ふうとう',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '手紙 = てがみ (ලිපිය / Letter).'
      },
      {
        order_num: 14,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）の漢字のひらがなはどう書きますか。\nもう少し【低い】いすを貸してください。',
        image_url: null,
        audio_url: null,
        option_a: 'たかい',
        option_b: 'ひくい',
        option_c: 'ながい',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '低い = ひくい (මිටි / පහත් / Low).'
      },
      {
        order_num: 15,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）の漢字のひらがなはどう書きますか。\nもう少し低いいすを【貸して】ください。',
        image_url: null,
        audio_url: null,
        option_a: 'かりて',
        option_b: 'かして',
        option_c: 'かいて',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '貸して = かして (ණයට / තාවකාලිකව දෙන්න / Lend).'
      },

      // ================= SECTION 2: Conversation & Grammar (会話・文法 - Q16 to Q30) =================
      {
        order_num: 16,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文と同じ意味の文を選びなさい。\n「てつだいましょうか。」',
        image_url: null,
        audio_url: null,
        option_a: 'てつだえますか',
        option_b: 'てつだってあげます',
        option_c: 'てつだってください',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'උදව් කිරීමට ස්වේච්ඡාවෙන් ඉදිරිපත් වීම: 「てつだってあげます」(මම ඔබට උදව් කරන්නද).'
      },
      {
        order_num: 17,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文と同じ意味の文を選びなさい。\n「ブラウンさんは留学生です。ドイツから来ました。」',
        image_url: null,
        audio_url: null,
        option_a: 'ブラウンさんはドイツからりょこうに来ました。',
        option_b: 'ブラウンさんはドイツから働きに来ました。',
        option_c: 'ブラウンさんはドイツから勉強に来ました。',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '留学生 (විදේශ ශිෂ්‍යයා) = ඉගෙනීමට පැමිණි අයෙකි (勉強に来ました).'
      },
      {
        order_num: 18,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文と同じ意味の文を選びなさい。\n「田中さんは35さいです。どくしんです。」',
        image_url: null,
        audio_url: null,
        option_a: '田中さんは35さいです。けっこんしていません。',
        option_b: '田中さんは35さいです。しごとをしていません。',
        option_c: '田中さんは35さいです。子供がいません。',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'どくしん (独身) = අවිවාහක / නොබැඳි (けっこんしていません).'
      },
      {
        order_num: 19,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文と同じ意味の文を選びなさい。\n「こんやのパーティーは何時からですか。」',
        image_url: null,
        audio_url: null,
        option_a: 'こんどのパーティーは何時からですか。',
        option_b: '今日の夜のパーティーは何時からですか。',
        option_c: '今週のパーティーは何時からですか。',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'こんや (今夜) = අද රාත්‍රිය (今日の夜).'
      },
      {
        order_num: 20,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文と同じ意味の文を選びなさい。\n「ひまなとき、うちでおんがくを聞きます」',
        image_url: null,
        audio_url: null,
        option_a: 'いそがしくないとき、うちでおんがくをききます。',
        option_b: 'うるさくないとき、うちでおんがくをききます。',
        option_c: 'たのしくないとき、うちでおんがくをききます。',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ひまなとき (විවේක වේලාවට) = කාර්යබහුල නොවන විට (いそがしくないとき).'
      },
      {
        order_num: 21,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、（　　）に一番いいものを一つ選んでください。\nA：明日、どこ（　　）出かけますか。\nB：いいえ、どこも行きません。',
        image_url: null,
        audio_url: null,
        option_a: 'かへ',
        option_b: 'も',
        option_c: 'が',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'කොහේ හෝ තැනක: 「どこかへ 出かけますか」。'
      },
      {
        order_num: 22,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(22)に入る一番いいものを一つ選んでください。\nA：明日(22)＿＿＿＿といいなあ。\nB：どうして。',
        image_url: null,
        audio_url: null,
        option_a: '晴れる',
        option_b: '晴れます',
        option_c: '晴れました',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'පැතුමක් ප්‍රකාශ කිරීම: 「〜といいなあ」ඉදිරියට Dictionary form: 晴れる.'
      },
      {
        order_num: 23,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(23)に入る一番いいものを一つ選んでください。\nA：明日(23)＿＿＿＿、パパといっしょにゆうえんちに行く予定なんだ。',
        image_url: null,
        audio_url: null,
        option_a: '晴れました',
        option_b: '晴れたら',
        option_c: '晴れたとき',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'කොන්දේසියක්: කාලගුණය යහපත් වුවහොත් (晴れたら).'
      },
      {
        order_num: 24,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(24)に入る一番いいものを一つ選んでください。\nA：富士山に(24)＿＿＿＿ことがありますか。\nB：いいえ、ありません。',
        image_url: null,
        audio_url: null,
        option_a: '登った',
        option_b: '登りました',
        option_c: '登る',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'අත්දැකීම් විමසීමට: 「V-た ことがありますか」(登ったことがありますか).'
      },
      {
        order_num: 25,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(25)に入る一番いいものを一つ選んでください。\nB：ぜひ(25)＿＿＿＿みたいです。',
        image_url: null,
        audio_url: null,
        option_a: '登ります',
        option_b: '登った',
        option_c: '登って',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'යමක් කර බැලීමේ ආශාව: 「V-て みたいです」(登ってみたいです).'
      },
      {
        order_num: 26,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、（　　）に一番いいものを一つ選んでください。\nA：何を飲むか、決めましたか。\nB：私はビールを＿＿＿＿しました。',
        image_url: null,
        audio_url: null,
        option_a: '飲むに',
        option_b: '飲みに',
        option_c: '飲みすぎ',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'තීරණය දැක්වීමට 「ビールを 飲みに / 飲むことに しました」.'
      },
      {
        order_num: 27,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(27)に入る一番いいものを一つ選んでください。\nA：このカメラは以前のより、ずっと使い方が(27)＿＿＿＿ですね。\nB：こんなにかんたんと、みんな使えますね。',
        image_url: null,
        audio_url: null,
        option_a: 'かんたんな',
        option_b: 'かんたん',
        option_c: 'かんたんに',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'භාවිතය පහසුයි: 「使い方が かんたんですね」。'
      },
      {
        order_num: 28,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(28)に入る一番いいものを一つ選んでください。\nA：そうです。お年よりも、子供も(28)＿＿＿＿よ。',
        image_url: null,
        audio_url: null,
        option_a: '使う',
        option_b: '使えます',
        option_c: '使って',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'හැකියාව දැක්වීම (Potential form): 「使えます」(භාවිතා කළ හැක).'
      },
      {
        order_num: 29,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(29)に入る一番いいものを一つ選んでください。\n客：すみません、この服を(29)＿＿＿＿みたいんですが。',
        image_url: null,
        audio_url: null,
        option_a: 'しちゃくする',
        option_b: 'しちゃく',
        option_c: 'しちゃくし',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ඇඳ බැලීමට: 「試着してみたいんですが」(しちゃくし).'
      },
      {
        order_num: 30,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(30)に入る一番いいものを一つ選んでください。\n店員：ええ、どうぞ。あちらで(30)＿＿＿＿ください。',
        image_url: null,
        audio_url: null,
        option_a: 'しちゃくして',
        option_b: 'しちゃくし',
        option_c: 'しちゃくに',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ඉල්ලීමක්: 「しちゃくして ください」(එහිදී ඇඳ බලන්න).'
      },

      // ================= SECTION 3: Listening Comprehension (聴解 - Choukai - Q31 to Q45) =================
      {
        order_num: 31,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、キムさんのけっこんのお祝いに合う絵（a, b, c, d）を選んでください。',
        image_url: '/uploads/images/jft16/jft16_img_6.jpg',
        audio_url: '/uploads/audio/jft16_q31.mp3',
        option_a: 'a (絵・時計)',
        option_b: 'b (シャツ・ネクタイ)',
        option_c: 'c (ペン・腕時計)',
        option_d: 'd (ベビー服・おもちゃ)',
        correct_option: 'C',
        marks: 5,
        explanation: 'විවාහ මංගල්‍යයට ඔරලෝසුව සහ පෑන තෑගි දෙන බව පවසයි (c).'
      },
      {
        order_num: 32,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、ジョイさんの出産のお祝いに合う絵（a, b, c, d）を選んでください。',
        image_url: '/uploads/images/jft16/jft16_img_7.jpg',
        audio_url: '/uploads/audio/jft16_q32.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c',
        option_d: 'd (ベビー服・おもちゃ)',
        correct_option: 'D',
        marks: 5,
        explanation: 'දරුවා ඉපදීම වෙනුවෙන් ළදරු ඇඳුම් සහ සෙල්ලම් බඩු තෑගි දෙයි (d).'
      },
      {
        order_num: 33,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、よしださんの就職のお祝いに合う絵（a, b, c, d）を選んでください。',
        image_url: '/uploads/images/jft16/jft16_img_8.jpg',
        audio_url: '/uploads/audio/jft16_q33.mp3',
        option_a: 'a',
        option_b: 'b (ネクタイ・シャツ)',
        option_c: 'c',
        option_d: 'd',
        correct_option: 'B',
        marks: 5,
        explanation: 'රැකියාව ලැබීම වෙනුවෙන් ටයි පටියක් සහ කමිසයක් තෑගි කරයි (b).'
      },
      {
        order_num: 34,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、すずきさんの父の日に合う絵（a, b, c, d）を選んでください。',
        image_url: '/uploads/images/jft16/jft16_img_9.jpg',
        audio_url: '/uploads/audio/jft16_q34.mp3',
        option_a: 'a (絵・時計)',
        option_b: 'b',
        option_c: 'c',
        option_d: 'd',
        correct_option: 'A',
        marks: 5,
        explanation: 'පියවරුන්ගේ දිනය වෙනුවෙන් සිතුවමක් තෑගි කරයි (a).'
      },
      {
        order_num: 35,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、話にあう絵（a, b, c, d）を選んでください。',
        image_url: '/uploads/images/jft16/jft16_img_10.jpg',
        audio_url: '/uploads/audio/jft16_q35_36.mp3',
        option_a: 'a (しゅうしょく)',
        option_b: 'b (ひっこし)',
        option_c: 'c (けっこん)',
        option_d: 'd (しゅっさん)',
        correct_option: 'C',
        marks: 5,
        explanation: 'විවාහ මංගල්‍යය (c - けっこん) පිළිබඳව කතා කරයි.'
      },
      {
        order_num: 36,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\nけっこんのおいわいのために何をしますか。',
        image_url: '/uploads/images/jft16/jft16_img_14.jpg',
        audio_url: '/uploads/audio/jft16_q35_36.mp3',
        option_a: 'e (プレゼントをあげます)',
        option_b: 'f (パーティーをします)',
        option_c: 'g (レストランでしょくじをします)',
        option_d: 'h (カードを書きます)',
        correct_option: 'A',
        marks: 5,
        explanation: 'විවාහයට තෑග්ගක් පිරිනමයි (e - プレゼントをあげます).'
      },
      {
        order_num: 37,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、話にあう絵（a, b, c, d）を選んでください。',
        image_url: '/uploads/images/jft16/jft16_img_10.jpg',
        audio_url: '/uploads/audio/jft16_q37_38.mp3',
        option_a: 'a',
        option_b: 'b (ひっこし)',
        option_c: 'c',
        option_d: 'd',
        correct_option: 'B',
        marks: 5,
        explanation: 'ගෙවල් මාරු කිරීම (b - ひっこし) පිළිබඳව කතා කරයි.'
      },
      {
        order_num: 38,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\nカーラさんのひっこしにおいわいに何をしますか。',
        image_url: '/uploads/images/jft16/jft16_img_14.jpg',
        audio_url: '/uploads/audio/jft16_q37_38.mp3',
        option_a: 'e',
        option_b: 'f (パーティーをします)',
        option_c: 'g',
        option_d: 'h',
        correct_option: 'B',
        marks: 5,
        explanation: 'සාදයක් පවත්වයි (f - パーティーをします).'
      },
      {
        order_num: 39,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、話にあう絵（a, b, c, d）を選んでください。',
        image_url: '/uploads/images/jft16/jft16_img_10.jpg',
        audio_url: '/uploads/audio/jft16_q39_40.mp3',
        option_a: 'a (しゅうしょく)',
        option_b: 'b',
        option_c: 'c',
        option_d: 'd',
        correct_option: 'A',
        marks: 5,
        explanation: 'රැකියාවක් ලැබීම (a - しゅうしょく) පිළිබඳව කතා කරයි.'
      },
      {
        order_num: 40,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\nパクさんのしゅうしょくおいわいに何をしますか。',
        image_url: '/uploads/images/jft16/jft16_img_14.jpg',
        audio_url: '/uploads/audio/jft16_q39_40.mp3',
        option_a: 'e',
        option_b: 'f',
        option_c: 'g (レストランで食事をします)',
        option_d: 'h',
        correct_option: 'C',
        marks: 5,
        explanation: 'අවන්හලකදී ආහාර වේලක් භුක්ති විඳියි (g - レストランでしょくじ).'
      },
      {
        order_num: 41,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、話にあう絵（a, b, c, d）を選んでください。',
        image_url: '/uploads/images/jft16/jft16_img_10.jpg',
        audio_url: '/uploads/audio/jft16_q41_42.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c',
        option_d: 'd (しゅっさん)',
        correct_option: 'D',
        marks: 5,
        explanation: 'දරු ප්‍රසූතිය (d - しゅっさん) පිළිබඳව කතා කරයි.'
      },
      {
        order_num: 42,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\nキルスティナさんのしゅっさんに何をしますか。',
        image_url: '/uploads/images/jft16/jft16_img_14.jpg',
        audio_url: '/uploads/audio/jft16_q41_42.mp3',
        option_a: 'e',
        option_b: 'f',
        option_c: 'g',
        option_d: 'h (カードを書きます)',
        correct_option: 'D',
        marks: 5,
        explanation: 'සුබපැතුම් පතක් ලියයි (h - カードを書きます).'
      },
      {
        order_num: 43,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\nなかむらさんはいつ来ますか。',
        image_url: '/uploads/images/jft16/jft16_img_17.jpg',
        audio_url: '/uploads/audio/jft16_q43_44.mp3',
        option_a: '18日',
        option_b: '28日',
        option_c: '27日',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'නකමුරා මහත්මිය 28 වන දින (28日) පැමිණේ.'
      },
      {
        order_num: 44,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\nなかむらさんはどこに働いていますか。',
        image_url: '/uploads/images/jft16/jft16_img_17.jpg',
        audio_url: '/uploads/audio/jft16_q43_44.mp3',
        option_a: '東京のししゃで',
        option_b: 'おおさかのししゃで',
        option_c: '東京のほんしゃで',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ටෝකියෝ ප්‍රධාන කාර්යාලයේ (東京の本社) සේවය කරයි.'
      },
      {
        order_num: 45,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、正しいものを選んでください。',
        image_url: '/uploads/images/jft16/jft16_img_18.jpg',
        audio_url: '/uploads/audio/jft16_q45.mp3',
        option_a: 'いしかわさんは21日に来ます',
        option_b: 'いしかわさんは朝9時のひこうきで来ます',
        option_c: 'いしかわさんはシドニーししゃで働いています',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ඉෂිකාවා මහතා 21 වන දින පැමිණේ (21日に来ます).'
      },

      // ================= SECTION 4: Reading Comprehension (読解 - Dokkai - Q46 to Q60) =================
      {
        order_num: 46,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、内容が合っていれば〇、ちがっていれば×を選びなさい。\nアランさんは日本人とときどき英語で話します。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ඇලන් මහතා සෑමවිටම ජපන් ජාතිකයන් සමග ජපන් බසින් කතා කරයි.'
      },
      {
        order_num: 47,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、内容が合っていれば〇、ちがっていれば×を選びなさい。\nアランさんは日本語がわかりませんから、日本人は英語で話します。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ඇලන් විදේශිකයෙකු නිසා ජපන් ජාතිකයන් ඉංග්‍රීසියෙන් කතා කිරීමට උත්සාහ කරයි.'
      },
      {
        order_num: 48,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、内容が合っていれば〇、ちがっていれば×を選びなさい。\n駅の前で日本人と話した時、女の人は男の人より親切でした。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'කාන්තාව කරුණාවන්තව මග පෙන්වා දුන්නාය (親切でした).'
      },
      {
        order_num: 49,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、内容が合っていれば〇、ちがっていれば×を選びなさい。\nアランさんが図書館へ行った時、図書館は休みでした。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'පුස්තකාලය නිවාඩු නොවූ අතර, එහි පුස්තකාලයක් තිබුණේ නැත.'
      },
      {
        order_num: 50,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、内容が合っていれば〇、ちがっていれば×を選びなさい。\nアランさんはアメリカ人です。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ඇලන් ප්‍රංශ ජාතිකයෙකි (フランス人です).'
      },
      {
        order_num: 51,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで答えてください。\nアランさんはどうして「日本人のみなさん、日本語でお願いします」と言いましたか。',
        image_url: null,
        audio_url: null,
        option_a: '英語がきらいですから',
        option_b: '日本語を覚えたいですから',
        option_c: '日本人の英語より日本語のほうがよくわかりますから',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ජපන් ජාතිකයන්ගේ ඉංග්‍රීසි වලට වඩා ජපන් භාෂාව තමන්ට වඩාත් හොඳින් වැටහෙන නිසාය.'
      },
      {
        order_num: 52,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '手紙を読んで答えてください。\nよしこさんは困っていることはどれですか。',
        image_url: null,
        audio_url: null,
        option_a: '大学の授業をはじめったから',
        option_b: '大学の学費（りょうきん）は高いから',
        option_c: '地理学の勉強がきらいだから',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'විශ්වවිද්‍යාල අධ්‍යාපන ගාස්තු අධික වීම (学費もとても高い) පිළිබඳව කනස්සල්ලෙන් පසුවේ.'
      },
      {
        order_num: 53,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、あきらさんが書いた正しい絵（1, 2, 3, 4）を一つ選びなさい。',
        image_url: '/uploads/images/jft16/jft16_img_19.jpg',
        audio_url: null,
        option_a: '1 (人・大・立)',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'A',
        marks: 5,
        explanation: 'මිනිසාගේ ඉරියව් අනුව කන්ජි හැඩ ගැන්වූ නිවැරදි රූප සටහන 1 වේ.'
      },
      {
        order_num: 54,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'ドラえもんの説明を読んで、内容が合っていれば〇、ちがっていれば×を選びなさい。\nドラえもんは動物です。',
        image_url: '/uploads/images/jft16/jft16_img_20.jpg',
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ඩොරෙමොන් සතෙකු නොව බළල් හැඩැති රොබෝවෙකි (ねこのかたちのロボット).'
      },
      {
        order_num: 55,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'ドラえもんの説明を読んで、内容が合っていれば〇、ちがっていれば×を選びなさい。\nドラえもんはポケットから便利なものを出します。',
        image_url: '/uploads/images/jft16/jft16_img_20.jpg',
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'සාක්කුවෙන් නොයෙකුත් පහසු උපකරණ ලබා දෙයි (ふしぎなポケット).'
      },
      {
        order_num: 56,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'ドラえもんの説明を読んで、内容が合っていれば〇、ちがっていれば×を選びなさい。\n空をとびたいとき「タケコプター」に乗ります。',
        image_url: '/uploads/images/jft16/jft16_img_20.jpg',
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ටකෙකොප්ටර් මත නගින්නේ නැත, හිස මත සවි කරයි (あたまにつけます).'
      },
      {
        order_num: 57,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'ドラえもんの説明を読んで、内容が合っていれば〇、ちがっていれば×を選びなさい。\n「どこでもドア」があったらどこでも行けます。',
        image_url: '/uploads/images/jft16/jft16_img_20.jpg',
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'දොර ඇරීමෙන් ඕනෑම තැනකට ක්ෂණිකව යා හැකිය (どこでも行けます).'
      },
      {
        order_num: 58,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'メールを読んで、内容が合っていれば〇、ちがっていれば×を選びなさい。\n田中さんはうちゅうひこうしです。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'තනකා මහතා අභ්‍යවකාශගාමියෙකි (宇宙飛行士).'
      },
      {
        order_num: 59,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'メールを読んで、内容が合っていれば〇、ちがっていれば×を選びなさい。\n田中さんはうちゅうへ行って、うちゅうせんの外へでました。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'පිටතට ගිය බවක් සඳහන් නොවේ.'
      },
      {
        order_num: 60,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'メールを読んで、内容が合っていれば〇、ちがっていれば×を選びなさい。\nでんしメールを送った人はうちゅうについてけんきゅうしています。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ඊමේල් එවූ තැනැත්තා අනාගතයේ අභ්‍යවකාශගාමියෙකු වීමට කැමති දරුවෙකි.'
      }
    ];

    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, section_name, question_text, question_type,
          image_url, audio_url,
          option_a, option_b, option_c, option_d,
          correct_option, marks, explanation, order_num
        ) VALUES (?, ?, ?, 'multiple_choice', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId, q.section_name, q.question_text,
        q.image_url, q.audio_url,
        q.option_a, q.option_b, q.option_c, q.option_d,
        q.correct_option, q.marks, q.explanation, q.order_num
      ]);
    }

    console.log(`🎉 SUCCESS: Seeded ${questions.length} questions for JFT Model Paper 16 (Exam ID: ${examId})`);
    return { success: true, examId, count: questions.length };
  } catch (err) {
    console.error('Error seeding JFT Model Paper 16:', err);
    throw err;
  }
}

module.exports = { seedJftModelPaper16 };
