const { query } = require('../config/database');

async function seedJftModelPaper15() {
  console.log('Seeding JFT-Basic Official Model Paper 15 (60 Questions, 250 Marks, Pass 200)...');
  const title = 'JFT-Basic Official Model Paper 15 (60 Minutes)';

  try {
    let exam = await query.get("SELECT id FROM exams WHERE title = ? OR title LIKE '%Paper 15%'", [title]);
    let examId;

    if (exam) {
      examId = exam.id;
      console.log(`Found existing Exam ID: ${examId}, resetting questions...`);
      await query.run('DELETE FROM questions WHERE exam_id = ?', [examId]);
      await query.run(`
        UPDATE exams 
        SET course_id = 1,
            title = ?,
            description = 'Official JFT-Basic Prometric Computer-Based Examination Paper 15 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Listening Audio Tracks and Sinhala Explanations)',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [title, examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (
          1,
          ?,
          'Official JFT-Basic Prometric Computer-Based Examination Paper 15 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Listening Audio Tracks and Sinhala Explanations)',
          60,
          200,
          1
        )
      `, [title]);
      examId = res.id;
      console.log(`Created new Exam ID: ${examId}`);
    }

    const questions = [
      // ================= SECTION 1: Script & Vocabulary (文字・語彙 - Q01 to Q15) =================
      {
        order_num: 1,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft15/jft15_img_1.jpg',
        audio_url: null,
        option_a: 'うでをあげます',
        option_b: 'くびをあげます',
        option_c: 'いきをすいます',
        option_d: '',
        correct_option: 'A',
        marks: 1,
        explanation: 'うでをあげます (腕を上げます) = දෑත් ඔසවයි / Raise arms.'
      },
      {
        order_num: 2,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft15/jft15_img_2.jpg',
        audio_url: null,
        option_a: 'うでをあげます',
        option_b: 'いきをすいます',
        option_c: 'くびをまげます',
        option_d: '',
        correct_option: 'C',
        marks: 1,
        explanation: 'くびをまげます (首を曲げます) = බෙල්ල නමයි / Bend neck.'
      },
      {
        order_num: 3,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft15/jft15_img_3.jpg',
        audio_url: null,
        option_a: 'いきをすいます',
        option_b: 'うでをあげます',
        option_c: 'くびをあげます',
        option_d: '',
        correct_option: 'A',
        marks: 1,
        explanation: 'いきをすいます (息を吸います) = හුස්ම ගනියි / Inhale.'
      },
      {
        order_num: 4,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft15/jft15_img_4.jpg',
        audio_url: null,
        option_a: 'くびをあげます',
        option_b: 'うでをあげます',
        option_c: 'かたをまわします',
        option_d: '',
        correct_option: 'C',
        marks: 1,
        explanation: 'かたをまわします (肩を回します) = උරහිස් කරකවයි / Rotate shoulders.'
      },
      {
        order_num: 5,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft15/jft15_img_5.jpg',
        audio_url: null,
        option_a: 'ぎゅうにゅうを飲みます',
        option_b: '薬を飲みます',
        option_c: 'みずを飲みます',
        option_d: '',
        correct_option: 'B',
        marks: 1,
        explanation: 'くすりをのみます (薬を飲みます) = බෙහෙත් බොයි / Take medicine.'
      },
      {
        order_num: 6,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft15/jft15_img_6.jpg',
        audio_url: null,
        option_a: 'ぎゅうにゅうを飲みます',
        option_b: 'みずを飲みます',
        option_c: '薬を飲みます',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: 'ぎゅうにゅうをのみます (牛乳を飲みます) = එළකිරි බොයි / Drink milk.'
      },
      {
        order_num: 7,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft15/jft15_img_7.jpg',
        audio_url: null,
        option_a: 'すわります',
        option_b: 'ヨガをします',
        option_c: 'たっています',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: 'ヨガをします = යෝගා ව්‍යායාම කරයි / Do yoga.'
      },
      {
        order_num: 8,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft15/jft15_img_8.jpg',
        audio_url: null,
        option_a: 'たばこをすいます',
        option_b: 'お酒をすいます',
        option_c: 'たばこをすいません',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: 'たばこをすいません = දුම්පානය නොකරයි / Refuse cigarette.'
      },
      {
        order_num: 9,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft15/jft15_img_9.jpg',
        audio_url: null,
        option_a: 'お酒を飲みます',
        option_b: 'お酒を飲みません',
        option_c: 'たばこをすいません',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: 'おさけをのみます (お酒を飲みます) = මත්පැන් බොයි / Drink alcohol / beer.'
      },
      {
        order_num: 10,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft15/jft15_img_10.jpg',
        audio_url: null,
        option_a: 'しゅっさん',
        option_b: 'じゅっさん',
        option_c: 'じゅうさん',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: 'しゅっさん (出産) = දරු ප්‍රසූතිය / Childbirth.'
      },
      {
        order_num: 11,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）のひらがなの漢字はどう書きますか。\nこのあたりはアニメの店が多いです。若い人に【にんき】があります。',
        image_url: null,
        audio_url: null,
        option_a: '元気',
        option_b: '人形',
        option_c: '人気',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '人気 (にんき) = ජනප්‍රියතාව / Popularity.'
      },
      {
        order_num: 12,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）のひらがなの漢字はどう書きますか。\nこの店はカメラが【やすい】です。',
        image_url: null,
        audio_url: null,
        option_a: '高い',
        option_b: '女い',
        option_c: '安い',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '安い (やすい) = මිල අඩු / Cheap.'
      },
      {
        order_num: 13,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）のひらがなの漢字はどう書きますか。\nテレビは【たかい】です。',
        image_url: null,
        audio_url: null,
        option_a: '高い',
        option_b: '女い',
        option_c: '安い',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '高い (たかい) = මිල අධික / Expensive.'
      },
      {
        order_num: 14,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）のひらがなの漢字はどう書きますか。\n駅で友達を【まちます】。',
        image_url: null,
        audio_url: null,
        option_a: '持ちます',
        option_b: '待ちます',
        option_c: '特ちます',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '待ちます (まちます) = බලා සිටියි / Wait.'
      },
      {
        order_num: 15,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）のひらがなの漢字はどう書きますか。\n雪で電車が【とまりました】。',
        image_url: null,
        audio_url: null,
        option_a: '泊まりました',
        option_b: '止まりました',
        option_c: '正まりました',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '止まりました (とまりました) = නැවතුණි / Stopped.'
      },

      // ================= SECTION 2: Conversation & Grammar (会話・文法 - Q16 to Q30) =================
      {
        order_num: 16,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\nこのあたりは店が＿＿＿＿便利です。',
        image_url: null,
        audio_url: null,
        option_a: '少なくて',
        option_b: '多くて',
        option_c: '大きくて',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'කඩසාප්පු වැඩි බැවින් පහසු බව: 「多くて (たくさんあって) 便利です」。'
      },
      {
        order_num: 17,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\nこのあたりは＿＿＿＿おもしろいです。',
        image_url: null,
        audio_url: null,
        option_a: 'にぎやかに',
        option_b: 'ひろいで',
        option_c: 'にぎやかで',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'නාම විශේෂණ සම්බන්ධ කිරීම: 「にぎやかで」(ජනාකීර්ණ සහ විනෝදජනකයි).'
      },
      {
        order_num: 18,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\nここは新しい＿＿＿＿にんきがあります。',
        image_url: null,
        audio_url: null,
        option_a: '町',
        option_b: '町で',
        option_c: '町に',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '新しい (විශේෂණය) + 町 (නාමපදය) = 新しい町 (අලුත් නගරය).'
      },
      {
        order_num: 19,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\nこのとおりは夜＿＿＿＿あぶないです。',
        image_url: null,
        audio_url: null,
        option_a: 'あかるくて',
        option_b: 'くろくて',
        option_c: 'くらくて',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'රාත්‍රිය අඳුරු වී අනතුරුදායක බව: 「くらくて あぶないです」。'
      },
      {
        order_num: 20,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\nこのゆうえんちは＿＿＿＿ふべんです。',
        image_url: null,
        audio_url: null,
        option_a: 'みじかくて',
        option_b: 'とおくて',
        option_c: 'ちかくて',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'දුර බැවින් අපහසු බව: 「とおくて (遠くて) ふべんです」。'
      },
      {
        order_num: 21,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、（　　）に一番いいものを一つ選んでください。\nA：すみません。コンピューターを＿＿＿＿。\nB：はい、どうぞ。',
        image_url: null,
        audio_url: null,
        option_a: 'かりてもいいですか',
        option_b: '買いてもいいですか。',
        option_c: '使ってほうがいいですか',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'අවසර ලබා ගැනීමට 「〜てもいいですか」(かりてもいいですか).'
      },
      {
        order_num: 22,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(22)に入る一番いいものを一つ選んでください。\n山田：こちらはひしょのキャシーさんです。\n田中：田中です。(22)＿＿＿＿。\nキャシー：こちらこそ。どうぞよろしく。',
        image_url: null,
        audio_url: null,
        option_a: 'どうもすみません',
        option_b: 'こちらこそ',
        option_c: 'どうぞよろしく',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'පළමු හමුවීමේ සුබපැතුම: 「どうぞよろしく」(Nice to meet you).'
      },
      {
        order_num: 23,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(23)に入る一番いいものを一つ選んでください。\n山田：キャシーさんは日本語、(23)＿＿＿＿ですよ。\n田中：そうですか。',
        image_url: null,
        audio_url: null,
        option_a: 'へらへら',
        option_b: 'ぺらぺら',
        option_c: 'べらべら',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'භාෂාවක් චතුර ලෙස කතා කිරීමට 「ぺらぺら」(චතුරයි / Fluent) භාවිතා කරයි.'
      },
      {
        order_num: 24,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '空港での会話を読んで、(24)に入る一番いいものを一つ選んでください。\nA：(24)＿＿＿＿、田中さん。\nB：(25)＿＿＿＿。(26)＿＿＿＿ありがとうございます。',
        image_url: '/uploads/images/jft15/jft15_img_14.jpg',
        audio_url: null,
        option_a: 'いらっしゃる',
        option_b: 'ようこそ',
        option_c: 'こちらこそ',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'පිළිගැනීමේදී 「ようこそ」(Welcome) භාවිතා කරයි.'
      },
      {
        order_num: 25,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '空港での会話を読んで、(25)に入る一番いいものを一つ選んでください。\nB：(25)＿＿＿＿。(26)＿＿＿＿ありがとうございます。',
        image_url: '/uploads/images/jft15/jft15_img_14.jpg',
        audio_url: null,
        option_a: 'ありがとう',
        option_b: 'おまたせしました',
        option_c: 'ようこそ',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ප්‍රමාද වී පැමිණි විට 「おまたせしました」(රස්තියාදු කිරීමට සිදු වූවාට සමාවෙන්න).'
      },
      {
        order_num: 26,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '空港での会話を読んで、(26)に入る一番いいものを一つ選んでください。\nB：おまたせしました。(26)＿＿＿＿ありがとうございます。',
        image_url: '/uploads/images/jft15/jft15_img_14.jpg',
        audio_url: null,
        option_a: '帰った',
        option_b: 'おでむかえ',
        option_c: 'でむこう',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'පිළිගැනීමට ගුවන්තොටුපළට පැමිණීම වෙනුවෙන් ස්තුතිය: 「お出迎えありがとうございます」。'
      },
      {
        order_num: 27,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '食事の会話を読んで、(27)に入る一番いいものを一つ選んでください。\nA：やぎさん、よかったら、サラダ(27)＿＿＿＿。\nB：はい、いただきます。このサラダちょっとからくて(28)＿＿＿＿ですね。',
        image_url: '/uploads/images/jft15/jft15_img_17.jpg',
        audio_url: null,
        option_a: 'どうぞ',
        option_b: 'ください',
        option_c: 'くださいませんか',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'කෑමක් පිරිනමන විට 「どうぞ」(කරුණාකර ගන්න) භාවිතා කරයි.'
      },
      {
        order_num: 28,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '食事の会話を読んで、(28)に入る一番いいものを一つ選んでください。\nB：はい、いただきます。このサラダちょっとからくて(28)＿＿＿＿ですね。',
        image_url: '/uploads/images/jft15/jft15_img_17.jpg',
        audio_url: null,
        option_a: 'おもしろい',
        option_b: 'おもしろくない',
        option_c: 'おいしい',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'රසවත් බව පැවසීමට 「おいしい」(රසයි).'
      },
      {
        order_num: 29,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '食事の会話を読んで、(29)に入る一番いいものを一つ選んでください。\nA：(29)＿＿＿＿。もう少しどうですか。',
        image_url: '/uploads/images/jft15/jft15_img_17.jpg',
        audio_url: null,
        option_a: 'どうですか',
        option_b: 'どうしてですか',
        option_c: 'そうですか',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'පිළිතුර අනුමත කිරීමට 「そうですか」(එසේද / එහෙමද).'
      },
      {
        order_num: 30,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '食事の会話を読んで、(30)に入る一番いいものを一つ選んでください。\nB：ありがとうございます。(30)＿＿＿＿。',
        image_url: '/uploads/images/jft15/jft15_img_17.jpg',
        audio_url: null,
        option_a: 'まだおなかがいたいです',
        option_b: 'まだおなかがいっぱいです',
        option_c: 'もうおなかがいっぱいです',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'බඩ පිරී ඇති බව ආචාරශීලීව පැවසීමට 「もう おなかが いっぱいです」。'
      },

      // ================= SECTION 3: Listening Comprehension (聴解 - Choukai - Q31 to Q45) =================
      {
        order_num: 31,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\n女の人はけんこうのために何をしていますか。',
        image_url: null,
        audio_url: '/uploads/audio/jft15_q31_33.mp3',
        option_a: 'ジョギング・ヨガ',
        option_b: 'ヨガ・ダイビング',
        option_c: 'ヨガ・すいえい',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'කාන්තාව යෝගා සහ පිහිනුම් (ヨガ・すいえい) කරන බව පවසයි.'
      },
      {
        order_num: 32,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\n毎朝何分ぐらいヨガをしていますか。',
        image_url: null,
        audio_url: '/uploads/audio/jft15_q31_33.mp3',
        option_a: '毎朝2分ぐらい',
        option_b: '毎朝50分ぐらい',
        option_c: '毎朝20分ぐらい',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'සෑම උදෑසනකම මිනිත්තු 20ක් (毎朝20分ぐらい) යෝගා කරන බව සඳහන් කරයි.'
      },
      {
        order_num: 33,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\n女の人はプールでどのぐらいおよぎますか。',
        image_url: null,
        audio_url: '/uploads/audio/jft15_q31_33.mp3',
        option_a: '週に1回ぐらい',
        option_b: '週に2回ぐらい',
        option_c: '週に3回ぐらい',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'සතියකට දෙවරක් පමණ (週に2回ぐらい) පිහිනයි.'
      },
      {
        order_num: 34,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて正しいものを選んでください。',
        image_url: null,
        audio_url: '/uploads/audio/jft15_q34.mp3',
        option_a: '女の人は毎日5キロぐらい歩きます',
        option_b: '女の人はしゅうかん5キロぐらいあるきます',
        option_c: '女の人は土曜日と日曜日5キロぐらい歩きます。',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'සෙනසුරාදා සහ ඉරිදා දිනවල කිලෝමීටර් 5 ක් පමණ ඇවිදින බව පවසයි.'
      },
      {
        order_num: 35,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\nけんこうのためにシンさんは何をしていますか。',
        image_url: '/uploads/images/jft15/jft15_img_11.jpg',
        audio_url: '/uploads/audio/jft15_q35_37.mp3',
        option_a: '家でヨガをしたりジムでトレーニングをしたりしています。',
        option_b: '公園でヨガをしたりジムでトレーニングをしたりしています。',
        option_c: '公園でヨガをしたり家でトレーニングをしたりしています。',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'උද්‍යානයේ යෝගා සහ ජිම් එකේ පුහුණුවීම් කරයි.'
      },
      {
        order_num: 36,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\n田中さんはけんこうのために何をしていますか。',
        image_url: '/uploads/images/jft15/jft15_img_12.jpg',
        audio_url: '/uploads/audio/jft15_q35_37.mp3',
        option_a: 'はしったりおよいだりしています',
        option_b: 'ヨガをしたりトレーニングしたりしています',
        option_c: 'お酒を飲んだりおんがくを聞いたりしています',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'දුවමින් සහ පිහිනමින් ව්‍යායාම කරයි (はしったりおよいだり).'
      },
      {
        order_num: 37,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\nよしださんはどこに行っていますか。',
        image_url: '/uploads/images/jft15/jft15_img_13.jpg',
        audio_url: '/uploads/audio/jft15_q35_37.mp3',
        option_a: 'たいしかん',
        option_b: 'たいいくかん',
        option_c: 'としょかん',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ක්‍රීඩාගාරය / Gymnasium (たいいくかん) වෙත යයි.'
      },
      {
        order_num: 38,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、表の A に入る数字を選んでください。',
        image_url: '/uploads/images/jft15/jft15_img_19.jpg',
        audio_url: '/uploads/audio/jft15_q38_39.mp3',
        option_a: '8',
        option_b: '7',
        option_c: '4',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'A සඳහා පුද්ගලයින් 8 දෙනෙක් (8人) ඇතුළත් වේ.'
      },
      {
        order_num: 39,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、表の B に入る数字を選んでください。',
        image_url: '/uploads/images/jft15/jft15_img_19.jpg',
        audio_url: '/uploads/audio/jft15_q38_39.mp3',
        option_a: '5',
        option_b: '4',
        option_c: '3',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'B සඳහා පුද්ගලයින් 4 දෙනෙක් (4人) ඇතුළත් වේ (15 - 3 - 8 = 4).'
      },
      {
        order_num: 40,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\nさいとうさんはいつ何時にきますか。',
        image_url: '/uploads/images/jft15/jft15_img_15.jpg',
        audio_url: '/uploads/audio/jft15_q40.mp3',
        option_a: '26日、夜3時',
        option_b: '16日、昼3時',
        option_c: '19日、昼3時',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '19 වන දින දවල් 3 ට (19日、昼3時) පැමිණේ.'
      },
      {
        order_num: 41,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて正しいものを選んでください。',
        image_url: null,
        audio_url: '/uploads/audio/jft15_q41.mp3',
        option_a: 'ネクタイは誕生日に彼にあげました',
        option_b: 'ネクタイは誕生日に彼にもらいました',
        option_c: 'ネックレスは誕生日に彼にもらいました',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'උපන්දිනයට පෙම්වතාගෙන් ටයි පටියක් තෑගි ලැබුණු බව පවසයි.'
      },
      {
        order_num: 42,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\nパクさんは父にもらったのはどれか。',
        image_url: null,
        audio_url: '/uploads/audio/jft15_q42.mp3',
        option_a: 'かっこう',
        option_b: 'とけい',
        option_c: 'とくい',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'පියාගෙන් ලැබුණේ ඔරලෝසුවක් (とけい - 時計) වේ.'
      },
      {
        order_num: 43,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\nかばんはいつ買いましたか。',
        image_url: null,
        audio_url: '/uploads/audio/jft15_q43.mp3',
        option_a: '11年前',
        option_b: '10年前',
        option_c: '2年前',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'වසර 2කට පෙර (2年前) මිලදී ගත් බව පවසයි.'
      },
      {
        order_num: 44,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\nセーターについて何がただしいですか。',
        image_url: null,
        audio_url: '/uploads/audio/jft15_q44_45.mp3',
        option_a: '山田さんの主人にもらいました',
        option_b: '山田さんはお店で買いました。',
        option_c: '山田さんは自分で作りました',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'යමඩා මහත්මිය විසින්ම ගොතන ලද (自分で作りました) බව පවසයි.'
      },
      {
        order_num: 45,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\n山田さんは何が好きと言っていますか。',
        image_url: null,
        audio_url: '/uploads/audio/jft15_q44_45.mp3',
        option_a: 'セーター',
        option_b: 'のみもの',
        option_c: 'あみもの',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ඇඳුම් ගෙතීම (あみもの - 編み物) විනෝදාංශය බව සඳහන් කරයි.'
      },

      // ================= SECTION 4: Reading Comprehension (読解 - Dokkai - Q46 to Q60) =================
      {
        order_num: 46,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'メッセージを読んで答えてください。\nここにあっているものはどれか。',
        image_url: '/uploads/images/jft15/jft15_img_20.jpg',
        audio_url: null,
        option_a: '田中さんは今晩エドワードさんと食事をします',
        option_b: '田中さんはしゅっちょうのために東京へ行きます。',
        option_c: 'エドワードさんは仕事のために来週東京へ来ます',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'පණිවිඩයේ තනකා මහතා රාජකාරි ගමනක් වෙනුවෙන් ටෝකියෝ යන බව සඳහන් වේ.'
      },
      {
        order_num: 47,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'メッセージを読んで答えてください。\nなぜ彼女は遅れるのですか。',
        image_url: '/uploads/images/jft15/jft15_img_21.jpg',
        audio_url: null,
        option_a: 'しんかんせんが止まったから',
        option_b: 'じかんがまちがえたから',
        option_c: 'しんかんせんはまちがえたから',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'පණිවිඩයේ 「じかんを まちがえました」(වේලාව වැරදුණි) ලෙස ලියා ඇත.'
      },
      {
        order_num: 48,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '会話と天気予報を見て答えてください。\nおがわさんはどこにいますか。',
        image_url: '/uploads/images/jft15/jft15_img_23.jpg',
        audio_url: null,
        option_a: 'おおさか',
        option_b: 'さっぽろ',
        option_c: 'きゅうしゅ',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ඔගාවා මහතා ඔසාකාහි (おおさか) සිට කතා කරයි.'
      },
      {
        order_num: 49,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '会話と天気予報を見て答えてください。\n今日おおさかについて何がただしいですか。',
        image_url: '/uploads/images/jft15/jft15_img_23.jpg',
        audio_url: null,
        option_a: '朝から雨がふっています',
        option_b: '午後雨がふるそうです',
        option_c: '夜雨がふらないそうです',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ඔසාකාහි දහවල් කාලයේ වැසි අපේක්ෂා කෙරේ (ごごは 雨です).'
      },
      {
        order_num: 50,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '会話と天気予報を見て答えてください。\n今日さっぽろはどうですか。',
        image_url: '/uploads/images/jft15/jft15_img_23.jpg',
        audio_url: null,
        option_a: 'はれですから寒いです',
        option_b: '雨がふっているから寒いです',
        option_c: '雪がふっているから寒いです',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'සප්පෝරෝහි හිම පතනය (雪) සිදුවන බව පවසයි.'
      },
      {
        order_num: 51,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'メールを読んで、内容が正しければ〇、ちがっていれば×を選んでください。\nエドワードさんは田中さんにメールを書きました。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'එඩ්වර්ඩ් මහතා විසින් තනකා මහතාට ඊමේල් පණිවිඩය යවන ලදී.'
      },
      {
        order_num: 52,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'メールを読んで、内容が正しければ〇、ちがっていれば×を選んでください。\n田中さんは来週出張します。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ලබන සතියේ රාජකාරි චාරිකාවක (出張) යෙදෙන බව සත්‍යයකි.'
      },
      {
        order_num: 53,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'メールを読んで、内容が正しければ〇、ちがっていれば×を選んでください。\n田中さんはエドワードさんに会ったことがありません。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'කලින් ජපානයේදී හමුවී ඇත (日本で会ったことがあります).'
      },
      {
        order_num: 54,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'メールを読んで、内容が正しければ〇、ちがっていれば×を選んでください。\nエドワードさんとタイラーさんはくうこうにむかえに行きます。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ගුවන්තොටුපළට පිළිගැනීමට යන්නේ ටයිලර් මහතා පමණි.'
      },
      {
        order_num: 55,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'メールを読んで、内容が正しければ〇、ちがっていれば×を選んでください。\n田中さんはエドワードさんにひこうきの時間をれんらくします。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ගුවන් යානය පැමිණෙන වේලාව දන්වන බව සඳහන් වේ.'
      },
      {
        order_num: 56,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'メールを読んで、内容が正しければ〇、ちがっていれば×を選んでください。\n田中さんの出発の時間は午前９時です。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'පිටත්වන වේලාව උදෑසන 9:00 වේ.'
      },
      {
        order_num: 57,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'メールを読んで、内容が正しければ〇、ちがっていれば×を選んでください。\n田中さんはおみあげに持って行くのは日本酒です。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'තෑග්ගක් ලෙස රැගෙන යන්නේ ජපන් සාකේ (日本酒) වේ.'
      },
      {
        order_num: 58,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '説明を読んで、合うグラフ（a または b）を選んでください。\n「男の人は朝ごはんを食べますか。毎朝食べる人は20人です。食べない人は30人です。ときどき食べる人は50人です。」',
        image_url: '/uploads/images/jft15/jft15_img_18.jpg',
        audio_url: null,
        option_a: 'a (毎朝20人, ときどき50人, 食べない30人)',
        option_b: 'b (毎朝22人, ときどき52人, 食べない26人)',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ප්‍රස්ථාරයේ නිවැරදි සංඛ්‍යාත්මක අනුපාතය දක්වන්නේ ප්‍රස්ථාර a වේ.'
      },
      {
        order_num: 59,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '会話を読んで答えてください。\nパーティーはどうしてですか。',
        image_url: null,
        audio_url: null,
        option_a: '田中さんの結婚式のために',
        option_b: '田中さんの誕生日のために',
        option_c: '田中さんの卒業のために',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'තනකා මහතාගේ උපන්දිනය සැමරීම වෙනුවෙන් සාදය සංවිධානය කෙරේ.'
      },
      {
        order_num: 60,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '会話を読んで答えてください。\nパーティーはどこですか。',
        image_url: null,
        audio_url: null,
        option_a: '日本れすとらんで',
        option_b: 'メキツコレストラン「ナミーゴ」で',
        option_c: 'メキシコのレストラン「アミーゴ」で',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'සාදය පවත්වන්නේ "Amigo" නම් මෙක්සිකානු අවන්හලේදීය.'
      }
    ];

    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, section_name, question_text, question_type,
          image_url, audio_url,
          option_a, option_b, option_c, option_d,
          correct_option, marks, explanation, order_num
        ) VALUES (?, ?, ?, 'multiple_choice', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId, q.section_name, q.question_text,
        q.image_url, q.audio_url,
        q.option_a, q.option_b, q.option_c, q.option_d,
        q.correct_option, q.marks, q.explanation, q.order_num
      ]);
    }

    console.log(`🎉 SUCCESS: Seeded ${questions.length} questions for JFT Model Paper 15 (Exam ID: ${examId})`);
    return { success: true, examId, count: questions.length };
  } catch (err) {
    console.error('Error seeding JFT Model Paper 15:', err);
    throw err;
  }
}

module.exports = { seedJftModelPaper15 };
