const { query } = require('../config/database');

async function seedJftModelPaper05() {
  try {
    const title = 'JFT-Basic Official Model Paper 05 (60 Minutes)';
    const existingExam = await query.get("SELECT id FROM exams WHERE title = ?", [title]);
    let examId;

    if (existingExam) {
      examId = existingExam.id;
      console.log(`Seeding JFT Model Paper 05 (Exam ID: ${examId})...`);
      await query.run(`
        UPDATE exams 
        SET description = 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper 05 (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [examId]);
      await query.run("DELETE FROM questions WHERE exam_id = ?", [examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (1, ?, 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper 05 (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.', 60, 200, 1)
      `, [title]);
      examId = res.id;
      console.log(`Created JFT Model Paper 05 (Exam ID: ${examId})`);
    }

    const questions = [
      // ==========================================
      // SECTION 1: Script & Vocabulary (文字・語彙 - Q01 to Q15)
      // ==========================================
      {
        order_num: 1,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q01.jpg',
        audio_url: null,
        option_a: 'したの人',
        option_b: 'となりの人',
        option_c: 'うえの人',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'となりの人 (Person next door / Neighbor / ළඟ/එහා ගෙදර කෙනා).'
      },
      {
        order_num: 2,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q02.jpg',
        audio_url: null,
        option_a: 'ちゅうごく',
        option_b: 'ベトナム',
        option_c: 'かんこく',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ちゅうごく (China / චීනය).'
      },
      {
        order_num: 3,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q03.jpg',
        audio_url: null,
        option_a: 'エンジニア',
        option_b: 'プログラマー',
        option_c: 'まんがか',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'エンジニア (Engineer / ඉංජිනේරුවා).'
      },
      {
        order_num: 4,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q04.jpg',
        audio_url: null,
        option_a: 'いぬとさんぽします',
        option_b: 'かいものをします',
        option_c: 'ペットをかいます',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ペットをかいます (Keep a pet / සුරතල් සතුන් ඇති කරනවා).'
      },
      {
        order_num: 5,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q05.jpg',
        audio_url: null,
        option_a: 'えをかきます',
        option_b: 'えをよみます',
        option_c: 'えをつくります',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'えをかきます (Draw/Paint a picture / චිත්‍ර අඳිනවා).'
      },
      {
        order_num: 6,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄に入る最もよい言葉を選んでください。\n\n______はカメラです。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q06.jpg',
        audio_url: null,
        option_a: 'これ',
        option_b: 'ここ',
        option_c: 'どこ',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '物を示す指示代名詞:「これ」はカメラです (This is a camera / මෙය කැමරාවකි).'
      },
      {
        order_num: 7,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄に入る最もよい言葉を選んでください。\n\nやまださんは______かたですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'どなた',
        option_b: 'どれ',
        option_c: 'どの',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '連体詞「どの」＋名詞「方（かた）」: 山田さんは「どの」方ですか (Which person is Yamada-san? / යමදා මහතා කවුරුන්ද/කොයි කෙනාද?).'
      },
      {
        order_num: 8,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て、空欄に入る最もよい言葉を選んでください。\n\n日本にはよっつの______があります。はる、なつ、あき、ふゆです。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q08.jpg',
        audio_url: null,
        option_a: 'しぜん',
        option_b: 'きせつ',
        option_c: 'てんき',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '春・夏・秋・冬: よっつの「きせつ」(Four seasons / සෘතු හතර).'
      },
      {
        order_num: 9,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '会話を読んで、空欄に入る最もよい言葉を選んでください。\n\nA：これは______ざっしですか。\nB：りょうりのざっしです。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q09.jpg',
        audio_url: null,
        option_a: 'なんの',
        option_b: 'どこの',
        option_c: 'だれの',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '内容をたずねる:「なんの」雑誌ですか -> 料理の雑誌です (What kind of magazine? / කුමන සඟරාවක්ද?).'
      },
      {
        order_num: 10,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄に入る最もよい言葉を選んでください。\n\nしんじゅくには50かいぐらいの______ビルがたくさんあります。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q10.jpg',
        audio_url: null,
        option_a: 'ながい',
        option_b: 'ちかい',
        option_c: 'たかい',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ビルの高さ:「たかい」ビル (Tall building / උස ගොඩනැගිල්ලක්).'
      },
      {
        order_num: 11,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '大学<u>卒業式</u>はいつですか。\n\nHow do you write the underlined kanji word in hiragana? Choose the correct one.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'けっこんしき',
        option_b: 'そつぎょうしき',
        option_c: 'げっこんしき',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '卒業式 -> そつぎょうしき (Graduation ceremony / උපාධි ප්‍රදානෝත්සවය).'
      },
      {
        order_num: 12,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '子供たちは<u>動物園</u>へ行くのはたのしいです。\n\nHow do you write the underlined kanji word in hiragana? Choose the correct one.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'はくぶつえん',
        option_b: 'どうぶつえん',
        option_c: 'こうえん',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '動物園 -> どうぶつえん (Zoo / සත්වෝද්‍යානය).'
      },
      {
        order_num: 13,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '彼女は<u>肉</u>がきらいです。\n\nHow do you write the underlined kanji word in hiragana? Choose the correct one.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'にく',
        option_b: 'さかな',
        option_c: 'やさい',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '肉 -> にく (Meat / මස්).'
      },
      {
        order_num: 14,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'けいたい<u>電話</u>をつかっている人はふえています。\n\nHow do you write the underlined kanji word in hiragana? Choose the correct one.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'でんしゃ',
        option_b: 'でんき',
        option_c: 'でんわ',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '電話 -> でんわ (Telephone / දුරකථනය).'
      },
      {
        order_num: 15,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'あそこに<u>座って</u>いる人は田中さんです。\n\nHow do you write the underlined kanji word in hiragana? Choose the correct one.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'たって',
        option_b: 'すわって',
        option_c: 'あそんで',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '座って -> すわって (Sitting / වාඩි වී සිටින).'
      },

      // ==========================================
      // SECTION 2: Conversation & Expression (会話・表現 - Q16 to Q30)
      // ==========================================
      {
        order_num: 16,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最もよい言葉を選んでください。\n\nちょっと______ですから、電気をつけましょうか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q16.jpg',
        audio_url: null,
        option_a: 'くろい',
        option_b: 'あかるい',
        option_c: 'くらい',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '部屋の暗さ: ちょっと「くらい」ですから、電気をつけましょうか。(Because it\'s a bit dark, shall I turn on the light? / අඳුරු නිසා ලයිට් දමමුද?).'
      },
      {
        order_num: 17,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最もよい言葉を選んでください。\n\nこの問題は______すぎてこたえられません。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'むずかし',
        option_b: 'むずかしく',
        option_c: 'むずかしい',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'い形容詞語幹＋すぎる:「むずかし」すぎて (Too difficult / අමාරු වැඩියි).'
      },
      {
        order_num: 18,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に入る最もよい助詞を選んでください。\n\nA：コーヒーか紅茶をください。\nB：すみません。今、コーヒー______紅茶もありません。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q18.jpg',
        audio_url: null,
        option_a: 'と',
        option_b: 'も',
        option_c: 'は',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '並列否定: コーヒー「も」紅茶「も」ありません (Neither coffee nor tea is available / කෝපිත් තේත් දෙකම නැහැ).'
      },
      {
        order_num: 19,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最もよい言葉を選んでください。\n\nゆうべ手紙を書きました。1時間______かかりました。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q19.jpg',
        audio_url: null,
        option_a: 'ぐらい',
        option_b: 'まで',
        option_c: 'ごろ',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '時間の長さ（期間）のおよそ: 1時間「ぐらい」(About 1 hour / පැයක් පමණ).'
      },
      {
        order_num: 20,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に入る最もよい言葉を選んでください。\n\nA：東京まで______行きますか。\nB：いいえ、友達といっしょに行きます。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '一人で',
        option_b: '何で',
        option_c: 'どのぐらい',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '「一人で」行きますか -> いいえ、友達といっしょに行きます (Will you go alone? / තනිවම යනවාද?).'
      },
      {
        order_num: 21,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に入る最もよい言葉を選んでください。\n\nA：明日の午後、______をしますか。\nB：サッカーをします。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q21.jpg',
        audio_url: null,
        option_a: 'どこ',
        option_b: '何',
        option_c: 'どんな',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '行動をたずねる:「何」をしますか -> サッカーをします (What will you do? / කුමක් කරනවාද?).'
      },
      {
        order_num: 22,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に入る最もよい言葉を選んでください。\n\nA：今日、3時間テニスをしました。\nB：3時間ですか！\nA：ええ、______つかれました。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q22.jpg',
        audio_url: null,
        option_a: 'とても',
        option_b: 'あまり',
        option_c: 'ぜんぜん',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '強調:「とても」つかれました (I got very tired / ගොඩක් මහන්සි වුණා).'
      },
      {
        order_num: 23,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に入る最もよい言葉を選んでください。\n\nA：ゆうべラジオを______か。\nB：いいえ、ききませんでした。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q23.jpg',
        audio_url: null,
        option_a: 'よみますか',
        option_b: 'ききますか',
        option_c: 'ききました',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '昨晩（ゆうべ）の過去の質問: ラジオを「ききました」か。(Did you listen to the radio? / රේඩියෝ ඇසුවාද?).'
      },
      {
        order_num: 24,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に入る最もよい言葉を選んでください。\n\nA：このたてもののいっかいに______ありますか。\nB：店があります。いろいろな店があります。\nA：にかいは。\nB：にかいとさんがいはとしょかんです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '何が',
        option_b: '何か',
        option_c: '何も',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '所在・内容の質問: 一階に「何が」ありますか -> 店があります (What is on the first floor? / පළමු මහලේ මොනවාද තියෙන්නේ?).'
      },
      {
        order_num: 25,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、(25)に入る最もよいものを選んでください。\n\nA：このえいごのクラスは(25)______。\nB：大変でした。イギリス人の先生は毎日ぶんぽうのテストをしました。\nA：それは(26)。テストはむずかしかったですか。\nB：いいえ、(27)むずかしくなかったです。もんだいはおもしろかったです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'どうでしたか',
        option_b: 'どうしてですか',
        option_c: 'いつですか',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '感想をたずねる:「どうでしたか」-> 大変でした (How was the English class? / ඉංග්‍රීසි පන්තිය කොහොමද තිබුණේ?).'
      },
      {
        order_num: 26,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、(26)に入る最もよいものを選んでください。\n\nA：このえいごのクラスは(25)どうでしたか。\nB：大変でした。イギリス人の先生は毎日ぶんぽうのテストをしました。\nA：それは(26)______。テストはむずかしかったですか。\nB：いいえ、(27)むずかしくなかったです。もんだいはおもしろかったです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'だいじょうぶでしたね',
        option_b: 'たいへんでしたね',
        option_c: 'よかったでしたね',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '共感: それは「たいへんでしたね」(That must have been tough / ඒක අමාරු වෙන්න ඇති නේද).'
      },
      {
        order_num: 27,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、(27)に入る最もよいものを選んでください。\n\nA：このえいごのクラスは(25)どうでしたか。\nB：大変でした。イギリス人の先生は毎日ぶんぽうのテストをしました。\nA：それは(26)たいへんでしたね。テストはむずかしかったですか。\nB：いいえ、(27)______むずかしくなかったです。もんだいはおもしろかったです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'とても',
        option_b: 'たいへん',
        option_c: 'あまり',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '部分否定（～ない）: いいえ、「あまり」むずかしくなかったです (No, it wasn\'t very difficult / නැහැ, එච්චර අමාරු වුණේ නැහැ).'
      },
      {
        order_num: 28,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、(28)に入る最もよいものを選んでください。\n\n山田：田中さん、帰りましょう。勉強はおわりましたか。\n田中：いいえ。私はこの本をここまで読みます。\n山田：えっ、そのむずかしい本ですか！(28)______。\n田中：ええ。お先にいってください。\n山田：わかりました。じゃ、(29)しつれいします。\n山田：(30)あした。さようなら。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q28_30.jpg',
        audio_url: null,
        option_a: 'だいじょうぶですね',
        option_b: 'たいへんですね',
        option_c: 'たのしいですね',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '相手の苦労を気遣う:「たいへんですね」(That must be hard / අමාරු වැඩක් නේද).'
      },
      {
        order_num: 29,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、(29)に入る最もよいものを選んでください。\n\n山田：田中さん、帰りましょう。勉強はおわりましたか。\n田中：いいえ。私はこの本をここまで読みます。\n山田：えっ、そのむずかしい本ですか！(28)たいへんですね。\n田中：ええ。お先にいってください。\n山田：わかりました。じゃ、(29)______しつれいします。\n山田：(30)あした。さようなら。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q28_30.jpg',
        audio_url: null,
        option_a: 'どうぞ',
        option_b: 'また',
        option_c: 'ちょっと',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '退席・挨拶: じゃ、「ちょっと」しつれいします (Excuse me then / එහෙනම් මම යන්නම්).'
      },
      {
        order_num: 30,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、(30)に入る最もよいものを選んでください。\n\n山田：田中さん、帰りましょう。勉強はおわりましたか。\n田中：いいえ。私はこの本をここまで読みます。\n山田：えっ、そのむずかしい本ですか！(28)たいへんですね。\n田中：ええ。お先にいってください。\n山田：わかりました。じゃ、(29)ちょっとしつれいします。\n山田：(30)______あした。さようなら。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q28_30.jpg',
        audio_url: null,
        option_a: 'どうぞ',
        option_b: 'また',
        option_c: 'ちょっと',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '別れの挨拶:「また」あした。さようなら。(See you tomorrow. Goodbye / හෙට හමුවෙමු. ආයුබෝවන්).'
      },

      // ==========================================
      // SECTION 3: Listening Comprehension (聴解 - Choukai - Q31 to Q45)
      // ==========================================
      {
        order_num: 31,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、イラストの状況に合う正しい言葉を選んでください。\n\nHe went to the house of someone he knew. What did he say?\n(知っている人の家に行きました。何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q31.jpg',
        audio_url: '/uploads/audio/jft05_q31.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '訪問時の玄関での挨拶:「ごめんください」(Excuse me / නිවසකට ඇතුළු වීමේදී කියන ආචාර වචනය). 正解は「1」です。'
      },
      {
        order_num: 32,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、イラストの状況に合う正しい言葉を選んでください。\n\nHe doesn\'t like sweet coffee. What does he say?\n(甘いコーヒーが好きではありません。何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q32.jpg',
        audio_url: '/uploads/audio/jft05_q32.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '砂糖を断る表現:「砂糖はいりません / 砂糖を入れないでください」。正解は「2」です。(Please don\'t add sugar / සීනි දමන්න එපා).'
      },
      {
        order_num: 33,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、イラストの状況に合う正しい言葉を選んでください。\n\nShe wants to see her friend\'s picture. What does she say?\n(友達の写真を見たいです。何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q33.jpg',
        audio_url: '/uploads/audio/jft05_q33.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '写真を見せてもらう依頼:「写真を見せてください」。正解は「3」です。(Please show me the picture / පින්තූරය මට පෙන්වන්න).'
      },
      {
        order_num: 34,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、イラストの状況に合う正しい言葉を選んでください。\n\nA granny came when he is sitting on the train. What does he say?\n(電車で座っているとき、おばあさんが来ました。何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q34.jpg',
        audio_url: '/uploads/audio/jft05_q34.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '席を譲る表現:「どうぞ座ってください」。正解は「1」です。(Please have a seat / කරුණාකර වාඩි වන්න).'
      },
      {
        order_num: 35,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、イラストの状況に合う正しい言葉を選んでください。\n\nShe doesn\'t know the person\'s name. What does she say?\n(その人の名前を知りません。何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q35.jpg',
        audio_url: '/uploads/audio/jft05_q35.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '名前をたずねる表現:「あの人は誰ですか / お名前は何ですか」。正解は「2」です。(What is that person\'s name? / ඒ කෙනාගේ නම කුමක්ද?).'
      },
      {
        order_num: 36,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しい答えを選んでください。\n\nListen to the track and choose the correct answer.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft05_q36.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '音声内容に基づく正しい選択肢は「1」です。(Correct choice: 1).'
      },
      {
        order_num: 37,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しい答えを選んでください。\n\nListen to the track and choose the correct answer.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft05_q37.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '音声内容に基づく正しい選択肢は「2」です。(Correct choice: 2).'
      },
      {
        order_num: 38,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しい答えを選んでください。\n\nListen to the track and choose the correct answer.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft05_q38.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '音声内容に基づく正しい選択肢は「3」です。(Correct choice: 3).'
      },
      {
        order_num: 39,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しい答えを選んでください。\n\nListen to the track and choose the correct answer.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft05_q39.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '音声内容に基づく正しい選択肢は「2」です。(Correct choice: 2).'
      },
      {
        order_num: 40,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しい答えを選んでください。\n\nListen to the track and choose the correct answer.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft05_q40.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '音声内容に基づく正しい選択肢は「1」です。(Correct choice: 1).'
      },
      {
        order_num: 41,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しい答えを選んでください。\n\nListen to the track and choose the correct answer.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft05_q41.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '音声内容に基づく正しい選択肢は「3」です。(Correct choice: 3).'
      },
      {
        order_num: 42,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しい答えを選んでください。\n\nListen to the track and choose the correct answer.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft05_q42.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '音声内容に基づく正しい選択肢は「2」です。(Correct choice: 2).'
      },
      {
        order_num: 43,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しい答えを選んでください。\n\nListen to the track and choose the correct answer.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft05_q43.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '音声内容に基づく正しい選択肢は「1」です。(Correct choice: 1).'
      },
      {
        order_num: 44,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しい答えを選んでください。\n\nListen to the track and choose the correct answer.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft05_q44.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '音声内容に基づく正しい選択肢は「2」です。(Correct choice: 2).'
      },
      {
        order_num: 45,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しい答えを選んでください。\n\nListen to the track and choose the correct answer.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft05_q45.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '音声内容に基づく正しい選択肢は「3」です。(Correct choice: 3).'
      },

      // ==========================================
      // SECTION 4: Reading Comprehension (読解 - Dokkai - Q46 to Q60)
      // ==========================================
      {
        order_num: 46,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで質問に答えてください。\n\n父は食べるものはどれか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q46_47.jpg',
        audio_url: null,
        option_a: 'みそしる、やさい、ごはん',
        option_b: 'パン、みそしる、やさい',
        option_c: 'パン、みそしる、魚',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '本文より：「父はご飯とみそしるが好きです。やさいも食べます。パンはあまり好きじゃないです。」正解は「みそしる、やさい、ごはん」です。(Miso soup, Vegetables, Rice).'
      },
      {
        order_num: 47,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで質問に答えてください。\n\n母はあまり食べないものはどれか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q46_47.jpg',
        audio_url: null,
        option_a: 'パン',
        option_b: '卵',
        option_c: '魚',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '本文より：「母は卵はあまり食べません。」正解は「卵」(Eggs / බිත්තර)です。'
      },
      {
        order_num: 48,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで、ここにあっているものはどれですか。\n\n「私は北海道に住んでいます。私のいえはアパートです。一人で住んでいます。私のいえはふるいです。でも、明るいです。近くに公園があります。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q48.jpg',
        audio_url: null,
        option_a: '私は北海道にあるホテルで住んでいます',
        option_b: '私は住んでいるアパートは明るくてふるいです',
        option_c: '私は北海道にある公園のちかくにすんでいます',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '本文に「私のいえはふるいです。でも、明るいです」とあります。(The apartment I live in is bright and old).'
      },
      {
        order_num: 49,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '手紙を読んで質問に答えてください。\n\nみちこさんの休みの日はいつですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q49.jpg',
        audio_url: null,
        option_a: '土曜日と日曜日',
        option_b: '月曜日と水曜日と',
        option_c: '土曜日と月曜日',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '手紙に「週末は休みです」と書かれています。週末は「土曜日と日曜日」(Saturday and Sunday / සෙනසුරාදා සහ ඉරිදා)です。'
      },
      {
        order_num: 50,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで質問に答えてください。\n\nおきなわはどこにありますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft05_passage_50_52.png',
        audio_url: null,
        option_a: 'きゅうしゅうの北',
        option_b: 'きゅうしゅうの西',
        option_c: 'きゅうしゅうの南',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '本文に「おきなわはきゅうしゅうの南にあります」と書かれています。(South of Kyushu / කියූෂූ වලට දකුණින්).'
      },
      {
        order_num: 51,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで質問に答えてください。\n\nおきなわでいちばん大きな町は何ですか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft05_passage_50_52.png',
        audio_url: null,
        option_a: 'なら',
        option_b: 'なは',
        option_c: 'きゅうしゅう',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '本文に「なはおきなわでいちばん大きい町です」と書かれています。(Naha is the largest town / නහා නගරය).'
      },
      {
        order_num: 52,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで、ここにあっているものはどれですか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft05_passage_50_52.png',
        audio_url: null,
        option_a: '私は３才のときおきなわへ行きました',
        option_b: 'さんごうしょうにきれいな魚がたくさん釣りました',
        option_c: 'おきなわの言葉がわからないけど人がしんせつでした',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '本文に「ときどきおきなわの言葉がわかりませんでしたが、人はしんせつでした」とあります。(Didn\'t understand local dialect sometimes, but people were kind).'
      },
      {
        order_num: 53,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'メールを読んで質問に答えてください。\n\n二人はどこであいますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft05_passage_53.png',
        audio_url: null,
        option_a: 'みどり駅の北口で',
        option_b: 'さくら駅の北口で',
        option_c: 'レストランで',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'メールに「6時にさくら駅の北口であいましょう」とあります。(Meet at North Exit of Sakura Station / සකුරා ස්ටේෂමේ උතුරු පිවිසුමේදී).'
      },
      {
        order_num: 54,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで、ここにあっているものはどれですか。\n\n「日曜日に誕生日のパーティーをしました。うちに子供の家族が来ました。いっしょに庭でバーベキューをしました。まごにプレゼントをもらいました。うれしかったです。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q54.jpg',
        audio_url: null,
        option_a: 'おじいさんの誕生日のために家族といっしょにパーティーをしました',
        option_b: 'まごの誕生日パーティーはおじいさんのうちにしました',
        option_c: '家族といっしょにりょこうをしました',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'おじいさんの家に子供家族が集まり、孫からプレゼントをもらって祝ったため「おじいさんの誕生日のために家族といっしょにパーティーをしました」が合致します。'
      },
      {
        order_num: 55,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'メッセージを読んで質問に答えてください。\n\nこの人は誰と日本へ行きましたか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q55_56.jpg',
        audio_url: null,
        option_a: '家族と',
        option_b: '友達と',
        option_c: '一人で',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '本文に「今年の08月に私は一人で、日本に行きました」とあります。(Went alone / තනිවම ගියා).'
      },
      {
        order_num: 56,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'メッセージを読んで、ここにあっているものはどれですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft05_q55_56.jpg',
        audio_url: null,
        option_a: 'この人は東京でたくさん買い物をしました',
        option_b: 'この人は友達といっしょにお寺へ行きました',
        option_c: 'この人は一人で買い物へ行きました',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '本文に「東京で友達に会いました。それから、いっしょに有名なお寺を見に行きました」と合致しています。(Went to temple together with friend).'
      },
      {
        order_num: 57,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで質問に答えてください。\n\nまさるは大学で何を勉強していますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'けいざい',
        option_b: 'びじゅつ',
        option_c: 'コンピューター',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '本文に「まさるの大学はびじゅつ大学です。まさるはここでまんがの勉強をしています」とあります。(Fine arts / Art / චිත්‍ර/ලලිත කලා).'
      },
      {
        order_num: 58,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで質問に答えてください。\n\nまさるの大学は東京のどこにありますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'にしのこうがい',
        option_b: 'ひがしのこうがい',
        option_c: '町の中',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '本文に「まさるの大学は東京のにしのほうにあります...こうがいの便利なところにひっこしました」とあります。(Western suburbs / බටහිර තදාසන්න පෙදෙසේ).'
      },
      {
        order_num: 59,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで質問に答えてください。\n\nまさるの大学はどんな大学ですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'せまくてふべんです',
        option_b: 'ふるくてせまいです',
        option_c: 'あたらしくて広いです',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '本文に「大学は広くてきれいです」とあります。(New and spacious / අලුත් සහ විශාලය).'
      },
      {
        order_num: 60,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'どうして大学はこうがいへひっこしましたか。正しくないものを一つ選びなさい。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '大学へ行く人が多くなったからです',
        option_b: 'こうがいには会社がたくさんあるからです',
        option_c: '東京の町の中にはばしょがないからです',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '「こうがいには会社がたくさんあるからです」という理由は本文に一切記載されておらず、誤り（正しくないもの）です。(Companies being in suburbs is not mentioned).'
      }
    ];

    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, order_num, section_name, question_text, question_type, 
          image_url, audio_url, option_a, option_b, option_c, option_d, 
          correct_option, marks, explanation
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId, q.order_num, q.section_name, q.question_text, q.question_type,
        q.image_url, q.audio_url, q.option_a, q.option_b, q.option_c, q.option_d,
        q.correct_option, q.marks, q.explanation
      ]);
    }

    console.log(`Successfully inserted all 60 questions for JFT Model Paper 05 (Exam ID: ${examId})`);
  } catch (err) {
    console.error('seedJftModelPaper05 error:', err);
  }
}

module.exports = { seedJftModelPaper05 };
