const { query } = require('../config/database');

async function seedJftModelPaper15() {
  console.log('Seeding JFT-Basic Official Model Paper 15 (60 Questions, Pass 200/250)...');

  try {
    let exam = await query.get("SELECT * FROM exams WHERE id = 154 OR title LIKE '%Model Paper 15%'");
    let examId = 154;

    if (exam) {
      examId = exam.id;
      const countRes = await query.get("SELECT COUNT(*) as count FROM questions WHERE exam_id = ?", [examId]);
      if (countRes && countRes.count >= 60) {
        await query.run('UPDATE exams SET duration_minutes = 60, passing_score = 200, is_active = 1 WHERE id = ?', [examId]);
        await query.run('UPDATE questions SET marks = 1 WHERE exam_id = ? AND order_num >= 1 AND order_num <= 5', [examId]);
        await query.run('UPDATE questions SET marks = 2 WHERE exam_id = ? AND order_num >= 6 AND order_num <= 15', [examId]);
        await query.run('UPDATE questions SET marks = 5 WHERE exam_id = ? AND order_num >= 16 AND order_num <= 60', [examId]);
        return;
      }
      console.log(`Found existing Exam ID: ${examId}, resetting questions...`);
      await query.run('DELETE FROM questions WHERE exam_id = ?', [examId]);
      await query.run(`
        UPDATE exams 
        SET course_id = 1,
            title = 'JFT-Basic Official Model Paper 15 (60 Minutes)',
            description = 'Official JFT-Basic Prometric Computer-Based Examination Paper 15 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Listening Audio Tracks and Sinhala Explanations)',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (id, course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (
          154,
          1,
          'JFT-Basic Official Model Paper 15 (60 Minutes)',
          'Official JFT-Basic Prometric Computer-Based Examination Paper 15 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Listening Audio Tracks and Sinhala Explanations)',
          60,
          200,
          1
        )
      `);
      examId = res.id;
      console.log(`Created new Exam ID: ${examId}`);
    }

    const questions = [
  {
    "order_num": 1,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n首を上に向けています。",
    "image_url": "/images/jft_paper15/p15_page_01_img_1.png",
    "audio_url": null,
    "option_a": "うでをあげます",
    "option_b": "くびをあげます",
    "option_c": "いきをすいます",
    "option_d": "",
    "correct_option": "A",
    "marks": 1,
    "explanation": "බෙල්ල ඉහළට එසවීම \"くびをあげます (Kubi o agemasu / 首を上げます)\" වේ."
  },
  {
    "order_num": 2,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n首を横に曲げてストレッチしています。",
    "image_url": "/images/jft_paper15/p15_page_01_img_2.png",
    "audio_url": null,
    "option_a": "うでをあげます",
    "option_b": "いきをすいます",
    "option_c": "くびをまげます",
    "option_d": "",
    "correct_option": "C",
    "marks": 1,
    "explanation": "බෙල්ල නැවීම හෝ ඇල කිරීම \"くびをまげます (Kubi o magemasu / 首を曲げます)\" වේ."
  },
  {
    "order_num": 3,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n息を深く吸い込んでいます。",
    "image_url": "/images/jft_paper15/p15_page_02_img_1.png",
    "audio_url": null,
    "option_a": "いきをすいます",
    "option_b": "うでをあげます",
    "option_c": "くびをあげます",
    "option_d": "",
    "correct_option": "A",
    "marks": 1,
    "explanation": "හුස්ම ගැනීම හෝ වාතය ඇතුළට ගැනීම \"いきをすいます (Iki o suimasu / 息を吸います)\" වේ."
  },
  {
    "order_num": 4,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n肩をぐるぐると回しています。",
    "image_url": "/images/jft_paper15/p15_page_02_img_2.png",
    "audio_url": null,
    "option_a": "くびをあげます",
    "option_b": "うでをあげます",
    "option_c": "かたをまわします",
    "option_d": "",
    "correct_option": "C",
    "marks": 1,
    "explanation": "උරහිස් කරකැවීම \"かたをまわします (Kata o mawashimasu / 肩を回します)\" වේ."
  },
  {
    "order_num": 5,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n水といっしょに錠剤を飲んでいます。",
    "image_url": "/images/jft_paper15/p15_page_03_img_1.png",
    "audio_url": null,
    "option_a": "ぎゅうにゅうを飲みます",
    "option_b": "薬を飲みます",
    "option_c": "みずを飲みます",
    "option_d": "",
    "correct_option": "B",
    "marks": 1,
    "explanation": "බෙහෙත් පෙති බීම \"薬を飲みます (Kusuri o nomimasu)\" වේ."
  },
  {
    "order_num": 6,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\nパックからコップについで飲んでいます。",
    "image_url": "/images/jft_paper15/p15_page_03_img_2.png",
    "audio_url": null,
    "option_a": "ぎゅうにゅうを飲みます",
    "option_b": "みずを飲みます",
    "option_c": "薬を飲みます",
    "option_d": "",
    "correct_option": "A",
    "marks": 2,
    "explanation": "කිරි බීම \"ぎゅうにゅうを飲みます (Gyuunyuu o nomimasu / 牛乳を飲みます)\" වේ."
  },
  {
    "order_num": 7,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\nマットの上でポーズをとっています。",
    "image_url": "/images/jft_paper15/p15_page_04_img_1.png",
    "audio_url": null,
    "option_a": "すわります",
    "option_b": "ヨガをします",
    "option_c": "たっています",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "යෝගා අභ්‍යාස කිරීම \"ヨガをします (Yoga o shimasu)\" වේ."
  },
  {
    "order_num": 8,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\nタバコを断っています（禁煙）。",
    "image_url": "/images/jft_paper15/p15_page_04_img_2.png",
    "audio_url": null,
    "option_a": "たばこをすいます",
    "option_b": "お酒をすいます",
    "option_c": "たばこをすいません",
    "option_d": "",
    "correct_option": "C",
    "marks": 2,
    "explanation": "දුම්පානය නොකිරීම \"たばこをすいません (Tabako o suimasen)\" වේ."
  },
  {
    "order_num": 9,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\nビールで乾杯しています。",
    "image_url": "/images/jft_paper15/p15_page_04_img_3.png",
    "audio_url": null,
    "option_a": "お酒を飲みます",
    "option_b": "お酒を飲みません",
    "option_c": "たばこをすいません",
    "option_d": "",
    "correct_option": "A",
    "marks": 2,
    "explanation": "මත්පැන්/බියර් බීම \"お酒を飲みます (Osake o nomimasu)\" වේ."
  },
  {
    "order_num": 10,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n赤ちゃんが生まれました。",
    "image_url": "/images/jft_paper15/p15_page_05_img_1.png",
    "audio_url": null,
    "option_a": "しゅっさん",
    "option_b": "じゅっさん",
    "option_c": "じゅうさん",
    "option_d": "",
    "correct_option": "A",
    "marks": 2,
    "explanation": "දරුවකු ප්‍රසූත කිරීම \"しゅっさん (Shussan / 出産)\" වේ."
  },
  {
    "order_num": 11,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "下線のひらがなはどう漢字で書きますか。\nこのあたりはアニメの店が多いです。若い人に<u>にんき</u>があります。",
    "image_url": null,
    "audio_url": null,
    "option_a": "元気",
    "option_b": "人形",
    "option_c": "人気",
    "option_d": "",
    "correct_option": "C",
    "marks": 2,
    "explanation": "ජනප්‍රියත්වය සඳහා නිවැරදි කන්ජිය \"人気 (にんき - Ninki)\" වේ."
  },
  {
    "order_num": 12,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "下線のひらがなはどう漢字で書きますか。\nこの店はカメラが(12)<u>やすい</u>です。テレビは(13)<u>たかい</u>です。",
    "image_url": null,
    "audio_url": null,
    "option_a": "高い",
    "option_b": "女い",
    "option_c": "安い",
    "option_d": "",
    "correct_option": "C",
    "marks": 2,
    "explanation": "ලාභදායී / මිල අඩු යන්නෙහි කන්ජිය \"安い (やすい - Yasui)\" වේ."
  },
  {
    "order_num": 13,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "下線のひらがなはどう漢字で書きますか。\nこの店はカメラが(12)やすいです。テレビは(13)<u>たかい</u>です。",
    "image_url": null,
    "audio_url": null,
    "option_a": "高い",
    "option_b": "女い",
    "option_c": "安い",
    "option_d": "",
    "correct_option": "A",
    "marks": 2,
    "explanation": "මිල අධික / උසස් යන්නෙහි කන්ජිය \"高い (たかい - Takai)\" වේ."
  },
  {
    "order_num": 14,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "下線のひらがなはどう漢字で書きますか。\n駅で友達を<u>まちます</u>。",
    "image_url": null,
    "audio_url": null,
    "option_a": "持ちます",
    "option_b": "待ちます",
    "option_c": "特ちます",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "බලා සිටීම / රැඳී සිටීම සඳහා කන්ජිය \"待ちます (まちます - Machimasu)\" වේ."
  },
  {
    "order_num": 15,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "下線のひらがなはどう漢字で書きますか。\n雪で電車が<u>とまりました</u>。",
    "image_url": null,
    "audio_url": null,
    "option_a": "泊まりました",
    "option_b": "止まりました",
    "option_c": "正まりました",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "දුම්රියක් නැවතීම සඳහා නිවැරදි කන්ජිය \"止まりました (とまりました - Tomarimashita)\" වේ."
  },
  {
    "order_num": 16,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "このあたりは店が ＿＿＿＿＿＿＿＿ 便利です。",
    "image_url": null,
    "audio_url": null,
    "option_a": "少なくて",
    "option_b": "多くて",
    "option_c": "大きくて",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "කඩසාප්පු බොහෝ ඇති බැවින් පහසු බව සම්බන්ධ කිරීමට「多くて (Ookute - බහුලව තිබී)」යෙදේ."
  },
  {
    "order_num": 17,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "このあたりは ＿＿＿＿＿＿＿＿ おもしろいです。",
    "image_url": null,
    "audio_url": null,
    "option_a": "にぎやかに",
    "option_b": "ひろいで",
    "option_c": "しずかで",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "な-විශේෂණයක Te-form සම්බන්ධකය \"〜で\" වේ (しずかで - නිස්කලංකව තිබී)."
  },
  {
    "order_num": 18,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "ここは新しい ＿＿＿＿＿＿＿＿ にんきがあります。",
    "image_url": null,
    "audio_url": null,
    "option_a": "町",
    "option_b": "町で",
    "option_c": "町に",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "විශේෂණයට පසුව සෘජුවම නාම පදය වන \"町 (Machi - නගරය)\" යෙදේ (新しい町)."
  },
  {
    "order_num": 19,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "このとおりは夜 ＿＿＿＿＿＿＿＿ あぶないです。",
    "image_url": null,
    "audio_url": null,
    "option_a": "あかるくて",
    "option_b": "くろくて",
    "option_c": "くらくて",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "අඳුරු නිසා අනතුරුදායක බව දැක්වීමට「暗くて (Kurakute)」යෙදේ."
  },
  {
    "order_num": 20,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "このゆうえんちは ＿＿＿＿＿＿＿＿ ふべんです。",
    "image_url": null,
    "audio_url": null,
    "option_a": "みじかくて",
    "option_b": "とおくて",
    "option_c": "ちかくて",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "දුර නිසා අපහසු බව දැක්වීමට「遠くて (Tookute - දුර වැඩි නිසා)」යෙදේ."
  },
  {
    "order_num": 21,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで正しいものを選びなさい】\nA: すみません。コンピューターを ＿＿＿＿＿＿＿＿。\nB: はい、どうぞ。",
    "image_url": "/images/jft_paper15/p15_page_07_img_1.png",
    "audio_url": null,
    "option_a": "かりてもいいですか",
    "option_b": "買いてもいいですか。",
    "option_c": "使ってほうがいいですか",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "අවසර ලබාගැනීමට「〜てもいいですか (かりてもいいですか - පාවිච්චි කළාට/ණයට ගත්තට කමක් නැද්ද?)」යෙදේ."
  },
  {
    "order_num": 22,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで正しいものを選びなさい】\n山田: こちらはひしょのキャシーさんです。\n田中: 田中です。(22)＿＿＿＿＿＿＿＿。\nキャシー: こちらこそ。どうぞよろしく。",
    "image_url": "/images/jft_paper15/p15_page_08_img_1.png",
    "audio_url": null,
    "option_a": "どうもすみません",
    "option_b": "こちらこそ",
    "option_c": "どうぞよろしく",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "මුල්වරට හඳුන්වා දීමේදී \"どうぞよろしく (Douzo yoroshiku)\" යෙදේ."
  },
  {
    "order_num": 23,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで正しいものを選びなさい】\n山田: キャシーさんは日本語、(23)＿＿＿＿＿＿＿＿ です。\n田中: そうですか。",
    "image_url": "/images/jft_paper15/p15_page_08_img_2.png",
    "audio_url": null,
    "option_a": "へらへら",
    "option_b": "ぺらぺら",
    "option_c": "べらべら",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "භාෂාවක් චතුර ලෙස කතා කළ හැකි බව හැඟවීමට \"ぺらぺら (Pera pera - චතුරව)\" ඔනොමටොපියාව යෙදේ."
  },
  {
    "order_num": 24,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【空港での会話】\nA: (24)＿＿＿＿＿＿＿＿、田中さん。\nB: (25)＿＿＿＿＿＿＿＿。(26)＿＿＿＿＿＿＿＿ ありがとうございます。",
    "image_url": "/images/jft_paper15/p15_page_09_img_1.png",
    "audio_url": null,
    "option_a": "いらっしゃる",
    "option_b": "ようこそ",
    "option_c": "こちらこそ",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "පැමිණි කෙනෙකු පිළිගැනීමේදී \"ようこそ (Youkoso - සාදරයෙන් පිළිගනිමු)\" යෙදේ."
  },
  {
    "order_num": 25,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【空港での会話】\nB: (25)＿＿＿＿＿＿＿＿。(26)＿＿＿＿＿＿＿＿ ありがとうございます。",
    "image_url": "/images/jft_paper15/p15_page_09_img_1.png",
    "audio_url": null,
    "option_a": "ありがとう",
    "option_b": "おまたせしました",
    "option_c": "ようこそ",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "රැඳී සිටීමට සිදුවීම ගැන ආචාරශීලීව \"おまたせしました (Omatase shimashita - ප්‍රමාද වූවාට සමාවෙන්න)\" යෙදේ."
  },
  {
    "order_num": 26,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【空港での会話】\nB: おまたせしました。(26)＿＿＿＿＿＿＿＿ ありがとうございます。\nA: フライトはどうでしたか。\nB: まあまあでした。",
    "image_url": "/images/jft_paper15/p15_page_09_img_1.png",
    "audio_url": null,
    "option_a": "帰った",
    "option_b": "でむかえ",
    "option_c": "でむこう",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ගුවන්තොටුපොළට පැමිණ පිළිගැනීම ගැන ස්තූති කිරීමට「お出迎え (でむかえ) ありがとうございます」යෙදේ."
  },
  {
    "order_num": 27,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【食事の会話】\nA: やぎさん、よかったら、サラダ(27)＿＿＿＿＿＿＿＿。\nB: はい、いただきます。",
    "image_url": null,
    "audio_url": null,
    "option_a": "どうぞ",
    "option_b": "ください",
    "option_c": "くださいませんか",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "කෑමක් පිරිනමමින් \"කරුණාකර ගන්න\" යැයි කීමට \"どうぞ (Douzo)\" යෙදේ."
  },
  {
    "order_num": 28,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【食事の会話】\nB: はい、いただきます。このサラダちょっとからくて(28)＿＿＿＿＿＿＿＿ ですね。",
    "image_url": null,
    "audio_url": null,
    "option_a": "おもしろい",
    "option_b": "おもしろくない",
    "option_c": "おいしい",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ආහාරයේ රසවත් බව ප්‍රකාශ කිරීමට \"おいしい (Oishii - රසවත්)\" යෙදේ."
  },
  {
    "order_num": 29,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【食事の会話】\nA: (29)＿＿＿＿＿＿＿＿。もう少しどうですか。\nB: ありがとうございます。(30)＿＿＿＿＿＿＿＿。",
    "image_url": null,
    "audio_url": null,
    "option_a": "どうですか",
    "option_b": "どうしてですか",
    "option_c": "そうですか",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "අනෙකාගේ ප්‍රකාශයට එකඟ වෙමින් \"එහෙමද\" කීමට \"そうですか (Sou desu ka)\" යෙදේ."
  },
  {
    "order_num": 30,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【食事の会話】\nA: もう少しどうですか。\nB: ありがとうございます。(30)＿＿＿＿＿＿＿＿。",
    "image_url": null,
    "audio_url": null,
    "option_a": "まだおなかがいたいです",
    "option_b": "まだおなかがいっぱいです",
    "option_c": "もうおなかがいっぱいです",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "තවදුරටත් කෑම අවශ්‍ය නොවන තරමට බඩ පිරී ඇති බව කීමට「もうおなかがいっぱいです (දැන් බඩ පිරිලා)」යෙදේ."
  },
  {
    "order_num": 31,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて答えなさい】\n女の人はけんこうのために何をしていますか。",
    "image_url": null,
    "audio_url": "/audio/jft_paper15/jft15_q31_q33.mp3",
    "option_a": "ジョギング・ヨガ",
    "option_b": "ヨガ・ダイビング",
    "option_c": "ヨガ・すいえい",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩය අනුව කාන්තාව සෞඛ්‍යය සඳහා යෝගා සහ පිහිනුම් (ヨガ・すいえい) කරයි."
  },
  {
    "order_num": 32,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて答えなさい】\n毎朝何分ぐらいヨガをしていますか。",
    "image_url": null,
    "audio_url": "/audio/jft_paper15/jft15_q31_q33.mp3",
    "option_a": "毎朝2分ぐらい",
    "option_b": "毎朝50分ぐらい",
    "option_c": "毎朝20分ぐらい",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "සෑම උදෑසනකම විනාඩි 20ක් පමණ (毎朝20分ぐらい) යෝගා කරන බව සඳහන් වේ."
  },
  {
    "order_num": 33,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて答えなさい】\n女の人はプールでどのぐらいおよぎますか。",
    "image_url": null,
    "audio_url": "/audio/jft_paper15/jft15_q31_q33.mp3",
    "option_a": "週に1回ぐらい",
    "option_b": "週に2回ぐらい",
    "option_c": "週に3回ぐらい",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "සතියකට දෙවතාවක් පමණ (週に2回ぐらい) පිහිනුම් තටාකයේ පිහිනයි."
  },
  {
    "order_num": 34,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて正しいものを選びなさい】",
    "image_url": null,
    "audio_url": "/audio/jft_paper15/jft15_q34.mp3",
    "option_a": "女の人は毎日5キロぐらい歩きます",
    "option_b": "女の人はしゅうかん5キロぐらいあるきます",
    "option_c": "女の人は土曜日と日曜日5キロぐらい歩きます。",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩය අනුව කාන්තාව දිනපතා කිලෝමීටර් 5ක් පමණ ඇවිදියි (毎日5キロぐらい歩きます)."
  },
  {
    "order_num": 35,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて答えなさい】\nけんこうのためにシンさんは何をしていますか。",
    "image_url": "/images/jft_paper15/p15_page_11_img_1.png",
    "audio_url": "/audio/jft_paper15/jft15_q35_q37.mp3",
    "option_a": "家でヨガをしたりジムでトレーニングをしたりしています。",
    "option_b": "公園でヨガをしたりジムでトレーニングをしたりしています。",
    "option_c": "公園でヨガをしたり家でトレーニングをしたりしています。",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ෂින් මහතා උද්‍යානයේ යෝගා සහ ජිම් එකේ පුහුණුවීම් කරයි (公園でヨガをしたりジムでトレーニングをしたりしています)."
  },
  {
    "order_num": 36,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて答えなさい】\n田中さんはけんこうのために何をしていますか。",
    "image_url": "/images/jft_paper15/p15_page_12_img_1.png",
    "audio_url": "/audio/jft_paper15/jft15_q35_q37.mp3",
    "option_a": "はしったりおよいだりしています",
    "option_b": "ヨガをしたりとトレーニングしたりしています",
    "option_c": "お酒を飲んだりおんがくを聞いたりしています",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "තනකා මහතා දිවීම සහ පිහිනීම සිදු කරයි (はしったりおよいだりしています)."
  },
  {
    "order_num": 37,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて答えなさい】\nよしださんはどこに行っていますか。",
    "image_url": "/images/jft_paper15/p15_page_12_img_2.png",
    "audio_url": "/audio/jft_paper15/jft15_q35_q37.mp3",
    "option_a": "たいしかん",
    "option_b": "たいいくかん",
    "option_c": "としょかん",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "යොෂිඩා මහතා ක්‍රීඩාංගණයට / ජිම්නාසියම් වෙත යයි (たいいくかん - 体育館)."
  },
  {
    "order_num": 38,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて答えなさい】\nAグループ（15人）のスポーツアンケートで、(A) ときどきするに入る人数はどれですか。",
    "image_url": "/images/jft_paper15/p15_page_13_img_1.png",
    "audio_url": "/audio/jft_paper15/jft15_q38_q39.mp3",
    "option_a": "8",
    "option_b": "7",
    "option_c": "4",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩය අනුව විටින් විට ක්‍රීඩා කරන පිරිස 8 දෙනෙකි (8)."
  },
  {
    "order_num": 39,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて答えなさい】\nAグループ（15人）のスポーツアンケートで、(B) しないに入る人数はどれですか。",
    "image_url": "/images/jft_paper15/p15_page_13_img_1.png",
    "audio_url": "/audio/jft_paper15/jft15_q38_q39.mp3",
    "option_a": "5",
    "option_b": "4",
    "option_c": "3",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ක්‍රීඩා නොකරන පිරිස 4 දෙනෙකි (15 - 3 - 8 = 4)."
  },
  {
    "order_num": 40,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて答えなさい】\nさいとうさんはいつ何時にきますか。",
    "image_url": "/images/jft_paper15/p15_page_13_img_2.png",
    "audio_url": "/audio/jft_paper15/jft15_q40.mp3",
    "option_a": "26日、夜3時",
    "option_b": "16日、昼3時",
    "option_c": "19日、昼3時",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "සයිතෝ මහත්මිය 19 වන දින දහවල් 3:00 ට පැමිණෙයි (19日、昼3時)."
  },
  {
    "order_num": 41,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて正しいものを選びなさい】",
    "image_url": "/images/jft_paper15/p15_page_14_img_1.png",
    "audio_url": "/audio/jft_paper15/jft15_q41.mp3",
    "option_a": "ネクタイは誕生日に彼にあげました",
    "option_b": "ネクタイは誕生日に彼にもらいました",
    "option_c": "ネックレスは誕生日に彼にもらいました",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "උපන්දිනයට ඔහුගෙන් ටයි පටියක් තෑගි ලැබුණි (ネクタイは誕生日に彼にもらいました)."
  },
  {
    "order_num": 42,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて答えなさい】\nパクさんは父にもらったのはどれですか。",
    "image_url": "/images/jft_paper15/p15_page_14_img_2.png",
    "audio_url": "/audio/jft_paper15/jft15_q42.mp3",
    "option_a": "かっこう",
    "option_b": "とけい",
    "option_c": "とくい",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "තාත්තාගෙන් ලැබුණු තෑග්ග ඔරලෝසුවකි (とけい - Watch)."
  },
  {
    "order_num": 43,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて答えなさい】\nかばんはいつ買いましたか。",
    "image_url": null,
    "audio_url": "/audio/jft_paper15/jft15_q43.mp3",
    "option_a": "11年前",
    "option_b": "10年前",
    "option_c": "2年前",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "බෑගය මිලදී ගත්තේ මීට වසර 2 කට පෙරයි (2年前)."
  },
  {
    "order_num": 44,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて答えなさい】\nセーターについて何がただしいですか。",
    "image_url": "/images/jft_paper15/p15_page_15_img_1.png",
    "audio_url": "/audio/jft_paper15/jft15_q44_q45.mp3",
    "option_a": "山田さんの主人にもらいました",
    "option_b": "山田さんはお店で買いました。",
    "option_c": "山田さんは自分で作りました",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ස්වීටරය යමඩා මහත්මිය විසින්ම ගොතන ලද එකකි (山田さんは自分で作りました)."
  },
  {
    "order_num": 45,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて答えなさい】\n山田さんは何が好きと言っていますか。",
    "image_url": "/images/jft_paper15/p15_page_15_img_1.png",
    "audio_url": "/audio/jft_paper15/jft15_q44_q45.mp3",
    "option_a": "セーター",
    "option_b": "のみもの",
    "option_c": "あみもの",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ඇය ගෙතුම් කලාවට කැමති බව පවසයි (あみもの - Knitting)."
  },
  {
    "order_num": 46,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【メッセージを読んで正しいものを選びなさい】\nメッセージ：「たなかさん、おつかれさまでした。らいげつ わたしも 日本に しゅっちょうします。東京で いっしょに しょくじしましょう。エドワード」",
    "image_url": "/images/jft_paper15/p15_page_15_img_2.png",
    "audio_url": null,
    "option_a": "田中さんは今晩エドワードさんと食事をします",
    "option_b": "田中さんはしゅっちょうのために東京へ行きます。",
    "option_c": "エドワードさんは仕事のために来月東京へ来ます",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "එඩ්වඩ් ලබන මාසයේ රාජකාරි ගමනක් (出張) සඳහා ටෝකියෝවට පැමිණෙයි (来月東京へ来ます)."
  },
  {
    "order_num": 47,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【スマホのメッセージを読んで答えなさい】\n「じかんをまちがえました。30分くらいおくれます。すみません m(_ _)m」\n\nなぜ彼女は遅れるのですか。",
    "image_url": "/images/jft_paper15/p15_page_16_img_1.png",
    "audio_url": null,
    "option_a": "しんかんせんが止まったから",
    "option_b": "じかんをまちがえたから",
    "option_c": "しんかんせんはまちがえたから",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ඇය වේලාව වරද්දා ගත් බැවින් ප්‍රමාද වේ (じかんをまちがえたから)."
  },
  {
    "order_num": 48,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【電話の会話を読んで答えなさい】\nさかい: もしもし、おがわさんですか。さかいです。\nおがわ: ああ、さかいさん。こんにちは。札幌はどうですか。\nさかい: 今、雪がふっていますよ。今日はちょっとさむいです。\nおがわ: そうですか。大阪はあさからくもっていますよ。たぶんごごは雨です。\n\nおがわさんはどこにいますか。",
    "image_url": "/images/jft_paper15/p15_page_16_img_2.png",
    "audio_url": null,
    "option_a": "おおさか",
    "option_b": "さっぽろ",
    "option_c": "きゅうしゅう",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "ඔගාවා මහතා ඔසාකාවේ සිටියි (大阪はあさからくもっていますよ)."
  },
  {
    "order_num": 49,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【電話の会話を読んで答えなさい】\n今日おおさかについて何がただしいですか。",
    "image_url": "/images/jft_paper15/p15_page_16_img_2.png",
    "audio_url": null,
    "option_a": "朝から雨がふっています",
    "option_b": "午後雨がふるそうです",
    "option_c": "夜雨がふらないそうです",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ඔසාකාවේ සවස් කාලයේ වැසි ඇති විය හැකි බව පවසයි (たぶんごごは雨です)."
  },
  {
    "order_num": 50,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【電話の会話を読んで答えなさい】\n今日さっぽろはどうですか。",
    "image_url": "/images/jft_paper15/p15_page_16_img_2.png",
    "audio_url": null,
    "option_a": "はれですから寒いです",
    "option_b": "雨がふっているから寒いです",
    "option_c": "雪がふっているから寒いです",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "සැප්පෝරෝ හි හිම වැටෙන බැවින් ශීතලයි (雪がふっていますよ。今日はちょっとさむいです)."
  },
  {
    "order_num": 51,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【出張連絡のメールを読んで○か×かを選びなさい】\n「たなかさん、エドワードです。らいしゅうの出張は私とタイラーさんが担当します。」\n\nエドワードさんは田中さんにメールを書きました。",
    "image_url": "/images/jft_paper15/p15_page_17_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "එඩ්වඩ් තනකා මහතා වෙත ඊමේල් පණිවිඩය යවා ඇත. එබැවින් නිවැරදිය (〇)."
  },
  {
    "order_num": 52,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【出張連絡のメールを読んで○か×かを選びなさい】\n田中さんは来週出張します。",
    "image_url": "/images/jft_paper15/p15_page_17_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "තනකා මහතා ලබන සතියේ රාජකාරි සංචාරයක නිරත වේ. එබැවින් නිවැරදිය (〇)."
  },
  {
    "order_num": 53,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【出張連絡のメールを読んで○か×かを選びなさい】\n「おぼえていますか。日本で会ったことがあります。」\n\n田中さんはエドワードさんに会ったことがありません。",
    "image_url": "/images/jft_paper15/p15_page_17_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ඔවුන් ජපානයේදී මුණගැසී ඇත. එබැවින් ප්‍රකාශය වැරදිය (×)."
  },
  {
    "order_num": 54,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【出張連絡のメールを読んで○か×かを選びなさい】\n「空港にはタイラーさんがむかえに行きます。」\n\nエドワードさんとタイラーさんはくうこうにむかえに行きます。",
    "image_url": "/images/jft_paper15/p15_page_17_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ගුවන් තොටුපොළට පිළිගැනීමට යන්නේ ටයිලර් පමණි. එබැවින් වැරදිය (×)."
  },
  {
    "order_num": 55,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【出張連絡のメールを読んで○か×かを選びなさい】\n「出発時間と到着時間をおしえてください。」\n\n田中さんはエドワードさんにひこうきの時間をれんらくします。",
    "image_url": "/images/jft_paper15/p15_page_17_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "තනකා මහතා පිටත්වන සහ ළඟාවන වේලාවන් දැනුම් දෙනු ඇත. එබැවින් නිවැරදිය (〇)."
  },
  {
    "order_num": 56,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【田中さんの返信メールを読んで○か×かを選びなさい】\n「出発時間は午前9時、到着時間は午後8時、フライトはJF071です。」\n\n田中さんの出発の時間は午前９時です。",
    "image_url": "/images/jft_paper15/p15_page_18_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "පිටත්වීමේ වේලාව පෙරවරු 9:00 යි. එබැවින් නිවැරදිය (〇)."
  },
  {
    "order_num": 57,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【田中さんの返信メールを読んで○か×かを選びなさい】\n「出張のとき、日本のお酒をおみやげに持って行きます。」\n\n田中さんはおみやげに持って行くのは日本酒です。",
    "image_url": "/images/jft_paper15/p15_page_18_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "තනකා රැගෙන එන්නේ ජපන් සාකේ මත්පැන් (日本酒) ය. එබැවින් නිවැරදිය (〇)."
  },
  {
    "order_num": 58,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【朝食アンケートの会話を読んで正しいグラフを選びなさい】\n「毎朝食べる人は20人、食べない人は30人、ときどき食べる人は50人です。」\n\n説明にあうグラフ（円グラフ）を選びなさい。",
    "image_url": "/images/jft_paper15/p15_page_19_img_1.png",
    "audio_url": null,
    "option_a": "a",
    "option_b": "b",
    "option_c": "",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "සෑම දිනම 20ක්, නොකන 30ක්, විටින් විට 50ක් දැක්වෙන නිවැරදි ප්‍රස්ථාරය \"a\" වේ."
  },
  {
    "order_num": 59,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【誕生日の会話を読んで答えなさい】\nのだ: 来週の木よう日、たなかさんの誕生日ですね。みんなでお祝いをしませんか。\nキム: いいですね。パーティーがいいと思います。\n\nパーティーはどうしてしますか。",
    "image_url": "/images/jft_paper15/p15_page_20_img_1.png",
    "audio_url": null,
    "option_a": "田中さんの結婚式のために",
    "option_b": "田中さんの誕生日のために",
    "option_c": "田中さんの卒業のために",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "තනකාගේ උපන්දිනය සැමරීමට සාදය පවත්වයි (田中さんの誕生日のために)."
  },
  {
    "order_num": 60,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【誕生日の会話を読んで答えなさい】\nキム: たなかさんはメキシコ料理が好きだと思います。レストラン「アミーゴ」はどうですか。\nのだ: いいですね。そうしましょう。\n\nパーティーはどこでしますか。",
    "image_url": "/images/jft_paper15/p15_page_20_img_1.png",
    "audio_url": null,
    "option_a": "日本れすとらんで",
    "option_b": "メキツコレストラン「ナミーゴ」で",
    "option_c": "メキシコのレストラン「アミーゴ」で",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "මෙක්සිකානු අවන්හලක් වන \"Amigo\" (メキシコのレストラン「アミーゴ」) හි සාදය පැවැත්වේ."
  }
];

    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, section_name, order_num, question_text, question_type,
          option_a, option_b, option_c, option_d, correct_option, marks, explanation,
          image_url, audio_url
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId,
        q.section_name,
        q.order_num,
        q.question_text,
        'multiple_choice',
        q.option_a,
        q.option_b,
        q.option_c,
        q.option_d || '',
        q.correct_option,
        q.marks,
        q.explanation,
        q.image_url,
        q.audio_url
      ]);
    }

    console.log(`Successfully seeded ${questions.length} questions for Paper 15 (Exam ${examId})`);
  } catch (err) {
    console.error('Error seeding JFT Paper 15:', err);
  }
}

module.exports = { seedJftModelPaper15 };
