const { query } = require('../config/database');

async function seedJftModelPaper03() {
  try {
    const title = 'JFT-Basic Official Model Paper 03 (60 Minutes)';
    const existingExam = await query.get("SELECT id FROM exams WHERE title = ?", [title]);
    let examId;

    if (existingExam) {
      examId = existingExam.id;
      const countRes = await query.get("SELECT COUNT(*) as count FROM questions WHERE exam_id = ?", [examId]);
      if (countRes && countRes.count >= 60) {
        await query.run('UPDATE exams SET duration_minutes = 60, passing_score = 200 WHERE id = ?', [examId]);
        await query.run('UPDATE questions SET marks = 1 WHERE exam_id = ? AND order_num >= 1 AND order_num <= 5', [examId]);
        await query.run('UPDATE questions SET marks = 2 WHERE exam_id = ? AND order_num >= 6 AND order_num <= 15', [examId]);
        await query.run('UPDATE questions SET marks = 5 WHERE exam_id = ? AND order_num >= 16 AND order_num <= 60', [examId]);
        return;
      }
      console.log(`Seeding JFT Model Paper 03 (Exam ID: ${examId})...`);
      await query.run(`
        UPDATE exams 
        SET description = 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper 03 (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [examId]);
      await query.run("DELETE FROM questions WHERE exam_id = ?", [examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (1, ?, 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper 03 (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.', 60, 200, 1)
      `, [title]);
      examId = res.id;
      console.log(`Created JFT Model Paper 03 (Exam ID: ${examId})`);
    }

    const questions = [
      // ==========================================
      // SECTION 1: Script & Vocabulary (文字・語彙 - Q01 to Q15)
      // ==========================================
      {
        order_num: 1,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q01.jpg',
        audio_url: null,
        option_a: 'おにいさん',
        option_b: 'おかあさん',
        option_c: 'おとうさん',
        option_d: '',
        correct_option: 'B',
        marks: 1,
        explanation: 'おかあさん (Mother / අම්මා).'
      },
      {
        order_num: 2,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q02.jpg',
        audio_url: null,
        option_a: 'よみます',
        option_b: 'わらいます',
        option_c: 'はしります',
        option_d: '',
        correct_option: 'A',
        marks: 1,
        explanation: 'よみます (Read / කියවනවා).'
      },
      {
        order_num: 3,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q03.jpg',
        audio_url: null,
        option_a: 'じてんしゃ',
        option_b: 'バス',
        option_c: 'くるま',
        option_d: '',
        correct_option: 'C',
        marks: 1,
        explanation: 'くるま (車 - Car / මෝටර් රථය).'
      },
      {
        order_num: 4,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q04.jpg',
        audio_url: null,
        option_a: 'うま',
        option_b: 'うし',
        option_c: 'とり',
        option_d: '',
        correct_option: 'A',
        marks: 1,
        explanation: 'うま (馬 - Horse / අශ්වයා).'
      },
      {
        order_num: 5,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q05.jpg',
        audio_url: null,
        option_a: 'やすみます',
        option_b: 'べんきょうします',
        option_c: 'ねます',
        option_d: '',
        correct_option: 'B',
        marks: 1,
        explanation: 'べんきょうします (勉強します - Study / පාඩම් කරනවා).'
      },
      {
        order_num: 6,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄に最もよく当てはまる助詞を選んでください。\n\nこれ（　）にほん（　）とけいです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'は・が',
        option_b: 'は・ご',
        option_c: 'は・の',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: 'これ「は」 日本「の」 時計です。(This is a Japanese watch).'
      },
      {
        order_num: 7,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄に最もよく当てはまる助詞を選んでください。\n\nＡ：ラオさんは　インド人　です。ナロンさん（　）インド人　ですか。\nＢ：いいえ、ナロンさん（　）インド人ではありません。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'も・は',
        option_b: 'は・も',
        option_c: 'も・も',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: 'ナロンさん「も」インド人ですか。いいえ、ナロンさん「は」インド人ではありません。'
      },
      {
        order_num: 8,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄に最もよく当てはまる助詞を選んでください。\n\nやまもとさん（　）かいしゃ（　）どこです（　）。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'の・は・が',
        option_b: 'の・の・か',
        option_c: 'の・は・か',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '山本さん「の」 会社「は」 どこです「か」。'
      },
      {
        order_num: 9,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄に最もよく当てはまる助詞を選んでください。\n\nこのざっし（　）ください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'を',
        option_b: 'に',
        option_c: 'が',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: 'この雑誌「を」ください。(Please give me this magazine).'
      },
      {
        order_num: 10,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄に最もよく当てはまる助詞を選んでください。\n\nＡ：これ　は　あなた（　）ノート　ですか。\nＢ：いいえ、私（　）ではありません。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'は・は',
        option_b: 'が・が',
        option_c: 'の・の',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: 'あなた「の」ノート ... 私「の」ではありません。(Mine).'
      },
      {
        order_num: 11,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（______）の漢字の読み方として正しいものを一つ選んでください。\n\n<u>辞書</u>で意味をしらべます。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'じしょう',
        option_b: 'じいしょ',
        option_c: 'じしょ',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '辞書 (じしょ - Dictionary / ශබ්දකෝෂය).'
      },
      {
        order_num: 12,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（______）の漢字の読み方として正しいものを一つ選んでください。\n\nここは<u>図書館</u>です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'としょかん',
        option_b: 'としょしつ',
        option_c: 'としょうかん',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '図書館 (としょかん - Library / පුස්තකාලය).'
      },
      {
        order_num: 13,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（______）の漢字の読み方として正しいものを一つ選んでください。\n\n明日<u>花火</u>を見に行きませんか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'はなや',
        option_b: 'はなび',
        option_c: 'ばなび',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '花火 (はなび - Fireworks / ගිනිකෙළි).'
      },
      {
        order_num: 14,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'Read the sentence and choose the word that fits in blank the most.\n\n私のうちは５にん<u>　（　）　</u>です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'きょうだい',
        option_b: 'ひと',
        option_c: 'かぞく',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '５人家族 (ごにんかぞく - Family of 5 / පස් දෙනෙකුගෙන් යුත් පවුලකි).'
      },
      {
        order_num: 15,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'Read the sentence and choose the word that fits in blank the most.\n\nこれはとうきょうのちずですね。やまださんのうちは<u>　（　）　</u>ですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'どこ',
        option_b: 'いつ',
        option_c: 'この',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: 'どこ (Where / කොහේද?).'
      },

      // ==========================================
      // SECTION 2: Conversation & Expression (会話・表現 - Q16 to Q30)
      // ==========================================
      {
        order_num: 16,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'イラストを見て、空欄に最もよく当てはまる言葉を選んでください。\n\n<u>　（　）　</u>に車をとめてください。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q16.jpg',
        audio_url: null,
        option_a: 'へや',
        option_b: 'ちゅうしゃじょう',
        option_c: 'しょくどう',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ちゅうしゃじょう (駐車場 - Parking lot / වාහන නැවතුම්පළ).'
      },
      {
        order_num: 17,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'イラストを見て、空欄に最もよく当てはまる言葉を選んでください。\n\nはこにりんごが<u>　（　）　</u>ありますか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q17.jpg',
        audio_url: null,
        option_a: 'なんご',
        option_b: 'なんこう',
        option_c: 'なんこ',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'なんこ (何個 - How many [pieces of fruit] / කීයක්ද?).'
      },
      {
        order_num: 18,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'イラストを見て、空欄に最もよく当てはまる言葉を選んでください。\n\nハンバーガーを<u>　（　）　</u>ください。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q18.jpg',
        audio_url: null,
        option_a: 'ひとり',
        option_b: 'ひとつ',
        option_c: 'いち',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ひとつ (一つ - One item / එකක්).'
      },
      {
        order_num: 19,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に最もよく当てはまる表現を選んでください。\n\nリサ：はじめまして。私はアメリカのリサです。\nアベ：はじめまして。私はアベです。タイじんです。私は23さいです。<u>　（　）　</u>。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q19.jpg',
        audio_url: null,
        option_a: 'ありがとうございました',
        option_b: 'はじめまして',
        option_c: 'どうぞよろしく',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'どうぞよろしく (どうぞよろしくお願いします - Nice to meet you).'
      },
      {
        order_num: 20,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に最もよく当てはまる言葉を選んでください。\n\nサリ：すみません。ぎんこうはどこですか。\nシン：えきのまえです。\nサリ：ぎんこうのちかくに<u>　（　）　</u>がありますか。\nシン：スーパーやデパートやレストランなどがあります。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'いくつ',
        option_b: 'なに',
        option_c: 'どの',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '何がありますか (なにがありますか - What is there?).'
      },
      {
        order_num: 21,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に最もよく当てはまる言葉を選んでください。\n\nシン：サリさんはたばこをすいますか。\nサリ：はい、すいます。シンさんはたばこをすいますか。\nシン：いいえ、私は<u>　（　）　</u>。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'すいません',
        option_b: 'すいます',
        option_c: 'すってもいいです',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'すいません (吸いません - I do not smoke / බොන්නේ නැත).'
      },
      {
        order_num: 22,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に最もよく当てはまる言葉を選んでください。\n\n中田：リンさんは、どんな人ですか。\nサリ：そうですね、<u>　（　）　</u>、やさしい人です。\n中田：そうですか。若いですか。\nサリ：ええ、若くてきれいです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'しんせつな',
        option_b: 'しんせつで',
        option_c: 'しんせつに',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'しんせつで（親切で）、やさしい人です。(na-adjective te-form to join adjectives).'
      },
      {
        order_num: 23,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄 [ 23 ] に最もよく当てはまる言葉を選んでください。\n\nサリ：土曜日の夜、カラオケへいきました。\nシン：そうですか。[ 23 ] うたをうたいましたか。\nサリ：日本のうたをうたいました。\nシン：シンさんも日本のうたをうたいますか。\nシン：はい、でも、私はうたが [ 24 ] です。妹はじょうずです。妹はこえがいいです。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q23_24.jpg',
        audio_url: null,
        option_a: 'どこ',
        option_b: 'なん',
        option_c: 'どんな',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'どんなうた (What kind of songs / මොන වගේ ගීතද?).'
      },
      {
        order_num: 24,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄 [ 24 ] に最もよく当てはまる言葉を選んでください。\n\n【会話文】\nサリ：土曜日の夜、カラオケへいきました。\nシン：そうですか。どんなうたをうたいましたか。\nサリ：日本のうたをうたいました。\nシン：シンさんも日本のうたをうたいますか。\nシン：はい、でも、私はうたが [ 24 ] です。妹はじょうずです。妹はこえがいいです。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q23_24.jpg',
        audio_url: null,
        option_a: 'へた',
        option_b: 'じょうず',
        option_c: 'とくい',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'へた (下手 - Bad at singing / දක්ෂ නැත). 「妹はじょうずです」 සමඟ ප්‍රතිවිරුද්ධ වේ.'
      },
      {
        order_num: 25,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に最もよく当てはまる言葉を選んでください。\n\nパク：ブラウンさん、これから何をしますか。\nブラウン：日本人の友達に<u>　（　）　</u>。\nパク：へえ、日本語でかきますか。\nブラウン：いいえ、えい語でかきます。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q25.jpg',
        audio_url: null,
        option_a: 'にっきをかきます',
        option_b: 'ねます',
        option_c: 'てがみをかきます',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'てがみをかきます (手紙を書きます - Write a letter / ලියුමක් ලියනවා).'
      },
      {
        order_num: 26,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄 [ 26 ] に最もよく当てはまる言葉を選んでください。\n\nがくせい：[ 26 ]。\nせんせい：はい。\nがくせい：きょうのテストは何時から何時までですか。\nせんせい：９時10分 [ 27 ] 10時までです。\nがくせい：どうもありがとうございます。\nせんせい：いいえ、どういたしまして。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q26_27.jpg',
        audio_url: null,
        option_a: 'どうですか',
        option_b: 'はじめまして',
        option_c: 'すみません',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'すみません (Excuse me / සමා වෙන්න).'
      },
      {
        order_num: 27,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄 [ 27 ] に最もよく当てはまる言葉を選んでください。\n\n【会話文】\nがくせい：すみません。\nせんせい：はい。\nがくせい：きょうのテストは何時から何時までですか。\nせんせい：９時10分 [ 27 ] 10時までです。\nがくせい：どうもありがとうございます。\nせんせい：いいえ、どういたしまして。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q26_27.jpg',
        audio_url: null,
        option_a: 'から',
        option_b: 'まで',
        option_c: 'ので',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'から (〜から 〜まで - From ... to ...).'
      },
      {
        order_num: 28,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に最もよく当てはまる言葉を選んでください。\n\nサリ：パクさんのえを見ましたか。\nシン：はい、見ました。とてもきれいなえですね。\nサリ：ええ、パクさんはえがじょうずですね。\nシン：そうですか、とてもじょうずですね。\nサリ：私はえがへたです。シンさんは<u>　（　）　</u>。\nシン：私もあまりじょうずではありません。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q28.jpg',
        audio_url: null,
        option_a: 'どうですか',
        option_b: 'どうしてですか',
        option_c: 'きれいですか',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'どうですか (How about you? / ඔයා කොහොමද?).'
      },
      {
        order_num: 29,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に最もよく当てはまる言葉を選んでください。\n\nきゃく：すみません、ミコンのカメラはありますか。\nでんいん：はい、こちらです。\nきゃく：<u>　（　）　</u>。\nでんいん：それは五万六千円です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'いくらになりますか',
        option_b: 'いつになりますか',
        option_c: 'いくつになりますか',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'いくらになりますか (いくらですか - How much is it? / මිල කීයද?).'
      },
      {
        order_num: 30,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に最もよく当てはまる言葉を選んでください。\n\nきゃく１：何がいいですか。\nきゃく２：ジュースがいいです。\nきゃく１：すみません。ジュースとコーラをおねがいします。\nウェートレス：はい、ジュースとコーラですね。<u>　（　）　</u>。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q30.jpg',
        audio_url: null,
        option_a: 'どうぞよろしく',
        option_b: 'かしこまりました',
        option_c: 'はい、そうします',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'かしこまりました (Certainly / understood / පැහැදිලියි, එසේ කරන්නම්).'
      },

      // ==========================================
      // SECTION 3: Listening Comprehension (聴解 - Choukai - Q31 to Q45)
      // ==========================================
      {
        order_num: 31,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA man and a woman are talking. Where will they meet on Saturday?\n(男の人と女の人が話しています。土曜日にどこで会いますか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft03_q31_meeting_place.mp3',
        option_a: 'かいしゃ',
        option_b: 'かいしゃのちかく',
        option_c: 'レストラン',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'レストラン (Restaurant / ආපන ශාලාවේදී).'
      },
      {
        order_num: 32,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA man and a woman are talking. What time and where will they meet?\n(男の人と女の人が話しています。何時にどこで会いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q32.jpg',
        audio_url: '/uploads/audio/jft03_q32_meeting_location.mp3',
        option_a: 'A (デパートの入口)',
        option_b: 'B (駅の改札口)',
        option_c: 'C (駅の時計の下)',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'B (At the train station ticket gates / දුම්රිය ස්ථානයේ ප්‍රවේශ පත්‍ර දොරටුව අසල).'
      },
      {
        order_num: 33,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA man and a woman are talking. What does woman do first?\n(男の人と女の人が話しています。女の人ははじめに何をしますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q33.jpg',
        audio_url: '/uploads/audio/jft03_q33_first_action.mp3',
        option_a: 'A (同僚と話す)',
        option_b: 'B (コピーをする)',
        option_c: 'C (書類を整理する)',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'B (Copy documents first / ලියකියවිලි කොපි කිරීම).'
      },
      {
        order_num: 34,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA man and a woman are talking. How many ballpoint pens does the woman buy?\n(男の人と女の人が話しています。女の人はボールペンを何本買いますか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft03_q34_pens_count.mp3',
        option_a: '1ぽん買います',
        option_b: '3ぼん買います',
        option_c: '12ほん買います',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '3ぼん買います (3本 - Three pens / බෝල්පොයින්ට් පෑන් 3ක්).'
      },
      {
        order_num: 35,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nThe man is calling to the hospital. When does the man go to hospital?\n(男の人が病院に電話しています。男の人はいつ病院へ行きますか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft03_q35_hospital_time.mp3',
        option_a: 'おひるです',
        option_b: '今日いきません',
        option_c: '夜7時のあとです',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '夜7時のあとです (After 7 PM in the evening / රාත්‍රී 7න් පසුව).'
      },
      {
        order_num: 36,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA man and a woman are talking. Where will they eat in next week?\n(男の人と女の人が話しています。来週どこで食事をしますか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft03_q36_eating_place.mp3',
        option_a: 'いつも行くレストランです',
        option_b: 'ホテルです',
        option_c: '女の人のうちです',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '女の人のうちです (At the woman\'s home / කාන්තාවගේ නිවසේදී).'
      },
      {
        order_num: 37,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】イラストと矢印（やじるし）を見て、正しい挨拶を選んでください。\n\nShe is going to school. What does she say?\n(学校へ出かけるとき、何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q37.jpg',
        audio_url: '/uploads/audio/jft03_q37_going_school.mp3',
        option_a: '1 (いってきます)',
        option_b: '2 (ただいま)',
        option_c: '3 (おかえりなさい)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '1 (いってきます - I\'m leaving / ගිහින් එන්නම්).'
      },
      {
        order_num: 38,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】イラストと矢印（やじるし）を見て、正しい表現を選んでください。\n\nIt\'s on the train. What does he say?\n(電車の中で席をゆずるとき、何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q38.jpg',
        audio_url: '/uploads/audio/jft03_q38_train_seat.mp3',
        option_a: '1 (どうぞ)',
        option_b: '2 (すみません)',
        option_c: '3 (ありがとう)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '1 (どうぞ - Please / මෙතනින් වාඩිවෙන්න).'
      },
      {
        order_num: 39,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】イラストと矢印（やじるし）を見て、正しいお祝いの言葉を選んでください。\n\nHaving a birthday party. What do they say?\n(誕生日パーティーで何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q39.jpg',
        audio_url: '/uploads/audio/jft03_q39_birthday_party.mp3',
        option_a: '1 (おたんじょうび おめでとう)',
        option_b: '2 (いただきます)',
        option_c: '3 (ごちそうさまでした)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '1 (おたんじょうび おめでとう - Happy Birthday!).'
      },
      {
        order_num: 40,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】イラストと矢印（やじるし）を見て、正しい返答を選んでください。\n\nLooking at the pen and answering. What does he say?\n(ペンを落としましたよと言われたとき、何と答えますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q40.jpg',
        audio_url: '/uploads/audio/jft03_q40_lost_pen.mp3',
        option_a: '1 (あ、ありがとうございます)',
        option_b: '2 (いいえ、けっこうです)',
        option_c: '3 (ごめんなさい)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '1 (あ、ありがとうございます - Ah, thank you!).'
      },
      {
        order_num: 41,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】イラストと矢印（やじるし）を見て、正しい注文の表現を選んでください。\n\nAsking for a drink at a coffee shop. What does she say?\n(カフェで飲み物を注文するとき、何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q41.jpg',
        audio_url: '/uploads/audio/jft03_q41_coffee_shop.mp3',
        option_a: '1 (コーヒーをください)',
        option_b: '2 (コーヒーはどうですか)',
        option_c: '3 (コーヒーがありますか)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '1 (コーヒーをください - Coffee, please / කෝපි එකක් දෙන්න).'
      },
      {
        order_num: 42,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、矢印（やじるし）の男の人の返答として正しいものを選んでください。\n\n(トイレの場所を聞かれました。何と答えますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q42.jpg',
        audio_url: '/uploads/audio/jft03_q42_toilet_location.mp3',
        option_a: '1 (あちらです)',
        option_b: '2 (ここです)',
        option_c: '3 (どちらです)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '1 (あちらです - Over that way / අර පැත්තේ).'
      },
      {
        order_num: 43,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、正しい挨拶を選んでください。\n\n(熱があって寝ている友達に何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q43.jpg',
        audio_url: '/uploads/audio/jft03_q43_fever_sick.mp3',
        option_a: '1 (お大事に)',
        option_b: '2 (お疲れ様でした)',
        option_c: '3 (ごめんなさい)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '1 (お大事に - おだいじに - Get well soon / ඉක්මන් සුවය පතනවා).'
      },
      {
        order_num: 44,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、矢印（やじるし）の人の言葉として正しいものを選んでください。\n\n(風が吹いて寒いとき、何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q44.jpg',
        audio_url: '/uploads/audio/jft03_q44_cold_weather.mp3',
        option_a: '1 (さむいですね)',
        option_b: '2 (あついですね)',
        option_c: '3 (すずしいですね)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '1 (さむいですね - It\'s cold, isn\'t it? / හරිම ශීතලයි නේද).'
      },
      {
        order_num: 45,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【リスニング問題】音声を聞いて、矢印（やじるし）の男の人の言葉として正しいものを選んでください。\n\n(クッキーを友達にすすめるとき、何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q45.jpg',
        audio_url: '/uploads/audio/jft03_q45_cookies.mp3',
        option_a: '1 (クッキー、いかがですか / どうぞ)',
        option_b: '2 (いただきます)',
        option_c: '3 (ごちそうさまでした)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '1 (クッキー、どうぞ - Please have some cookies / කුකීස් ටිකක් ගන්න).'
      },

      // ==========================================
      // SECTION 4: Reading Comprehension (読解 - Dokkai - Q46 to Q60)
      // ==========================================
      {
        order_num: 46,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、正しい答えを選んでください。\n\n【メイさんの自己紹介】\n私はメイ・スミスです。私はカナダじん（ 46 ）。今、日本にすんでいます。しごとはえいごの先生です。しゅみはりょこうと本をよむことです。スポーツはしませんが、見るのはとてもすきです。\n\n質問：（ 46 ）の中にいちばんよいものをいれなさい。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'です',
        option_b: 'でした',
        option_c: 'ではありません',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'です (私はカナダ人です - I am Canadian).'
      },
      {
        order_num: 47,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【メイさんの自己紹介】\n私はメイ・スミスです。私はカナダじんです。今、日本にすんでいます。しごとはえいごの先生です。しゅみはりょこうと本をよむことです。スポーツはしませんが、見るのはとてもすきです。\n\n質問：メイさんのしゅみでないのはどれですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '本をよむこと',
        option_b: 'りょこうすること',
        option_c: 'スポーツをすること',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'スポーツをすること (「スポーツはしません」と書いてあるため、趣味ではありません).'
      },
      {
        order_num: 48,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、正しい答えを選んでください。\n\nヤンさんのうちは町の中にべんりなところにあります。となりにパン屋があります。前は花屋で花屋のとなりは魚やです。ちかくにくすり屋と肉屋もあります。ゆうびんきょくも病院もあります。\n今日のゆうがたヤンさんの友達があそびに来ます。ヤンさんはとり肉の料理と魚の料理を作ります。れいぞうこの中にとり肉と魚がありませんから、ヤンさんはこれから買い物に出かけます。それから、ゆうびんきょくへ行って、きってを買います。\n\n質問：今日ヤンさんはどこに行きますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'にくや、さかなや、ゆうびんきょく',
        option_b: 'パンや、くすりや、ゆうびんきょく',
        option_c: 'びょういん、はなや、さかなや',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'にくや、さかなや、ゆうびんきょく (鶏肉を買うため肉屋、魚を買うため魚屋、切手を買うため郵便局へ行きます).'
      },
      {
        order_num: 49,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、空欄に最もよく当てはまる言葉を選んでください。\n\nジョンさんとアベさんは明日じこしょうかいをします。二人はじこしょうかいのぶんしょうをかきました。\n\n（１）ジョンさんの自己紹介\nはじめまして。ジョン・スミスです。アメリカから来ました。私はえいががすきです。アメリカのえいがはよくしっています。でも、日本のえいがはあまりしりません。日本では、日本のえいがをたくさん見たいです。どうぞよろしくお願いします。\n\n（２）アベさんの自己紹介\nみなさん、こんにちは。アベです。私は日本語がっこうで毎日べんきょうしています。今は、がっこうのちかくに姉とすんでいます。姉がいるから、<u>　（　）　</u>。私は、日本でたくさん友達がほしいです。みなさん、うちにあそびに来てください。どうぞよろしくお願いします。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q49.jpg',
        audio_url: null,
        option_a: 'さびしいです',
        option_b: 'さびしくありません',
        option_c: 'さびしいであります',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'さびしくありません (姉がいるから、さびしくありません - Because my sister is with me, I am not lonely).'
      },
      {
        order_num: 50,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '説明文を読んで、「これ」が指すものを選んでください。\n\nこれはてがみをだすときにつかいます。ふうとうにこれをはって、それから、ポストにいれます。これはゆうびんきょくなどで買います。\n\n質問：「これ」は何ですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q50.jpg',
        audio_url: null,
        option_a: 'はがき',
        option_b: 'きっぷ',
        option_c: 'きって',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'きって (切手 - Postage stamp / මුද්දරය). 封筒に貼るものは切手です。'
      },
      {
        order_num: 51,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、正しいものを選んでください。\n\n昨日、友達のいえへ行って、友達がつくりょうりを食べました。すこしからかったです。とてもおいしかったです。私も友達もたくさん食べました。またたべたいです。\n\n質問：ここにあっているものはどれですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '私はりょうりをつくりました',
        option_b: '友達はりょうりがじょうずです',
        option_c: 'りょうりはおいしくありませんでした。',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '友達はりょうりがじょうずです (Friend makes delicious food).'
      },
      {
        order_num: 52,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、空欄に最もよく当てはまる時間を選んでください。\n\n私のうちからがっこうまで<u>　（　）　</u>かかります。うちからＡえきまで、うちから10分です。ＡえきからＢえきまででんしゃで30分ぐらいです。それから、Ｂえきでバスにのります。バスにのってだいたい10分か15分でがっこうにつきます。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '1時間ぐらい',
        option_b: '30分ぐらい',
        option_c: '45分か40分ぐらい',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '1時間ぐらい (10分徒歩 + 30分電車 + 10〜15分バス = 合計約50〜55分 ≈ 1時間).'
      },
      {
        order_num: 53,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【３つのスーパーについての文章】\n私のうちのちかくにスーパーがみっつあります。「毎日屋」と「ABCストア」と「ジャパン」です。\n「毎日屋」はいちばんちいさいみせですが、ちかいです。うちからあるいて５分です。あたらしいさかなが多いです。やさいや、くだものも多いです。がいこくのものはぜんぜんありません。\n「ABCストア」はうちからあるいて15分かかります。にくが多いです。いちばんやすいみせです。がいこくのものもありますが「ジャパン」よりすくないです。おいしいパンがあります。\n「ジャパン」はいちばんとおいです。さかなはあまり多くないですが、にくがたくさんあります。がいこくのものが多いです。とても大きいみせです。「ABCストア」より大きいです。みっつみせの中で私は「ABCストア」がいちばんすきです。\n\n質問：みっつの店で「ジャパン」がいちばん大きいです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (正しくない)',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '〇 (「とても大きいみせです。ABCストアより大きいです」とあり、ジャパンが一番大きいです).'
      },
      {
        order_num: 54,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【３つのスーパーについての文章】\n私のうちのちかくにスーパーがみっつあります。「毎日屋」と「ABCストア」と「ジャパン」です。\n「毎日屋」はいちばんちいさいみせですが、ちかいです。うちからあるいて５分です。あたらしいさかなが多いです。やさいや、くだものも多いです。がいこくのものはぜんぜんありません。\n「ABCストア」はうちからあるいて15分かかります。にくが多いです。いちばんやすいみせです。がいこくのものもありますが「ジャパン」よりすくないです。おいしいパンがあります。\n「ジャパン」はいちばんとおいです。さかなはあまり多くないですが、にくがたくさんあります。がいこくのものが多いです。とても大きいみせです。「ABCストア」より大きいです。みっつみせの中で私は「ABCストア」がいちばんすきです。\n\n質問：「毎日屋」のさかなはあたらしいですが、すくないです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (正しくない)',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '× (「あたらしいさかなが多いです」と書かれているため、すくないは間違いです).'
      },
      {
        order_num: 55,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【３つのスーパーについての文章】\n私のうちのちかくにスーパーがみっつあります。「毎日屋」と「ABCストア」と「ジャパン」です。\n「毎日屋」はいちばんちいさいみせですが、ちかいです。うちからあるいて５分です。あたらしいさかなが多いです。やさいや、くだものも多いです。がいこくのものはぜんぜんありません。\n「ABCストア」はうちからあるいて15分かかります。にくが多いです。いちばんやすいみせです。がいこくのものもありますが「ジャパン」よりすくないです。おいしいパンがあります。\n「ジャパン」はいちばんとおいです。さかなはあまり多くないですが、にくがたくさんあります。がいこくのものが多いです。とても大きいみせです。「ABCストア」より大きいです。みっつみせの中で私は「ABCストア」がいちばんすきです。\n\n質問：私のうちから「ABCストア」がいちばんちかいです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (正しくない)',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '× (いちばん近いのは歩いて5分の「毎日屋」です).'
      },
      {
        order_num: 56,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '地図を見て、質問に答えてください。\n\n質問：レストランとこうえんのあいだに何がありますか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q56_57.jpg',
        audio_url: null,
        option_a: 'びょういんがあります',
        option_b: 'でんわがあります',
        option_c: 'なにもありません',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'なにもありません (レストランと公園の間は道路で、建物等はありません).'
      },
      {
        order_num: 57,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '地図を見て、質問に答えてください。\n\n質問：えいごのがっこうは東京ビルのなんがいですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q56_57.jpg',
        audio_url: null,
        option_a: '3がい',
        option_b: '2かい',
        option_c: '4かい',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '3がい (3階 英語の学校).'
      },
      {
        order_num: 58,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'メモを読んで、空欄に最もよく当てはまる言葉を選んでください。\n\n明日やまに行くので、ながそでとながズボンで８時半までにがっこうに<u>　（　）　</u>ください。ぼうしもかぶって来てください。おべんとうとのみものをもってきてください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '来て',
        option_b: '来',
        option_c: '来ないで',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '来て (来てください - Please come / එන්න).'
      },
      {
        order_num: 59,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'メモの指示に合う服装のイラストを選んでください。\n\n【メモ】\n明日やまに行くので、ながそでとながズボンで８時半までにがっこうに来てください。ぼうしもかぶって来てください。\n\n質問：明日やまに行くときはどれがいいですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft03_q59.jpg',
        audio_url: null,
        option_a: 'A (半袖・半ズボン・帽子)',
        option_b: 'B (長袖・半ズボン・帽子)',
        option_c: 'C (長袖・長ズボン・帽子)',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'C (長袖・長ズボン・帽子 - Long sleeves, Long trousers, and Hat).'
      },
      {
        order_num: 60,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、正しい答えを選んでください。\n\n私は今日友達と買い物に行きました。３か月前に見たえいがの DVD は、ほしかったからです。買った DVD は、友達や妹といっしょに見ます。\n\n質問：今日かれは何をしましたか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '友達とDVDを買いにいきました',
        option_b: '妹とえいがを見に行きました',
        option_c: '友達とえいがを見にいきました',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '友達とDVDを買いにいきました (Went shopping with friend to buy DVD).'
      }
    ];

    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, section_name, question_text, question_type,
          image_url, audio_url,
          option_a, option_b, option_c, option_d,
          correct_option, marks, explanation, order_num
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId,
        q.section_name,
        q.question_text,
        q.question_type,
        q.image_url,
        q.audio_url,
        q.option_a,
        q.option_b,
        q.option_c,
        q.option_d || '',
        q.correct_option,
        q.marks,
        q.explanation || '',
        q.order_num
      ]);
    }
    console.log('✅ Auto-seeded JFT Model Paper 03 with all 60 questions successfully!');
  } catch (err) {
    console.error('seedJftModelPaper03 error:', err);
  }
}

module.exports = { seedJftModelPaper03 };
