const { query } = require('../config/database');

async function seedJftModelPaper04() {
  try {
    const title = 'JFT-Basic Official Model Paper 04 (60 Minutes)';
    const existingExam = await query.get("SELECT id FROM exams WHERE title = ?", [title]);
    let examId;

    if (existingExam) {
      examId = existingExam.id;
      console.log(`Seeding JFT Model Paper 04 (Exam ID: ${examId})...`);
      await query.run(`
        UPDATE exams 
        SET description = 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper 04 (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [examId]);
      await query.run("DELETE FROM questions WHERE exam_id = ?", [examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (1, ?, 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper 04 (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.', 60, 200, 1)
      `, [title]);
      examId = res.id;
      console.log(`Created JFT Model Paper 04 (Exam ID: ${examId})`);
    }

    const questions = [
      // ==========================================
      // SECTION 1: Script & Vocabulary (文字・語彙 - Q01 to Q15)
      // ==========================================
      {
        order_num: 1,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q01.jpg',
        audio_url: null,
        option_a: 'おじいさん',
        option_b: 'おばあさん',
        option_c: 'いもうと',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'おばあさん (Grandmother / ආච්චි).'
      },
      {
        order_num: 2,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q02.jpg',
        audio_url: null,
        option_a: 'かいしゃいん',
        option_b: 'いしゃ',
        option_c: 'まんがか',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'いしゃ (Doctor / වෛද්‍යවරයා).'
      },
      {
        order_num: 3,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q03.jpg',
        audio_url: null,
        option_a: 'かきます',
        option_b: 'よびます',
        option_c: 'おどります',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'かきます (Write / ලියනවා).'
      },
      {
        order_num: 4,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q04.jpg',
        audio_url: null,
        option_a: 'ドイツ',
        option_b: 'ちゅうごく',
        option_c: 'イギリス',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'イギリス (United Kingdom / බ්‍රිතාන්‍යය).'
      },
      {
        order_num: 5,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q05.jpg',
        audio_url: null,
        option_a: 'えび',
        option_b: 'かに',
        option_c: 'にく',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'えび (Shrimp/Prawn / ඉස්සා).'
      },
      {
        order_num: 6,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q06.jpg',
        audio_url: null,
        option_a: 'ホテル',
        option_b: 'きっさてん',
        option_c: 'こうえん',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'きっさてん (Coffee Shop / Cafe / තේපැන්හල/කෝපි හල).'
      },
      {
        order_num: 7,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q07.jpg',
        audio_url: null,
        option_a: 'しつもんをします',
        option_b: 'うたをうたいます',
        option_c: 'おけしょうをします',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'おけしょうをします (Put on makeup / වේශ නිරූපණය/මේකප් කරනවා).'
      },
      {
        order_num: 8,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q08.jpg',
        audio_url: null,
        option_a: 'でんわをします',
        option_b: 'てがみをかきます',
        option_c: 'えをかきます',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'でんわをします (Make a phone call / දුරකථන ඇමතුමක් ගන්නවා).'
      },
      {
        order_num: 9,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '毎朝<u>こうえん</u>をさんぽします。\n\nHow do you write the underlined hiragana word in kanji? Choose the correct one.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '公園',
        option_b: '公演',
        option_c: '講園',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'こうえん -> 公園 (Park / උද්‍යානය).'
      },
      {
        order_num: 10,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'あのひとは私の<u>ともだち</u>です。\n\nHow do you write the underlined hiragana word in kanji? Choose the correct one.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '友人',
        option_b: '友好',
        option_c: '友達',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ともだち -> 友達 (Friend / මිතුරා).'
      },
      {
        order_num: 11,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'おとうとは<u>ことし</u>なんさいですか。\n\nHow do you write the underlined hiragana word in kanji? Choose the correct one.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '来年',
        option_b: '今年',
        option_c: '去年',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ことし -> 今年 (This year / මේ වසර).'
      },
      {
        order_num: 12,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '<u>しゅうまつ</u>は休みですか。\n\nHow do you write the underlined hiragana word in kanji? Choose the correct one.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '周末',
        option_b: '週末',
        option_c: '週間',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'しゅうまつ -> 週末 (Weekend / සති අන්තය).'
      },
      {
        order_num: 13,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'いつか<u>ちゅうごく</u>へ行きたいです。\n\nHow do you write the underlined hiragana word in kanji? Choose the correct one.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '中国',
        option_b: '日本',
        option_c: '韓国',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ちゅうごく -> 中国 (China / චීනය).'
      },
      {
        order_num: 14,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '<u>りょうしん</u>とかいがいりょこうをしたいです。\n\nHow do you write the underlined hiragana word in kanji? Choose the correct one.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '両側',
        option_b: '両父',
        option_c: '両親',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'りょうしん -> 両親 (Parents / දෙමාපියන්).'
      },
      {
        order_num: 15,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '東京はおおきな<u>まち</u>です。\n\nHow do you write the underlined hiragana word in kanji? Choose the correct one.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '町',
        option_b: '田舎',
        option_c: '店',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'まち -> 町 (Town/City / නගරය).'
      },

      // ==========================================
      // SECTION 2: Conversation & Expression (会話・表現 - Q16 to Q30)
      // ==========================================
      {
        order_num: 16,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'Read the sentence and choose the word that fits in the blank the most.\n\n時間がある______そうじをしてしまいましょう。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q16.jpg',
        audio_url: null,
        option_a: 'まで',
        option_b: 'とき',
        option_c: 'と',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '時間がある「とき」そうじをしてしまいましょう。(When there is time, let\'s clean up / වේලාව ඇති විට අස්පස් කරමු).'
      },
      {
        order_num: 17,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '明日しけんがあることはまだだれも______ようです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'しらない',
        option_b: 'わかりません',
        option_c: 'しります',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'だれも「知らない」ようです (It seems nobody knows yet / කවුරුත් දන්නේ නැති බවක් පෙනේ).'
      },
      {
        order_num: 18,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'あの店は朝8時半______開いています。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q18.jpg',
        audio_url: null,
        option_a: 'で',
        option_b: 'を',
        option_c: 'から',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '朝8時半「から」開いています (Open from 8:30 AM / උදේ 8:30 සිට විවෘතයි).'
      },
      {
        order_num: 19,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、(19)に入る最もよいものを選んでください。\n\nリサ：あの人は(19)______ですか。\nリン：あの人はシンさんです。\nリサ：シンさんもちゅうごく人ですか。\nリン：いいえ、ちゅうごく人ではありません。かんこく人です。シンさんはがっこうのじむの人です。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q19.jpg',
        audio_url: null,
        option_a: 'だれ',
        option_b: 'どれ',
        option_c: 'どんな',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'あの人は「だれ」ですか (Who is that person? / ඒ පුද්ගලයා කවුද?).'
      },
      {
        order_num: 20,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に入る最もよいものを選んでください。\n\nA：あたらしい かばん ですね。たかかったでしょう。\nB：いいえ、______よ。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q20.jpg',
        audio_url: null,
        option_a: 'とてもたかかったです',
        option_b: 'たいへんたかいです',
        option_c: 'あまり たかくありませんでした',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'いいえ、「あまり たかくありませんでした」よ (No, it wasn\'t very expensive / නැහැ, එච්චර ගණන් වුණේ නැහැ).'
      },
      {
        order_num: 21,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、(21)に入る最もよいものを選んでください。\n\nA：きむらさんのじどうしゃは(21)______ですか。\nB：あそこです。\nA：とてもふるいじどうしゃですね。\nB：いいえ、あれではありません。あのしろいのです。\nA：えっ、しろいの・・・ああ、(22)じどうしゃですね。\nB：あたらしいじどうしゃです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'どこ',
        option_b: 'どの',
        option_c: 'どんな',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'きむらさんの自動車は「どこ」ですか (Where is Kimura\'s car? / කිමුරාගේ වාහනය කොහේද? -> あそこです).'
      },
      {
        order_num: 22,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、(22)に入る最もよいものを選んでください。\n\nA：きむらさんのじどうしゃは(21)どこですか。\nB：あそこです。\nA：とてもふるいじどうしゃですね。\nB：いいえ、あれではありません。あのしろいのです。\nA：えっ、しろいの・・・ああ、(22)______じどうしゃですね。\nB：あたらしいじどうしゃです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'わるい',
        option_b: 'ふるい',
        option_c: 'いい',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '「いい」自動車ですね (Nice car, isn\'t it? / හොඳ වාහනයක් නේද?).'
      },
      {
        order_num: 23,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'レストランでの会話です。空欄に入る最もよい言葉を選んでください。\n\n店の人：______。お2人さまですか。\n客1：いいえ、3人ですが、\n店の人：では、あちらへどうぞ。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q23.jpg',
        audio_url: null,
        option_a: 'どうぞよろしく',
        option_b: 'いらっしゃいませ',
        option_c: 'しつれいします',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '店の人:「いらっしゃいませ」(Welcome to the restaurant / සාදරයෙන් පිළිගනිමු).'
      },
      {
        order_num: 24,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、(24)に入る最もよいものを選んでください。\n\nたなか：きむらさん、きょうは妹のたんじょうびですね。\nきむら：ええ。\nたなか：これ、たんじょうびの(24)______です。\nきむら：ああ、(25)。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q24_25.jpg',
        audio_url: null,
        option_a: 'パーティー',
        option_b: 'はこ',
        option_c: 'プレゼント',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'たんじょうびの「プレゼント」です (Birthday present / උපන්දින තෑග්ග).'
      },
      {
        order_num: 25,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、(25)に入る最もよいものを選んでください。\n\nたなか：きむらさん、きょうは妹のたんじょうびですね。\nきむら：ええ。\nたなか：これ、たんじょうびの(24)プレゼントです。\nきむら：ああ、(25)______。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q24_25.jpg',
        audio_url: null,
        option_a: 'しつれいします',
        option_b: 'どうもありがとうございます。',
        option_c: 'ごちそうさまでした',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'プレゼントをもらったとき:「どうもありがとうございます」(Thank you very much / බොහොම ස්තූතියි).'
      },
      {
        order_num: 26,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に入る最もよいものを選んでください。\n\nブラウン：ここはにぎやかですね。\nシン：ええ、いつもわかい人がおおぜいいます。\nブラウン：きれいなみせもありますね。\nシン：あれは______ビルです。\nブラウン：たかいビルですね。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q26.jpg',
        audio_url: null,
        option_a: 'ゆうめい',
        option_b: 'ゆうめいに',
        option_c: 'ゆうめいな',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '「有名（ゆうめい）な」ビル (Famous building / ප්‍රසිද්ධ ගොඩනැගිල්ලක්).'
      },
      {
        order_num: 27,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に入る最もよいものを選んでください。\n\nA：すみません、この手紙はたっきゅうびんで______ですか。\nB：えーと、180円です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'いつ',
        option_b: 'いくら',
        option_c: 'いくつ',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '値段を聞くとき:「いくら」ですか (How much is it? / මිල කීයද? -> 180円です).'
      },
      {
        order_num: 28,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に入る最もよいものを選んでください。\n\nA：このバナナはちょっと古くて、よくないですよ。\nB：では、あのりんごは______。\nA：ああ、あれはいいですね。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q28.jpg',
        audio_url: null,
        option_a: 'どうですか',
        option_b: 'わるいですか',
        option_c: 'いくらですか',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '提案や意見を聞くとき: あのりんごは「どうですか」(How about that apple? / ඒ ඇපල් ගෙඩිය කොහොමද?).'
      },
      {
        order_num: 29,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '電話での会話です。空欄に入る最もよいものを選んでください。\n\nA：もしもし、お姉さん、そちらにおじいさんは______。\nB：おじいさんはいませんが、おばあさんはいますよ。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ありますか',
        option_b: 'おきますか',
        option_c: 'いますか',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '人・生き物の存在: おじいさんは「いますか」(Is grandfather there? / සීයා ඉන්නවද?).'
      },
      {
        order_num: 30,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、空欄に入る最もよいものを選んでください。\n\nカスん：あなたの教室に______。\nサチに：つくえやいすなどがあります。こくばんもあります。先生のつくえのよこに本だなもあります。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q30.jpg',
        audio_url: null,
        option_a: '何がありますか',
        option_b: '何かありますか',
        option_c: 'どこにありますか',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '教室に「何がありますか」(What is in your classroom? / පන්ති කාමරයේ මොනවාද තියෙන්නේ?).'
      },

      // ==========================================
      // SECTION 3: Listening Comprehension (聴解 - Choukai - Q31 to Q45)
      // ==========================================
      {
        order_num: 31,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA teacher is talking to the students. What will students do first?\n(先生が学生に話しています。学生はまず何をしますか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft04_q31.mp3',
        option_a: 'ばんごうをかく',
        option_b: 'かみをとる',
        option_c: 'すわってまつ',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '先生が「まず、つくえの上の紙をとってください」と言いました。正解は「かみをとる」です。(First take the paper / මුලින්ම කොළය ලබා ගැනීම).'
      },
      {
        order_num: 32,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、イラストから正しいものを選んでください。\n\nA girl and a boy are talking in the class. What will the girl buy?\n(女の子と男の子が話しています。女の子は何を買いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q32.jpg',
        audio_url: '/uploads/audio/jft04_q32.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '4',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '女の子は「私はコーヒーとお弁当にしよう」と言いました。コーヒー1つとお弁当1つのイラストは「4」です。(Girl buys coffee and bento / කෝපි සහ බෙන්තෝ).'
      },
      {
        order_num: 33,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、イラストから正しい位置を選んでください。\n\nA woman and a man are talking in a house. Where does the man put the vase?\n(女の人と男の人が話しています。男の人は花瓶をどこに置きますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q33.jpg',
        audio_url: '/uploads/audio/jft04_q33.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '女の人が「テレビの前のテーブルの上に置いて」と頼みました。正解は「3」(テーブルの上)です。(On the table in front of TV / ටීවී එක ඉදිරිපිට මේසය උඩ).'
      },
      {
        order_num: 34,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、女の人のコートを選んでください。\n\nA man and a woman are talking. Which one is the woman\'s coat?\n(男の人と女の人が話しています。女の人のコートはどれですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q34.jpg',
        audio_url: '/uploads/audio/jft04_q34.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '女の人は「黒くて、ボタンがたくさん（6つ）ついているやつ」と言いました。黒でボタン6個のコートは「1」です。(Black coat with 6 buttons / බොත්තම් 6ක් සහිත කළු කබාය).'
      },
      {
        order_num: 35,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA teacher and a student are talking in the school. What will the student do today?\n(先生と学生が話しています。学生は今日何をしますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q35.jpg',
        audio_url: '/uploads/audio/jft04_q35.mp3',
        option_a: 'アとイ',
        option_b: 'アとイとウ',
        option_c: 'ウとエ',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '学生は今日「ご飯を食べて（ア）、カラオケに行きます（イ）」と言いました。正解は「アとイ」です。(Eating and Karaoke / කෑම කෑම සහ කැරෝකී).'
      },
      {
        order_num: 36,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、イラストから正しい人を選んでください。\n\nA man and a woman are talking. To whom does the man want to speak?\n(男の人と女の人が話しています。男の人は誰と話したいですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q36.jpg',
        audio_url: '/uploads/audio/jft04_q36.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '4',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '男の人は「眼鏡をかけて背が高い男の子」と話したいと言いました。眼鏡をかけた長身の男の子は「1」です。(Tall boy with glasses / කණ්ණාඩි දැමූ උස පිරිමි ළමයා).'
      },
      {
        order_num: 37,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA man and a woman are talking. How much does a taxi cost to the station?\n(男の人と女の人が話しています。駅までタクシーでいくらですか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft04_q37.mp3',
        option_a: '210',
        option_b: '250',
        option_c: '630',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'バスは210円、タクシーはその3倍で「630円」と言いました。(Taxi costs 630 yen / ටැක්සි ගාස්තුව යෙන් 630).'
      },
      {
        order_num: 38,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA man and a woman are talking. Where are they going after this?\n(男の人と女の人が話しています。この後、二人はどこへ行きますか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft04_q38.mp3',
        option_a: 'えいがかん',
        option_b: 'ぎんこう',
        option_c: 'レストラン',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '映画を見た後、お腹が空いたので「レストランでお昼ご飯を食べよう」と決めました。(Going to a restaurant / අවන්හල වෙත යාම).'
      },
      {
        order_num: 39,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA teacher is talking to a student. How do they go to the sea?\n(先生と学生が話しています。海へ何で行きますか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft04_q39.mp3',
        option_a: 'でんしゃ',
        option_b: 'じてんしゃ',
        option_c: 'バス',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '先生は「みんなでバスに乗って行きます」と答えました。(Go by bus / බස් රථයෙන් යාම).'
      },
      {
        order_num: 40,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA girl and a boy are talking. When is his day off?\n(女の子と男の子が話しています。男の子の休みはいつですか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft04_q40.mp3',
        option_a: 'げつようび',
        option_b: 'もくようび',
        option_c: 'げつようびともくようび',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '男の子は「月曜日と木曜日だよ」と答えました。(Monday and Thursday / සඳුදා සහ බ්‍රහස්පතින්දා).'
      },
      {
        order_num: 41,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA man and a woman are talking. What did the woman ask for?\n(男の人と女の人が話しています。女の人は何を頼みましたか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft04_q41.mp3',
        option_a: 'つめたいコーヒー',
        option_b: 'あたたかいこうちゃ',
        option_c: 'つめたいこうちゃ',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '女の人は「あたたかい紅茶をお願い」と頼みました。(Hot tea / උණුසුම් තේ).'
      },
      {
        order_num: 42,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、質問に答えてください。\n\nA man and a woman are talking. What is the man doing on the train?\n(男の人と女の人が話しています。男の人は電車の中で何をしていますか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft04_q42.mp3',
        option_a: 'ねている',
        option_b: '本をよんでいる',
        option_c: 'おんがくをきいている',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '男の人は電車の中で「本を読んでいるよ」と答えました。(Reading a book / පොතක් කියවීම).'
      },
      {
        order_num: 43,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しい答えを選んでください。\n\nListen to the track and choose the correct answer.',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q43.jpg',
        audio_url: '/uploads/audio/jft04_q43.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '音声:「ペンを持っています」。正しい答えは「1」です。(Holding a pen / පෑනක් අතැතිව සිටීම).'
      },
      {
        order_num: 44,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しい答えを選んでください。\n\nListen to the track and choose the correct answer.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft04_q44.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '音声内容に基づく正しい選択肢は「2」です。(Correct choice: 2).'
      },
      {
        order_num: 45,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しい答えを選んでください。\n\nListen to the track and choose the correct answer.',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft04_q45.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '音声内容に基づく正しい選択肢は「3」です。(Correct choice: 3).'
      },

      // ==========================================
      // SECTION 4: Reading Comprehension (読解 - Dokkai - Q46 to Q60)
      // ==========================================
      {
        order_num: 46,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '表を読んで質問に答えてください。\n\n山田さんはいちばん何がよみますか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q46.jpg',
        audio_url: null,
        option_a: 'えいご',
        option_b: 'ちゅうごくご',
        option_c: 'にほんご',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '表より：かんじ(1時間)、にほんご(1時間半)、えいご(1時間15分)、ちゅうごくご(1時間)。いちばん長いのは「にほんご」です。(Japanese is read longest / ජපන් භාෂාව වැඩිම වේලාවක් කියවයි).'
      },
      {
        order_num: 47,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで質問に答えてください。\n\n田中さんは何時間がっこうで勉強しますか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q47_48.jpg',
        audio_url: null,
        option_a: '6時間',
        option_b: '5時間',
        option_c: '7時間',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '本文に「がっこうで5時間勉強します」と書かれています。(Studies 5 hours at school / පාසලේ පැය 5ක් ඉගෙන ගනී).'
      },
      {
        order_num: 48,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで、ここにあっているものはどれですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q47_48.jpg',
        audio_url: null,
        option_a: '田中さんは毎日3時間ぐらいテレビをみます',
        option_b: '田中さんはごご6時半に晩ご飯を食べます',
        option_c: '田中さんは毎日うちで1時間ぐらいしゅくだいをします',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '本文に「うちで1時間ぐらいしゅくだいをします」と合致しています。(Does homework at home for about 1 hour / නිවසේදී පැයක් ගෙදර වැඩ කරයි).'
      },
      {
        order_num: 49,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで、ここにあっている職業（仕事）はどれですか。\n\n「私はりょうりやおかしをつくります。ときどき家族や友達のためにおいしいりょうりをつくります。しょうらい、自分のレストランで毎日りょうりをつくりたいです。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q49.jpg',
        audio_url: null,
        option_a: 'かんごし',
        option_b: 'しゅふ',
        option_c: 'シェフ',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'レストランで料理を作る仕事は「シェフ」(Chef / ප්‍රධාන අරක්කැමියා)です。'
      },
      {
        order_num: 50,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで、ここにあっている職業（仕事）はどれですか。\n\n「私はコンピューターが大好きです。毎日ゲームをします。いろいろなホームページを見ます。しょうらいもっと便利なプログラムをつくりたいです。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q50.jpg',
        audio_url: null,
        option_a: 'プログラム',
        option_b: 'プログラマ',
        option_c: 'プログラマー',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '便利なプログラムを作る仕事は「プログラマー」(Programmer / පරිගණක ක්‍රමලේඛකයා)です。'
      },
      {
        order_num: 51,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで、ここにあっている職業（仕事）はどれですか。\n\n「私はしょうらい、いしゃのしごとをてつだいたいです。病気の人のせわをしたいです。夜、しごとがあります。たいへんですが、がんばります。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q51.jpg',
        audio_url: null,
        option_a: 'いしゃ',
        option_b: 'かんごし',
        option_c: 'じゅうい',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '医師を手伝い病気の人の世話をする仕事は「かんごし」(Nurse / හෙදිය)です。'
      },
      {
        order_num: 52,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで、ここにあっている職業（仕事）はどれですか。\n\n「私はどうぶつが好きです。いえでいぬととりをかいます。どうぶつのせわがたのしいです。しょうらいはどうぶつをなおしたいです。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q52.jpg',
        audio_url: null,
        option_a: 'いしゃ',
        option_b: 'かんごし',
        option_c: 'じゅうい',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '動物の病気を治す仕事は「じゅうい」(Veterinarian / පශු වෛද්‍යවරයා)です。'
      },
      {
        order_num: 53,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'カレンダーを見て質問に答えてください。\n\n今日は何曜日ですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q53_55.jpg',
        audio_url: null,
        option_a: '月曜日',
        option_b: '金曜日',
        option_c: '土曜日',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'カレンダーの「今日」の矢印は3月17日（Fri）を指しています。金曜日（Fri）です。(Friday / සිකුරාදා).'
      },
      {
        order_num: 54,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'カレンダーを見て質問に答えてください。\n\nおとといは何日でしたか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q53_55.jpg',
        audio_url: null,
        option_a: '15日の水曜日',
        option_b: '14日の木曜日',
        option_c: '19日の日曜日',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '今日が17日（金）なので、おととい（2日前）は「15日の水曜日」です。(15th Wednesday / 15 වන බදාදා).'
      },
      {
        order_num: 55,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '田中さんの誕生日は今日から1週間のあとです。田中さんの誕生日はいつですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q53_55.jpg',
        audio_url: null,
        option_a: '25日の土曜日',
        option_b: '10日の金曜日',
        option_c: '24日の金曜日',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '今日（17日）の1週間後は「24日の金曜日」です。(24th Friday / 24 වන සිකුරාදා).'
      },
      {
        order_num: 56,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで質問に答えてください。\n\n春きせつではよくどのところへあそびに行きますか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q56_57.jpg',
        audio_url: null,
        option_a: 'おきなわ',
        option_b: 'なら',
        option_c: 'きょうと',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '本文に「とくにおきなわへ行きます」と書かれています。(Goes to Okinawa / ඔකිනාවා වෙත යයි).'
      },
      {
        order_num: 57,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'どうして春きせつであそびに行きますか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft04_q56_57.jpg',
        audio_url: null,
        option_a: 'たのしいので',
        option_b: '休みがあるので',
        option_c: 'いちばん好きなきせつから',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '本文に「このきせつでは休みがありますからあそびに行きます」と書かれています。(Because there is a holiday / නිවාඩුවක් ඇති නිසා).'
      },
      {
        order_num: 58,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '案内を読んで質問に答えてください。\n\nカラオケコンテストはいつですか。（05月04日の読み方）',
        question_type: 'multiple_choice',
        image_url: '/images/jft04_passage_58_60.png',
        audio_url: null,
        option_a: 'よっか',
        option_b: 'よちか',
        option_c: 'よつか',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '4日の正しい読み方は「よっか」(Yokka / 4 වන දින)です。'
      },
      {
        order_num: 59,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'カラオケコンテストではうたをうたう人が何人さんかしなければなりませんか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft04_passage_58_60.png',
        audio_url: null,
        option_a: '7人',
        option_b: '5人',
        option_c: '12人',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'クラシック歌（5人）＋ジャズ歌（7人）＝合計「12人」です。(Total singers = 12 people / ගායන ශිල්පීන් 12 දෙනෙකි).'
      },
      {
        order_num: 60,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'カラオケコンテストは何時からですか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft04_passage_58_60.png',
        audio_url: null,
        option_a: '朝9時からです',
        option_b: '夜9時からです',
        option_c: '午後3時からです。',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '案内に「時間：午前9時〜午後3時」とあります。正解は「朝9時からです」(From 9 AM in the morning / උදෑසන 9:00 සිට).'
      }
    ];

    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, order_num, section_name, question_text, question_type, 
          image_url, audio_url, option_a, option_b, option_c, option_d, 
          correct_option, marks, explanation
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId, q.order_num, q.section_name, q.question_text, q.question_type,
        q.image_url, q.audio_url, q.option_a, q.option_b, q.option_c, q.option_d,
        q.correct_option, q.marks, q.explanation
      ]);
    }

    console.log(`Successfully inserted all 60 questions for JFT Model Paper 04 (Exam ID: ${examId})`);
  } catch (err) {
    console.error('seedJftModelPaper04 error:', err);
  }
}

module.exports = { seedJftModelPaper04 };
