const { query } = require('../config/database');

async function seedJftModelPaper10() {
  try {
    const title = 'JFT-Basic Official Model Paper 10 (60 Minutes)';
    const existingExam = await query.get("SELECT id FROM exams WHERE title = ?", [title]);
    let examId;

    if (existingExam) {
      examId = existingExam.id;
      const countRes = await query.get("SELECT COUNT(*) as count FROM questions WHERE exam_id = ?", [examId]);
      if (countRes && countRes.count >= 60) {
        return;
      }
      console.log(`Seeding JFT Model Paper 10 (Exam ID: ${examId})...`);
      await query.run(`
        UPDATE exams 
        SET description = 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper 10 (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [examId]);
      await query.run("DELETE FROM questions WHERE exam_id = ?", [examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (1, ?, 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper 10 (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.', 60, 200, 1)
      `, [title]);
      examId = res.id;
      console.log(`Created JFT Model Paper 10 (Exam ID: ${examId})`);
    }

    const questions = [
      // ==========================================
      // SECTION 1: Script & Vocabulary (文字・語彙 - Q01 to Q15)
      // ==========================================
      {
        order_num: 1,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q01.jpg',
        audio_url: null,
        option_a: 'さる',
        option_b: 'パンダ',
        option_c: 'うさぎ',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'さる (Monkey / වඳුරා).'
      },
      {
        order_num: 2,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q02.jpg',
        audio_url: null,
        option_a: 'オーストラリア',
        option_b: 'ドイツ',
        option_c: 'ニュージーランド',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'オーストラリア (Australia / ඕස්ට්‍රේලියාව).'
      },
      {
        order_num: 3,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q03.jpg',
        audio_url: null,
        option_a: 'すうもう',
        option_b: 'すもう',
        option_c: 'すうも',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'すもう (Sumo wrestling / සුමෝ ක්‍රීඩාව).'
      },
      {
        order_num: 4,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q04.jpg',
        audio_url: null,
        option_a: 'ピアノをひきます',
        option_b: 'ピアノをたちます',
        option_c: 'ピアノをあげます',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ピアノをひきます (Play piano / පියානෝ වාදනය කරනවා).'
      },
      {
        order_num: 5,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q05.jpg',
        audio_url: null,
        option_a: 'なきます',
        option_b: 'なります',
        option_c: 'なおします',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'なきます (Cry / අඬනවා).'
      },
      {
        order_num: 6,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q06.jpg',
        audio_url: null,
        option_a: 'けんかをします',
        option_b: 'けっこんします',
        option_c: 'けがをします',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'けがをします (Get injured / තුවාල වෙනවා).'
      },
      {
        order_num: 7,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'おこります',
        option_b: 'すわります',
        option_c: 'たちます',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'すわります (Sit down / වාඩි වෙනවා).'
      },
      {
        order_num: 8,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'バナナ',
        option_b: 'きゅうり',
        option_c: 'キャベツ',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'キャベツ (Cabbage / ගෝවා).'
      },
      {
        order_num: 9,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ぶどう',
        option_b: 'すいか',
        option_c: 'バナナ',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'すいか (Watermelon / පැණි කොමඩු).'
      },
      {
        order_num: 10,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q10.jpg',
        audio_url: null,
        option_a: '服をきります',
        option_b: '服をぬぎます',
        option_c: '服をかぶります',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '服をぬぎます (Take off clothes / ඇඳුම් ගලවනවා).'
      },
      {
        order_num: 11,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線の言葉は漢字でどう書きますか。一番いいものを一つ選んでください。\n\n(11)【せんしゅう】の(12)もくようび家族と旅行へ行きました。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q11_12.jpg',
        audio_url: null,
        option_a: '来週',
        option_b: '今週',
        option_c: '先週',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '先週 (せんしゅう - Last week / පසුගිය සතිය).'
      },
      {
        order_num: 12,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線の言葉は漢字でどう書きますか。一番いいものを一つ選んでください。\n\n(11)せんしゅうの(12)【もくようび】家族と旅行へ行きました。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q11_12.jpg',
        audio_url: null,
        option_a: '木曜日',
        option_b: '火曜日',
        option_c: '水曜日',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '木曜日 (もくようび - Thursday / බ්‍රහස්පතින්දා).'
      },
      {
        order_num: 13,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線の言葉は漢字でどう書きますか。一番いいものを一つ選んでください。\n\nふじさんは【かざん】ですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q13.jpg',
        audio_url: null,
        option_a: '花山',
        option_b: '火山',
        option_c: '火三',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '火山 (かざん - Volcano / ගිනි කන්ද).'
      },
      {
        order_num: 14,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線の言葉は漢字でどう書きますか。一番いいものを一つ選んでください。\n\nいけに【きんぎょ】がたくさんいます。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q14.jpg',
        audio_url: null,
        option_a: '金魚',
        option_b: '金肉',
        option_c: '近魚',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '金魚 (きんぎょ - Goldfish / රන් මත්ස්‍යයා).'
      },
      {
        order_num: 15,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線の言葉は漢字でどう書きますか。一番いいものを一つ選んでください。\n\n父は毎朝【しんぶん】を読みます。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q15.jpg',
        audio_url: null,
        option_a: '雑誌',
        option_b: '新聞',
        option_c: '新誌',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '新聞 (しんぶん - Newspaper / පුවත්පත).'
      },

      // ==========================================
      // SECTION 2: Conversation & Expression (会話・表現 - Q16 to Q30)
      // ==========================================
      {
        order_num: 16,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。\n\nA:「まゆみさん【＿＿】弟さん【＿＿】いますか。」\nB:「ええ、ふたりいます。でも、妹【＿＿】一人もいません。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q16.jpg',
        audio_url: null,
        option_a: 'は・が・は',
        option_b: 'は・の・は',
        option_c: 'の・は・が',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'は・が・は (まゆみさんは弟さんがいますか・妹はいません).'
      },
      {
        order_num: 17,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。\n\nおいしいものを【＿＿＿＿】にレストランへ行きましょう。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '食べ',
        option_b: '食べます',
        option_c: '食べる',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '食べに行きましょう (Let\'s go to eat / කෑමට යමු).'
      },
      {
        order_num: 18,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。\n\n昨日のえいがは【＿＿＿＿】えいがでした。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'おもしろかった',
        option_b: 'おもしろ',
        option_c: 'おもしろい',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'おもしろいえいがでした (It was an interesting movie / රසවත් චිත්‍රපටයක් විය).'
      },
      {
        order_num: 19,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。\n\nA:「午後はぶんぽうのテストですね。【＿＿＿＿】しますか。」\nB:「1010 号室でします。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q19.jpg',
        audio_url: null,
        option_a: 'どこで',
        option_b: 'いつで',
        option_c: 'いくつで',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'どこでしますか (Where will it be held? / කොහේද පවත්වන්නේ?).'
      },
      {
        order_num: 20,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。\n\nA:「【＿＿＿＿】、田中さんの部屋はここですか。」\nB:「はい、そうです。」\nA:「こんにちは、まりこです。」\nB:「ああ、まりこさん、はじめまして。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q20.jpg',
        audio_url: null,
        option_a: 'すみません',
        option_b: 'ありがとう',
        option_c: 'どうぞ',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'すみません (Excuse me / සමාවෙන්න).'
      },
      {
        order_num: 21,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。\n\nA:「どれ【＿＿】ホテルですか。」\nB:「あそこに高いたてもの【＿＿】ありますね。あのたてもの【＿＿】うしろにあります。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q21.jpg',
        audio_url: null,
        option_a: 'が・が・の',
        option_b: 'は・は・の',
        option_c: 'が・の・の',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'どれがホテルですか・たてものがありますね・たてもののうしろにあります。'
      },
      {
        order_num: 22,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '店員とまり、キムの会話の【22】に入る最も適切な表現を選んでください。\n\nまり:「ハンバーガーをください。あなたは【22】食べますか。」\nキム:「ぼくは二つでいいです。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q22_24.jpg',
        audio_url: null,
        option_a: 'いくら',
        option_b: '何',
        option_c: 'いくつ',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'いくつ (How many / කීයක්ද?).'
      },
      {
        order_num: 23,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '店員とまり、キムの会話の【23】に入る最も適切な表現を選んでください。\n\nまり:「私は一つを食べます。じゃ、【23】。」\n店員:「はい、三つで900円になります。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q22_24.jpg',
        audio_url: null,
        option_a: 'ハンバーガーを一ください',
        option_b: 'ハンバーガーを二つください',
        option_c: 'ハンバーガーを三つください',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ハンバーガーを三つください (Please give 3 hamburgers / බර්ගර් 3ක් දෙන්න).'
      },
      {
        order_num: 24,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '店員とまり、キムの会話の【24】に入る最も適切な表現を選んでください。\n\nまり:「あ、それから飲み物等はどうですか。」\nキム:「ぼくはみずでいいです。」\nまり:「私はコーラを飲みたいです。じゃ、【24】。」\n店員:「ぜんぶで1100円です。かしこまりました。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q22_24.jpg',
        audio_url: null,
        option_a: '一つをください',
        option_b: '一つでもいいですか',
        option_c: '一つしかありません',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '一つをください (Please give me one / එකක් දෙන්න).'
      },
      {
        order_num: 25,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '電話での会話の【25】に入る表現を選んでください。\n\nミラー:「もしもし、ミラーです。」\nきむら:「ああ、ミラーさん、こんにちは。【25】。」\nミラー:「ええ、元気です。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q25_28.jpg',
        audio_url: null,
        option_a: '天気はいいですね',
        option_b: 'きむらです',
        option_c: 'お元気ですか',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'お元気ですか (How are you? / සුවෙන් ඉන්නවාද?).'
      },
      {
        order_num: 26,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '電話での会話の【26】に入る表現を選んでください。\n\nミラー:「あのう、きむらさん、大学のコンサート、いっしょにいかがですか。」\nきむら:「いいですね。【26】。」\nミラー:「来週の金曜日のばんです。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q25_28.jpg',
        audio_url: null,
        option_a: 'いかがですか',
        option_b: 'いつですか',
        option_c: 'いくらですか',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'いつですか (When is it? / කවදාද?).'
      },
      {
        order_num: 27,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '電話での会話の【27】に入る表現を選んでください。\n\nきむら:「金曜日ですか。【27】。」\nミラー:「だめですか。」\nきむら:「ええ、友達とやくそくがありますから。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q25_28.jpg',
        audio_url: null,
        option_a: '金曜日はいいです',
        option_b: '金曜日はだめです',
        option_c: '金曜日はちょっと',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '金曜日はちょっと (Friday is a bit difficult / සිකුරාදා නම් ටිකක් අපහසුයි).'
      },
      {
        order_num: 28,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '電話での会話の【28】に入る表現を選んでください。\n\nミラー:「そうですか。【28】。」\nきむら:「ええ、またこんどお願いします。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q25_28.jpg',
        audio_url: null,
        option_a: 'しかたがありませんね',
        option_b: 'しつれいしますね',
        option_c: 'またこんど',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'またこんど (Next time / ඊළඟ වතාවක).'
      },
      {
        order_num: 29,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。\n\nA:「今日はずいぶん歩きましたね。」\nB:「ええ。つかれましたね。おふろに入りましょうか、それともさきに食事をしましょうか。」\nA:「まず、おふろに入って、【＿＿＿＿】食事をしませんか。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q29.jpg',
        audio_url: null,
        option_a: 'それから',
        option_b: 'そのうえ',
        option_c: 'それでは',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'それから (After that / ඉන්පසු).'
      },
      {
        order_num: 30,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。\n\n田中:「先生、あの薬を飲んだら、きぶんがよくなっ【＿＿＿＿】。」\n医者:「そうですか、それはよかったですね。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'いきました',
        option_b: 'きました',
        option_c: 'しまいます',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'きぶんがよくなってきました (Started feeling better / සනීපයක් දැනීගෙන ආවා).'
      },

      // ==========================================
      // SECTION 3: LISTENING COMPREHENSION (聴解 - Choukai - Q31 to Q45)
      // ==========================================
      {
        order_num: 31,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: 'How will brother\'s look tomorrow? (明日の弟の格好はどれですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q31.jpg',
        audio_url: '/uploads/audio/jft10_q31.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'A',
        marks: 5,
        explanation: '1 (1 වන රූපය).'
      },
      {
        order_num: 32,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: 'Where is the post office? (郵便局はどこですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q32.jpg',
        audio_url: '/uploads/audio/jft10_q32.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'C',
        marks: 5,
        explanation: '3 (3 වන ස්ථානය).'
      },
      {
        order_num: 33,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: 'What kind of bread does eat in woman\'s country? (女の人の国で食べるパンはどれですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q33.jpg',
        audio_url: '/uploads/audio/jft10_q33.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'B',
        marks: 5,
        explanation: '2 (2 වන ප්‍රංශ පාන්).'
      },
      {
        order_num: 34,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: 'What does a man buy? (男の人は何を買いますか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft10_q34.mp3',
        option_a: 'ぎゅうにゅう1ぽんだけ',
        option_b: 'ぎゅうにゅう1ぽんとチーズ',
        option_c: 'ぎゅうにゅう2ほんだけ',
        option_d: 'ぎゅうにゅう2ほんとチーズ',
        correct_option: 'D',
        marks: 5,
        explanation: 'ぎゅうにゅう2ほんとチーズ (2 bottles of milk and cheese / කිරි බෝතල් 2ක් සහ චීස්).'
      },
      {
        order_num: 35,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: 'Listen to the answer while looking at the picture. What do the arrowheads say? (矢印の人は何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q35.jpg',
        audio_url: '/uploads/audio/jft10_q35.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '1 (いただきます).'
      },
      {
        order_num: 36,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: 'Listen to the answer while looking at the picture. What do the arrowheads say? (矢印の人は何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q36.jpg',
        audio_url: '/uploads/audio/jft10_q36.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '2 (ආචාර කිරීම).'
      },
      {
        order_num: 37,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: 'Listen to the answer while looking at the picture. What do the arrowheads say? (矢印の人は何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q37.jpg',
        audio_url: '/uploads/audio/jft10_q37.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '1 (失礼します).'
      },
      {
        order_num: 38,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: 'Listen to the answer while looking at the picture. What do the arrowheads say? (矢印の人は何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q38.jpg',
        audio_url: '/uploads/audio/jft10_q38.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '3 (どうぞ).'
      },
      {
        order_num: 39,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: 'Listen to the answer while looking at the picture. What do the arrowheads say? (矢印の人は何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q39.jpg',
        audio_url: '/uploads/audio/jft10_q39.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '2 (お待たせいたしました).'
      },
      {
        order_num: 40,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: 'Listen to the answer while looking at the picture. What do the arrowheads say? (矢印の人は何と言いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q40.jpg',
        audio_url: '/uploads/audio/jft10_q40.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '1 (すみません).'
      },
      {
        order_num: 41,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: 'A woman is asking a man where the bus stop is. Where is the bus stop? (バス停はどこですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q41.jpg',
        audio_url: '/uploads/audio/jft10_q41.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'C',
        marks: 5,
        explanation: '3 (3 වන බස් නැවතුම).'
      },
      {
        order_num: 42,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: 'A woman is talking with her boss. What will they drink in the meeting? (二人は会議で何を飲みますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q42.jpg',
        audio_url: '/uploads/audio/jft10_q42.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'A',
        marks: 5,
        explanation: '1 (වතුර බෝතලයක් සහ කෝපි එකක්).'
      },
      {
        order_num: 43,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: 'A woman is talking to a shop staff. Which computer is she going to buy? (女の人はどのパソコンを買いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q43.jpg',
        audio_url: '/uploads/audio/jft10_q43.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'B',
        marks: 5,
        explanation: '2 (2 වන පරිගණකය).'
      },
      {
        order_num: 44,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: 'A man is talking with a woman about his trip schedule. When is he coming back home? (男の人はいつ家に帰ってきますか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft10_q44.mp3',
        option_a: '火曜日',
        option_b: '木曜日',
        option_c: '金曜日',
        option_d: '土曜日',
        correct_option: 'C',
        marks: 5,
        explanation: '金曜日 (Friday / සිකුරාදා).'
      },
      {
        order_num: 45,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: 'A man is ordering a pizza by phone. What is he going to order? (男の人は何を注文しますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_q45.jpg',
        audio_url: '/uploads/audio/jft10_q45.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'D',
        marks: 5,
        explanation: '4 (4 වන ඇණවුම).'
      },

      // ==========================================
      // SECTION 4: READING COMPREHENSION (読解 - Dokkai - Q46 to Q60)
      // ==========================================
      {
        order_num: 46,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【46/47/48/49 共通問題】文章を読んで、質問に答えてください。\n\nタローのことを正しい説明しているのはどれか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_passage_46_49.jpg',
        audio_url: null,
        option_a: '友達がタローをくれました',
        option_b: '友達にタローあげました',
        option_c: '友達にタローをくれました',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '友達がタローをくれました (A friend gave me Taro / මිතුරා මට තාරෝව දුන්නේය).'
      },
      {
        order_num: 47,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'なぜ動物病院へ行きましたか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_passage_46_49.jpg',
        audio_url: null,
        option_a: 'タローがいたそうにないていたから',
        option_b: '私は元気ないタローがしんぱいだったから',
        option_c: 'タローは食べ物がほとんど食べられなくなったから',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '私は元気ないタローがしんぱいだったから (I was worried about Taro having no energy / තාරෝට අපහසු නිසා මම බිය වූ බැවින්).'
      },
      {
        order_num: 48,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'いしゃは何と言いましたか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_passage_46_49.jpg',
        audio_url: null,
        option_a: '毎日病院へつれて行かなければならないと言いました',
        option_b: 'ちゅうしゃをしたのですぐによくなるだろうと言いました',
        option_c: '毎日薬を飲ませなければならないと言いました',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '毎日薬を飲ませなければならないと言いました (Must give medicine every day / දිනපතා බෙහෙත් දිය යුතු බව කීවේය).'
      },
      {
        order_num: 49,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'この人「私」のことを正しい説明しているのはどれですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_passage_46_49.jpg',
        audio_url: null,
        option_a: 'さいしょからしんぱいないだろうと思っていた',
        option_b: 'はじめしんぱいだったがあとで少あんしんした',
        option_c: 'いたくてないていたが、1週間ぐらいでよくなろうと思いました',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'はじめしんぱいだったがあとで少あんしんした (Was worried at first, but was relieved later / පසුව සැනසුමට පත් විය).'
      },
      {
        order_num: 50,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【50/51/52/53/54 共通問題】文章を読んで、質問に答えてください。\n\nこの写真は誰がとったものですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_passage_50_54.jpg',
        audio_url: null,
        option_a: '日本人',
        option_b: 'フランス人',
        option_c: '外国人',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'フランス人 (French person / ප්‍රංශ ජාතිකයෙකි).'
      },
      {
        order_num: 51,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '日本とフランスでは何がちがいますか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_passage_50_54.jpg',
        audio_url: null,
        option_a: 'フランスでは電車の中でねむっている人が見られません',
        option_b: 'フランスでは電車の中で写真をとる人が見られません',
        option_c: 'フランスでは電車の中でアナウンスをしません',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'フランスでは電車の中でねむっている人が見られません (In France, sleeping in trains is not seen).'
      },
      {
        order_num: 52,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '①「あの人たちにはひつようなんだ」誰に何がひつようですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_passage_50_54.jpg',
        audio_url: null,
        option_a: 'フランス人はいねむりをしたいです',
        option_b: '日本人はフランス人の写真をとりたいです',
        option_c: '日本人はいねむりをしたいです。',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '日本人はいねむりをしたいです (Japanese people need inemuri / ජපන් ජාතිකයන්ට කෙටි නින්දක් අවශ්‍යය).'
      },
      {
        order_num: 53,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '②「日本人はすごいさいのうがある」と書いてありますが、どんなさいのうですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_passage_50_54.jpg',
        audio_url: null,
        option_a: 'いねむりについていろいろ考えるさいのうです',
        option_b: 'みじかい時間、いねむりをするさいのうです',
        option_c: '外国人と友達になるさいのうです',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'みじかい時間、いねむりをするさいのうです (Talent to sleep in short periods / කෙටි වේලාවකින් නිදාගැනීමේ හැකියාව).'
      },
      {
        order_num: 54,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '日本人はどうして電車の中でいねむりをしていますか。正しくないのはどれか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_passage_50_54.jpg',
        audio_url: null,
        option_a: 'とても疲れているので',
        option_b: '写真をとるのができるので',
        option_c: '家がとおいので',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '写真をとるのができるので (2 වන කරුණ වැරදිය).'
      },
      {
        order_num: 55,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【55/56/57/58/59/60 共通問題】正しいものに〇、ちがうものに×を選びなさい。\n\n夜12時には駅の前にバスはありません。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_passage_55_60.jpg',
        audio_url: null,
        option_a: '〇',
        option_b: '×',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '〇 (රාත්‍රී 12ට බස් රථ නොමැත).'
      },
      {
        order_num: 56,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '女の人も夜おそく帰ります。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_passage_55_60.jpg',
        audio_url: null,
        option_a: '〇',
        option_b: '×',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '〇 (කාන්තාවන්ද රාත්‍රියේ ප්‍රමාද වී ආපසු යයි).'
      },
      {
        order_num: 57,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '夜12時には駅の前に人があまりいません。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_passage_55_60.jpg',
        audio_url: null,
        option_a: '〇',
        option_b: '×',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '× (බොහෝ පිරිසක් පෝලිමේ රැඳී සිටිති).'
      },
      {
        order_num: 58,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'タクシーは夜たくさん来ます。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_passage_55_60.jpg',
        audio_url: null,
        option_a: '〇',
        option_b: '×',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '× (ටැක්සි පහසුවෙන් නොපැමිණේ).'
      },
      {
        order_num: 59,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'うんてんしゅは近い所へ帰るきゃくをのせたいです。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_passage_55_60.jpg',
        audio_url: null,
        option_a: '〇',
        option_b: '×',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '× (රියදුරන් කැමති දුර ප්‍රදේශවල මගීන්ටයි).'
      },
      {
        order_num: 60,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '[ ] に 1・2・3 の中で,どれが入りますか。いちばんいいものを選びなさい。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft10_passage_55_60.jpg',
        audio_url: null,
        option_a: 'タクシーは夜おそい時たいせつです',
        option_b: 'タクシーはなかなか来ませんから、ふべんです',
        option_c: '雨の日はタクシーが来ません',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'タクシーはなかなか来ませんから、ふべんです (ටැක්සි පහසුවෙන් නොපැමිණෙන නිසා අපහසුය).'
      }
    ];

    console.log(`Inserting ${questions.length} questions for JFT Model Paper 10...`);
    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, section_name, question_text, question_type, 
          image_url, audio_url, option_a, option_b, option_c, option_d, 
          correct_option, marks, explanation, order_num
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId, q.section_name, q.question_text, q.question_type,
        q.image_url, q.audio_url, q.option_a, q.option_b, q.option_c, q.option_d,
        q.correct_option, q.marks, q.explanation, q.order_num
      ]);
    }

    console.log(`Successfully seeded all 60 questions for JFT Model Paper 10 (Exam ID: ${examId})`);
  } catch (err) {
    console.error('Error seeding JFT Model Paper 10:', err);
  }
}

module.exports = { seedJftModelPaper10 };
