const { query } = require('../config/database');

async function seedJftModelPaper15() {
  console.log('Seeding JFT-Basic Official Model Paper 15 (60 Questions, Pass 200/250)...');

  try {
    let exam = await query.get("SELECT * FROM exams WHERE title LIKE '%Model Paper 15%' OR title LIKE '%Paper 15%'");
    let examId;

    if (exam) {
      examId = exam.id;
      console.log(`Found existing Exam ID: ${examId}, resetting questions...`);
      await query.run('DELETE FROM questions WHERE exam_id = ?', [examId]);
      await query.run(`
        UPDATE exams 
        SET course_id = 1,
            title = 'JFT-Basic Official Model Paper 15 (60 Minutes)',
            description = 'Official JFT-Basic Prometric Computer-Based Examination Paper 15 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Listening Audio Tracks and Sinhala Explanations)',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (
          1,
          'JFT-Basic Official Model Paper 15 (60 Minutes)',
          'Official JFT-Basic Prometric Computer-Based Examination Paper 15 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Listening Audio Tracks and Sinhala Explanations)',
          60,
          200,
          1
        )
      `);
      examId = res.id;
      console.log(`Created new Exam ID: ${examId}`);
    }

    const questions = [
      // ================= SECTION 1: Script and Vocabulary (文字・語彙) [Q01 - Q15] =================
      {
        order_num: 1,
        section_name: 'Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)',
        question_text: '【<ruby>絵<rt>え</rt></ruby>を<ruby>見<rt>み</rt></ruby>て<ruby>正<rt>ただ</rt></ruby>しい<ruby>言葉<rt>ことば</rt></ruby>を<ruby>選<rt>えら</rt></ruby>んでください】\n<ruby>両手<rt>りょうて</rt></ruby>を<ruby>上<rt>うえ</rt></ruby>に<ruby>伸<rt>の</rt></ruby>ばしています。',
        image_url: null,
        audio_url: null,
        option_a: 'うでをあげます',
        option_b: 'くびをあげます',
        option_c: 'いきをすいます',
        option_d: '',
        correct_option: 'A',
        marks: 1,
        explanation: 'අත් දෙක ඉහළට එසවීම "うでをあげます (Ude o agemasu / 腕を上げます)" වේ.'
      },
      {
        order_num: 2,
        section_name: 'Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)',
        question_text: '【<ruby>絵<rt>え</rt></ruby>を<ruby>見<rt>み</rt></ruby>て<ruby>正<rt>ただ</rt></ruby>しい<ruby>言葉<rt>ことば</rt></ruby>を<ruby>選<rt>えら</rt></ruby>んでください】\n<ruby>首<rt>くび</rt></ruby>を<ruby>横<rt>よこ</rt></ruby>に<ruby>曲<rt>ま</rt></ruby>げてストレッチしています。',
        image_url: null,
        audio_url: null,
        option_a: 'うでをあげます',
        option_b: 'いきをすいます',
        option_c: 'くびをまげます',
        option_d: '',
        correct_option: 'C',
        marks: 1,
        explanation: 'බෙල්ල නැවීම හෝ ඇල කිරීම "くびをまげます (Kubi o magemasu / 首を曲げます)" වේ.'
      },
      {
        order_num: 3,
        section_name: 'Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)',
        question_text: '【<ruby>絵<rt>え</rt></ruby>を<ruby>見<rt>み</rt></ruby>て<ruby>正<rt>ただ</rt></ruby>しい<ruby>言葉<rt>ことば</rt></ruby>を<ruby>選<rt>えら</rt></ruby>んでください】\n<ruby>深呼吸<rt>しんこきゅう</rt></ruby>をして<ruby>空気<rt>くうき</rt></ruby>を<ruby>吸<rt>す</rt></ruby>い<ruby>込<rt>こ</rt></ruby>んでいます。',
        image_url: null,
        audio_url: null,
        option_a: 'いきをすいます',
        option_b: 'うでをあげます',
        option_c: 'くびをあげます',
        option_d: '',
        correct_option: 'A',
        marks: 1,
        explanation: 'හුස්ම ගැනීම හෝ වාතය ඇතුළට ගැනීම "いきをすいます (Iki o suimasu / 息を吸います)" වේ.'
      },
      {
        order_num: 4,
        section_name: 'Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)',
        question_text: '【<ruby>絵<rt>え</rt></ruby>を<ruby>見<rt>み</rt></ruby>て<ruby>正<rt>ただ</rt></ruby>しい<ruby>言葉<rt>ことば</rt></ruby>を<ruby>選<rt>えら</rt></ruby>んでください】\n<ruby>肩<rt>かた</rt></ruby>をぐるぐると<ruby>回<rt>まわ</rt></ruby>しています。',
        image_url: null,
        audio_url: null,
        option_a: 'くびをあげます',
        option_b: 'うでをあげます',
        option_c: 'かたをまわします',
        option_d: '',
        correct_option: 'C',
        marks: 1,
        explanation: 'උරහිස් කරකැවීම "かたをまわします (Kata o mawashimasu / 肩を回します)" වේ.'
      },
      {
        order_num: 5,
        section_name: 'Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)',
        question_text: '【<ruby>絵<rt>え</rt></ruby>を<ruby>見<rt>み</rt></ruby>て<ruby>正<rt>ただ</rt></ruby>しい<ruby>言葉<rt>ことば</rt></ruby>を<ruby>選<rt>えら</rt></ruby>んでください】\n<ruby>水<rt>みず</rt></ruby>といっしょに<ruby>錠剤<rt>じょうざい</rt></ruby>を<ruby>飲<rt>の</rt></ruby>んでいます。',
        image_url: null,
        audio_url: null,
        option_a: 'ぎゅうにゅうを飲みます',
        option_b: '薬を飲みます',
        option_c: 'みずを飲みます',
        option_d: '',
        correct_option: 'B',
        marks: 1,
        explanation: 'බෙහෙත් පෙති බීම "薬を飲みます (Kusuri o nomimasu)" වේ.'
      },
      {
        order_num: 6,
        section_name: 'Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)',
        question_text: '【<ruby>絵<rt>え</rt></ruby>を<ruby>見<rt>み</rt></ruby>て<ruby>正<rt>ただ</rt></ruby>しい<ruby>言葉<rt>ことば</rt></ruby>を<ruby>選<rt>えら</rt></ruby>んでください】\nパックからコップについで<ruby>飲<rt>の</rt></ruby>んでいます。',
        image_url: null,
        audio_url: null,
        option_a: 'ぎゅうにゅうを飲みます',
        option_b: 'みずを飲みます',
        option_c: '薬を飲みます',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: 'කිරි බීම "ぎゅうにゅうを飲みます (Gyuunyuu o nomimasu / 牛乳を飲みます)" වේ.'
      },
      {
        order_num: 7,
        section_name: 'Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)',
        question_text: '【<ruby>絵<rt>え</rt></ruby>を<ruby>見<rt>み</rt></ruby>て<ruby>正<rt>ただ</rt></ruby>しい<ruby>言葉<rt>ことば</rt></ruby>を<ruby>選<rt>えら</rt></ruby>んでください】\nマットの<ruby>上<rt>うえ</rt></ruby>でポーズをとっています。',
        image_url: null,
        audio_url: null,
        option_a: 'すわります',
        option_b: 'ヨガをします',
        option_c: 'たっています',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: 'යෝගා අභ්‍යාස කිරීම "ヨガをします (Yoga o shimasu)" වේ.'
      },
      {
        order_num: 8,
        section_name: 'Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)',
        question_text: '【<ruby>絵<rt>え</rt></ruby>を<ruby>見<rt>み</rt></ruby>て<ruby>正<rt>ただ</rt></ruby>しい<ruby>言葉<rt>ことば</rt></ruby>を<ruby>選<rt>えら</rt></ruby>んでください】\nタバコを<ruby>断<rt>ことわ</rt></ruby>っています（<ruby>禁煙<rt>きんえん</rt></ruby>）。',
        image_url: null,
        audio_url: null,
        option_a: 'たばこをすいます',
        option_b: 'お酒をすいます',
        option_c: 'たばこをすいません',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: 'දුම්පානය නොකිරීම "たばこをすいません (Tabako o suimasen)" වේ.'
      },
      {
        order_num: 9,
        section_name: 'Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)',
        question_text: '【<ruby>絵<rt>え</rt></ruby>を<ruby>見<rt>み</rt></ruby>て<ruby>正<rt>ただ</rt></ruby>しい<ruby>言葉<rt>ことば</rt></ruby>を<ruby>選<rt>えら</rt></ruby>んでください】\nビールで<ruby>乾杯<rt>かんぱい</rt></ruby>しています。',
        image_url: null,
        audio_url: null,
        option_a: 'お酒を飲みます',
        option_b: 'お酒を飲みません',
        option_c: 'たばこをすいません',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: 'මත්පැන්/බියර් බීම "お酒を飲みます (Osake o nomimasu)" වේ.'
      },
      {
        order_num: 10,
        section_name: 'Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)',
        question_text: '【<ruby>絵<rt>え</rt></ruby>を<ruby>見<rt>み</rt></ruby>て<ruby>正<rt>ただ</rt></ruby>しい<ruby>言葉<rt>ことば</rt></ruby>を<ruby>選<rt>えら</rt></ruby>んでください】\n<ruby>赤<rt>あか</rt></ruby>ちゃんが<ruby>生<rt>う</rt></ruby>まれました。',
        image_url: null,
        audio_url: null,
        option_a: 'しゅっさん',
        option_b: 'じゅっさん',
        option_c: 'じゅうさん',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: 'දරුවකු ප්‍රසූත කිරීම "しゅっさん (Shussan / 出産)" වේ.'
      },
      {
        order_num: 11,
        section_name: 'Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)',
        question_text: '<ruby>下線<rt>かせん</rt></ruby>のひらがなはどう<ruby>漢字<rt>かんじ</rt></ruby>で<ruby>書<rt>か</rt></ruby>きますか。\nこのあたりはアニメの<ruby>店<rt>みせ</rt></ruby>が<ruby>多<rt>おお</rt></ruby>いです。<ruby>若<rt>わか</rt></ruby>い<ruby>人<rt>ひと</rt></ruby>に<u>にんき</u>があります。',
        image_url: null,
        audio_url: null,
        option_a: '元気',
        option_b: '人形',
        option_c: '人気',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: 'ජනප්‍රියත්වය සඳහා නිවැරදි කන්ජිය "人気 (にんき - Ninki)" වේ.'
      },
      {
        order_num: 12,
        section_name: 'Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)',
        question_text: '<ruby>下線<rt>かせん</rt></ruby>のひらがなはどう<ruby>漢字<rt>かんじ</rt></ruby>で<ruby>書<rt>か</rt></ruby>きますか。\nこの<ruby>店<rt>みせ</rt></ruby>はカメラが(12)<u>やすい</u>です。テレビは(13)<u>たかい</u>です。',
        image_url: null,
        audio_url: null,
        option_a: '高い',
        option_b: '女い',
        option_c: '安い',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: 'ලාභදායී / මිල අඩු යන්නෙහි කන්ජිය "安い (やすい - Yasui)" වේ.'
      },
      {
        order_num: 13,
        section_name: 'Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)',
        question_text: '<ruby>下線<rt>かせん</rt></ruby>のひらがなはどう<ruby>漢字<rt>かんじ</rt></ruby>で<ruby>書<rt>か</rt></ruby>きますか。\nこの<ruby>店<rt>みせ</rt></ruby>はカメラが(12)やすいです。テレビは(13)<u>たかい</u>です。',
        image_url: null,
        audio_url: null,
        option_a: '高い',
        option_b: '女い',
        option_c: '安い',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: 'මිල අධික / උසස් යන්නෙහි කන්ජිය "高い (たかい - Takai)" වේ.'
      },
      {
        order_num: 14,
        section_name: 'Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)',
        question_text: '<ruby>下線<rt>かせん</rt></ruby>のひらがなはどう<ruby>漢字<rt>かんじ</rt></ruby>で<ruby>書<rt>か</rt></ruby>きますか。\n<ruby>駅<rt>えき</rt></ruby>で<ruby>友達<rt>ともだち</rt></ruby>を<u>まちます</u>。',
        image_url: null,
        audio_url: null,
        option_a: '持ちます',
        option_b: '待ちます',
        option_c: '特ちます',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: 'බලා සිටීම / රැඳී සිටීම සඳහා කන්ජිය "待ちます (まちます - Machimasu)" වේ.'
      },
      {
        order_num: 15,
        section_name: 'Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)',
        question_text: '<ruby>下線<rt>かせん</rt></ruby>のひらがなはどう<ruby>漢字<rt>かんじ</rt></ruby>で<ruby>書<rt>か</rt></ruby>きますか。\n<ruby>雪<rt>ゆき</rt></ruby>で<ruby>電車<rt>でんしゃ</rt></ruby>が<u>とまりました</u>。',
        image_url: null,
        audio_url: null,
        option_a: '泊まりました',
        option_b: '止まりました',
        option_c: '正まりました',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: 'දුම්රියක් නැවතීම සඳහා නිවැරදි කන්ජිය "止まりました (とまりました - Tomarimashita)" වේ.'
      },

      // ================= SECTION 2: Conversation and Grammar (会話・文法) [Q16 - Q30] =================
      {
        order_num: 16,
        section_name: 'Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)',
        question_text: 'このあたりは<ruby>店<rt>みせ</rt></ruby>が ＿＿＿＿＿＿＿＿ <ruby>便利<rt>べんり</rt></ruby>です。',
        image_url: null,
        audio_url: null,
        option_a: '少なくて',
        option_b: '多くて',
        option_c: '大きくて',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'කඩසාප්පු බොහෝ ඇති බැවින් පහසු බව සම්බන්ධ කිරීමට「多くて (Ookute - බහුලව තිබී)」යෙදේ.'
      },
      {
        order_num: 17,
        section_name: 'Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)',
        question_text: 'このあたりは ＿＿＿＿＿＿＿＿ おもしろいです。',
        image_url: null,
        audio_url: null,
        option_a: 'にぎやかに',
        option_b: 'ひろいで',
        option_c: 'しずかで',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'な-විශේෂණයක Te-form සම්බන්ධකය "〜で" වේ (しずかで - නිස්කලංකව තිබී).'
      },
      {
        order_num: 18,
        section_name: 'Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)',
        question_text: 'ここは<ruby>新<rt>あたら</rt></ruby>しい ＿＿＿＿＿＿＿＿ にんきがあります。',
        image_url: null,
        audio_url: null,
        option_a: '町',
        option_b: '町で',
        option_c: '町に',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'විශේෂණයට පසුව සෘජුවම නාම පදය වන "町 (Machi - නගරය)" යෙදේ (新しい町).'
      },
      {
        order_num: 19,
        section_name: 'Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)',
        question_text: 'このとおりは<ruby>夜<rt>よる</rt></ruby> ＿＿＿＿＿＿＿＿ あぶないです。',
        image_url: null,
        audio_url: null,
        option_a: 'あかるくて',
        option_b: 'くろくて',
        option_c: 'くらくて',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'අඳුරු නිසා අනතුරුදායක බව දැක්වීමට「暗くて (Kurakute)」යෙදේ.'
      },
      {
        order_num: 20,
        section_name: 'Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)',
        question_text: 'このゆうえんちは ＿＿＿＿＿＿＿＿ ふべんです。',
        image_url: null,
        audio_url: null,
        option_a: 'みじかくて',
        option_b: 'とおくて',
        option_c: 'ちかくて',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'දුර නිසා අපහසු බව දැක්වීමට「遠くて (Tookute - දුර වැඩි නිසා)」යෙදේ.'
      },
      {
        order_num: 21,
        section_name: 'Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)',
        question_text: '【<ruby>会話<rt>かいわ</rt></ruby>を<ruby>読<rt>よ</rt></ruby>んで<ruby>正<rt>ただ</rt></ruby>しいものを<ruby>選<rt>えら</rt></ruby>びなさい】\nA: すみません。コンピューターを ＿＿＿＿＿＿＿＿。\nB: はい、どうぞ。',
        image_url: null,
        audio_url: null,
        option_a: 'かりてもいいですか',
        option_b: '買いてもいいですか。',
        option_c: '使ってほうがいいですか',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'අවසර ලබාගැනීමට「〜てもいいですか (かりてもいいですか - පාවිච්චි කළාට/ණයට ගත්තට කමක් නැද්ද?)」යෙදේ.'
      },
      {
        order_num: 22,
        section_name: 'Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)',
        question_text: '【<ruby>会話<rt>かいわ</rt></ruby>を<ruby>読<rt>よ</rt></ruby>んで<ruby>正<rt>ただ</rt></ruby>しいものを<ruby>選<rt>えら</rt></ruby>びなさい】\n山田: こちらはひしょのキャシーさんです。\n田中: 田中です。(22)＿＿＿＿＿＿＿＿。\nキャシー: こちらこそ。どうぞよろしく。',
        image_url: null,
        audio_url: null,
        option_a: 'どうもすみません',
        option_b: 'こちらこそ',
        option_c: 'どうぞよろしく',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'මුල්වරට හඳුන්වා දීමේදී "どうぞよろしく (Douzo yoroshiku)" යෙදේ.'
      },
      {
        order_num: 23,
        section_name: 'Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)',
        question_text: '【<ruby>会話<rt>かいわ</rt></ruby>を<ruby>読<rt>よ</rt></ruby>んで<ruby>正<rt>ただ</rt></ruby>しいものを<ruby>選<rt>えら</rt></ruby>びなさい】\n山田: キャシーさんは日本語、(23)＿＿＿＿＿＿＿＿ です。\n田中: そうですか。',
        image_url: null,
        audio_url: null,
        option_a: 'へらへら',
        option_b: 'ぺらぺら',
        option_c: 'べらべら',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'භාෂාවක් චතුර ලෙස කතා කළ හැකි බව හැඟවීමට "ぺらぺら (Pera pera - චතුරව)" ඔනොමටොපියාව යෙදේ.'
      },
      {
        order_num: 24,
        section_name: 'Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)',
        question_text: '【<ruby>空港<rt>くうこう</rt></ruby>での<ruby>会話<rt>かいわ</rt></ruby>】\nA: (24)＿＿＿＿＿＿＿＿、田中さん。\nB: (25)＿＿＿＿＿＿＿＿。(26)＿＿＿＿＿＿＿＿ ありがとうございます。',
        image_url: null,
        audio_url: null,
        option_a: 'いらっしゃる',
        option_b: 'ようこそ',
        option_c: 'こちらこそ',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'පැමිණි කෙනෙකු පිළිගැනීමේදී "ようこそ (Youkoso - සාදරයෙන් පිළිගනිමු)" යෙදේ.'
      },
      {
        order_num: 25,
        section_name: 'Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)',
        question_text: '【<ruby>空港<rt>くうこう</rt></ruby>での<ruby>会話<rt>かいわ</rt></ruby>】\nB: (25)＿＿＿＿＿＿＿＿。(26)＿＿＿＿＿＿＿＿ ありがとうございます。',
        image_url: null,
        audio_url: null,
        option_a: 'ありがとう',
        option_b: 'おまたせしました',
        option_c: 'ようこそ',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'රැඳී සිටීමට සිදුවීම ගැන ආචාරශීලීව "おまたせしました (Omatase shimashita - ප්‍රමාද වූවාට සමාවෙන්න)" යෙදේ.'
      },
      {
        order_num: 26,
        section_name: 'Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)',
        question_text: '【<ruby>空港<rt>くうこう</rt></ruby>での<ruby>会話<rt>かいわ</rt></ruby>】\nB: おまたせしました。(26)＿＿＿＿＿＿＿＿ ありがとうございます。\nA: フライトはどうでしたか。\nB: まあまあでした。',
        image_url: null,
        audio_url: null,
        option_a: '帰った',
        option_b: 'でむかえ',
        option_c: 'でむこう',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ගුවන්තොටුපොළට පැමිණ පිළිගැනීම ගැන ස්තූති කිරීමට「お出迎え (でむかえ) ありがとうございます」යෙදේ.'
      },
      {
        order_num: 27,
        section_name: 'Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)',
        question_text: '【<ruby>食事<rt>しょくじ</rt></ruby>の<ruby>会話<rt>かいわ</rt></ruby>】\nA: やぎさん、よかったら、サラダ(27)＿＿＿＿＿＿＿＿。\nB: はい、いただきます。',
        image_url: null,
        audio_url: null,
        option_a: 'どうぞ',
        option_b: 'ください',
        option_c: 'くださいませんか',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'කෑමක් පිරිනමමින් "කරුණාකර ගන්න" යැයි කීමට "どうぞ (Douzo)" යෙදේ.'
      },
      {
        order_num: 28,
        section_name: 'Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)',
        question_text: '【<ruby>食事<rt>しょくじ</rt></ruby>の<ruby>会話<rt>かいわ</rt></ruby>】\nB: はい、いただきます。このサラダちょっとからくて(28)＿＿＿＿＿＿＿＿ ですね。',
        image_url: null,
        audio_url: null,
        option_a: 'おもしろい',
        option_b: 'おもしろくない',
        option_c: 'おいしい',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ආහාරයේ රසවත් බව ප්‍රකාශ කිරීමට "おいしい (Oishii - රසවත්)" යෙදේ.'
      },
      {
        order_num: 29,
        section_name: 'Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)',
        question_text: '【<ruby>食事<rt>しょくじ</rt></ruby>の<ruby>会話<rt>かいわ</rt></ruby>】\nA: (29)＿＿＿＿＿＿＿＿。もう<ruby>少<rt>すこ</rt></ruby>しどうですか。\nB: ありがとうございます。(30)＿＿＿＿＿＿＿＿。',
        image_url: null,
        audio_url: null,
        option_a: 'どうですか',
        option_b: 'どうしてですか',
        option_c: 'そうですか',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'අනෙකාගේ ප්‍රකාශයට එකඟ වෙමින් "එහෙමද" කීමට "そうですか (Sou desu ka)" යෙදේ.'
      },
      {
        order_num: 30,
        section_name: 'Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)',
        question_text: '【<ruby>食事<rt>しょくじ</rt></ruby>の<ruby>会話<rt>かいわ</rt></ruby>】\nA: もう少しどうですか。\nB: ありがとうございます。(30)＿＿＿＿＿＿＿＿。',
        image_url: null,
        audio_url: null,
        option_a: 'まだおなかがいたいです',
        option_b: 'まだおなかがいっぱいです',
        option_c: 'もうおなかがいっぱいです',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'තවදුරටත් කෑම අවශ්‍ය නොවන තරමට බඩ පිරී ඇති බව කීමට「もうおなかがいっぱいです (දැන් බඩ පිරිලා)」යෙදේ.'
      },

      // ================= SECTION 3: Listening Comprehension (聴解) [Q31 - Q45] =================
      {
        order_num: 31,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【<ruby>音声<rt>おんせい</rt></ruby>を<ruby>聞<rt>き</rt></ruby>いて<ruby>答<rt>こた</rt></ruby>えなさい】\n<ruby>女<rt>おんな</rt></ruby>の<ruby>人<rt>ひと</rt></ruby>はけんこうのために<ruby>何<rt>なに</rt></ruby>をしていますか。',
        image_url: null,
        audio_url: 'https://drive.google.com/file/d/1jeQEvd0B4EWFakC0ItNiqL9sFnM32U83/view?usp=sharing',
        option_a: 'ジョギング・ヨガ',
        option_b: 'ヨガ・ダイビング',
        option_c: 'ヨガ・すいえい',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ශ්‍රව්‍ය ඛණ්ඩය අනුව කාන්තාව සෞඛ්‍යය සඳහා යෝගා සහ පිහිනුම් (ヨガ・すいえい) කරයි.'
      },
      {
        order_num: 32,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【<ruby>音声<rt>おんせい</rt></ruby>を<ruby>聞<rt>き</rt></ruby>いて<ruby>答<rt>こた</rt></ruby>えなさい】\n<ruby>毎朝<rt>まいあさ</rt></ruby><ruby>何分<rt>なんぷん</rt></ruby>ぐらいヨガをしていますか。',
        image_url: null,
        audio_url: 'https://drive.google.com/file/d/1jeQEvd0B4EWFakC0ItNiqL9sFnM32U83/view?usp=sharing',
        option_a: '毎朝2分ぐらい',
        option_b: '毎朝50分ぐらい',
        option_c: '毎朝20分ぐらい',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'සෑම උදෑසනකම විනාඩි 20ක් පමණ (毎朝20分ぐらい) යෝගා කරන බව සඳහන් වේ.'
      },
      {
        order_num: 33,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【<ruby>音声<rt>おんせい</rt></ruby>を<ruby>聞<rt>き</rt></ruby>いて<ruby>答<rt>こた</rt></ruby>えなさい】\n<ruby>女<rt>おんな</rt></ruby>の<ruby>人<rt>ひと</rt></ruby>はプールでどのぐらいおよぎますか。',
        image_url: null,
        audio_url: 'https://drive.google.com/file/d/1jeQEvd0B4EWFakC0ItNiqL9sFnM32U83/view?usp=sharing',
        option_a: '週に1回ぐらい',
        option_b: '週に2回ぐらい',
        option_c: '週に3回ぐらい',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'සතියකට දෙවතාවක් පමණ (週に2回ぐらい) පිහිනුම් තටාකයේ පිහිනයි.'
      },
      {
        order_num: 34,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【<ruby>音声<rt>おんせい</rt></ruby>を<ruby>聞<rt>き</rt></ruby>いて<ruby>正<rt>ただ</rt></ruby>しいものを<ruby>選<rt>えら</rt></ruby>びなさい】',
        image_url: null,
        audio_url: 'https://drive.google.com/file/d/1omaVuFlZJAOfRtj7rctQT_Qr4wP8DoQw/view?usp=sharing',
        option_a: '女の人は毎日5キロぐらい歩きます',
        option_b: '女の人はしゅうかん5キロぐらいあるきます',
        option_c: '女の人は土曜日と日曜日5キロぐらい歩きます。',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ශ්‍රව්‍ය ඛණ්ඩය අනුව කාන්තාව දිනපතා කිලෝමීටර් 5ක් පමණ ඇවිදියි (毎日5キロぐらい歩きます).'
      },
      {
        order_num: 35,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【<ruby>音声<rt>おんせい</rt></ruby>を<ruby>聞<rt>き</rt></ruby>いて<ruby>答<rt>こた</rt></ruby>えなさい】\nけんこうのためにシンさんは<ruby>何<rt>なに</rt></ruby>をしていますか。',
        image_url: null,
        audio_url: 'https://drive.google.com/file/d/199OsIp9LjdyvAxxjlgpXbAXv-SdnOB1v/view?usp=sharing',
        option_a: '家でヨガをしたりジムでトレーニングをしたりしています。',
        option_b: '公園でヨガをしたりジムでトレーニングをしたりしています。',
        option_c: '公園でヨガをしたり家でトレーニングをしたりしています。',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ෂින් මහතා උද්‍යානයේ යෝගා සහ ජිම් එකේ පුහුණුවීම් කරයි (公園でヨガをしたりジムでトレーニングをしたりしています).'
      },
      {
        order_num: 36,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【<ruby>音声<rt>おんせい</rt></ruby>を<ruby>聞<rt>き</rt></ruby>いて<ruby>答<rt>こた</rt></ruby>えなさい】\n<ruby>田中<rt>たなか</rt></ruby>さんはけんこうのために<ruby>何<rt>なに</rt></ruby>をしていますか。',
        image_url: null,
        audio_url: 'https://drive.google.com/file/d/199OsIp9LjdyvAxxjlgpXbAXv-SdnOB1v/view?usp=sharing',
        option_a: 'はしったりおよいだりしています',
        option_b: 'ヨガをしたりとトレーニングしたりしています',
        option_c: 'お酒を飲んだりおんがくを聞いたりしています',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'තනකා මහතා දිවීම සහ පිහිනීම සිදු කරයි (はしったりおよいだりしています).'
      },
      {
        order_num: 37,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【<ruby>音声<rt>おんせい</rt></ruby>を<ruby>聞<rt>き</rt></ruby>いて<ruby>答<rt>こた</rt></ruby>えなさい】\nよしださんはどこに<ruby>行<rt>い</rt></ruby>っていますか。',
        image_url: null,
        audio_url: 'https://drive.google.com/file/d/199OsIp9LjdyvAxxjlgpXbAXv-SdnOB1v/view?usp=sharing',
        option_a: 'たいしかん',
        option_b: 'たいいくかん',
        option_c: 'としょかん',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'යොෂිඩා මහතා ක්‍රීඩාංගණයට / ජිම්නාසියම් වෙත යයි (たいいくかん - 体育館).'
      },
      {
        order_num: 38,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【<ruby>音声<rt>おんせい</rt></ruby>を<ruby>聞<rt>き</rt></ruby>いて<ruby>答<rt>こた</rt></ruby>えなさい】\nAグループ（15人）のスポーツアンケートで、(A) ときどきするに入る人数はどれですか。',
        image_url: null,
        audio_url: 'https://drive.google.com/file/d/1Uywj74_heGIPi42YFVOuEdruR7_KJpfG/view?usp=sharing',
        option_a: '8',
        option_b: '7',
        option_c: '4',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ශ්‍රව්‍ය ඛණ්ඩය අනුව විටින් විට ක්‍රීඩා කරන පිරිස 8 දෙනෙකි (8).'
      },
      {
        order_num: 39,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【<ruby>音声<rt>おんせい</rt></ruby>を<ruby>聞<rt>き</rt></ruby>いて<ruby>答<rt>こた</rt></ruby>えなさい】\nAグループ（15人）のスポーツアンケートで、(B) しないに入る人数はどれですか。',
        image_url: null,
        audio_url: 'https://drive.google.com/file/d/1Uywj74_heGIPi42YFVOuEdruR7_KJpfG/view?usp=sharing',
        option_a: '5',
        option_b: '4',
        option_c: '3',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ක්‍රීඩා නොකරන පිරිස 4 දෙනෙකි (15 - 3 - 8 = 4).'
      },
      {
        order_num: 40,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【<ruby>音声<rt>おんせい</rt></ruby>を<ruby>聞<rt>き</rt></ruby>いて<ruby>答<rt>こた</rt></ruby>えなさい】\nさいとうさんはいつ<ruby>何時<rt>なんじ</rt></ruby>にきますか。',
        image_url: null,
        audio_url: 'https://drive.google.com/file/d/1zAJbtMeJD3cmBVwo31L9oerVrkLdXf0L/view?usp=sharing',
        option_a: '26日、夜3時',
        option_b: '16日、昼3時',
        option_c: '19日、昼3時',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'සයිතෝ මහත්මිය 19 වන දින දහවල් 3:00 ට පැමිණෙයි (19日、昼3時).'
      },
      {
        order_num: 41,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【<ruby>音声<rt>おんせい</rt></ruby>を<ruby>聞<rt>き</rt></ruby>いて<ruby>正<rt>ただ</rt></ruby>しいものを<ruby>選<rt>えら</rt></ruby>びなさい】',
        image_url: null,
        audio_url: 'https://drive.google.com/file/d/1HCaqdQTV99qZSwv-ZOyJc57d6nez_pdH/view?usp=sharing',
        option_a: 'ネクタイは誕生日に彼にあげました',
        option_b: 'ネクタイは誕生日に彼にもらいました',
        option_c: 'ネックレスは誕生日に彼にもらいました',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'උපන්දිනයට ඔහුගෙන් ටයි පටියක් තෑගි ලැබුණි (ネクタイは誕生日に彼にもらいました).'
      },
      {
        order_num: 42,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【<ruby>音声<rt>おんせい</rt></ruby>を<ruby>聞<rt>き</rt></ruby>いて<ruby>答<rt>こた</rt></ruby>えなさい】\nパクさんは<ruby>父<rt>ちち</rt></ruby>にもらったのはどれですか。',
        image_url: null,
        audio_url: 'https://drive.google.com/file/d/16taFSqdBJKn2PVTyQNq2YMitddnHnC0J/view?usp=sharing',
        option_a: 'かっこう',
        option_b: 'とけい',
        option_c: 'とくい',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'තාත්තාගෙන් ලැබුණු තෑග්ග ඔරලෝසුවකි (とけい - Watch).'
      },
      {
        order_num: 43,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【<ruby>音声<rt>おんせい</rt></ruby>を<ruby>聞<rt>き</rt></ruby>いて<ruby>答<rt>こた</rt></ruby>えなさい】\nかばんはいつ<ruby>買<rt>か</rt></ruby>いましたか。',
        image_url: null,
        audio_url: 'https://drive.google.com/file/d/1z-SB1PP0Yykn27SGFda-sSjxu5VryBHU/view?usp=sharing',
        option_a: '11年前',
        option_b: '10年前',
        option_c: '2年前',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'බෑගය මිලදී ගත්තේ මීට වසර 2 කට පෙරයි (2年前).'
      },
      {
        order_num: 44,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【<ruby>音声<rt>おんせい</rt></ruby>を<ruby>聞<rt>き</rt></ruby>いて<ruby>答<rt>こた</rt></ruby>えなさい】\nセーターについて<ruby>何<rt>なに</rt></ruby>がただしいですか。',
        image_url: null,
        audio_url: 'https://drive.google.com/file/d/17w38p0k7CeWSrh9aQF8ZC7e3jrfj8Jti/view?usp=sharing',
        option_a: '山田さんの主人にもらいました',
        option_b: '山田さんはお店で買いました。',
        option_c: '山田さんは自分で作りました',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ස්වීටරය යමඩා මහත්මිය විසින්ම ගොතන ලද එකකි (山田さんは自分で作りました).'
      },
      {
        order_num: 45,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '【<ruby>音声<rt>おんせい</rt></ruby>を<ruby>聞<rt>き</rt></ruby>いて<ruby>答<rt>こた</rt></ruby>えなさい】\n<ruby>山田<rt>やまだ</rt></ruby>さんは<ruby>何<rt>なに</rt></ruby>が<ruby>好<rt>す</rt></ruby>きと<ruby>言<rt>い</rt></ruby>っていますか。',
        image_url: null,
        audio_url: 'https://drive.google.com/file/d/17w38p0k7CeWSrh9aQF8ZC7e3jrfj8Jti/view?usp=sharing',
        option_a: 'セーター',
        option_b: 'のみもの',
        option_c: 'あみもの',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ඇය ගෙතුම් කලාවට කැමති බව පවසයි (あみもの - Knitting).'
      },

      // ================= SECTION 4: Reading Comprehension (読解) [Q46 - Q60] =================
      {
        order_num: 46,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【カプセルホテルの文章を読んで答えなさい】\n「東京は、いろいろなホテルがありますが、最近、カプセルホテルと言うホテルが多くなりました。一つ一つの部屋が、薬のカプセルとおなじかたちをしています。」\n\nカプセルホテルがある場所はどこですか。',
        image_url: null,
        audio_url: null,
        option_a: '東京',
        option_b: 'ちほう',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ඡේදයේ පැහැදිලිවම ටෝකියෝ (東京) ගැන සඳහන් වේ.'
      },
      {
        order_num: 47,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【カプセルホテルの文章を読んで答えなさい】\nカプセルホテルのかたちはどんなかたちですか。',
        image_url: null,
        audio_url: null,
        option_a: 'ふつうのホテルとおなじ',
        option_b: '小さい部屋がたくさんある',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'බෙහෙත් කරල් හෝ මී වදයක් මෙන් කුඩා කාමර රාශියක් ඇත (小さい部屋がたくさんある).'
      },
      {
        order_num: 48,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【カプセルホテルの文章を読んで答えなさい】\n部屋の中はどうですか。',
        image_url: null,
        audio_url: null,
        option_a: 'せまい',
        option_b: 'ひろい',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'කාමරය ඉතා පටුය (せまい - Narrow/Small).'
      },
      {
        order_num: 49,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【カプセルホテルの文章を読んで答えなさい】\nカプセルホテルの主な利用者はだれですか。',
        image_url: null,
        audio_url: null,
        option_a: 'かんこうきゃく',
        option_b: 'サラリーマン',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ප්‍රධාන වශයෙන් නවාතැන් ගන්නේ කාර්යාල සේවකයන් (サラリーマン - Businessmen) ය.'
      },
      {
        order_num: 50,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【カプセルホテルの文章を読んで答えなさい】\nこの文の「ハチのす」は何ですか。',
        image_url: null,
        audio_url: null,
        option_a: '会社',
        option_b: 'ハチの家',
        option_c: 'ホテル',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'මී වදයක් ලෙස උපමාවට ගෙන ඇත්තේ හෝටලයයි (ホテル).'
      },
      {
        order_num: 51,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【カプセルホテルの文章を読んで答えなさい】\nこの文の「たくさんの働きバチ」は何ですか。',
        image_url: null,
        audio_url: null,
        option_a: 'むし',
        option_b: 'ホテルの人',
        option_c: 'サラリーマン',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'වැඩකරන මී මැස්සන් ලෙස උපමා කර ඇත්තේ වෙහෙස මහන්සි වී වැඩකරන කාර්යාල සේවකයන්ය (サラリーマン).'
      },
      {
        order_num: 52,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【カプセルホテルの文章を読んで答えなさい】\nどうしてカプセルホテルができましたか。',
        image_url: null,
        audio_url: null,
        option_a: '夜遅くまで、趣味を楽しみたいから',
        option_b: '夜遅くまで仕事をして、家に帰れないから',
        option_c: '家族といっしょに食事をしたり、話したりしたくないから',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'රාත්‍රිය වනතුරු අතිකාල වැඩ කර දුර බැහැර නිවෙස්වලට යා නොහැකි නිසාය (夜遅くまで仕事をして、家に帰れないから).'
      },
      {
        order_num: 53,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【アルバイトの文章を読んで答えなさい】\n「やまもとさんは、大学生です。大学のお金は両親に払ってもらい、毎月10万円送ってもらいます。」\n\nやまもとさんは、両親から毎月送ってもらうお金はどうしていますか。',
        image_url: null,
        audio_url: null,
        option_a: '大学にはらっています。',
        option_b: '旅行やあそびのために使っています。',
        option_c: 'きっさてんにはらっています。',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'විශ්වවිද්‍යාල ගාස්තු වෙනම දෙමාපියන් ගෙවන අතර එවන මුදල් ජීවන වියදම් හා විනෝදයට යොදවයි (旅行やあそびのために使っています).'
      },
      {
        order_num: 54,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【アルバイトの文章を読んで答えなさい】\nやまもとさんは今アルバイトをどう思っていますか。',
        image_url: null,
        audio_url: null,
        option_a: '今の仕事は早くやめてもっと勉強する時間を作りたいです',
        option_b: '仕事がいそがしくて大学に行けないのでやめたいです',
        option_c: '仕事もあまり大変ではないし、もらえるお金も悪くないです',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'කැෆේ රැකියාව එතරම් අමාරු නැති අතර ලැබෙන මුදලද හොඳ බව සිතයි (仕事もあまり大変ではないし、もらえるお金も悪くないです).'
      },
      {
        order_num: 55,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【アルバイトの文章を読んで答えなさい】\nアルバイトのことを正しく説明しているのはどれですか。',
        image_url: null,
        audio_url: null,
        option_a: '学生はきっさてんのアルバイトは1日1時間しかできません',
        option_b: '図書館で本を貸す手伝いをするアルバイトはもらえるお金が少ないです',
        option_c: '両親から10万円おくってもらえるとアルバイトをしなくてもいいです',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'පුස්තකාල රැකියාවට පැයකට ලැබෙන්නේ යෙන් 600ක් පමණක් බැවින් මුදල් අඩුය (図書館のアルバイトはもらえるお金が少ないです).'
      },
      {
        order_num: 56,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【日本まつりボランティアカードを読んで答えなさい】\nカード：「したい仕事：さつえい、うけつけ（丸印）」\n\nタイラーモスさんはしたい仕事は何ですか。',
        image_url: null,
        audio_url: null,
        option_a: 'あんない・うけつけ',
        option_b: 'しかい・うけつけ',
        option_c: 'さつえい・うけつけ',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'කාඩ්පතේ රවුම් කර ඇත්තේ ඡායාරූපකරණය සහ පිළිගැනීමයි (さつえい・うけつけ).'
      },
      {
        order_num: 57,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【日本まつりボランティアカードを読んで答えなさい】\nカード：「できること：にほんごが はなせます。コンピューターが つかえます。」\n\nこの人は何ができますか。',
        image_url: null,
        audio_url: null,
        option_a: '日本語と韓国語がはなすことができます',
        option_b: 'パソコンの使い方がわかります',
        option_c: '日本語でコンピューターでタイプすることができます',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'පරිගණක භාවිතය දන්නා බව දක්වා ඇත (パソコンの使い方がわかります).'
      },
      {
        order_num: 58,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【カラオケコンテストのお知らせを読んで○か×かを選びなさい】\n「はじめにみなさんにおねがいがあります。このかいじょうでは飲食はごえんりょください。」\n\nここに食事をしてもいいです。',
        image_url: null,
        audio_url: null,
        option_a: '〇',
        option_b: '×',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ආහාර ගැනීම තහනම් කර ඇත (飲食はご遠慮ください). එබැවින් වැරදිය (×).'
      },
      {
        order_num: 59,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【カラオケコンテストのお知らせを読んで○か×かを選びなさい】\nこれは歌を歌うコンテストです。',
        image_url: null,
        audio_url: null,
        option_a: '〇',
        option_b: '×',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'කරෝකේ තරඟය යනු ගීත ගායනා තරඟයකි (歌を歌うコンテスト). එබැවින් නිවැරදිය (〇).'
      },
      {
        order_num: 60,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '【カラオケコンテストのお知らせを読んで○か×かを選びなさい】\nこのところに映画も見るごとができます。',
        image_url: null,
        audio_url: null,
        option_a: '〇',
        option_b: '×',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'චිත්‍රපට නැරඹීම ගැන කිසිවක් සඳහන් නොවේ. එබැවින් වැරදිය (×).'
      }
    ];

    console.log(`Inserting ${questions.length} questions for JFT Model Paper 15...`);
    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, order_num, section_name, question_text, 
          image_url, audio_url, option_a, option_b, option_c, option_d, 
          correct_option, marks, explanation
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId, q.order_num, q.section_name, q.question_text,
        q.image_url, q.audio_url, q.option_a, q.option_b, q.option_c, q.option_d,
        q.correct_option, q.marks, q.explanation
      ]);
    }

    console.log('✅ JFT Model Paper 15 seeded successfully with 60 questions!');
  } catch (err) {
    console.error('❌ Error seeding JFT Model Paper 15:', err);
    throw err;
  }
}

module.exports = { seedJftModelPaper15 };
if (require.main === module) {
  seedJftModelPaper15().then(() => process.exit(0)).catch(err => { console.error(err); process.exit(1); });
}
