const { query } = require('../config/database');

async function seedJftModelPaper09() {
  try {
    const title = 'JFT-Basic Official Model Paper 09 (60 Minutes)';
    const existingExam = await query.get("SELECT id FROM exams WHERE title = ?", [title]);
    let examId;

    if (existingExam) {
      examId = existingExam.id;
      const countRes = await query.get("SELECT COUNT(*) as count FROM questions WHERE exam_id = ?", [examId]);
      if (countRes && countRes.count >= 60) {
        return;
      }
      console.log(`Seeding JFT Model Paper 09 (Exam ID: ${examId})...`);
      await query.run(`
        UPDATE exams 
        SET description = 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper 09 (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [examId]);
      await query.run("DELETE FROM questions WHERE exam_id = ?", [examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (1, ?, 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper 09 (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.', 60, 200, 1)
      `, [title]);
      examId = res.id;
      console.log(`Created JFT Model Paper 09 (Exam ID: ${examId})`);
    }

    const questions = [
      // ==========================================
      // SECTION 1: Script & Vocabulary (文字・語彙 - Q01 to Q15)
      // ==========================================
      {
        order_num: 1,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q01.jpg',
        audio_url: null,
        option_a: 'アイオン',
        option_b: 'マロン',
        option_c: 'アイロン',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'アイロン (Iron / ඉස්තිරික්කය).'
      },
      {
        order_num: 2,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q02.jpg',
        audio_url: null,
        option_a: 'そうじ',
        option_b: 'そうじき',
        option_c: 'そうじぎ',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'そうじき (Vacuum cleaner / වැකියුම් ක්ලීනර්).'
      },
      {
        order_num: 3,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q03.jpg',
        audio_url: null,
        option_a: 'かおをそうじします',
        option_b: 'かおをあつめます',
        option_c: 'かおをあらいます',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'かおをあらいます (Wash face / මුහුණ සෝදනවා).'
      },
      {
        order_num: 4,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、【　】に何を入れますか。一番いいものを一つ選んでください。\n\n朝、顔を洗って、【＿＿＿】。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q04.jpg',
        audio_url: null,
        option_a: 'せんたくします',
        option_b: 'ひげをそります',
        option_c: 'ひげをきります',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ひげをそります (Shave beard / රැවුල කපනවා/බානවා).'
      },
      {
        order_num: 5,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q05.jpg',
        audio_url: null,
        option_a: 'さどう',
        option_b: 'さとう',
        option_c: 'ざどう',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'さどう (Tea ceremony / තේ උත්සව කලාව).'
      },
      {
        order_num: 6,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、【　】に何を入れますか。一番いいものを一つ選んでください。\n\nホワイトさんは4月に日本の大学に【＿＿＿】しました。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q06.jpg',
        audio_url: null,
        option_a: 'りゅうがく',
        option_b: 'にゅういん',
        option_c: 'そつぎょう',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'りゅうがく (Study abroad / විදේශ අධ්‍යාපනය).'
      },
      {
        order_num: 7,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、【　】に何を入れますか。一番いいものを一つ選んでください。\n\n私の【＿＿＿】は本を読むことです。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q07.jpg',
        audio_url: null,
        option_a: 'しゅみ',
        option_b: 'しゅうかん',
        option_c: 'しゅうまつ',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'しゅみ (Hobby / විනෝදාංශය).'
      },
      {
        order_num: 8,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、【　】に何を入れますか。一番いいものを一つ選んでください。\n\nきれいな【＿＿＿】ですね。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q08.jpg',
        audio_url: null,
        option_a: 'おと',
        option_b: 'かお',
        option_c: 'こえ',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'こえ (Voice / කටහඬ).'
      },
      {
        order_num: 9,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、【　】に何を入れますか。一番いいものを一つ選んでください。\n\n日曜日に【＿＿＿】のれんしゅうをします。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q09.jpg',
        audio_url: null,
        option_a: 'カメラ',
        option_b: 'ドライブ',
        option_c: 'ゴルフ',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ゴルフ (Golf / ගොල්ෆ් ක්‍රීඩාව).'
      },
      {
        order_num: 10,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、【　】に何を入れますか。一番いいものを一つ選んでください。\n\nこうさてんの【＿＿＿】が赤のときは、止まらなければなりません。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q10.jpg',
        audio_url: null,
        option_a: 'しごうき',
        option_b: 'しんこうき',
        option_c: 'しんごうき',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'しんごうき (Traffic light / රථවාහන සංඥා ලාම්පුව).'
      },
      {
        order_num: 11,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線の言葉は漢字でどう書きますか。一番いいものを一つ選んでください。\n\nこれは日本の【かんじ】です。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q11.jpg',
        audio_url: null,
        option_a: '感じ',
        option_b: '漢字',
        option_c: '漢学',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '漢字 (かんじ - Kanji characters / කන්ජි අක්ෂර).'
      },
      {
        order_num: 12,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線の言葉は漢字でどう書きますか。一番いいものを一つ選んでください。\n\n週末、友達の家に【あそびに】行きました。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q12.jpg',
        audio_url: null,
        option_a: '族び',
        option_b: '遊び',
        option_c: '笑び',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '遊び (あそび - Play / visit / විනෝද වීම/සෙල්ලම් කිරීම).'
      },
      {
        order_num: 13,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線の言葉は漢字でどう書きますか。一番いいものを一つ選んでください。\n\n家族と一緒に【しょくじ】をしました。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q13.jpg',
        audio_url: null,
        option_a: '食事',
        option_b: '仕事',
        option_c: '食堂',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '食事 (しょくじ - Meal / ආහාර වේල).'
      },
      {
        order_num: 14,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線の言葉は漢字でどう書きますか。一番いいものを一つ選んでください。\n\n田中さんは私の【しんゆう】です。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q14.jpg',
        audio_url: null,
        option_a: '新有',
        option_b: '新友',
        option_c: '親友',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '親友 (しんゆう - Best friend / හොඳම මිතුරා).'
      },
      {
        order_num: 15,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線の言葉は漢字でどう書きますか。一番いいものを一つ選んでください。\n\n日本での【せいかつ】にもう慣れました。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q15.jpg',
        audio_url: null,
        option_a: '生活',
        option_b: '先活',
        option_c: '制活',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '生活 (せいかつ - Life / Living / ජීවිතය).'
      },

      // ==========================================
      // SECTION 2: Conversation & Expression (会話・表現 - Q16 to Q30)
      // ==========================================
      {
        order_num: 16,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、【　】に何を入れますか。一番いいものを一つ選んでください。\n\n弟は山が好きです。よく山に【＿＿＿】。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q16.jpg',
        audio_url: null,
        option_a: 'のぼります',
        option_b: 'あがります',
        option_c: 'のります',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '山にのぼります (Climb mountain / කඳු නගිනවා).'
      },
      {
        order_num: 17,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、【　】に何を入れますか。一番いいものを一つ選んでください。\n\n大学の授業は朝9時に【＿＿＿】。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q17.jpg',
        audio_url: null,
        option_a: 'つづきます',
        option_b: 'はじまります',
        option_c: 'おきます',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '授業ははじまります (Class begins / පන්තිය ආරම්භ වේ).'
      },
      {
        order_num: 18,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、【　】に何を入れますか。一番いいものを一つ選んでください。\n\nとなりの人のノートを【＿＿＿】もらいました。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q18.jpg',
        audio_url: null,
        option_a: '見て',
        option_b: '見せて',
        option_c: '見ます',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '見せてもらいました (Was shown / පෙන්වා ගත්තා).'
      },
      {
        order_num: 19,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、【　】に何を入れますか。一番いいものを一つ選んでください。\n\n学校の図書館の本は、家に持って【＿＿＿】はできません。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q19.jpg',
        audio_url: null,
        option_a: '帰るよう',
        option_b: '帰ること',
        option_c: '帰ったこと',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '持って帰ることはできません (Cannot take home / ගෙදර ගෙන යා නොහැක).'
      },
      {
        order_num: 20,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、【　】に何を入れますか。一番いいものを一つ選んでください。\n\nこくばんの字が【＿＿＿】人は、前のほうに来てください。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q20.jpg',
        audio_url: null,
        option_a: '見えない',
        option_b: '見られない',
        option_c: '見られる',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '見えない (Cannot see / නොපෙනෙන).'
      },
      {
        order_num: 21,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、【　】に何を入れますか。一番いいものを一つ選んでください。\n\nA:「健康のために何をしていますか。」\nB:「【＿＿＿】、およいだりしています。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q21.jpg',
        audio_url: null,
        option_a: '書いたり',
        option_b: '読んだり',
        option_c: '歩いたり',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '歩いたり、およいだりしています (Walking and swimming / ඇවිදීම සහ පිහිනීම).'
      },
      {
        order_num: 22,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、【　】に何を入れますか。一番いいものを一つ選んでください。\n\nA:「お国はどちらですか。」\nB:「かんこくです。」\nA:「英語は【＿＿＿】。」\nB:「はい、少しなら。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q22.jpg',
        audio_url: null,
        option_a: 'できます',
        option_b: 'できません',
        option_c: 'できますか',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '英語はできますか (Can you speak English? / ඉංග්‍රීසි පුළුවන්ද?).'
      },
      {
        order_num: 23,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '会話を読んで、【　】に何を入れますか。一番いいものを一つ選んでください。\n\nA:「たろうさんは学校のことをうちで話しますか。」\nB:「はい。昨日も先生にさくぶんを【＿＿＿】ことを話していました。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q23.jpg',
        audio_url: null,
        option_a: 'ほめていた',
        option_b: 'ほめられた',
        option_c: 'ほめた',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '先生にさくぶんをほめられた (Was praised by the teacher / ගුරුවරයා විසින් ප්‍රශංසා ලැබූ).'
      },
      {
        order_num: 24,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、【　】に何を入れますか。一番いいものを一つ選んでください。\n\n明日試験が【＿＿＿】勉強しなくてはいけないんです。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q24_25.jpg',
        audio_url: null,
        option_a: 'あるので',
        option_b: 'あっても',
        option_c: 'あったら',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'あるので (Because there is / ඇති නිසා).'
      },
      {
        order_num: 25,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、【　】に何を入れますか。一番いいものを一つ選んでください。\n\n主人は料理を【＿＿＿】のが趣味なんですよ。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q24_25.jpg',
        audio_url: null,
        option_a: 'できる',
        option_b: 'される',
        option_c: 'する',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '料理をするのが趣味 (Cooking is hobby / ඉවුම් පිහුම් කිරීම විනෝදාංශයයි).'
      },
      {
        order_num: 26,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話の【26】に入る最も適切な表現を選んでください。\n\nサンドラ:「ペーターさん、弟さんは【26】。」\nペーター:「はい、日曜日に時々しますよ。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q26_27.jpg',
        audio_url: null,
        option_a: 'サッカーをしますか',
        option_b: 'サッカーをみますか',
        option_c: 'いっしょに行きますか',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'サッカーをしますか (Does he play soccer? / පාපන්දු සෙල්ලම් කරනවාද?).'
      },
      {
        order_num: 27,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話の【27】に入る最も適切な表現を選んでください。\n\nサンドラ:「今度の日曜日のしあいは【27】。」\nペーター:「午前10時からです。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q26_27.jpg',
        audio_url: null,
        option_a: '何時ですか',
        option_b: '何時にはじまりますか',
        option_c: '何時間ですか',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '何時ですか (What time is it? / වේලාව කීයටද?).'
      },
      {
        order_num: 28,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'カフェでの会話の【28】に入る表現を選んでください。\n\nケン:「ちょっと疲れたから、あそこのカフェでお茶でも飲まない？」\nりさ:「【28】。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q28_30.jpg',
        audio_url: null,
        option_a: 'はい、そうしましょう',
        option_b: 'いいえ、今はちょっと',
        option_c: 'はい、かえりましょう',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'はい、そうしましょう (Yes, let\'s do that / ඔව්, එසේ කරමු).'
      },
      {
        order_num: 29,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'カフェでの会話の【29】に入る表現を選んでください。\n\n店員:「いらっしゃいませ。ご注文は【29】。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q28_30.jpg',
        audio_url: null,
        option_a: 'すみません',
        option_b: '何にしますか',
        option_c: 'どうしますか',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '何にしますか (What would you like? / මොනවාද ලබා ගන්නේ?).'
      },
      {
        order_num: 30,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: 'カフェでの会話の【30】に入る表現を選んでください。\n\n店員:「かしこまりました。【30】。」',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q28_30.jpg',
        audio_url: null,
        option_a: 'しょうしょうおまちください',
        option_b: 'ありがとうございます',
        option_c: 'しつれいします',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'しょうしょうおまちください (Please wait a moment / මඳක් රැඳී සිටින්න).'
      },

      // ==========================================
      // SECTION 3: LISTENING COMPREHENSION (聴解 - Choukai - Q31 to Q45)
      // ==========================================
      {
        order_num: 31,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '男の人は冷蔵庫に何を入れますか。(What does the man put in the fridge?)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q31.jpg',
        audio_url: '/uploads/audio/jft09_q31.mp3',
        option_a: 'くだもの',
        option_b: 'ビール',
        option_c: 'くだもの・ビール',
        option_d: 'くだもの・ビール・おかし',
        correct_option: 'C',
        marks: 5,
        explanation: 'くだもの・ビール (Fruits and beer / පළතුරු සහ බියර්).'
      },
      {
        order_num: 32,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '学生は何をしますか。(What does the student do?)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q32.jpg',
        audio_url: '/uploads/audio/jft09_q32.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'B',
        marks: 5,
        explanation: '2 (2 වන රූපය).'
      },
      {
        order_num: 33,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '写真はどれですか。(What is the photo?)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q33.jpg',
        audio_url: '/uploads/audio/jft09_q33.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'C',
        marks: 5,
        explanation: '3 (3 වන ඡායාරූපය).'
      },
      {
        order_num: 34,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '今月のカレンダーはどれですか。(Which is this month\'s calendar?)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q34.jpg',
        audio_url: '/uploads/audio/jft09_q34.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'A',
        marks: 5,
        explanation: '1 (1 වන දින දර්ශනය).'
      },
      {
        order_num: 35,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '男の人はどの本を取りますか。(Which book does the man take?)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q35.jpg',
        audio_url: '/uploads/audio/jft09_q35.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'D',
        marks: 5,
        explanation: '4 (4 වන පොත).'
      },
      {
        order_num: 36,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: 'お母さんは何をあげましたか。(What did mother give?)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q36.jpg',
        audio_url: '/uploads/audio/jft09_q36.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'B',
        marks: 5,
        explanation: '2 (2 වන තෑග්ග).'
      },
      {
        order_num: 37,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '学生は明日何を持ってきますか。(What will the students bring tomorrow?)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft09_q37.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'C',
        marks: 5,
        explanation: '3 (3 වන විකල්පය).'
      },
      {
        order_num: 38,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '女の子はどの財布を買いましたか。(Which wallet did the girl buy?)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q38.jpg',
        audio_url: '/uploads/audio/jft09_q38.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'B',
        marks: 5,
        explanation: '2 (2 වන මුදල් පසුම්බිය).'
      },
      {
        order_num: 39,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '女の人の国は今何時ですか。(What time is the woman\'s country now?)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft09_q39.mp3',
        option_a: '午前8時50分',
        option_b: '午後8時50分',
        option_c: '午前8時15分',
        option_d: '午後8時15分',
        correct_option: 'A',
        marks: 5,
        explanation: '午前8時50分 (8:50 AM / උදෑසන 8:50).'
      },
      {
        order_num: 40,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '女の人はいつ荷物を受け取りますか。(When does the woman receive the luggage?)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft09_q40.mp3',
        option_a: '明日の午前',
        option_b: '明日の午後',
        option_c: 'あさっての午前',
        option_d: 'あさっての午後',
        correct_option: 'B',
        marks: 5,
        explanation: '明日の午後 (Tomorrow afternoon / හෙට සවස).'
      },
      {
        order_num: 41,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '学生は先生に何をどうやって送りますか。(What and how do students send to their teachers?)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q41.jpg',
        audio_url: '/uploads/audio/jft09_q41.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'A',
        marks: 5,
        explanation: '1 (1 වන ක්‍රමය).'
      },
      {
        order_num: 42,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '男の人の町で今いちばん有名なものはどれですか。(Which is the most famous in man\'s town right now?)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q42.jpg',
        audio_url: '/uploads/audio/jft09_q42.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'C',
        marks: 5,
        explanation: '3 (3 වන ප්‍රසිද්ධ ස්ථානය/දෙය).'
      },
      {
        order_num: 43,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '女の人は今日何をしますか。正しい順番を選んでください。(What does woman do today? Choose the correct order.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q43.jpg',
        audio_url: '/uploads/audio/jft09_q43.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'B',
        marks: 5,
        explanation: '2 (2 වන පිළිවෙළ).'
      },
      {
        order_num: 44,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '女の人は何をしましたか。(What did the woman do?)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_q44.jpg',
        audio_url: '/uploads/audio/jft09_q44.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'A',
        marks: 5,
        explanation: '1 (1 වන ක්‍රියාව).'
      },
      {
        order_num: 45,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '男の人は今日何をしてはいけませんか。(What should man not do today?)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft09_q45.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'C',
        marks: 5,
        explanation: '3 (3 වන තහනම් ක්‍රියාව).'
      },

      // ==========================================
      // SECTION 4: READING COMPREHENSION (読解 - Dokkai - Q46 to Q60)
      // ==========================================
      {
        order_num: 46,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【46/47/48 共通問題】文章を読んで、質問に答えてください。\n\nおばあちゃんは天気がいいときどこへ行きますか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_passage_46_48.jpg',
        audio_url: null,
        option_a: '友達のあうために友達に家へ行きます',
        option_b: '友達のあうために病院へ行きます',
        option_c: '友達のあうために私のうちに来ます',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '友達のあうために病院へ行きます (Goes to hospital to meet friends / මිතුරන් හමුවීමට රෝහලට යයි).'
      },
      {
        order_num: 47,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'おばあちゃんは天気が悪いときどこへも行きません。どうしてですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_passage_46_48.jpg',
        audio_url: null,
        option_a: 'かぜがひくかもしれないので',
        option_b: 'その時友達が病院にいないので',
        option_c: 'あしのちょうしぎがよくないので',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'あしのちょうしがよくないので (Because legs/feet are not in good condition / පාදයේ අපහසුතාවය නිසා).'
      },
      {
        order_num: 48,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'おばあちゃんは私のうちに来たときどうしますか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_passage_46_48.jpg',
        audio_url: null,
        option_a: '古い日本の話をしたり、おかしを作ったりします',
        option_b: 'おどいたり、話したりします',
        option_c: 'あそんだり、料理を作ったりします',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '古い日本の話をしたり、おかしを作ったりします (Tells old Japanese stories and makes sweets / පැරණි කතා කීම හා රසකැවිලි සෑදීම).'
      },
      {
        order_num: 49,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【49/50 共通問題】文章を読んで、質問に答えてください。\n\nキャプテン・クックはカンガルーをどこで見ましたか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_passage_49_50.jpg',
        audio_url: null,
        option_a: 'イギリス',
        option_b: 'ドイツ',
        option_c: 'オーストラリア―',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'オーストラリア (Australia / ඕස්ට්‍රේලියාව).'
      },
      {
        order_num: 50,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'カンガルーと言うのはオーストラリアの言葉でどう言う意味ですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_passage_49_50.jpg',
        audio_url: null,
        option_a: '私はしっています',
        option_b: '私は知っていません',
        option_c: '私はつくります',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '私は知っていません (I don\'t know / මම දන්නේ නෑ).'
      },
      {
        order_num: 51,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【51/52 共通問題】文章を読んで、質問に答えてください。\n\nここにあっていないものはどれか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_passage_51_52.jpg',
        audio_url: null,
        option_a: '富士山は日本でいちばん高いやまです',
        option_b: '七月と九月だけ富士山にのぼることができます',
        option_c: '富士山は冬でも夏でも山のちょうじょうに雪があります',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '富士山は冬でも夏でも山のちょうじょうに雪があります (3 වන ප්‍රකාශය වැරදිය. ගිම්හානයේ හිම නොමැත).'
      },
      {
        order_num: 52,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '人がいつ富士山の絵を書くのですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_passage_51_52.jpg',
        audio_url: null,
        option_a: 'かつしかほくさいさんは富士山の赤い絵を書いたとき',
        option_b: 'いい天気のために夏と秋に午前中富士山が赤くなるとき',
        option_c: '人が夏と秋に写真をたくさんとるとき',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'いい天気のために夏と秋に午前中富士山が赤くなるとき (ගිම්හාන හා සරත් සමයේ උදෑසන ෆුජි කන්ද රතු පැහැ වන විට).'
      },
      {
        order_num: 53,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【53/54/55 共通問題】文章を読んで、質問に答えてください。\n\nジェーンさんとはるこさんはデパートについてから、まず何階に行きましたか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_passage_53_55.jpg',
        audio_url: null,
        option_a: '2階',
        option_b: '4階',
        option_c: '6階',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '6階 (6th floor / 6 වන මහල).'
      },
      {
        order_num: 54,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'ジェーンさんとはるこさんはバーゲンセールで何を買いましたか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_passage_53_55.jpg',
        audio_url: null,
        option_a: 'ジェーンさんは白いバッグ、Tシャツとはるこさんは手紙セット、ハンカチ',
        option_b: 'はるこさんは白いバッグ、Tシャツとジェーンさんは手紙セット、ハンカチ',
        option_c: 'はるこさんはフランスパンとジェーンさんはおせんべい',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ジェーンさんは白いバッグ、Tシャツとはるこさんは手紙セット、ハンカチ.'
      },
      {
        order_num: 55,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'ここにあっていないものはどれか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_passage_53_55.jpg',
        audio_url: null,
        option_a: '6階のバーゲンセールの場所は人でこんでいました',
        option_b: 'バーゲンセールの後二人ののどがかわいていたので紅茶を飲むために行きました',
        option_c: '4階はバーゲンセールの場所のほど人がいっぱいで、うるさいでした',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '4階はバーゲンセールの場所のほど人がいっぱいで、うるさいでした (4 වන මහල සන්සුන් වූ නිසා 3 වන ප්‍රකාශය වැරදිය).'
      },
      {
        order_num: 56,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【56/57/58/59/60 共通問題】正しいものに〇、ちがうものに×を選びなさい。\n\n今、山田さんは奥さんにきゅうりょうをもってかえりません。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_passage_56_60.jpg',
        audio_url: null,
        option_a: '〇',
        option_b: '×',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '〇 (වැටුප කෙලින්ම බැංකුවට වැටෙන බැවින් අතින් රැගෙන නොඑයි).'
      },
      {
        order_num: 57,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '山田さんは駅のちかくのぎんこうへお金を出しに行きます。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_passage_56_60.jpg',
        audio_url: null,
        option_a: '〇',
        option_b: '×',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '〇 (යමදා මහතා දුම්රිය ස්ථානය අසල බැංකුවෙන් මුදල් ලබා ගනී).'
      },
      {
        order_num: 58,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '山田さんの奥さんは家の近くにあるゆうびんきょくで働いています。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_passage_56_60.jpg',
        audio_url: null,
        option_a: '〇',
        option_b: '×',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '× (බිරිඳ තැපැල් කාර්යාලයේ සේවය කරන්නේ නැත).'
      },
      {
        order_num: 59,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '奥さんはぎんこうへガスや電話のりょうきんを払いに行きます。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_passage_56_60.jpg',
        audio_url: null,
        option_a: '〇',
        option_b: '×',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '× (බිරිඳ බිල්පත් ගෙවීමට යන්නේ තැපැල් කාර්යාලයටයි).'
      },
      {
        order_num: 60,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '山田さんの奥さんはゆうびんきょくで何をしますか。1・2・3の中で、いちばんいいものを選びなさい。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft09_passage_56_60.jpg',
        audio_url: null,
        option_a: 'カードでお金を出したりちょきんをしたりします。',
        option_b: 'ガスなどのりょうきんを払ったりちょきんをしたりします。',
        option_c: 'ご主人のきゅうりょうをぜんぶちょきんします。',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ガスなどのりょうきんを払ったりちょきんをしたりします (බිල්පත් ගෙවීම සහ ඉතිරි කිරීම සිදු කරයි).'
      }
    ];

    console.log(`Inserting ${questions.length} questions for JFT Model Paper 09...`);
    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, section_name, question_text, question_type, 
          image_url, audio_url, option_a, option_b, option_c, option_d, 
          correct_option, marks, explanation, order_num
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId, q.section_name, q.question_text, q.question_type,
        q.image_url, q.audio_url, q.option_a, q.option_b, q.option_c, q.option_d,
        q.correct_option, q.marks, q.explanation, q.order_num
      ]);
    }

    console.log(`Successfully seeded all 60 questions for JFT Model Paper 09 (Exam ID: ${examId})`);
  } catch (err) {
    console.error('Error seeding JFT Model Paper 09:', err);
  }
}

module.exports = { seedJftModelPaper09 };
