const { query } = require('../config/database');

async function seedJftModelPaper14() {
  console.log('Seeding JFT-Basic Official Model Paper 14 (60 Questions, Pass 200/250)...');

  try {
    let exam = await query.get("SELECT * FROM exams WHERE id = 153 OR title LIKE '%Model Paper 14%'");
    let examId = 153;

    if (exam) {
      examId = exam.id;
      const countRes = await query.get("SELECT COUNT(*) as count FROM questions WHERE exam_id = ?", [examId]);
      if (countRes && countRes.count >= 60) {
        await query.run('UPDATE exams SET duration_minutes = 60, passing_score = 200, is_active = 1 WHERE id = ?', [examId]);
        await query.run('UPDATE questions SET marks = 1 WHERE exam_id = ? AND order_num >= 1 AND order_num <= 5', [examId]);
        await query.run('UPDATE questions SET marks = 2 WHERE exam_id = ? AND order_num >= 6 AND order_num <= 15', [examId]);
        await query.run('UPDATE questions SET marks = 5 WHERE exam_id = ? AND order_num >= 16 AND order_num <= 60', [examId]);
        return;
      }
      console.log(`Found existing Exam ID: ${examId}, resetting questions...`);
      await query.run('DELETE FROM questions WHERE exam_id = ?', [examId]);
      await query.run(`
        UPDATE exams 
        SET course_id = 1,
            title = 'JFT-Basic Official Model Paper 14 (60 Minutes)',
            description = 'Official JFT-Basic Prometric Computer-Based Examination Paper 14 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Listening Audio Tracks and Sinhala Explanations)',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (id, course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (
          153,
          1,
          'JFT-Basic Official Model Paper 14 (60 Minutes)',
          'Official JFT-Basic Prometric Computer-Based Examination Paper 14 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Listening Audio Tracks and Sinhala Explanations)',
          60,
          200,
          1
        )
      `);
      examId = res.id;
      console.log(`Created new Exam ID: ${examId}`);
    }

    const questions = [
  {
    "order_num": 1,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n桜の木の下でみんなでお弁当を食べている日本の春の行事は何ですか。",
    "image_url": "/images/jft_paper14/jft14_img_01.jpg",
    "audio_url": null,
    "option_a": "はなみ",
    "option_b": "はなび",
    "option_c": "はな",
    "option_d": "",
    "correct_option": "A",
    "marks": 1,
    "explanation": "චෙරි මල් පිපෙන කාලයේ මල් නැරඹීම සඳහා කරන විනෝද චාරිකාව ජපන් බසින් \"はなみ (Hanami / 花見)\" වේ."
  },
  {
    "order_num": 2,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n甘いあんこが入った日本の伝統的なお菓子は何ですか。",
    "image_url": "/images/jft_paper14/jft14_img_02.jpg",
    "audio_url": null,
    "option_a": "まんじゅう",
    "option_b": "パン",
    "option_c": "りんご",
    "option_d": "",
    "correct_option": "A",
    "marks": 1,
    "explanation": "ජපන් සාම්ප්‍රදායික පැණි රස කෑමක් වන බනිස් වර්ගය \"まんじゅう (Manju / 饅頭)\" වේ."
  },
  {
    "order_num": 3,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n赤くて丸いこの野菜はカタカナでどう書きますか。",
    "image_url": "/images/jft_paper14/jft14_img_03.jpg",
    "audio_url": null,
    "option_a": "トマド",
    "option_b": "トマート",
    "option_c": "トマト",
    "option_d": "",
    "correct_option": "C",
    "marks": 1,
    "explanation": "තක්කාලි සඳහා නිවැරදි කටකනා වචනය \"トマト (Tomato)\" වේ."
  },
  {
    "order_num": 4,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n日本のとても速い特急電車は何ですか。",
    "image_url": "/images/jft_paper14/jft14_img_04.jpg",
    "audio_url": null,
    "option_a": "しんかんせん",
    "option_b": "でんしゃ",
    "option_c": "きしゃ",
    "option_d": "",
    "correct_option": "A",
    "marks": 1,
    "explanation": "ජපානයේ අධිවේගී බුලට් දුම්රිය \"しんかんせん (Shinkansen / 新幹線)\" වේ."
  },
  {
    "order_num": 5,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n体を動かして運動をしている様子は何ですか。",
    "image_url": "/images/jft_paper14/jft14_img_05.jpg",
    "audio_url": null,
    "option_a": "ジャンプ",
    "option_b": "ジョギングをします",
    "option_c": "たいそうをします",
    "option_d": "",
    "correct_option": "C",
    "marks": 1,
    "explanation": "ශාරීරික අභ්‍යාස හෝ ජිම්නාස්ටික් කිරීම \"たいそうをします (Taisou o shimasu / 体操をします)\" වේ."
  },
  {
    "order_num": 6,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "彼はお金が ＿＿＿＿＿＿＿＿ でしょう。",
    "image_url": null,
    "audio_url": null,
    "option_a": "あります",
    "option_b": "ある",
    "option_c": "ありません",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "「〜でしょう」ඉදිරියට සාමාන්‍ය ක්‍රියාපදයේ Plain form (Dictionary form) එක වන \"ある\" යෙදේ (あるでしょう)."
  },
  {
    "order_num": 7,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "母の大切なかびんを ＿＿＿＿＿＿＿＿ しまいました。",
    "image_url": null,
    "audio_url": null,
    "option_a": "こわしました",
    "option_b": "こわす",
    "option_c": "こわして",
    "option_d": "",
    "correct_option": "C",
    "marks": 2,
    "explanation": "අත්වැරැද්දකින් සිදුවූ දෙයක් ප්‍රකාශ කිරීමට Te-form + しまいました භාවිතා කරයි (こわしてしまいました)."
  },
  {
    "order_num": 8,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "来月のはじめに家を出て、一人で ＿＿＿＿＿＿＿＿ つもりです。",
    "image_url": null,
    "audio_url": null,
    "option_a": "住みます",
    "option_b": "住む",
    "option_c": "住んでいます",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "අදහසක් හෝ සැලසුමක් ප්‍රකාශ කරන「〜つもりです」ඉදිරියට Dictionary form එක වන \"住む\" යෙදේ (住むつもりです)."
  },
  {
    "order_num": 9,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "7月には北海道へ ＿＿＿＿＿＿＿＿ よていです。",
    "image_url": null,
    "audio_url": null,
    "option_a": "行きます",
    "option_b": "行きました",
    "option_c": "行く",
    "option_d": "",
    "correct_option": "C",
    "marks": 2,
    "explanation": "සැලසුම් ප්‍රකාශ කරන「〜よていです (予定です)」ඉදිරියට Dictionary form එක වන \"行く\" යෙදේ (行く予定です)."
  },
  {
    "order_num": 10,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "明日からスキーに行きます。1週間 ＿＿＿＿＿＿＿＿ んです。",
    "image_url": null,
    "audio_url": null,
    "option_a": "休み",
    "option_b": "休みな",
    "option_c": "休みます",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "නාම පදයක් හෝ な-විශේෂණයක් සමග「〜んです」යෙදීමේදී \"な\" සම්බන්ධ වේ (名詞＋なんです → 休みな＋んです)."
  },
  {
    "order_num": 11,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "下線の漢字はどう読みますか。\n<u>右</u>と<u>左</u>をよく見て道をわたりましょう。",
    "image_url": null,
    "audio_url": null,
    "option_a": "ひだり・みぎ",
    "option_b": "くち・みぎ",
    "option_c": "みぎ・ひだり",
    "option_d": "",
    "correct_option": "C",
    "marks": 2,
    "explanation": "「右」යනු みぎ (Migi) වන අතර「左」යනු ひだり (Hidari) වේ. එබැවින් \"みぎ・ひだり\" නිවැරදි වේ."
  },
  {
    "order_num": 12,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "下線の漢字はどう読みますか。\nひとつめのかどをまがります。<u>赤い</u>はしがあります。",
    "image_url": null,
    "audio_url": null,
    "option_a": "あおい",
    "option_b": "あかい",
    "option_c": "しろい",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "「赤い」කන්ජි කියවීම \"あかい (Akai - රතු)\" වේ."
  },
  {
    "order_num": 13,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "下線の漢字はどう読みますか。\nこの<u>通り</u>に白いビルが二つあります。",
    "image_url": null,
    "audio_url": null,
    "option_a": "とおり",
    "option_b": "みち",
    "option_c": "どうろ",
    "option_d": "",
    "correct_option": "A",
    "marks": 2,
    "explanation": "「通り」කන්ජි කියවීම \"とおり (Toori - මාවත/පාර)\" වේ."
  },
  {
    "order_num": 14,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "下線の漢字はどう読みますか。\n<u>青い</u>ビルの前でアイスクリームを食べました。",
    "image_url": null,
    "audio_url": null,
    "option_a": "あかい",
    "option_b": "しろい",
    "option_c": "あおい",
    "option_d": "",
    "correct_option": "C",
    "marks": 2,
    "explanation": "「青い」කන්ජි කියවීම \"あおい (Aoi - නිල් පැහැති)\" වේ."
  },
  {
    "order_num": 15,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "下線の漢字はどう読みますか。\n<u>黒い</u>タクシーにのりました。",
    "image_url": null,
    "audio_url": null,
    "option_a": "くろい",
    "option_b": "くらい",
    "option_c": "しろい",
    "option_d": "",
    "correct_option": "A",
    "marks": 2,
    "explanation": "「黒い」කන්ජි කියවීම \"くろい (Kuroi - කළු පැහැති)\" වේ."
  },
  {
    "order_num": 16,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "あそこにきれいなたてものが ＿＿＿＿＿＿＿＿。",
    "image_url": null,
    "audio_url": null,
    "option_a": "見せます",
    "option_b": "見て",
    "option_c": "見えます",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ස්වභාවිකව හෝ ඉබේම ඇසට පෙනෙන දෙයක් සඳහා「〜が見えます (Mie masu)」භාවිතා වේ."
  },
  {
    "order_num": 17,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "ふじさんはとても(17)＿＿＿＿＿＿＿＿、ここからちょっと(18)＿＿＿＿＿＿＿＿。",
    "image_url": null,
    "audio_url": null,
    "option_a": "きれいな",
    "option_b": "きれいに",
    "option_c": "きれいだけど",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "විරුද්ධ අදහස් දෙකක් සම්බන්ධ කිරීමේදී (ලස්සන වුවත් දුරයි)「〜だけど」යොදා ගනී (きれいだけど)."
  },
  {
    "order_num": 18,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "ふじさんはとても(17)きれいだけど、ここからちょっと(18)＿＿＿＿＿＿＿＿。",
    "image_url": null,
    "audio_url": null,
    "option_a": "とおい",
    "option_b": "とおく",
    "option_c": "とおき",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "වාක්‍ය අවසානයේ plain i-adjective එකක් ලෙස \"とおい (Tooi - දුරයි)\" යෙදේ."
  },
  {
    "order_num": 19,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "このとおりはいい店がおおいけど夜 ＿＿＿＿＿＿＿＿。私はあまり行きたくないです。",
    "image_url": null,
    "audio_url": null,
    "option_a": "あかるいです",
    "option_b": "くらいです",
    "option_c": "くろいです",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "රාත්‍රී කාලයේදී අඳුරු බව හැඟවීමට \"くらいです (Kurai desu - අඳුරුයි)\" යෙදේ."
  },
  {
    "order_num": 20,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "東京のうえの ＿＿＿＿＿＿＿＿ しんじゅくなど大きい町がたくさんあります。",
    "image_url": null,
    "audio_url": null,
    "option_a": "に",
    "option_b": "や",
    "option_c": "が",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "උදාහරණ ලැයිස්තුගත කිරීමේදී「A や B など (A සහ B වැනි)」සඳහා \"や\" නිපාතය යෙදේ."
  },
  {
    "order_num": 21,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで正しいものを選びなさい】\nA: すみません、サクラぎんこうは(21)＿＿＿＿＿＿＿＿。\nB: サクラぎんこうはこの通りをまっすぐ行って、ひとつめのしんごうを右にまがってください。",
    "image_url": null,
    "audio_url": null,
    "option_a": "どうろですか",
    "option_b": "どのですか",
    "option_c": "どこですか",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ස්ථානයක් කොහේදැයි විමසීමට \"どこですか (Doko desu ka)\" භාවිතා කරයි."
  },
  {
    "order_num": 22,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで正しいものを選びなさい】\nA: (22)＿＿＿＿＿＿＿＿、右ですね。\nB: はいそうです。まっすぐ行って右にまがります。",
    "image_url": null,
    "audio_url": null,
    "option_a": "まっすぐ行く",
    "option_b": "まっすぐ行かないで",
    "option_c": "まっすぐ行って",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ක්‍රියා දෙකක් අනුපිළිවෙලින් දැක්වීමේදී Te-form එක වන \"まっすぐ行って (Straight gihin)\" යෙදේ."
  },
  {
    "order_num": 23,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで正しいものを選びなさい】\nカーラ: 金曜日の食事、まちあわせの時間はどうしますか。\nやまだ: 6時はどうですか。\nカーラ: すみません、(23)＿＿＿＿＿＿＿＿。。。6時半でもいいですか。",
    "image_url": null,
    "audio_url": null,
    "option_a": "6時はだいじょうぶです",
    "option_b": "6時はいいです",
    "option_c": "6時はちょっと",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "යෝජනාවක් ආචාරශීලීව ප්‍රතික්ෂේප කිරීමේදී「〜はちょっと… (අපහසුයි/ටිකක් අමාරුයි)」යෙදේ."
  },
  {
    "order_num": 24,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで正しいものを選びなさい】\nやまだ: ええ、いいですよ。じゃ、6時半にレストランの入り口で(24)＿＿＿＿＿＿＿＿。",
    "image_url": null,
    "audio_url": null,
    "option_a": "あいましょう",
    "option_b": "あいます",
    "option_c": "あいません",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "යෝජනාවකට එකඟ වෙමින් \"හමුවෙමු\" යැයි කීමට Volitional/Invitation form එක වන「〜ましょう (あいましょう)」යෙදේ."
  },
  {
    "order_num": 25,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで正しいものを選びなさい】\nカーラ: ああ、服はジーンズでもいいですか。\nやまだ: ええ、(25)＿＿＿＿＿＿＿＿。",
    "image_url": null,
    "audio_url": null,
    "option_a": "たいへんです",
    "option_b": "わるいです",
    "option_c": "だいじょうぶです",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ජීන්ස් ඇඳීම ගැටලුවක් නොවන බව තහවුරු කිරීමට \"だいじょうぶです (Daijoubu desu / ප්‍රශ්නයක් නෑ)\" යෙදේ."
  },
  {
    "order_num": 26,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【電話の会話】\nA: (26)＿＿＿＿＿＿＿＿、田中さんですか。\nB: はい、ああ、カーラさん。",
    "image_url": "/images/jft_paper14/jft14_img_06.jpg",
    "audio_url": null,
    "option_a": "もうしもうし",
    "option_b": "もうしわけもし",
    "option_c": "もしもし",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "දුරකථනයට පිළිතුරු දීමේදී ආරම්භක ආචාර වචනය \"もしもし (Moshi moshi - හෙලෝ)\" වේ."
  },
  {
    "order_num": 27,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【電話の会話】\nA: すみません。15分ぐらいおくれます。ちょっと(27)＿＿＿＿＿＿＿＿。\nB: だいじょうぶですか。じゃ、またあとで。",
    "image_url": "/images/jft_paper14/jft14_img_06.jpg",
    "audio_url": null,
    "option_a": "道にわたります",
    "option_b": "道にまよって",
    "option_c": "道にいます",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "පාර අතරමං වූ බව හේතුවක් ලෙස දැක්වීමට Te-form එක වන「道にまよって (Michi ni mayotte)」යෙදේ."
  },
  {
    "order_num": 28,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで答えなさい】\nA: キムさん、もうびじゅつかんに行きましたか。\nB: はい、(28)＿＿＿＿＿＿＿＿。",
    "image_url": null,
    "audio_url": null,
    "option_a": "行きません",
    "option_b": "行きました",
    "option_c": "行きます",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "පසුගිය කාලීන ප්‍රශ්නයකට \"ඔව්, ගියා\" ලෙස පිළිතුරු දීමට \"行きました (Ikimashita)\" යෙදේ."
  },
  {
    "order_num": 29,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで答えなさい】\nA: どうでしたか。\nB: 山の絵がとても(29)＿＿＿＿＿＿＿＿。",
    "image_url": null,
    "audio_url": null,
    "option_a": "よくないです",
    "option_b": "よくなかったです",
    "option_c": "よかったです",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "පසුගිය අත්දැකීම හොඳ බව ප්‍රකාශ කිරීමට「よかったです (Yokatta desu - ගොඩක් හොඳයි)」යෙදේ."
  },
  {
    "order_num": 30,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで答えなさい】\nA: そうですか。ホセさんはもう行きましたか。\nC: いいえ、(30)＿＿＿＿＿＿＿＿。私も行ってみたいです。",
    "image_url": null,
    "audio_url": null,
    "option_a": "まだです",
    "option_b": "もうです",
    "option_c": "いいです",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "තවමත් කර නොමැති දෙයක් සඳහා「いいえ、まだです (නැහැ, තවම නෑ)」යෙදේ."
  },
  {
    "order_num": 31,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて答えなさい】\nエドワードさんはだれですか。",
    "image_url": null,
    "audio_url": "/audio/jft_paper14/jft14_q31.mp3",
    "option_a": "ひしょ",
    "option_b": "じむのスタッフ",
    "option_c": "しゃちょう",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩය අනුව එඩ්වඩ් කාර්යාල කාර්ය මණ්ඩල සාමාජිකයෙකි (じむのスタッフ - Office staff)."
  },
  {
    "order_num": 32,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて答えなさい】\nナターリヤさんはだれですか。",
    "image_url": null,
    "audio_url": "/audio/jft_paper14/jft14_q32.mp3",
    "option_a": "ひしょ",
    "option_b": "しゃちょう",
    "option_c": "うけつけの人",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩය අනුව නටාලියා පිළිගැනීමේ නිලධාරිනියයි (うけつけの人 - Receptionist)."
  },
  {
    "order_num": 33,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて答えなさい】\nハリードさんはだれですか。",
    "image_url": "/images/jft_paper14/jft14_img_07.jpg",
    "audio_url": "/audio/jft_paper14/jft14_q33.mp3",
    "option_a": "しゃちょう",
    "option_b": "じむのスタッフ",
    "option_c": "ドライバー",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩය අනුව හලීඩ් රියදුරෙකි (ドライバー - Driver)."
  },
  {
    "order_num": 34,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて正しい絵を選んでください】\n(a: パソコン / b: ファックス / c: コピーき / d: でんわ)",
    "image_url": "/images/jft_paper14/jft14_img_08.jpg",
    "audio_url": "/audio/jft_paper14/jft14_q34.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "d",
    "correct_option": "A",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩයේ සඳහන් උපකරණය පරිගණකය (パソコン - a) වේ."
  },
  {
    "order_num": 35,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて正しい絵を選んでください】\n(a: パソコン / b: ファックス / c: コピーき / d: でんわ)",
    "image_url": null,
    "audio_url": "/audio/jft_paper14/jft14_q35.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "d",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩයේ සඳහන් උපකරණය ෆොටෝකොපි යන්ත්‍රය (コピー機 - c) වේ."
  },
  {
    "order_num": 36,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて正しい絵を選んでください】\n(a: パソコン / b: ファックス / c: コピーき / d: でんわ)",
    "image_url": "/images/jft_paper14/jft14_img_09.jpg",
    "audio_url": "/audio/jft_paper14/jft14_q36.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "d",
    "correct_option": "D",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩයේ සඳහන් උපකරණය දුරකථනය (でんわ - d) වේ."
  },
  {
    "order_num": 37,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて正しい絵を選んでください】\n(a: パソコン / b: ファックス / c: コピーき / d: でんわ)",
    "image_url": null,
    "audio_url": "/audio/jft_paper14/jft14_q37.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "d",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩයේ සඳහන් උපකරණය ෆැක්ස් යන්ත්‍රය (ファックス - b) වේ."
  },
  {
    "order_num": 38,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて正しい場所を選びなさい】\nまりさんは体のどこが痛いですか。(a: あたま / b: かた / c: こし / d: くび)",
    "image_url": "/images/jft_paper14/jft14_img_10.jpg",
    "audio_url": "/audio/jft_paper14/jft14_q38_q40.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "d",
    "correct_option": "A",
    "marks": 5,
    "explanation": "මාරිගේ හිස කැක්කුම (あたま - a) ගැන ශ්‍රව්‍ය ඛණ්ඩයේ සාකච්ඡා වේ."
  },
  {
    "order_num": 39,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて正しい場所を選びなさい】\nのださんは体のどこが痛いですか。(a: あたま / b: かた / c: こし / d: くび)",
    "image_url": "/images/jft_paper14/jft14_img_11.jpg",
    "audio_url": "/audio/jft_paper14/jft14_q38_q40.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "d",
    "correct_option": "C",
    "marks": 5,
    "explanation": "නොඩා මහතාගේ කොන්දේ වේදනාව (こし - c) ගැන සඳහන් වේ."
  },
  {
    "order_num": 40,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて正しい場所を選びなさい】\nたなかさんは体のどこが痛いですか。(a: あたま / b: かた / c: こし / d: くび)",
    "image_url": "/images/jft_paper14/jft14_img_12.jpg",
    "audio_url": "/audio/jft_paper14/jft14_q38_q40.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "d",
    "correct_option": "B",
    "marks": 5,
    "explanation": "තනකා මහතාගේ උරහිසේ කැක්කුම (かた - b) ගැන සඳහන් වේ."
  },
  {
    "order_num": 41,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて正しい絵を選びなさい】\n(a: おなかが痛い / b: ねられません / c: つかれています)",
    "image_url": null,
    "audio_url": "/audio/jft_paper14/jft14_q41.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "බඩේ කැක්කුම (おなかが痛い - a) පිළිබඳව ප්‍රකාශ වේ."
  },
  {
    "order_num": 42,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて正しい絵を選びなさい】\n(a: おなかが痛い / b: ねられません / c: つかれています)",
    "image_url": "/images/jft_paper14/jft14_img_13.jpg",
    "audio_url": "/audio/jft_paper14/jft14_q42.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "නින්ද නොයෑම (ねられません - b) පිළිබඳව ශ්‍රව්‍ය ඛණ්ඩයේ සඳහන් වේ."
  },
  {
    "order_num": 43,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて正しい絵を選びなさい】\n(a: おなかが痛い / b: ねられません / c: つかれています)",
    "image_url": null,
    "audio_url": "/audio/jft_paper14/jft14_q43.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "මහන්සිය (つかれています - c) පිළිබඳව ප්‍රකාශ වේ."
  },
  {
    "order_num": 44,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて正しい絵を選びなさい】\n(a: おなかが痛い / b: ねられません / c: つかれています)",
    "image_url": null,
    "audio_url": "/audio/jft_paper14/jft14_q44_q45.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "වෙහෙසට පත්වීම (つかれています - c) පිළිබඳව සඳහන් වේ."
  },
  {
    "order_num": 45,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聞いて答えなさい】\nつかれているとき何をしたほうがいいですか。",
    "image_url": "/images/jft_paper14/jft14_img_15.jpg",
    "audio_url": "/audio/jft_paper14/jft14_q44_q45.mp3",
    "option_a": "薬をのむ",
    "option_b": "お風呂に入る",
    "option_c": "おんがくを聞く",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "මහන්සි වූ විට උණුසුම් ස්නානය කිරීම (お風呂に入る) වඩාත් යහපත් බව ශ්‍රව්‍ය ඛණ්ඩයේ උපදෙස් දෙයි."
  },
  {
    "order_num": 46,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【スマホのメッセージを読んで答えなさい】\nメッセージ：「すみません！じゅうたいです。ちょっとおくれます。」\n\nなぜ彼女は遅れるのですか。",
    "image_url": "/images/jft_paper14/jft14_img_17.jpg",
    "audio_url": null,
    "option_a": "じこがあったので",
    "option_b": "じゅうたいので",
    "option_c": "道にまよいたから",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "පණිවිඩයේ පැහැදිලිවම රථවාහන තදබදය (じゅうたい - Traffic jam) නිසා ප්‍රමාද වන බව දක්වා ඇත."
  },
  {
    "order_num": 47,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【フェスティバルの案内】\nステージ（世界のうたと おどり）：\n10:00〜10:30 タイのダンス\n11:00〜11:30 フランスのうた\n14:00〜14:30 日本語ミニレッスン\n\nダンスを見たい人たちは何時にステージの前に行ったほうがいいですか。",
    "image_url": "/images/jft_paper14/jft14_img_18.jpg",
    "audio_url": null,
    "option_a": "10時",
    "option_b": "11時",
    "option_c": "2時",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "තායි නැටුම් සංදර්ශනය (タイのダンス) ආරම්භ වන්නේ පෙරවරු 10:00 ට (10時) ය."
  },
  {
    "order_num": 48,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【フェスティバルの案内】\n世界の料理ブース：1 韓国料理, 2 ロシア料理, 3 メキシコ料理, 4 ドイツ料理, 5 マレーシア料理\n\nマレーシア料理はどこにありますか。ブース番号を選びなさい。",
    "image_url": "/images/jft_paper14/jft14_img_18.jpg",
    "audio_url": null,
    "option_a": "2",
    "option_b": "3",
    "option_c": "4",
    "option_d": "5",
    "correct_option": "D",
    "marks": 5,
    "explanation": "මැලේසියානු ආහාර ඇත්තේ අංක 5 දරන කුටියේ (5) ය."
  },
  {
    "order_num": 49,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【フェスティバルの案内】\n民芸品・お土産：6 スペイン民芸品, 7 日本茶, 8 フィリピンアクセサリー\n\n木で作ったにんぎょうを買いたいです。どこへいきますか。",
    "image_url": "/images/jft_paper14/jft14_img_18.jpg",
    "audio_url": null,
    "option_a": "6",
    "option_b": "7",
    "option_c": "8",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "සාම්ප්‍රදායික බෝනික්කන් සහ කැටයම් මිලදී ගැනීමට ස්පාඤ්ඤ අත්කම් කුටිය වන අංක 6 (6) වෙත යා යුතුය."
  },
  {
    "order_num": 50,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【フェスティバルの案内】\n日本語を学びたいです。どこへ行きますか。",
    "image_url": "/images/jft_paper14/jft14_img_18.jpg",
    "audio_url": null,
    "option_a": "7のストール",
    "option_b": "2時にステージの前",
    "option_c": "10時にステージの前",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ජපන් භාෂා මිනි පාඩම (日本語ミニレッスン) පැවැත්වෙන්නේ පස්වරු 2:00 (14:00) ට ප්‍රධාන වේදිකාව ඉදිරිපිටදීය."
  },
  {
    "order_num": 51,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【説明に合うのはどれですか】\n「からくて、おいしいです。色は少し赤いです。きゅうりや白菜などの野菜の食べ物です。韓国の食べ物です。日本でとても人気があります。」",
    "image_url": "/images/jft_paper14/jft14_img_19.jpg",
    "audio_url": null,
    "option_a": "トマト",
    "option_b": "さしみ",
    "option_c": "キムチ",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "කොරියානු සැර සහිත පැසුණු එළවළු ආහාරය කිම්චි (キムチ - Kimchi) වේ."
  },
  {
    "order_num": 52,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【文章を読んで答えなさい】\n「私は小さいアパートに住んでいます。先週、となりの部屋に外国の人がひっこしてきました。「彼はアメリカから来ました。留学生ですよ。」とおおやさんが言いました。私は今まで外国人の友達がいませんでした。ですから、私はその人と友達になりたいと思いました。」\n\n私がはじめてマリオさんに会った時、どんなきもちでしたか。",
    "image_url": null,
    "audio_url": null,
    "option_a": "何も話したくないと思っていました。",
    "option_b": "何か話したいと思っていました。",
    "option_c": "朝ではなかったので困りました。",
    "option_d": "いっしょにかいものに行きたいと思っていました。",
    "correct_option": "B",
    "marks": 5,
    "explanation": "මාරියෝ සමඟ මිතුරු වීමට සහ කතා කිරීමට අවශ්‍යව සිටියේය (何か話したいと思っていました)."
  },
  {
    "order_num": 53,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【文章を読んで答えなさい】\n「部屋に帰ってから、明日の朝はグッドモーニングと言いたいと思いました。でも、つぎに会った時は夜でしたから、私は何も言いませんでした。」\n\n私が夜マリオさんに会った時、どんなきもちでしたか。",
    "image_url": null,
    "audio_url": null,
    "option_a": "何も話したくないと思っていました。",
    "option_b": "何か話したいと思っていました。",
    "option_c": "グッドモーニングと練習をしましたが、朝ではなかったので困りました。",
    "option_d": "いっしょにかいものに行きたいと思っていました。",
    "correct_option": "C",
    "marks": 5,
    "explanation": "උදෑසන කීමට Good Morning පුරුදු වුවද රාත්‍රිය වූ නිසා කුමක් කියන්නදැයි අපහසුතාවට පත් විය."
  },
  {
    "order_num": 54,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【文章を読んで答えなさい】\nこの人がどうして小さい声で「グッドモーニング」と言いましたか。",
    "image_url": null,
    "audio_url": null,
    "option_a": "アパートがしずかだったからです",
    "option_b": "かいものに行きたくなかったからです",
    "option_c": "外国の人がなんと言うかしんぱいだったからです",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "විදේශිකයා කුමක් කියයිද යන චකිතය/බිය නිසා හෙමින් කීවේය (外国の人がなんと言うかしんぱいだったからです)."
  },
  {
    "order_num": 55,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【手紙の文章を読んで○か×かを選びなさい】\n「私は高校1年生のとき、ざっしで男子高校生（すずきさん・高3・北海道）を知りました。友達のかずこさんと相談して手紙を書きました。」\n\nかずこさんは私のペンフレンドです。",
    "image_url": null,
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "කසුකෝ යනු ලියුම් ලියූ මිතුරියයි; පෑන් මිතුරා සුසුකි මහතාය. එබැවින් ප්‍රකාශය වැරදිය (×)."
  },
  {
    "order_num": 56,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【手紙の文章を読んで○か×かを選びなさい】\nかずこさんと私のペンフレンドは高校3年生です。",
    "image_url": null,
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "කසුකෝ සහ ලේඛකයා උසස් පෙළ 1 වන වසරේ වන අතර, සුසුකි පමණක් 3 වන වසරේ වේ. එබැවින් වැරදිය (×)."
  },
  {
    "order_num": 57,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【手紙の文章を読んで○か×かを選びなさい】\n「かずこさんの趣味はピアノで私の趣味はテニスでしたが、「私の趣味はピアノとテニスです」と書きました。」\n\n私の趣味はピアノとテニスです。",
    "image_url": null,
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ඇත්ත වශයෙන්ම ලේඛකයාගේ විනෝදාංශය ටෙනිස් පමණි. එබැවින් ප්‍රකාශය වැරදිය (×)."
  },
  {
    "order_num": 58,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【手紙の文章を読んで○か×かを選びなさい】\n「すずきさんは「東京へ大学入学試験を受けに行きます。あなたの写真を送ってください。」と書きました。」\n\nすずきさんは手紙に写真がほしいと書きました。",
    "image_url": null,
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "සුසුකි මහතා ඡායාරූපයක් එවන ලෙස ලියුමේ ඉල්ලා ඇත. එබැවින් ප්‍රකාශය නිවැරදිය (〇)."
  },
  {
    "order_num": 59,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【手紙の文章を読んで○か×かを選びなさい】\n私たちは東京でペンフレンドに会いました。",
    "image_url": null,
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ඔවුන්ට පිළිතුරු ලිපියක් යැවීමට නොහැකි වූ අතර ටෝකියෝවේදී හමුවූයේ නැත. එබැවින් වැරදිය (×)."
  },
  {
    "order_num": 60,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【手紙の文章を読んで正しい文を選びなさい】\n「私たちはへんじを出せませんでした。[ ＿＿＿＿＿＿＿＿ ]」",
    "image_url": null,
    "audio_url": null,
    "option_a": "そして、二人の写真を送りました",
    "option_b": "写真も送りませんでした。",
    "option_c": "「東京で会いましょう。」と書きました。",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "පිළිතුරු ලිපියක් නොයැවූ නිසා ඡායාරූපයද යැව්වේ නැත (写真も送りませんでした)."
  }
];

    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, section_name, order_num, question_text, question_type,
          option_a, option_b, option_c, option_d, correct_option, marks, explanation,
          image_url, audio_url
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId,
        q.section_name,
        q.order_num,
        q.question_text,
        'multiple_choice',
        q.option_a,
        q.option_b,
        q.option_c,
        q.option_d || '',
        q.correct_option,
        q.marks,
        q.explanation,
        q.image_url,
        q.audio_url
      ]);
    }

    console.log(`Successfully seeded ${questions.length} questions for Paper 14 (Exam ${examId})`);
  } catch (err) {
    console.error('Error seeding JFT Paper 14:', err);
  }
}

module.exports = { seedJftModelPaper14 };
