const { query } = require('../config/database');

async function seedJLPTN5Paper04() {
  try {
    console.log('====================================================');
    console.log('Seeding JLPT N5 Official Examination - December 2012 (Paper 04)...');
    console.log('====================================================');

    const course = await query.get("SELECT id, code, name FROM courses WHERE id = 2 OR code = 'JLPT-N5'");
    if (!course) {
      throw new Error("Course JLPT-N5 (ID: 2) not found in database.");
    }
    const courseId = course.id;
    console.log(`Target Course: ${course.name} (ID: ${courseId})`);

    const title = 'JLPT N5 Official Examination - December 2012 (Paper 04)';
    const description = 'Official JLPT N5 Examination from December 2012 (Paper 04). Features all 3 sections: Language Knowledge (Vocabulary), Language Knowledge (Grammar) & Reading, and Listening Comprehension with authentic audio and high-resolution diagrams.';

    // Check if exam record already exists
    let exam = await query.get("SELECT * FROM exams WHERE course_id = ? AND title = ?", [courseId, title]);

    let examId;
    if (exam) {
      examId = exam.id;
      console.log(`Found existing Exam record with ID: ${examId}`);
      await query.run(`
        UPDATE exams
        SET title = ?,
            course_id = ?,
            duration_minutes = 105,
            passing_score = 50,
            total_marks = 180,
            description = ?,
            category = 'JLPT-N5',
            is_active = 1
        WHERE id = ?
      `, [title, courseId, description, examId]);
    } else {
      console.log('Creating new Exam record for Paper 04...');
      const insertResult = await query.run(`
        INSERT INTO exams (course_id, title, duration_minutes, passing_score, total_marks, description, category, is_active)
        VALUES (?, ?, 105, 50, 180, ?, 'JLPT-N5', 1)
      `, [courseId, title, description]);
      examId = insertResult.id;
      console.log(`Created Exam record with ID: ${examId}`);
    }

    const audioTrackUrl = '/audio/n5_paper4_listening.m4a';

    const questionsData = [
      // =========================================================================
      // SECTION 1: 言語知識（文字・語彙） (Q01 to Q35, 1 mark each = 35 marks)
      // =========================================================================
      // 問題１ (Q1-Q12) 漢字読み
      {
        order_num: 1,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 1　＿＿＿の ことばは ひらがなで どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんで ください。\n\nすみません、水を ください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'すい',
        option_b: 'ずい',
        option_c: 'みず',
        option_d: 'みす',
        correct_option: 'C',
        marks: 1,
        explanation: '「水」の訓読みは「みず」です。「すみません、水を ください。」（Excuse me, please give me water.）',
        explanation_sin: '「水」කියවන්නේ「みず」(මිසු - වතුර) ලෙසයි. කරුණාකර මට වතුර දෙන්න.'
      },
      {
        order_num: 2,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 1\n\nまいあさ 8じに 学校に いきます。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'かくこう',
        option_b: 'がくこう',
        option_c: 'かっこう',
        option_d: 'がっこう',
        correct_option: 'D',
        marks: 1,
        explanation: '「学校」の読み方は促音化して「がっこう」です。「まいあさ 8じに 学校に いきます。」（I go to school at 8 o\'clock every morning.）',
        explanation_sin: '「学校」කියවන්නේ「がっこう」(ගක්කෝ - පාසල) ලෙසයි. සෑම උදෑසනකම 8ට පාසලට යමි.'
      },
      {
        order_num: 3,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 1\n\nこの コートは 安いですね。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'やすい',
        option_b: 'かるい',
        option_c: 'ふるい',
        option_d: 'うすい',
        correct_option: 'A',
        marks: 1,
        explanation: '「安い」の読み方は「やすい」です。「この コートは 安いですね。」（This coat is cheap/inexpensive, isn\'t it?）',
        explanation_sin: '「安い」කියවන්නේ「やすい」(යසුයි - ලාභ/මිල අඩු) ලෙසයි. මේ කබාය ලාභයි නේද.'
      },
      {
        order_num: 4,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 1\n\nきょうは しゅくだいが 少ないです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'すこない',
        option_b: 'すくない',
        option_c: 'すごない',
        option_d: 'すぐない',
        correct_option: 'B',
        marks: 1,
        explanation: '「少ない」の読み方は「すくない」です。「きょうは しゅくだいが 少ないです。」（Today there is little homework.）',
        explanation_sin: '「少ない」කියවන්නේ「すくない」(සුකුනායි - අඩු/ස්වල්ප) ලෙසයි. අද ගෙදර වැඩ අඩුයි.'
      },
      {
        order_num: 5,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 1\n\nこの ふくは 六万円です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'よんせんえん',
        option_b: 'ろくせんえん',
        option_c: 'ろくまんえん',
        option_d: 'よんまんえん',
        correct_option: 'C',
        marks: 1,
        explanation: '「六万円」の読み方は「ろくまんえん」です。「六（ろく）」＋「万（まん）」＋「円（えん）」です。',
        explanation_sin: '「六万円」කියවන්නේ「ろくまんえん」(රොකුමංඑන් - යෙන් හැටදහස) ලෙසයි. මේ ඇඳුම යෙන් 60,000කි.'
      },
      {
        order_num: 6,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 1\n\nその かどを 左に まがって ください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ひだり',
        option_b: 'みき',
        option_c: 'みぎ',
        option_d: 'ひたり',
        correct_option: 'A',
        marks: 1,
        explanation: '「左」の読み方は「ひだり」です。「その かどを 左に まがって ください。」（Please turn left at that corner.）',
        explanation_sin: '「左」කියවන්නේ「ひだり」(හිදාරි - වම) ලෙසයි. ඒ කෙළවරින් වමට හැරෙන්න.'
      },
      {
        order_num: 7,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 1\n\nえんぴつを 三本 かして ください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'さんぽん',
        option_b: 'さんぼん',
        option_c: 'さんべん',
        option_d: 'さんぺん',
        correct_option: 'B',
        marks: 1,
        explanation: '細長いものの助数詞「本」は、3の後は濁音化して「さんぼん」となります。',
        explanation_sin: 'දිගැටි දේවල් ගණනය කිරීමේදී 3 පසු「本」ශබ්ද වන්නේ「さんぼん」(සම්බොන් - පැන්සල් තුනක්) ලෙසයි.'
      },
      {
        order_num: 8,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 1\n\nさとうさんは 先月 けっこんしました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'せんげつ',
        option_b: 'せんしゅう',
        option_c: 'こんげつ',
        option_d: 'こんしゅう',
        correct_option: 'A',
        marks: 1,
        explanation: '「先月」の読み方は「せんげつ」です。「先月（せんげつ）」＝ last month。',
        explanation_sin: '「先月」කියවන්නේ「せんげつ」(සෙන්ගෙත්සු - ගිය මස) ලෙසයි. සාතෝ මහතා ගිය මාසයේ විවාහ විය.'
      },
      {
        order_num: 9,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 1\n\nあの 山の なまえは なんですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'やま',
        option_b: 'はな',
        option_c: 'とり',
        option_d: 'かわ',
        correct_option: 'A',
        marks: 1,
        explanation: '「山」の訓読みは「やま」です。「あの 山の なまえは なんですか。」（What is the name of that mountain?）',
        explanation_sin: '「山」කියවන්නේ「やま」(යාමා - කන්ද) ලෙසයි. අර කන්දේ නම කුමක්ද?'
      },
      {
        order_num: 10,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 1\n\nかんじを 九つ おぼえました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ななつ',
        option_b: 'いつつ',
        option_c: 'やっつ',
        option_d: 'ここのつ',
        correct_option: 'D',
        marks: 1,
        explanation: '和語の数詞で「9つ」は「ここのつ」と読みます。',
        explanation_sin: 'ජපන් ක්‍රමයට ද්‍රව්‍ය ගණන් කිරීමේදී 9「九つ」කියවන්නේ「ここのつ」(කොකොනොත්සු - නවයක්) ලෙසයි.'
      },
      {
        order_num: 11,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 1\n\nこれは どこの くにの お金ですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'おがし',
        option_b: 'おがね',
        option_c: 'おかし',
        option_d: 'おかね',
        correct_option: 'D',
        marks: 1,
        explanation: '「お金」の読み方は「おかね」です。「これは どこの くにの お金ですか。」（Which country\'s money is this?）',
        explanation_sin: '「お金」කියවන්නේ「おかね」(ඔකනෙ - මුදල්) ලෙසයි. මේ කොයි රටේ මුදල්ද?'
      },
      {
        order_num: 12,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 1\n\nどうぞ 飲んで ください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'あそんで',
        option_b: 'ならんで',
        option_c: 'よんで',
        option_d: 'のんで',
        correct_option: 'D',
        marks: 1,
        explanation: '「飲む」のて形は撥音便になり「飲んで（のんで）」と読みます。',
        explanation_sin: '「飲む」(බොනවා) ක්‍රියාපදයේ තෙ-ආකාරය「飲んで」කියවන්නේ「のんで」(නොන්දෙ - බොන්න) ලෙසයි.'
      },

      // 問題２ (Q13-Q20) 表記・漢字書き
      {
        order_num: 13,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 2　＿＿＿の ことばは どう かきますか。1・2・3・4から いちばん いい ものを ひとつ えらんで ください。\n\nあれが この まちで いちばん たかい ビルです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '高い',
        option_b: '高かい',
        option_c: '新い',
        option_d: '新かい',
        correct_option: 'A',
        marks: 1,
        explanation: '「たかい」の漢字は「高い」です。送り仮名は「い」です。',
        explanation_sin: '「たかい」(උස/මිල අධික) හි නිවැරදි කන්ජි අක්ෂරය වන්නේ「高い」වේ.'
      },
      {
        order_num: 14,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 2\n\nすずきさんは えいごが できますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '英話',
        option_b: '英説',
        option_c: '英語',
        option_d: '英訳',
        correct_option: 'C',
        marks: 1,
        explanation: '「えいご（English language）」の漢字は「英語」です。',
        explanation_sin: '「えいご」(ඉංග්‍රීසි භාෂාව) හි නිවැරදි කන්ජි අක්ෂරය වන්නේ「英語」වේ.'
      },
      {
        order_num: 15,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 2\n\nたなかさんは きのう やすみでした。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '体み',
        option_b: '休み',
        option_c: '仕み',
        option_d: '任み',
        correct_option: 'B',
        marks: 1,
        explanation: '「やすみ」の漢字表記は「休み」です。人偏に木で「休」です。',
        explanation_sin: '「やすみ」(නිවාඩුව) සඳහා නිවැරදි කන්ජිය වන්නේ「休み」වේ.'
      },
      {
        order_num: 16,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 2\n\nわたしは きょうとで うまれました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '主まれました',
        option_b: '生まれました',
        option_c: '佐まれました',
        option_d: '住まれました',
        correct_option: 'B',
        marks: 1,
        explanation: '「うまれました」の漢字表記は「生まれました」です。',
        explanation_sin: '「うまれました」(උපන්නෙමි) හි නිවැරදි කන්ජිය「生まれました」වේ.'
      },
      {
        order_num: 17,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 2\n\nあさから あめが ふって います。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '雪',
        option_b: '風',
        option_c: '雨',
        option_d: '雷',
        correct_option: 'C',
        marks: 1,
        explanation: '「あめ（Rain）」を表す漢字は「雨」です。（1は雪＝ゆき、2は風＝かぜ）。',
        explanation_sin: '「あめ」(වැස්ස) සඳහා කන්ජි අක්ෂරය「雨」වේ (1: 雪-හිම, 2: 風-සුළඟ).'
      },
      {
        order_num: 18,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 2\n\nさとうさんと はやしさんの あいだに たって ください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '閤',
        option_b: '間',
        option_c: '開',
        option_d: '問',
        correct_option: 'B',
        marks: 1,
        explanation: '「あいだ（Between）」の漢字は門構えに日の「間」です。',
        explanation_sin: '「あいだ」(අතර) හි නිවැරදි කන්ජිය වන්නේ「間」වේ.'
      },
      {
        order_num: 19,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 2\n\nこうえんの きたがわに としょかんが あります。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '東がわ',
        option_b: '南がわ',
        option_c: '西がわ',
        option_d: '北がわ',
        correct_option: 'D',
        marks: 1,
        explanation: '「きたがわ（North side）」の方角の漢字は「北（きた）」なので、「北がわ」です。',
        explanation_sin: '「きたがわ」(උතුරු පැත්ත) හි 「きた」(උතුර) අක්ෂරය වන්නේ「北」බැවින්「北がわ」නිවැරදිය.'
      },
      {
        order_num: 20,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 2\n\nこの わいしゃつを ください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ウイシャソ',
        option_b: 'ウイシャツ',
        option_c: 'ワイシャソ',
        option_d: 'ワイシャツ',
        correct_option: 'D',
        marks: 1,
        explanation: '「わいしゃつ（Dress shirt）」のカタカナ表記は「ワイシャツ」です。ウとワ、ソとツの書き分けが問われています。',
        explanation_sin: '「わいしゃつ」(කමිසය) නිවැරදි කටකනා අක්ෂරවලින් ලියන්නේ「ワイシャツ」ලෙසයි.'
      },

      // 問題３ (Q21-Q30) 文脈規定
      {
        order_num: 21,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 3　(　) に なにが はいりますか。1・2・3・4から いちばん いい ものを ひとつ えらんで ください。\n\nともだちから ざっしを 3(　) もらいました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'さつ',
        option_b: 'まい',
        option_c: 'だい',
        option_d: 'びき',
        correct_option: 'A',
        marks: 1,
        explanation: '本や雑誌などの冊子類を数える助数詞は「〜冊（さつ）」です。',
        explanation_sin: 'පොත් සහ සඟරා ගණනය කිරීමට භාවිතා කරන ඒකකය「〜さつ」(සත්සු) වේ. මිතුරාගෙන් සඟරා 3ක් ලැබිණි.'
      },
      {
        order_num: 22,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 3\n\nでんきを つけましたから、へやが (　) です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'さむい',
        option_b: 'きたない',
        option_c: 'あかるい',
        option_d: 'せまい',
        correct_option: 'C',
        marks: 1,
        explanation: '電気をつけた（turned on the light）ので、部屋が「あかるい（bright）」になります。',
        explanation_sin: 'විදුලි බුබුල දැමූ නිසා කාමරය「あかるい」(එළිය/දීප්තිමත්) විය.'
      },
      {
        order_num: 23,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 3\n\nびょういんは えきから (　) ですから、バスで いきましょう。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ながい',
        option_b: 'ふとい',
        option_c: 'とおい',
        option_d: 'ひろい',
        correct_option: 'C',
        marks: 1,
        explanation: 'バスで行く理由として、距離が「とおい（far）」ことが適切です。',
        explanation_sin: 'බසයෙන් යාමට හේතුව දුම්රියපොළේ සිට රෝහල「とおい」(දුර) බැවිනි.'
      },
      {
        order_num: 24,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 3\n\n(　) が ありませんから、じかんが わかりません。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'かぎ',
        option_b: 'じしょ',
        option_c: 'さいふ',
        option_d: 'とけい',
        correct_option: 'D',
        marks: 1,
        explanation: '時間がわからないのは「とけい（clock/watch）」がないからです。',
        explanation_sin: 'වේලාව නොදන්නේ「とけい」(ඔරලෝසුවක්) නැති බැවිනි.'
      },
      {
        order_num: 25,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 3\n\nかばんは いすの うえに (　) ください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'のって',
        option_b: 'おいて',
        option_c: 'まって',
        option_d: 'すわって',
        correct_option: 'B',
        marks: 1,
        explanation: '物を置く動詞は「置く（おく）」で、て形は「おいて」です。「いすの うえに おいて ください。」',
        explanation_sin: 'බෑගය පුටුව උඩින්「おいて」(තබන්න - ඔයිතෙ).「置く」(තබනවා) හි තෙ-ආකාරයයි.'
      },
      {
        order_num: 26,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 3\n\nあそこの しんごうで (　) を わたりましょう。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ちかてつ',
        option_b: 'ちず',
        option_c: 'でぐち',
        option_d: 'みち',
        correct_option: 'D',
        marks: 1,
        explanation: '信号で渡るのは「みち（道＝road/street）」です。「道を 渡る（みちを わたる）」。',
        explanation_sin: 'සංඥා එළියෙන් තරණය කරන්නේ「みち」(මාර්ගය/පාර) වේ. පාර මාරු වෙමු.'
      },
      {
        order_num: 27,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 3\n\nこの でんしゃは とうきょうえきを 9じに (　)。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'おります',
        option_b: 'でます',
        option_c: 'かえります',
        option_d: 'はじまります',
        correct_option: 'B',
        marks: 1,
        explanation: '場所を起点として離れる助詞「を」とともに用いられる動詞は「出ます（でます＝departs/leaves）」です。',
        explanation_sin: 'දුම්රිය දුම්රියපොළෙන් නික්මෙන විට「〜を出ます」(දෙමස් - පිටත්වේ) භාවිතා කරයි.'
      },
      {
        order_num: 28,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 3\n\nことしの なつは あついですから、(　) が ほしいです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ラジオ',
        option_b: 'ストーブ',
        option_c: 'エアコン',
        option_d: 'テレビ',
        correct_option: 'C',
        marks: 1,
        explanation: '夏が暑いときに欲しい家電は「エアコン（air conditioner）」です。',
        explanation_sin: 'ගිම්හානය රස්නෙ නිසා අවශ්‍ය වන්නේ「エアコン」(වායුසමීකරණ යන්ත්‍රයක්) ය.'
      },
      {
        order_num: 29,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 3\n\nわたしの (　) は、ちちと ははと わたしの 3にんです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'きょうだい',
        option_b: 'こども',
        option_c: 'りょうしん',
        option_d: 'かぞく',
        correct_option: 'D',
        marks: 1,
        explanation: '父、母、私の3人全体を表す言葉は「かぞく（family）」です。',
        explanation_sin: 'පියා, මව සහ මා ඇතුළු තිදෙනා එක්ව හඳුන්වන්නේ「かぞく」(පවුල) ලෙසයි.'
      },
      {
        order_num: 30,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 3\n\nあそこの ドアから なかに (　) ください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'はいって',
        option_b: 'のぼって',
        option_c: 'ついて',
        option_d: 'とまって',
        correct_option: 'A',
        marks: 1,
        explanation: 'ドアから中に入るので「入る（はいる）」のて形「はいって」が正解です。',
        explanation_sin: 'දොරෙන් ඇතුළට යාම සඳහා「入る」(ඇතුල් වෙනවා) හි තෙ-ආකාරය「はいって」(ඇතුල් වන්න) යොදයි.'
      },

      // 問題４ (Q31-Q35) 類義表現
      {
        order_num: 31,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 4　＿＿＿の ぶんと だいたい おなじ いみの ぶんが あります。1・2・3・4から いちばん いい ものを ひとつ えらんで ください。\n\nいま ごはんを つくって います。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'いま べんきょうを して います',
        option_b: 'いま せんたくを して います',
        option_c: 'いま りょうりを して います',
        option_d: 'いま れんしゅうを して います',
        correct_option: 'C',
        marks: 1,
        explanation: '「ごはんを つくる（make food/meals）」は「りょうりを する（cook）」と同義です。',
        explanation_sin: '「ごはんを つくって います」(කෑම හදමින් සිටියි) යන්න「りょうりを して います」(ඉවුම් පිහුම් කරමින් සිටියි) යන්නට සමාන වේ.'
      },
      {
        order_num: 32,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 4\n\nわたしは まいあさ さんぽして います。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'わたしは まいあさ あるいて います',
        option_b: 'わたしは まいあさ およいで います',
        option_c: 'わたしは まいあさ はしって います',
        option_d: 'わたしは まいあさ はたらいて います',
        correct_option: 'A',
        marks: 1,
        explanation: '「さんぽする（take a walk）」は「あるく（walk）」とほぼ同じ意味を表します。',
        explanation_sin: '「さんぽして います」(ඇවිදිමින් සිටියි) යන්න「あるいて います」(පයින් ගමන් කරයි/ඇවිදියි) යන්නට සමාන අර්ථයක් දෙයි.'
      },
      {
        order_num: 33,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 4\n\nわたしは どうぶつが すきです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'わたしは くるまや ひこうきが すきです。',
        option_b: 'わたしは いぬや ねこが すきです。',
        option_c: 'わたしは こうちゃや コーヒーが すきです。',
        option_d: 'わたしは ケーキや チョコレートが すきです。',
        correct_option: 'B',
        marks: 1,
        explanation: '「どうぶつ（animals）」の具体例は「いぬや ねこ（dogs and cats）」です。',
        explanation_sin: '「どうぶつ」(සතුන්) සඳහා උදාහරණ වන්නේ「いぬや ねこ」(බල්ලන් සහ බළලුන්) ය.'
      },
      {
        order_num: 34,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 4\n\nもりさんは「そぼは いま、いえに いません」と いいました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'もりさんの おかあさんは いま、いえに いません。',
        option_b: 'もりさんの おとうさんは いま、いえに いません。',
        option_c: 'もりさんの おばあさんは いま、いえに いません。',
        option_d: 'もりさんの おじいさんは いま、いえに いません。',
        correct_option: 'C',
        marks: 1,
        explanation: '自分の祖母を表す「そぼ」は、他人に言うときの表現で、「おばあさん（grandmother）」のことです。',
        explanation_sin: 'තමාගේ ආච්චි හැඳින්වීමට「そぼ」භාවිතා කරන අතර, එය「おばあさん」(ආච්චි අම්මා) ට සමාන වේ.'
      },
      {
        order_num: 35,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: 'もんだい 4\n\nこの ジュースは まずいです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'この ジュースは つめたくないです。',
        option_b: 'この ジュースは おいしくないです。',
        option_c: 'この ジュースは からくないです。',
        option_d: 'この ジュースは すっぱくないです。',
        correct_option: 'B',
        marks: 1,
        explanation: '「まずい（bad-tasting）」は「おいしくない（not delicious）」と同義です。',
        explanation_sin: '「まずい」(රස නැති/නීරස) යන්න「おいしくない」(රසවත් නැත) යන්නට සමාන අර්ථයක් ගනී.'
      },

      // =========================================================================
      // SECTION 2: 言語知識（文法）・読解 (Q36 to Q67, 2 marks each = 64 marks)
      // =========================================================================
      // 文法 問題１ (Q36-Q51) 助詞・文法形式
      {
        order_num: 36,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 1　(　) に 何を 入れますか。1・2・3・4から いちばん いい ものを 一つ えらんで ください。\n\n西川「はじめまして、私は A銀行(　) 西川です。」\n中山「はじめまして、中山です。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'や',
        option_b: 'が',
        option_c: 'を',
        option_d: 'の',
        correct_option: 'D',
        marks: 2,
        explanation: '所属を表す助詞「の」を用います。「A銀行の 西川（Nishikawa of A Bank）」です。',
        explanation_sin: 'ආයතනයක සාමාජිකත්වය පෙන්වීමට「の」යොදයි. "මම A බැංකුවේ නිෂිකාවා වෙමි."'
      },
      {
        order_num: 37,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 1\n\nきのう、大山さんが 私(　) 花を くれました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'に',
        option_b: 'や',
        option_c: 'と',
        option_d: 'を',
        correct_option: 'A',
        marks: 2,
        explanation: '相手が自分に物を授受する「〜が 私に [物]を くれる」の構文で、受取人の「私」に助詞「に」が付きます。',
        explanation_sin: 'අනෙකෙකු මට යමක් දීමේදී ලබන්නාට「に」යොදයි. (ඊයේ ඕයාමා මහතා මට මල් දුන්නේය).'
      },
      {
        order_num: 38,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 1\n\nこの スカート(　) 先週デパートで 買いました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'の',
        option_b: 'に',
        option_c: 'で',
        option_d: 'は',
        correct_option: 'D',
        marks: 2,
        explanation: '主題（トピック）を取り立てる助詞「は」です。「この スカートは（As for this skirt, I bought it at the department store last week）」となります。',
        explanation_sin: 'මාතෘකාව ඉස්මතු කිරීමට「は」යොදයි. "මේ සාය ගිය සතියේ දෙපාර්තමේන්තු සාප්පුවෙන් මිලදී ගත්තෙමි."'
      },
      {
        order_num: 39,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 1\n\n今日は 風(　) 強いです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'を',
        option_b: 'の',
        option_c: 'が',
        option_d: 'へ',
        correct_option: 'C',
        marks: 2,
        explanation: '自然現象や状態の主語を表す格助詞は「が」です。「風が 強い（The wind is strong）」。',
        explanation_sin: 'ස්වභාවික සංසිද්ධි හෝ තත්වයන් දැක්වීමට「が」යොදයි. "අද සුළඟ තදයි."'
      },
      {
        order_num: 40,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 1\n\n毎日 私は 1時間(　) さんぽします。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'が',
        option_b: 'に',
        option_c: 'ごろ',
        option_d: 'ぐらい',
        correct_option: 'D',
        marks: 2,
        explanation: '時間の長さ（期間）のおよその目安を表すのは「ぐらい」です。「ごろ」はある特定の時点（時刻）に使います。',
        explanation_sin: 'කාල පරාසයක් (පැයක් පමණ) දැක්වීමට「ぐらい」යොදයි. (ごろ යොදන්නේ නිශ්චිත වේලාවක් දැක්වීමට පමණි).'
      },
      {
        order_num: 41,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 1\n\nきょうしつ(　)、ぼうしを ぬいで ください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'では',
        option_b: 'には',
        option_c: 'へは',
        option_d: 'とは',
        correct_option: 'B',
        marks: 2,
        explanation: '教室の中での規則や状態の限定を表す助詞として公式正解は「には（2番）」です。',
        explanation_sin: 'නිල ප්‍රශ්න පත්‍රයේ පිළිතුරු පත්‍රයට අනුව නිවැරදි පිළිතුර「には」(2) වේ. "පන්ති කාමරයේදී තොප්පිය ගලවන්න."'
      },
      {
        order_num: 42,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 1\n\n(会社で)\nA「えいがの チケットが 5枚 あります。だれ(　) 行きませんか。」\nB「あ、行きたいです。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'と',
        option_b: 'か',
        option_c: 'の',
        option_d: 'に',
        correct_option: 'B',
        marks: 2,
        explanation: '不特定の誰かを誘う表現は「だれか（someone / anyone）」です。助詞「か」が入ります。',
        explanation_sin: 'අවිනිශ්චිත පුද්ගලයෙකු ආමන්ත්‍රණයට「だれか」(කවුරුහරි) යොදයි. "කවුරුහරි යන්න කැමතිද?"'
      },
      {
        order_num: 43,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 1\n\nあしたは しごとの 後、(　) びょういんへ 行きます。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'すぐに',
        option_b: 'もう',
        option_c: 'よく',
        option_d: 'だんだん',
        correct_option: 'A',
        marks: 2,
        explanation: '仕事が終わった直後に行動することを表す副詞は「すぐに（immediately/right away）」です。',
        explanation_sin: 'වැඩ අවසන් වූ වහාම යන බව දැක්වීමට「すぐに」(වහාම/එසැනින්) යෙදීම සුදුසුය.'
      },
      {
        order_num: 44,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 1\n\nA「急いで ください。出かけますよ。」\nB「あ、(　) 待って ください。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'とても',
        option_b: 'あまり',
        option_c: 'ぜんぜん',
        option_d: 'ちょっと',
        correct_option: 'D',
        marks: 2,
        explanation: '相手に少し待ってもらうときの決まり文句は「ちょっと 待って ください（Please wait a moment）」です。',
        explanation_sin: 'මදක් රැඳී සිටින ලෙස ඉල්ලීමේදී「ちょっと 待って ください」(සුළු මොහොතක් ඉන්න) යොදයි.'
      },
      {
        order_num: 45,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 1\n\nA「りょうりを しますか。」\nB「はい、します。でも、じょうず(　)ですよ。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ない',
        option_b: 'が ない',
        option_c: 'しない',
        option_d: 'じゃない',
        correct_option: 'D',
        marks: 2,
        explanation: 'な形容詞「じょうず（上手）」の否定形は「じょうずじゃない（です）」となります。',
        explanation_sin: '「じょうず」(දක්ෂ) නම් な-විශේෂණයේ සෘණාත්මක ස්වරූපය「じょうずじゃない」(දක්ෂ නැත) වේ.'
      },
      {
        order_num: 46,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 1\n\n私は 小さい (　)、外国に 住んで いました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'まで',
        option_b: 'までの',
        option_c: 'とき',
        option_d: 'の とき',
        correct_option: 'C',
        marks: 2,
        explanation: 'い形容詞「小さい」に「とき」が直接接続します（名詞ではないため「の」は不要です）。「小さい とき（When I was small/young）」。',
        explanation_sin: 'い-විශේෂණ පදයක් 「とき」සමග එක්වීමේදී කෙලින්ම සම්බන්ධ වේ (の අනවශ්‍යයි). "කුඩා කාලයේදී".'
      },
      {
        order_num: 47,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 1\n\n日本の 食べ物は おいしいです。いちばん (　)のは すしです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '好き',
        option_b: '好きな',
        option_c: '好きだ',
        option_d: '好きで',
        correct_option: 'B',
        marks: 2,
        explanation: 'な形容詞「好き」が名詞化の「の」を修飾するときは「連体形：好きな＋の」となります。',
        explanation_sin: 'な-විශේෂණ පදයක් 「の」(දෙය) නාමපදය විස්තර කිරීමේදී「な」සහිතව යෙදේ:「好きなの」(කැමතිම එක).'
      },
      {
        order_num: 48,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 1\n\n(電話で)\n山下「もしもし、西川さんですか。」\n西川「はい、そうですが、(　)ですか。」\n山下「山下です。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'どなた',
        option_b: 'どの 人',
        option_c: 'だれが',
        option_d: 'なにか',
        correct_option: 'A',
        marks: 2,
        explanation: '電話などで相手の名前を尋ねる丁寧な疑問詞は「どなた（who/whom）」です。「どなたですか。」',
        explanation_sin: 'දුරකථනයෙන් ආචාරශීලීව කතා කරන්නේ කවුරුන්දැයි විමසීමට「どなたですか」(කවුරුන්ද?) යොදයි.'
      },
      {
        order_num: 49,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 1\n\nA「来月の 旅行は 電車で 行きません。バスで 行きます。」\nB「(　)。」\nA「バスの ほうが 安いからです。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'どちらですか',
        option_b: 'どうしてですか',
        option_c: 'どう しますか',
        option_d: 'どこへ 行きますか',
        correct_option: 'B',
        marks: 2,
        explanation: '理由を表す「〜からです」と答えているため、理由を問う「どうしてですか（Why is that?）」が入ります。',
        explanation_sin: 'පිළිතුරේ「〜からです」(හේතුවෙන්) ඇති බැවින් හේතුව විමසීමට「どうしてですか」(ඒ ඇයි?) යොදයි.'
      },
      {
        order_num: 50,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 1\n\n(きょうしつで)\n山下「南さん、いっしょに しゅくだいを やりませんか。」\n南「すみません、私は 家に 帰ってから(　)。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'います',
        option_b: 'あります',
        option_c: 'します',
        option_d: '終わります',
        correct_option: 'C',
        marks: 2,
        explanation: '宿題を「する」動詞を受けて、「帰ってから（宿題を）します」となります。',
        explanation_sin: 'ගෙදර වැඩ සම්බන්ධයෙන් "නිවසට ගිය පසු කරමි" යනුවෙන්「します」යෙදීම නිවැරදිය.'
      },
      {
        order_num: 51,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 1\n\n(食堂で)\n西川「ラーメンはありませんか。」\n食堂の人「ええ、ありますよ。しょうゆラーメンと しおラーメンが あります。」\n西川「じゃあ、しおラーメン(　)。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'に ください',
        option_b: 'に して ください',
        option_c: 'が おねがいです',
        option_d: 'が おねがいします',
        correct_option: 'B',
        marks: 2,
        explanation: '選択肢の中から決めて注文する文型は「〜にする」の依頼表現「〜に して ください」です。',
        explanation_sin: 'තෝරාගැනීමක් කරමින් ඇණවුම් කිරීමේදී「〜に して ください」(මට එය ලබා දෙන්න) භාවිතා කරයි.'
      },

      // 文法 問題２ (Q52-Q56) 文の組み立て
      {
        order_num: 52,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 2　★に 入る ものは どれですか。1・2・3・4から いちばん いい ものを 一つ えらんで ください。\n\n毎日 私は ＿＿ ＿＿ ★ ＿＿ はを みがきます。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '前',
        option_b: 'の',
        option_c: 'に',
        option_d: '朝ごはん',
        correct_option: 'A',
        marks: 2,
        explanation: '文の組み立て：毎日 私は [朝ごはん] [の] [★前] [に] はを みがきます。（4-2-1-3）。★に入るのは「前（1番）」です。',
        explanation_sin: 'වාක්‍ය සැකැස්ම: 朝ごはん(4) の(2) 前(1) に(3) はを みがきます. ★ සලකුණට එන්නේ「前」(1) වේ.'
      },
      {
        order_num: 53,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 2\n\nA「今日は いい 天気ですね。」\nB「きのうは ＿＿ ＿＿ ★ ＿＿ ましたね。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '晴れ',
        option_b: '雨',
        option_c: '今日は',
        option_d: 'でしたが',
        correct_option: 'C',
        marks: 2,
        explanation: '文の組み立て：きのうは [雨] [でしたが] [★今日は] [晴れ] ましたね。（2-4-3-1）。★に入るのは「今日は（3番）」です。',
        explanation_sin: 'වාක්‍ය සැකැස්ම: 雨(2) でしたが(4) 今日は(3) 晴れ(1) ましたね. ★ සලකුණට එන්නේ「今日は」(3) වේ.'
      },
      {
        order_num: 54,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 2\n\n海に ＿＿ ＿＿ ★ ＿＿ です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '近くて',
        option_b: '家に',
        option_c: '大きい',
        option_d: '住みたい',
        correct_option: 'B',
        marks: 2,
        explanation: '文の組み立て：海に [近くて] [大きい] [★家に] [住みたい] です。（1-3-2-4）。★に入るのは「家に（2番）」です。',
        explanation_sin: 'වාක්‍ය සැකැස්ම: 近くて(1) 大きい(3) 家に(2) 住みたい(4) です. ★ සලකුණට එන්නේ「家に」(2) වේ.'
      },
      {
        order_num: 55,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 2\n\nきのう 私が ＿＿ ＿＿ ★ ＿＿ です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'は',
        option_b: '本',
        option_c: '読んだ',
        option_d: 'おもしろかった',
        correct_option: 'A',
        marks: 2,
        explanation: '文の組み立て：きのう 私が [読んだ] [本] [★は] [おもしろかった] です。（3-2-1-4）。★に入るのは「は（1番）」です。',
        explanation_sin: 'වාක්‍ය සැකැස්ම: 読んだ(3) 本(2) は(1) おもしろかった(4) です. ★ සලකුණට එන්නේ「は」(1) වේ.'
      },
      {
        order_num: 56,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 2\n\n南「中山さん、ダンスを 教えて ください。」\n中山「いいですよ。毎週 水曜日と 土曜日は ここで ＿＿ ＿＿ ★ ＿＿ ください。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '来て',
        option_b: 'います',
        option_c: 'れんしゅうして',
        option_d: 'から',
        correct_option: 'D',
        marks: 2,
        explanation: '文の組み立て：ここで [れんしゅうして] [います] [★から] [来て] ください。（3-2-4-1）。★に入るのは「から（4番）」です。',
        explanation_sin: 'වාක්‍ය සැකැස්ම: れんしゅうして(3) います(2) から(4) 来て(1) ください. ★ සලකුණට එන්නේ「から」(4) වේ.'
      },

      // 文法 問題３ (Q57-Q61) 文章の文法
      {
        order_num: 57,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 3　22から26に 何を 入れますか。ぶんしょうの いみを かんがえて、1・2・3・4から いちばん いい ものを 一つ えらんで ください。\n\n【リュウさんの ぶんしょう】\n私は 風町に 住んで います。風町には 南駅が あります。南駅 [ 22 ] 大きい 駅です。\n駅の 前には いろいろな 店が あります。ようふくや くつの 安い 店が 多いです。いつも たくさんの 人が 買い物を [ 23 ] 。私も よく ようふくを 買います。\nみなさん 買い物は 好きですか。いっしょに 風町で 買い物を [ 24 ] 。駅の 前の 安い 店を 教えますよ。\n\n22に 入る ものは どれですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'は',
        option_b: 'か',
        option_c: 'で',
        option_d: 'より',
        correct_option: 'A',
        marks: 2,
        explanation: '南駅についての説明を行うため、主題を提示する「は」が適切です。「南駅は 大きい 駅です。」',
        explanation_sin: 'දකුණු දුම්රියපොළ ගැන විස්තර ඉදිරිපත් කිරීමේ ප්‍රධාන මාතෘකාව ලෙස「は」යොදයි.'
      },
      {
        order_num: 58,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 3\n\n【リュウさんの ぶんしょう】\n23に 入る ものは どれですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'しますか',
        option_b: 'して います',
        option_c: 'しました',
        option_d: 'して いましたか',
        correct_option: 'B',
        marks: 2,
        explanation: '「いつも たくさんの 人が」という日常的な習慣・状態を表すため、現在進行形・習慣を表す「して います」が入ります。',
        explanation_sin: 'නිරන්තරයෙන් සිදුවන පුරුද්දක්/තත්වයක් දැක්වීමට「して います」(කරමින් සිටියි) යොදයි.'
      },
      {
        order_num: 59,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 3\n\n【リュウさんの ぶんしょう】\n24に 入る ものは どれですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '買いましたか',
        option_b: '買います',
        option_c: '買いませんか',
        option_d: '買いたいです',
        correct_option: 'C',
        marks: 2,
        explanation: '「いっしょに」とクラスメイトを誘いかけているため、勧誘表現の「〜ませんか」である「買いませんか」が適切です。',
        explanation_sin: '「いっしょに」(එක්ව) සමග ආරාධනා කිරීමේ ස්වරූපය「〜ませんか」(買いませんか - බඩු ගනිමුද?) වේ.'
      },
      {
        order_num: 60,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 3\n\n【アントさんの ぶんしょう】\n私の 町には 広い こうえんが あります。\n毎朝 私は 町の 人と いっしょに こうえんを そうじします。 [ 25 ] こうえんは きれいです。\nゆうがたは 一人で こうえんを さんぽします。今、こうえんには きれいな さくらが さいて います。今日の ゆうがたも 見に [ 26 ] 。\n\n25に 入る ものは どれですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'しかし',
        option_b: 'もっと',
        option_c: 'それから',
        option_d: 'だから',
        correct_option: 'D',
        marks: 2,
        explanation: '毎朝掃除をするから公園が綺麗であるという順接・因果関係を表す接続詞「だから（Therefore / So）」が入ります。',
        explanation_sin: 'උදෑසන පිරිසිදු කරන බැවින් උද්‍යානය ලස්සනයි යන හේතුඵල සම්බන්ධය දැක්වීමට「だから」(එමනිසා) යොදයි.'
      },
      {
        order_num: 61,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 3\n\n【アントさんの ぶんしょう】\n26に 入る ものは どれですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '行きました',
        option_b: '行きたいです',
        option_c: '行きませんでした',
        option_d: '行きましょう',
        correct_option: 'B',
        marks: 2,
        explanation: '桜がきれいに咲いていて「今日の夕方も」見に行きたいという話者の主観的な希望を表す「行きたいです（want to go）」が適切です。',
        explanation_sin: 'අද සවසද මල් නැරඹීමට යාමේ කැමැත්ත ප්‍රකාශ කිරීමට「行きたいです」(යාමට කැමතියි) යෙදිය යුතුය.'
      },

      // 読解 問題４ (Q62-Q64) 短文読解
      {
        order_num: 62,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 4　つぎの ぶんしょうを 読んで、しつもんに こたえて ください。こたえは、1・2・3・4から いちばん いい ものを 一つ えらんで ください。\n\n私の 大学は 駅の ちかくに あります。大学の まえには びょういんや ぎんこうが あります。そして、大学の となりには 大きい こうえんが あります。\n\n大学の となりに 何が ありますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'びょういん',
        option_b: 'としょかん',
        option_c: 'ぎんこう',
        option_d: 'こうえん',
        correct_option: 'D',
        marks: 2,
        explanation: '「大学の となりには 大きい こうえんが あります」と明記されているため、正解は「こうえん（4番）」です。',
        explanation_sin: 'ඡේදයේ පැහැදිලිව සඳහන් වන්නේ විශ්වවිද්‍යාලය අසල විශාල උද්‍යානයක් ඇති බවයි (こうえん).'
      },
      {
        order_num: 63,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 4\n\n「日本語A組の 学生へ」\n来週の 水曜日は、ごぜんは 105教室で 日本の えいがの DVDを 見ます。ごごは 103教室で いつもの じゅぎょうを します。まちがえないで ください。\n\n日本語A組の 学生は 来週の 水曜日に どの 教室へ 行きますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ごぜんも ごごも 103教室',
        option_b: 'ごぜんも ごごも 105教室',
        option_c: 'ごぜんは 103教室、ごごは 105教室',
        option_d: 'ごぜんは 105教室、ごごは 103教室',
        correct_option: 'D',
        marks: 2,
        explanation: '通知文より、午前は105教室、午後は103教室に行くため、4番が正解です。',
        explanation_sin: 'දැන්වීමට අනුව උදෑසන 105 පන්ති කාමරයටද, දහවල් 103 පන්ති කාමරයටද යා යුතුය (4).'
      },
      {
        order_num: 64,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 4\n\nエミさんへ\nコンサートの 切符を 買いました。大西先生と 高木先生と エミさんの 3枚です。高木先生の 切符と エミさんの 切符は、エミさんの 机の 上に おいて おきます。\n\nエミさんの 机の 上の 切符は だれの 切符ですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '大西先生と 高木先生',
        option_b: '大西先生と エミさん',
        option_c: '高木先生と エミさん',
        option_d: '高木先生だけ',
        correct_option: 'C',
        marks: 2,
        explanation: 'メモに「高木先生の 切符と エミさんの 切符は、エミさんの 机の 上に おいて おきます」とあるので、3番（高木先生と エミさん）が正解です。',
        explanation_sin: 'සටහනෙහි පැහැදිලිව සඳහන් පරිදි මේසය මත ඇත්තේ තකාගි ගුරුතුමාගේ සහ එමිගේ ප්‍රවේශපත්‍රයි (3).'
      },

      // 読解 問題５ (Q65-Q66) 中文読解（ラジャさんの手紙）
      {
        order_num: 65,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 5　つぎの ぶんしょうを 読んで、しつもんに こたえて ください。こたえは、1・2・3・4から いちばん いい ものを 一つ えらんで ください。\n\nラジャさんは 山中さんの かぞくに 手紙を 書きました。\n\nみなさん お元気ですか。\n先週は いろいろ ありがとうございました。みなさんと いっしょの 夏休みは とても 楽しかったです。一週間 日本語で たくさん 話が できました。京子さんと プールで 泳いだり、お母さんと 日本の りょうりを 作ったりしました。\nわたしは はじめて おすしと おにぎりを 作りました。おすしは むずかしかったです。でも、おにぎりは かんたんでしたから、また 自分で 作りたいです。お母さんが 作った みそしるは おいしかったです。わたしが 作った カレーも みなさんが「おいしいですね。」と 言いましたから、うれしかったです。\nみなさんと とった しゃしんを 見ながら、この手紙を 書いて います。来週の 月曜日から また 学校が 始まります。\nそれでは また。\nラジャ\n\nラジャさんは 先週 何を しましたか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'しゃしんを とったり、学校で 日本語を 習ったりしました。',
        option_b: 'プールに 行ったり、りょうりを 作って 食べたりしました。',
        option_c: '国の ことばで たくさん 話したり、手紙を 書いたりしました。',
        option_d: 'おにぎりの 作り方を 教えた、みそしるを 作ったりしました。',
        correct_option: 'B',
        marks: 2,
        explanation: '本文第1段落で「京子さんと プールで 泳いだり、お母さんと 日本の りょうりを 作ったりしました」とあり、2番が合致しています。',
        explanation_sin: 'ලිපියේ සඳහන් පරිදි රජා පසුගිය සතියේ පිහිනුම් තටාකයට ගොස් ජපන් කෑම සාදා අනුභව කළේය (2).'
      },
      {
        order_num: 66,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 5\n\nこの 手紙で ラジャさんは 何が いちばん 言いたいですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'おすしの 作り方を 習いたいです。おねがいします。',
        option_b: 'カレーが おいしかったです。また 作って ください。',
        option_c: '先週は 楽しかったです。ありがとうございました。',
        option_d: '月曜日から 学校が 始まります。うれしいです。',
        correct_option: 'C',
        marks: 2,
        explanation: '手紙の主旨は、夏休みに山中さんの家族と過ごした楽しい思い出に対する感謝を伝えることであり、3番が正解です。',
        explanation_sin: 'ලිපියේ මූලික අරමුණ පසුගිය සතියේ විනෝදයෙන් ගත කළ කාලය වෙනුවෙන් පවුලේ සැමට ස්තුතිය පළ කිරීමයි (3).'
      },

      // 読解 問題６ (Q67) 情報検索
      {
        order_num: 67,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: 'もんだい 6　右の ページを 見て、下の しつもんに こたえて ください。こたえは、1・2・3・4から いちばん いい ものを 一つ えらんで ください。\n\nアンさんは、「はじめましてパーティー」に 行きます。アンさんは C クラスです。何を 持っていきますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper4/reading_m6_q32.png',
        audio_url: null,
        option_a: '300円',
        option_b: 'おかし',
        option_c: 'くだもの',
        option_d: '飲み物',
        correct_option: 'C',
        marks: 2,
        explanation: '案内表の「持ってくるもの」の欄で、Cクラスの人は「くだもの（fruit）」を持ってくることになっているため、3番が正解です。',
        explanation_sin: 'වගුවට අනුව C පන්තියේ සිසුන් රැගෙන ආ යුත්තේ පලතුරු「くだもの」(3) වේ.'
      },

      // =========================================================================
      // SECTION 3: 聴解 (Q68 to Q91, 2 marks each = 48 marks)
      // =========================================================================
      // 聴解 問題１ (Q68-Q74) 課題理解
      {
        order_num: 68,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 1　もんだい 1では、はじめに しつもんを きいて ください。それから はなしを きいて、もんだいようしの 1から 4の なかから、いちばん いい ものを ひとつ えらんで ください。\n\n1ばん：女の人と 男の人が 話して います。男の人は どれを 取りますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper4/listening_m1_q1.png',
        audio_url: audioTrackUrl,
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'B',
        marks: 2,
        explanation: '会話で「白いカップを取ってください」「小さいカップの隣のです」と指示されており、小さいカップ（3）の隣にある白いカップは2番です。',
        explanation_sin: 'කුඩා කෝප්පය (3) අසල ඇති සුදු කෝප්පය වන්නේ 2 වන කෝප්පයයි (2).'
      },
      {
        order_num: 69,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 1\n\n2ばん：教室で 先生が 話して います。学生は 明日 何を 持ってきますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper4/listening_m1_q2.png',
        audio_url: audioTrackUrl,
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'B',
        marks: 2,
        explanation: '「明日は葉書を持ってきてください。切手は入りません。鉛筆じゃなくて、ペンで書きますから、ペンも忘れないでください」とあるので、葉書とペン（2番）です。',
        explanation_sin: 'තැපැල්පත් සහ පෑන රැගෙන ආ යුතුය. මුද්දර අනවශ්‍යයි (2).'
      },
      {
        order_num: 70,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 1\n\n3ばん：会社で 女の人と 男の人が 話して います。男の人は 何を 消しますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'テレビと エアコン',
        option_b: 'テレビと でんき',
        option_c: 'エアコンと でんき',
        option_d: 'テレビと エアコンと でんき',
        correct_option: 'C',
        marks: 2,
        explanation: '女性が「テレビはもう消しましたから、エアコンを消してください」「電気もお願いします」と頼んでいるので、エアコンと電気（3番）です。',
        explanation_sin: 'රූපවාහිනිය දැනටමත් නිවා දමා ඇති බැවින්, නිවා දැමිය යුත්තේ වායුසමීකරණය සහ විදුලි බුබුලුයි (3).'
      },
      {
        order_num: 71,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 1\n\n4ばん：料理の クラスで 女の先生と 男の学生が 話して います。男の学生は この後 すぐ 何を しますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper4/listening_m1_q4.png',
        audio_url: audioTrackUrl,
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'C',
        marks: 2,
        explanation: '学生が「野菜を切りましょうか」と聞きますが、先生が「いえ、野菜じゃなくて、肉を切ってください」と指示しているため、肉を切る3番です。',
        explanation_sin: 'ගුරුතුමිය උපදෙස් දෙන්නේ එළවළු වෙනුවට මස් කපන ලෙසයි (3).'
      },
      {
        order_num: 72,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 1\n\n5ばん：病院で 医者と 女の人が 話して います。女の人は 来週 いつ 病院へ 来ますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'げつようびの 3じ',
        option_b: 'げつようびの 3じはん',
        option_c: 'かようびの 3じ',
        option_d: 'かようびの 3じはん',
        correct_option: 'D',
        marks: 2,
        explanation: '月曜は忙しいので火曜になり、医師が「じゃ、三時半に来てください」と言い承諾したため、火曜日の3時半（4番）です。',
        explanation_sin: 'සඳුදා කාර්යබහුල බැවින් අඟහරුවාදා පස්වරු 3:30ට පැමිණීමට තීරණය විය (4).'
      },
      {
        order_num: 73,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 1\n\n6ばん：男の人と 女の人が 話して います。男の人は どこに 行きますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper4/listening_m1_q6.png',
        audio_url: audioTrackUrl,
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'B',
        marks: 2,
        explanation: '「レストランの隣が郵便局です。レストランと銀行の間です」と説明されており、銀行とレストランの間は2番です。',
        explanation_sin: 'බැංකුව සහ අවන්හල අතර පිහිටි තැපැල් කාර්යාලය වන්නේ 2 වන ස්ථානයයි (2).'
      },
      {
        order_num: 74,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 1\n\n7ばん：大学で 男の学生と 女の人が 話して います。この後、男の学生は どこへ 行きますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '1かいの きょうしつ',
        option_b: '2かいの きょうしつ',
        option_c: '3かいの きょうしつ',
        option_d: '4かいの きょうしつ',
        correct_option: 'C',
        marks: 2,
        explanation: '女性が「今週から、一つ上の三階の教室になりましたよ」と教えてくれたため、3階の教室（3番）へ行きます。',
        explanation_sin: 'පන්ති කාමරය ඉහළ මාලයේ 3 වන මහලට මාරු වී ඇති බැවින් 3 වන මහලේ පන්තියට යයි (3).'
      },

      // 聴解 問題２ (Q75-Q80) ポイント理解
      {
        order_num: 75,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 2　もんだい 2では、はじめに しつもんを きいて ください。それから はなしを きいて、もんだいようしの 1から 4の なかから、いちばん いい ものを ひとつ えらんで ください。\n\n1ばん：女の人と 男の人が 話して います。二人は どの 果物を 使いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper4/listening_m2_q1.png',
        audio_url: audioTrackUrl,
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'B',
        marks: 2,
        explanation: 'リンゴとミカンを入れることにし、バナナはないと言っているため、リンゴとミカンの組み合わせである2番です。',
        explanation_sin: 'ඇපල් සහ දොඩම් පමණක් යොදා ගනී (කෙසෙල් නැත). එබැවින් 2 වන රූපය නිවැරදිය (2).'
      },
      {
        order_num: 76,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 2\n\n2ばん：女の人と 男の人が 話して います。男の人は 何を 飲みますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'あつい コーヒー',
        option_b: 'つめたい コーヒー',
        option_c: 'あつい おちゃ',
        option_d: 'つめたい おちゃ',
        correct_option: 'D',
        marks: 2,
        explanation: '昨日もらったお茶を飲むことになり、温度を聞かれて「冷たいのをお願いします」と答えたため、冷たいお茶（4番）です。',
        explanation_sin: 'මිතුරාගෙන් ලැබුණු තේ පානය කිරීමට තෝරාගත් අතර, සීතල තේ ඉල්ලා සිටියේය (4).'
      },
      {
        order_num: 77,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 2\n\n3ばん：公園で 男の人と 女の人が 話して います。女の人の 子供は どの 子供ですか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper4/listening_m2_q3.png',
        audio_url: audioTrackUrl,
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'D',
        marks: 2,
        explanation: '「私の子供も絵を描いています」「木の下で描いています」と答えているため、木の下で絵を描いている男の子（4番）です。',
        explanation_sin: 'ගස යට සිට චිත්‍ර අඳිමින් සිටින දරුවා ඇගේ පුතා වේ (4).'
      },
      {
        order_num: 78,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 2\n\n4ばん：学校で 女の学生と 男の学生が 話して います。二人は どこで 会いますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'えいがかん',
        option_b: 'もんの まえ',
        option_c: 'しょくどう',
        option_d: 'きょうしつ',
        correct_option: 'C',
        marks: 2,
        explanation: '門の前は授業時間と合わないため、「食堂で待っていますから、来てください」「分かりました」と合意したため、食堂（3番）です。',
        explanation_sin: 'පාසල් දොරටුව අසල හමුවිය නොහැකි බැවින් ආපනශාලාවේදී හමුවීමට තීරණය කළහ (3).'
      },
      {
        order_num: 79,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 2\n\n5ばん：女の先生と 男の学生が 話して います。来週は はじめに 何ページを 勉強しますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '17ページ',
        option_b: '18ページ',
        option_c: '19ページ',
        option_d: '20ページ',
        correct_option: 'A',
        marks: 2,
        explanation: '学生が17ページをもう一度教えてほしいと頼み、先生が「じゃあ、17ページをやってから20ページをやりましょう」と言ったため、最初にするのは17ページ（1番）です。',
        explanation_sin: 'ගුරුතුමිය පවසන්නේ පළමුව 17 වන පිටුව කර ඉන්පසු 20 වන පිටුව කරන ලෙසයි (1).'
      },
      {
        order_num: 80,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 2\n\n6ばん：図書館で 男の人が 留学生に 話して います。土曜日 図書館は 何時から 何時までですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'ごぜん9じ ～ ごご6じ',
        option_b: 'ごぜん9じ ～ ごご10じ',
        option_c: 'ごぜん10じ ～ ごご6じ',
        option_d: 'ごぜん10じ ～ ごご10じ',
        correct_option: 'A',
        marks: 2,
        explanation: '「図書館は朝九時に開いて...土曜日と日曜日は午後六時に閉まります」とあるので、午前9時〜午後6時（1番）です。',
        explanation_sin: 'සෙනසුරාදා දින පුස්තකාලය උදෑසන 9ට විවෘත වී සවස 6ට වැසෙයි (1).'
      },

      // 聴解 問題３ (Q81-Q85) 発話表現 (3 options; option_d = "")
      {
        order_num: 81,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 3　もんだい 3では、えを みながら しつもんを きいて ください。（やじるし）の ひとは なんと いいますか。1から 3の なかから、いちばん いい ものを ひとつ えらんで ください。\n\n1ばん：友達の 誕生日です。何と 言いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper4/listening_m3_q1.png',
        audio_url: audioTrackUrl,
        option_a: 'おめでとう。',
        option_b: 'どうぞよろしく。',
        option_c: 'どういたしまして。',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '友達への誕生日のお祝いの言葉は「おめでとう（Congratulations / Happy Birthday）」です。',
        explanation_sin: 'උපන්දිනයකට සුබපැතීමේදී「おめでとう」(සුබ උපන්දිනයක්) යැයි පවසයි.'
      },
      {
        order_num: 82,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 3\n\n2ばん：熱いお茶が 買いたいです。何と 言いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper4/listening_m3_q2.png',
        audio_url: audioTrackUrl,
        option_a: '熱いお茶を どうぞ。',
        option_b: '熱いお茶は ありますか。',
        option_c: '熱いお茶を 買って ください。',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '店で熱いお茶があるか尋ねて購入する際の適切な表現は「熱いお茶は ありますか（Do you have hot tea?）」です。',
        explanation_sin: 'උණුසුම් තේ මිලදී ගැනීමට වෙළෙන්දාගෙන් විමසන්නේ「熱いお茶は ありますか」(උණු තේ තිබේද?) යනුවෙනි.'
      },
      {
        order_num: 83,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 3\n\n3ばん：今から クラスの 人たちに 話したいです。何と 言いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper4/listening_m3_q3.png',
        audio_url: audioTrackUrl,
        option_a: '話しますか。',
        option_b: 'わかりましたね。',
        option_c: '聞いて ください。',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: 'クラスのみんなに注意を促して話を聞いてもらう合図は「聞いて ください（Please listen）」です。',
        explanation_sin: 'පන්තියේ සැමට ඇහුම්කන් දෙන ලෙස පවසන යෙදුම「聞いて ください」(කරුණාකර අහන්න) වේ.'
      },
      {
        order_num: 84,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 3\n\n4ばん：昼ごはんが 食べたいです。友達と 店を 選びます。何と 言いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper4/listening_m3_q4.png',
        audio_url: audioTrackUrl,
        option_a: '誰と 食べますか。',
        option_b: 'いつ 店に 行きますか。',
        option_c: 'どの 店が いいですか。',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '並んでいる店の中からどれが良いか友達に尋ねる表現は「どの 店が いいですか（Which shop would be good?）」です。',
        explanation_sin: 'මිතුරාගෙන් කිනම් අවන්හල හොඳදැයි විමසීමට「どの 店が いいですか」(කොයි කඩේද හොඳ?) යොදයි.'
      },
      {
        order_num: 85,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 3\n\n5ばん：友達が 荷物を たくさん 持って います。何と 言いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper4/listening_m3_q5.png',
        audio_url: audioTrackUrl,
        option_a: '持ちましょうか。',
        option_b: '持ちませんか。',
        option_c: '持って ください。',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '重い荷物を持つ手助けを申し出る表現は「持ちましょうか（Shall I carry it for you?）」です。',
        explanation_sin: 'බඩු ඔසවාගෙන යන මිතුරෙකුට උදව් කිරීමට අසන්නේ「持ちましょうか」(මම උස්සන්නද?) යනුවෙනි.'
      },

      // 聴解 問題４ (Q86-Q91) 即時応答 (3 options; option_d = "")
      {
        order_num: 86,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 4　もんだい 4は、えなどが ありません。ぶんを きいて、1から 3の なかから、いちばん いい ものを ひとつ えらんで ください。\n\n1ばん：日本語の テストは 難しかったですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'とても 安かったです。',
        option_b: 'あまり 難しくなかったです。',
        option_c: 'よく 勉強しますね。',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '難しかったか尋ねられているので、「あまり 難しくなかったです（It was not very difficult）」が自然な応答です。',
        explanation_sin: 'ප්‍රශ්නය: "ජපන් විභාගය අමාරුද?" පිළිතුර: "එතරම් අමාරු වුණේ නැහැ" (2).'
      },
      {
        order_num: 87,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 4\n\n2ばん：スポーツは 何が 一番 好きですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'はい、とても 好きです。',
        option_b: 'サッカーの 方が 好きです。',
        option_c: 'そうですね、テニスです。',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '何のスポーツが一番好きかを聞かれているため、「そうですね、テニスです（Well, it\'s tennis）」が適切です。',
        explanation_sin: 'ප්‍රශ්නය: "වඩාත්ම කැමති ක්‍රීඩාව කුමක්ද?" පිළිතුර: "ටෙනිස් ක්‍රීඩාවටයි" (3).'
      },
      {
        order_num: 88,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 4\n\n3ばん：いつ、日本へ 来ましたか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '去年の 春です。',
        option_b: 'はい、来ました。',
        option_c: '6時間ぐらいです。',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: 'いつ来たかを尋ねられているので、時期を表す「去年の 春です（Last year\'s spring）」が適切です。',
        explanation_sin: 'ප්‍රශ්නය: "ජපානයට ආවේ කවදාද?" පිළිතුර: "ගිය වසරේ වසන්ත කාලයේදීය" (1).'
      },
      {
        order_num: 89,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 4\n\n4ばん：何時の バスに 乗りますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '30分ぐらい 乗ります。',
        option_b: 'はい、バスで 行きます。',
        option_c: '2時半の バスです。',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '何時のバスに乗るかを聞かれているので、時刻を表す「2時半の バスです（The 2:30 bus）」が正解です。',
        explanation_sin: 'ප්‍රශ්නය: "නගින්නේ කීයේ බසයටද?" පිළිතුර: "2:30 බසයටයි" (3).'
      },
      {
        order_num: 90,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 4\n\n5ばん：来週の 山田さんの 誕生日に 何を あげますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '何も もらいません。',
        option_b: '本を プレゼントします。',
        option_c: '来週の 水曜日です。',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: 'プレゼントに何をあげるかを聞かれているので、「本を プレゼントします（I will give a book as a present）」が適切です。',
        explanation_sin: 'ප්‍රශ්නය: "යමදාගේ උපන්දිනයට මොනවාද දෙන්නේ?" පිළිතුර: "පොතක් තෑගි කරමි" (2).'
      },
      {
        order_num: 91,
        section_name: '聴解 - Listening Comprehension',
        question_text: 'もんだい 4\n\n6ばん：あそこで 田中さんと 話して いる 人は 誰ですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'あそこで 話して いますよ。',
        option_b: '私も 知りません。',
        option_c: '白い シャツを 着て います。',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '誰であるかを尋ねられて、知らない場合に「私も 知りません（I don\'t know either）」と答えるのが自然です。',
        explanation_sin: 'ප්‍රශ්නය: "අර තනකා මහතා සමග කතා කරන්නේ කවුද?" පිළිතුර: "මමත් දන්නේ නැත" (2).'
      }
    ];

    console.log(`Prepared ${questionsData.length} questions for seeding.`);

    // Delete existing questions for this exam ONLY (re-seed cleanly)
    await query.run("DELETE FROM questions WHERE exam_id = ?", [examId]);
    console.log(`Cleaned existing questions for Exam ID: ${examId}`);

    for (const q of questionsData) {
      await query.run(`
        INSERT INTO questions (
          exam_id,
          section_name,
          question_text,
          question_type,
          image_url,
          audio_url,
          option_a,
          option_b,
          option_c,
          option_d,
          correct_option,
          marks,
          explanation,
          explanation_sin,
          order_num,
          difficulty_level
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId,
        q.section_name,
        q.question_text,
        q.question_type,
        q.image_url,
        q.audio_url,
        q.option_a,
        q.option_b,
        q.option_c,
        q.option_d,
        q.correct_option,
        q.marks,
        q.explanation,
        q.explanation_sin,
        q.order_num,
        'N5'
      ]);
    }

    console.log(`✅ Successfully seeded all ${questionsData.length} questions for "${title}" (Exam ID: ${examId})!`);

    // Verification checks
    const countCheck = await query.get("SELECT COUNT(*) as count FROM questions WHERE exam_id = ?", [examId]);
    console.log(`Verification: Exam ID ${examId} now has ${countCheck.count} questions.`);

    // IMMUTABILITY SAFETY CHECKS
    const exam2Check = await query.get("SELECT COUNT(*) as count FROM questions WHERE exam_id = 2");
    console.log(`Safety Check: Original Mock Exam ID 2 question count = ${exam2Check.count} (Must be exactly 8).`);
    if (exam2Check.count !== 8) {
      throw new Error(`CRITICAL: Exam ID 2 was modified! Count is ${exam2Check.count}, expected 8.`);
    }

    const exam184Check = await query.get("SELECT COUNT(*) as count FROM questions WHERE exam_id = 184");
    console.log(`Safety Check: Paper 02 Exam ID 184 question count = ${exam184Check.count} (Must be exactly 67).`);
    if (exam184Check.count !== 67) {
      throw new Error(`CRITICAL: Exam ID 184 was modified! Count is ${exam184Check.count}, expected 67.`);
    }

    const exam185Check = await query.get("SELECT COUNT(*) as count FROM questions WHERE exam_id = 185");
    console.log(`Safety Check: Paper 03 Exam ID 185 question count = ${exam185Check.count} (Must be exactly 89).`);
    if (exam185Check.count !== 89) {
      throw new Error(`CRITICAL: Exam ID 185 was modified! Count is ${exam185Check.count}, expected 89.`);
    }

    return { examId, totalQuestions: countCheck.count };
  } catch (err) {
    console.error('Error in seedJLPTN5Paper04:', err);
    throw err;
  }
}

module.exports = { seedJLPTN5Paper04 };

if (require.main === module) {
  seedJLPTN5Paper04()
    .then((result) => {
      console.log('Seeding completed successfully:', result);
      process.exit(0);
    })
    .catch((err) => {
      console.error('Seeding failed:', err);
      process.exit(1);
    });
}
