const { query } = require('../config/database');

async function seedJftModelPaper06() {
  try {
    const title = 'JFT-Basic Official Model Paper 06 (60 Minutes)';
    const existingExam = await query.get("SELECT id FROM exams WHERE title = ?", [title]);
    let examId;

    if (existingExam) {
      examId = existingExam.id;
      console.log(`Seeding JFT Model Paper 06 (Exam ID: ${examId})...`);
      await query.run(`
        UPDATE exams 
        SET description = 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper 06 (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [examId]);
      await query.run("DELETE FROM questions WHERE exam_id = ?", [examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (1, ?, 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper 06 (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.', 60, 200, 1)
      `, [title]);
      examId = res.id;
      console.log(`Created JFT Model Paper 06 (Exam ID: ${examId})`);
    }

    const questions = [
      // ==========================================
      // SECTION 1: Script & Vocabulary (文字・語彙 - Q01 to Q15)
      // ==========================================
      {
        order_num: 1,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q01.jpg',
        audio_url: null,
        option_a: 'お母さん',
        option_b: 'お父さん',
        option_c: 'おばあさん',
        option_d: '',
        correct_option: 'B',
        marks: 1,
        explanation: 'お父さん (Father / තාත්තා).'
      },
      {
        order_num: 2,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q02.jpg',
        audio_url: null,
        option_a: 'ちゅうごく',
        option_b: 'アメリカ',
        option_c: 'カナダ',
        option_d: '',
        correct_option: 'C',
        marks: 1,
        explanation: 'カナダ (Canada / කැනඩාව).'
      },
      {
        order_num: 3,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q03.jpg',
        audio_url: null,
        option_a: 'のうか',
        option_b: 'かいしゃいん',
        option_c: 'かんごし',
        option_d: '',
        correct_option: 'A',
        marks: 1,
        explanation: 'のうか (Farmer / ගොවියා/ගොවිතැන් කරන්නා).'
      },
      {
        order_num: 4,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q04.jpg',
        audio_url: null,
        option_a: 'すいます',
        option_b: 'のみます',
        option_c: '食べます',
        option_d: '',
        correct_option: 'B',
        marks: 1,
        explanation: 'のみます (To drink / බොනවා).'
      },
      {
        order_num: 5,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q05.jpg',
        audio_url: null,
        option_a: 'のぼります',
        option_b: 'おります',
        option_c: 'のります',
        option_d: '',
        correct_option: 'C',
        marks: 1,
        explanation: 'バスにのります (To get on / board a bus / බස් එකට නගිනවා).'
      },
      {
        order_num: 6,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q06.jpg',
        audio_url: null,
        option_a: 'ねこ',
        option_b: 'いぬ',
        option_c: 'うさぎ',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: 'いぬ (Dog / බල්ලා).'
      },
      {
        order_num: 7,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q07.jpg',
        audio_url: null,
        option_a: 'シャワーをあびます',
        option_b: 'あそびます',
        option_c: 'おどります',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: 'シャワーをあびます (Take a shower / නානවා).'
      },
      {
        order_num: 8,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q08.jpg',
        audio_url: null,
        option_a: 'はなします',
        option_b: '勉強します',
        option_c: 'おきます',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: 'おきます (Wake up / get up / අවදි වෙනවා).'
      },
      {
        order_num: 9,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ねます',
        option_b: 'おきます',
        option_c: '本をよみます',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: 'ねます (Go to sleep / to bed / නිදාගන්නවා).'
      },
      {
        order_num: 10,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined hiragana word in kanji.? Choose the correct one.\n\n妹は今年【なんさい】ですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '何最',
        option_b: '何才',
        option_c: '南才',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '何才 (なんさい - How old / වයස කීයද).'
      },
      {
        order_num: 11,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined hiragana word in kanji.? Choose the correct one.\n\nみちこさんは私の【ゆうじん】です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '友人',
        option_b: '夕人',
        option_c: '友達',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '友人 (ゆうじん - Friend / මිතුරා).'
      },
      {
        order_num: 12,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined hiragana word in kanji.? Choose the correct one.\n\n私の家族には【さんにん】います。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '参人',
        option_b: '三入',
        option_c: '三人',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '三人 (さんにん - 3 people / තිදෙනෙක්).'
      },
      {
        order_num: 13,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined hiragana word in kanji.? Choose the correct one.\n\nにほんは【しき】があります。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '式',
        option_b: '四季',
        option_c: '四着',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '四季 (しき - Four seasons / සෘතු හතර).'
      },
      {
        order_num: 14,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined hiragana word in kanji.? Choose the correct one.\n\nその【じょせい】はきむら先生です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '好性',
        option_b: '好生',
        option_c: '女性',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '女性 (じょせい - Woman / Female / කාන්තාව).'
      },
      {
        order_num: 15,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined hiragana word in kanji.? Choose the correct one.\n\n【たなばた】は日本の祭りです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '七多',
        option_b: '七夕',
        option_c: '多七',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '七夕 (たなばた - Tanabata Star Festival / තනබත උත්සවය).'
      },

      // ==========================================
      // SECTION 2: Conversation & Expression (会話・表現 - Q16 to Q30)
      // ==========================================
      {
        order_num: 16,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\n明日パーティーにみちこさんが来るといいですね。みちこさんはとても＿＿＿人ですから。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'つめたい',
        option_b: 'こわい',
        option_c: 'たのしい',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'みちこさんはとても楽しい人ですから (Michiko is a very fun/pleasant person / මිචිකෝ විනෝදජනක කෙනෙක්).'
      },
      {
        order_num: 17,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\nはこの中にりんごがひとつ＿＿＿あります。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q17.jpg',
        audio_url: null,
        option_a: 'しか',
        option_b: 'だけ',
        option_c: 'あまり',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'りんごがひとつだけあります (There is only one apple / එක ඇපල් ගෙඩියක් පමණක් ඇත. 肯定文には「だけ」を使います).'
      },
      {
        order_num: 18,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\nこのワンピースは長いですから、もう少し＿＿＿してください。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q18.jpg',
        audio_url: null,
        option_a: 'みじかい',
        option_b: 'みじかいな',
        option_c: 'みじかく',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'い形容詞 + します -> みじかくしてください (Please make it shorter / කොට කර දෙන්න).'
      },
      {
        order_num: 19,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\nあのケーキはあまり＿＿＿です。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q19.jpg',
        audio_url: null,
        option_a: 'おいしくない',
        option_b: 'おいしい',
        option_c: 'おもしろくない',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'あまり + 否定 -> あまりおいしくないです (It is not very delicious / එතරම් රසවත් නැත).'
      },
      {
        order_num: 20,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\nスリランカではアヌラーダプラがいちばん＿＿＿町です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'あつい',
        option_b: 'さむい',
        option_c: 'すずしい',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'いちばんあつい町 (The hottest city / උණුසුම්ම නගරය).'
      },
      {
        order_num: 21,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the phrase that fits the most.)\n\nA: Ｂさんはさしみが食べられますか。\nB: はい、＿＿＿＿＿。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q21.jpg',
        audio_url: null,
        option_a: 'わかりました',
        option_b: 'そうですね',
        option_c: 'だいじょうぶです',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'はい、だいじょうぶです (Yes, I can eat it / I am fine with it / ඔව් කමක් නෑ/මට කන්න පුළුවන්).'
      },
      {
        order_num: 22,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the phrase that fits the most.)\n\nA: あたらしいモールですね。もう行きましたか。\nB: いいえ、＿＿＿＿＿。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q22.jpg',
        audio_url: null,
        option_a: 'まだです',
        option_b: 'でも',
        option_c: 'これから',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'いいえ、まだです (No, not yet / නැහැ, තවම ගියේ නෑ).'
      },
      {
        order_num: 23,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the phrase that fits the most.)\n\nA: この料理を食べてみてください。\nB: ありがとう。＿＿＿＿＿。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q23.jpg',
        audio_url: null,
        option_a: 'こちらこそ',
        option_b: 'いただきます',
        option_c: 'すみません',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'いただきます (Thank you for the food / ආහාර ගැනීමට පෙර පවසන ආචාර වචනය).'
      },
      {
        order_num: 24,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the phrase that fits the most.)\n\nA: 土曜日いっしょに食事をしませんか。\nB: ＿＿＿＿＿、よていがあるんです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ごめんなさい',
        option_b: 'いいですよ',
        option_c: 'ありがとう',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ごめんなさい、よていがあるんです (I am sorry, I have other plans / සමාවෙන්න මට වෙන වැඩක් තියෙනවා).'
      },
      {
        order_num: 25,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄 (25) に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the best phrase for 25.)\n\nA: (25)＿＿＿＿＿。具合が悪そうですね。\nB: ええ、ちょっとあたまがいたくて。\nA: だいじょうぶですか。\nB: すみませんが、(26)＿＿＿＿＿いいですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q25_26.jpg',
        audio_url: null,
        option_a: 'どうもうありがとう',
        option_b: 'はじめまして',
        option_c: 'どうしたんですか',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'どうしたんですか (What happened? What is wrong? / මොකක්ද වුණේ?).'
      },
      {
        order_num: 26,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄 (26) に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the best phrase for 26.)\n\nA: (25)どうしたんですか。具合が悪そうですね。\nB: ええ、ちょっとあたまがいたくて。\nA: だいじょうぶですか。\nB: すみませんが、(26)＿＿＿＿＿いいですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q25_26.jpg',
        audio_url: null,
        option_a: '休みたい',
        option_b: '休んでも',
        option_c: '休む',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '〜てもいいですか -> 休んでもいいですか (May I take rest/time off? / විවේකයක් ගත්තට කමක් නැද්ද?).'
      },
      {
        order_num: 27,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the phrase that fits the most.)\n\nA: マリアさんはどの人ですか。\nB: そこで本を＿＿＿人です。\nA: ああ、あの人ですね。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q27.jpg',
        audio_url: null,
        option_a: '読んでいる',
        option_b: '読みます',
        option_c: '読み',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '本を読んでいる人 (The person who is reading a book / පොත කියවමින් සිටින කෙනා).'
      },
      {
        order_num: 28,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄 (28) に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the best phrase for 28.)\n\nA: もうすぐ、夏休みですね。\nB: そうですね。(28)＿＿＿をしますか。\nA: 海に行ったり、りょこう(29)＿＿＿します。\nB: いいですね。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q28_29.jpg',
        audio_url: null,
        option_a: 'いつ',
        option_b: '何',
        option_c: 'どこ',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '何をしますか (What will you do? / මොනවද කරන්නේ?).'
      },
      {
        order_num: 29,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄 (29) に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the best phrase for 29.)\n\nA: もうすぐ、夏休みですね。\nB: そうですね。(28)何をしますか。\nA: 海に行ったり、りょこう(29)＿＿＿します。\nB: いいですね。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q28_29.jpg',
        audio_url: null,
        option_a: 'し',
        option_b: 'した',
        option_c: 'したり',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '〜たり〜たりします -> りょこうしたりします (Listing actions / ක්‍රියා කිහිපයක් එක පෙළට පැවසීමේදී).'
      },
      {
        order_num: 30,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the phrase that fits the most.)\n\nA: この時計すてきですね。\nB: ありがとうございます。\nA: どこで買ったんですか。\nB: 父が誕生日に＿＿＿＿＿。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q30.jpg',
        audio_url: null,
        option_a: 'あげました',
        option_b: 'くれました',
        option_c: 'もらいました',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '父がくれました (Father gave it to me / තාත්තා මට උපන්දිනේට දුන්නා. 主語が「父が」のため「くれました」).'
      },

      // ==========================================
      // SECTION 3: LISTENING COMPREHENSION (聴解 - Choukai - Q31 to Q45)
      // ==========================================
      {
        order_num: 31,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、イラストの番号から正しいものを選んでください。\n\nA man and a woman are talking in their house. What does the woman give to the man?\n(男の人と女の人が家で話しています。女の人は男の人に何をあげますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q31.jpg',
        audio_url: '/uploads/audio/jft06_q31.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '音声の指示に従い、女の人が男の人に出した飲み物（1番）を選びます。'
      },
      {
        order_num: 32,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しいものを選んでください。\n\nA person from a travel agency is talking to the students. What will students do first?\n(旅行会社の人と学生が話しています。学生は初めに何をしますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q32.jpg',
        audio_url: '/uploads/audio/jft06_q32.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '旅行会社の案内に従い、学生が最初に行う集合写真の撮影（2番）が正解です。'
      },
      {
        order_num: 33,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しいものを選んでください。\n\nA man and the store clerk are talking. What floor does the man go?\n(男の人と店の人が話しています。男の人は何階に行きますか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft06_q33.mp3',
        option_a: '2かい',
        option_b: '6かい',
        option_c: '8かい',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '案内された8階（はっかい / 8かい）へ向かいます。'
      },
      {
        order_num: 34,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しいものを選んでください。\n\nA teacher is talking in the classroom. Which books will students bring tomorrow?\n(教室で先生が話しています。学生は明日どの本を持ってきますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q34.jpg',
        audio_url: '/uploads/audio/jft06_q34.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '先生が指定した教科書の組み合わせ（2番）を選びます。'
      },
      {
        order_num: 35,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しいものを選んでください。\n\nA man and a woman are talking. What does the man do?\n(男の人と女の人が話しています。男の人は何をしますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q35.jpg',
        audio_url: '/uploads/audio/jft06_q35.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '男性が指示に従って行う行動（1番）を選びます。'
      },
      {
        order_num: 36,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しいものを選んでください。\n\nA girl and a boy are talking. Which curtain does the girl buy?\n(女の人と男の人が話しています。女の人はどのカーテンを買いますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q36.jpg',
        audio_url: '/uploads/audio/jft06_q36.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '女性が購入を決めたカーテン（1番: 白くて長いカーテン）を選びます。'
      },
      {
        order_num: 37,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しいものを選んでください。\n\nA man and a woman are talking behind the car. Which bag does the man take?\n(車の後ろで男の人と女の人が話しています。男の人はどの鞄を持っていきますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q37.jpg',
        audio_url: '/uploads/audio/jft06_q37.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '指定された鞄（2番）を選びます。'
      },
      {
        order_num: 38,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しいものを選んでください。\n\nA woman and a station staff are talking. What number platform does the woman get on the train?\n(女の人と駅員が話しています。女の人は何番ホームの電車に乗りますか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft06_q38.mp3',
        option_a: '1ばんホームのでんしゃ',
        option_b: '2ばんホームのでんしゃ',
        option_c: '3ばんホームのでんしゃ',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '駅員が案内した「2番ホームの電車」に乗ります。'
      },
      {
        order_num: 39,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しいものを選んでください。\n\nA girl and a boy are talking. When will they go to buy the present?\n(二人はいつプレゼントを買いに行きますか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft06_q39.mp3',
        option_a: 'ふつか (2日)',
        option_b: 'みっか (3日)',
        option_c: 'よっか (4日)',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '二人がプレゼントを買いに行く日は「3日（みっか）」です。'
      },
      {
        order_num: 40,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しいものを選んでください。\n\nA man and a woman are talking in a post office. How much does the woman pay?\n(郵便局で女の人はいくら払いますか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft06_q40.mp3',
        option_a: '80円',
        option_b: '160円',
        option_c: '250円',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '郵便局で支払う金額は合計「250円」です。'
      },
      {
        order_num: 41,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しいものを選んでください。\n\nA man and a woman are talking in a library. How many books did the man borrow?\n(図書館で男の人は何冊本を借りましたか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft06_q41.mp3',
        option_a: '2さつ',
        option_b: '5さつ',
        option_c: '7さつ',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '男性が借りた本の冊数は「5冊（ごさつ）」です。'
      },
      {
        order_num: 42,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しいものを選んでください。\n\nA man and a woman are talking. How did the man go to Osaka?\n(男の人はどうやって大阪へ行きましたか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft06_q42.mp3',
        option_a: 'くるま',
        option_b: 'バス',
        option_c: 'しんかんせん',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '大阪へは「新幹線（しんかんせん）」で行きました。'
      },
      {
        order_num: 43,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しいものを選んでください。\n\nA girl and a boy are talking. What time will the girl come to school tomorrow?\n(女の子は明日何時ごろ学校に来ますか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft06_q43.mp3',
        option_a: '8時30分ごろ',
        option_b: '8時40分ごろ',
        option_c: '8時50分ごろ',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '女の子が明日学校に来る時間は「8時30分ごろ」です。'
      },
      {
        order_num: 44,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しいものを選んでください。\n\nA girl and a boy are talking. When will they go to watch the movie?\n(二人はいつ映画を見に行きますか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft06_q44.mp3',
        option_a: '今週の火曜日',
        option_b: '今週の水曜日',
        option_c: '来週の水曜日',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '二人が映画を見に行く予定は「来週の水曜日」です。'
      },
      {
        order_num: 45,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しいものを選んでください。\n\nA man and a woman are talking. Where will the woman go tomorrow?\n(女の人は明日どこへ行きますか。)',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: '/uploads/audio/jft06_q45.mp3',
        option_a: '公園',
        option_b: 'デパート',
        option_c: 'としょかん',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '女の人が明日行く場所は「図書館（としょかん）」です。'
      },

      // ==========================================
      // SECTION 4: READING COMPREHENSION (読解 - Dokkai - Q46 to Q60)
      // ==========================================
      {
        order_num: 46,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで、正しい答えを選んでください。(Read the note and choose the correct answer.)\n\nアリさんは出かける前に何をしますか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q46.jpg',
        audio_url: null,
        option_a: '学校にいきます',
        option_b: '電気をけします',
        option_c: '先生にかりた本を読みます',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'メモに「電気をけして出かけてください」と書かれているため、出かける前に電気を消します。(Turn off the lights before leaving / එළියට යාමට පෙර විදුලි පහන් නිවා දමයි).'
      },
      {
        order_num: 47,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【47/48 共通問題】\n日曜日に留学生センターで料理をしました。いろいろな国の留学生が来ていました。10時から自分の国の料理を作りました。12時にみんなで食べてどれがいちばんおいしいか選びました。いちばんおいしかったのはチンさんのぎょうざで 27点でした。にばんは私のカレーで、22点でした。さんばんはスミスさんのハンバーガーで 18点でした。\n\nいちばんおいしくなったのはどれか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q47_48.jpg',
        audio_url: null,
        option_a: 'ぎょうざ',
        option_b: 'カレー',
        option_c: 'ハンバーガー',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '「いちばんおいしかったのはチンさんのぎょうざで27点でした」とあります。(Gyoza was 1st with 27 points / ග්යෝජා පළමු ස්ථානය ලබා ගත්තේය).'
      },
      {
        order_num: 48,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'カレーは点がいくつですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q47_48.jpg',
        audio_url: null,
        option_a: '18点',
        option_b: '27点',
        option_c: '22点',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '「にばんは私のカレーで、22点でした」とあります。(Curry received 22 points / කරියට ලකුණු 22 ක් ලැබුණි).'
      },
      {
        order_num: 49,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '友達に手紙を書きました。写真をいっしょにおくりたいです。手紙はふつうにいれて 15グラム、写真は 1まい 4グラムです。写真は何まいいれることができますか。いちばん安くおくりたいです。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q49.jpg',
        audio_url: null,
        option_a: '1まい',
        option_b: '2まい',
        option_c: '3まい',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '手紙を一番安い80円（25gまで）で送る場合、手紙本体が15gなので、写真（1枚4g）は2枚（8g、合計23g）まで同封できます。3枚入れると27gとなり90円になります。(Can include at most 2 photos to stay under 25g / ලාභම 80 යෙන් ගාස්තුවෙන් යැවීමට උපරිම ඡායාරූප 2 ක් දැමිය හැක).'
      },
      {
        order_num: 50,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで、正しい答えを選んでください。\n\n朝は時間がありません。駅でパンを買って食べます。昼も仕事が忙しいですから、たいていパンとぎゅうにゅうです。晩ご飯はうちのそばのレストランでゆっくりご飯を食べます。\n\nこの人はいつもどんなものを食べていますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft06_passage_50.png',
        audio_url: null,
        option_a: '朝も夜もパンを食べます',
        option_b: '朝と昼はパンで、夜はそばを食べます',
        option_c: '朝、昼はパンで夜はレストランでご飯を食べます',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '朝と昼はパン、夜はレストランでご飯を食べると書かれています。(Eats bread for breakfast & lunch, and rice at a restaurant for dinner / උදේ සහ දවල්ට පාන්, රෑට අවන්හලකින් බත් කයි).'
      },
      {
        order_num: 51,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【51/52/53 共通問題】\n私は 11月にオーストラリアに来ました。去年02月からこちらの大学で英語を勉強します。学校がはじまるまでオーストラリアをりょこうしていて、今はアパートでこれを書いています。\n私は住んでいるところは大学がある町から少しとおいです。でも、アパートの近くにおいしいパン屋があって、コーヒーをのむこともできます。\n日本は 02月はとてもさむくなりますが、オーストラリアは、02月はとてもあつくなります。雨もあまりふりません。でも、あきはすずしくなりますから、あそびに来ませんか。\n\nこの人はいまどこにいますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft06_passage_51_53.png',
        audio_url: null,
        option_a: '中国',
        option_b: '日本',
        option_c: 'オーストラリア',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '「私は11月にオーストラリアに来ました... 今はアパートでこれを書いています」とあり、オーストラリアにいます。(Currently in Australia / දැනට ඕස්ට්‍රේලියාවේ සිටී).'
      },
      {
        order_num: 52,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '日本は02月にどうなりますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft06_passage_51_53.png',
        audio_url: null,
        option_a: 'あつくなります',
        option_b: 'さむくなります',
        option_c: '雨がふります',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '「日本は02月はとてもさむくなりますが」とあります。(In Japan it becomes very cold in Feb / ජපානයේ පෙබරවාරියේදී දැඩි සීතලක් ඇති වේ).'
      },
      {
        order_num: 53,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'ここにあっているものはどれか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft06_passage_51_53.png',
        audio_url: null,
        option_a: '大学はこの人のアパートからとおいです',
        option_b: '大学のとなりにパンやがあります',
        option_c: 'オーストラリアは02月あめがとてもふります',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '「私は住んでいるところは大学がある町から少しとおいです」と一致します。(The university is far from the apartment / විශ්වවිද්‍යාලය ඇගේ නිවසේ සිට තරමක් දුරින් පිහිටා ඇත).'
      },
      {
        order_num: 54,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '文章を読んで、正しい答えを選んでください。\n\n去年ははとひろしまへ行きました。東京からしんかんせんで行きました。私たちはげんばくドームを見ました。それからおいしい料理を食べました。ひろしまはとてもよかったです。そして、きれいでした。つぎはながさきへ行きたいです。\n\nここにあっているものはどれか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft06_passage_54.png',
        audio_url: null,
        option_a: '家族とひろしまへ行きました',
        option_b: '東京からしんかんせんでひろしまへ行ってげんばくドームを見ました',
        option_c: 'ひろしまでおいしい料理を食べたあとながさきへ行きました',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '東京から新幹線で広島へ行き原爆ドームを見たと明記されています。(Went to Hiroshima by Shinkansen from Tokyo and saw Genbaku Dome / ටෝකියෝවේ සිට ෂින්කන්සෙන් දුම්රියෙන් හිරෝෂිමාවට ගොස් පරමාණු බෝම්බ ස්මාරකය නැරඹුවා).'
      },
      {
        order_num: 55,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【55/56 共通問題】\nメニューを見て答えてください。(Look at the menu and answer the questions.)\n\n焼き魚定食のご飯大盛りにして、ホットコーヒーをちゅうもんすると、いくらになりますか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q55_56.jpg',
        audio_url: null,
        option_a: '700円',
        option_b: '800円',
        option_c: '850円',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '焼き魚定食（650円）＋ ご飯大盛り（50円）＋ 食後のホットコーヒー（150円）＝ 合計850円。(650 + 50 + 150 = 850 yen / යෙන් 850 ක් වේ).'
      },
      {
        order_num: 56,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'みそ汁をおかわりしたいとき、何曜日に言ったらいいですか。',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft06_q55_56.jpg',
        audio_url: null,
        option_a: '金曜日',
        option_b: '土曜日',
        option_c: '日曜日',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'メニューの注意書きに「みそ汁 おかわり自由 (平日のみ)」とあるため、平日である金曜日（A）が正解です。(Miso soup refill is free on weekdays only -> Friday / මිසෝ සුප් නැවත ලබාගත හැක්කේ සතියේ දිනවල පමණි -> සිකුරාදා).'
      },
      {
        order_num: 57,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【57〜60 共通問題】\nけさ田中さんはあたまがいたくて、ねつも少しありました。ですから、近くの小さい病院へ行きました。病院は家から歩いて 5 分です。先生は 60 才ぐらいです。先生がしんさつして、おくさんがくすりを作ります。この病院のしんさつの時間は午前中と、午後 3 時から 6 時までです。田中さんはくすりをもらって病院を出ました。40 分ぐらいかかりました。少しおそくなりましたが、会社へ行きました。かぜをひいたときや少しおなかがいたいときは、きんじょの人は みんなこの病院へ行きます。そして、おもい病気のときや、しゅじゅつのときは、大きい病院へ行きます。しかし、そこには人がおおぜい来ていますから、2，3 時間まちます。そして、しんさつは午前中だけですから、会社から帰ってから行くことができません。田中さんは大きい病院があまり好きではありません。\n\n次の文はＡ（小さい病院）ですか、Ｂ（大きい病院）ですか。ＡかＢを選びなさい。\n\nあまり時間がかかりません。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'A (小さい病院)',
        option_b: 'B (大きい病院)',
        option_c: 'どちらでもない',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '小さい病院は40分程度で終わり、あまり時間がかかりません。(Small clinic doesn\'t take much time / කුඩා රෝහලේදී වැඩි වේලාවක් ගත නොවේ).'
      },
      {
        order_num: 58,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'かんごふがおおぜいいます。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'A (小さい病院)',
        option_b: 'B (大きい病院)',
        option_c: 'どちらでもない',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '小さい病院は先生と奥さんの2人だけで、看護師が大勢いるのは大きい病院です。(Large hospital has many nurses / විශාල රෝහලේ හෙදියන් විශාල පිරිසක් සිටිති).'
      },
      {
        order_num: 59,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'かぜをひいて少しあたまがいたいとき、行きます。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'A (小さい病院)',
        option_b: 'B (大きい病院)',
        option_c: 'どちらでもない',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '「かぜをひいたときや少しおなかがいたいときは、きんじょの人は みんなこの病院（小さい病院）へ行きます」とあります。(Go to small clinic for mild cold/headache / සෙම්ප්‍රතිශ්‍යාව හෝ සුළු හිසරදයක් ඇති විට යන්නේ කුඩා රෝහලටයි).'
      },
      {
        order_num: 60,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '田中さんはどうして大きい病院へ行きませんでしたか。 1・2・3 の中で、いちばんいいものを選びなさい。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '大きい病院は午前中やすみだからです。',
        option_b: '会社へおそく行くたかったからです。',
        option_c: '時間が長くかかるからです。',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '大きい病院は2〜3時間待つなど時間が長くかかり、会社に遅れるため行きませんでした。(Because it takes a long time / වැඩි වේලාවක් ගත වන නිසා).'
      }
    ];

    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, order_num, section_name, question_text, question_type, 
          image_url, audio_url, option_a, option_b, option_c, option_d, 
          correct_option, marks, explanation
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId, q.order_num, q.section_name, q.question_text, q.question_type,
        q.image_url, q.audio_url, q.option_a, q.option_b, q.option_c, q.option_d,
        q.correct_option, q.marks, q.explanation
      ]);
    }

    console.log(`Successfully inserted all 60 questions for JFT Model Paper 06 (Exam ID: ${examId})`);
  } catch (err) {
    console.error('seedJftModelPaper06 error:', err);
  }
}

module.exports = { seedJftModelPaper06 };
