const { query } = require('../config/database');

async function seedJftModelPaper08() {
  try {
    const title = 'JFT-Basic Official Model Paper 08 (60 Minutes)';
    const existingExam = await query.get("SELECT id FROM exams WHERE title = ?", [title]);
    let examId;

    if (existingExam) {
      examId = existingExam.id;
      console.log(`Seeding JFT Model Paper 08 (Exam ID: ${examId})...`);
      await query.run(`
        UPDATE exams 
        SET description = 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper 08 (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [examId]);
      await query.run("DELETE FROM questions WHERE exam_id = ?", [examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (1, ?, 'Official Prometric Computer-Based JFT-Basic A2 simulation mock paper 08 (60 Questions). Features Script & Vocabulary, Conversation & Expressions, Choukai Listening Comprehension with audio tracks, and Dokkai Reading Comprehension.', 60, 200, 1)
      `, [title]);
      examId = res.id;
      console.log(`Created JFT Model Paper 08 (Exam ID: ${examId})`);
    }

    const questions = [
      // ==========================================
      // SECTION 1: Script & Vocabulary (文字・語彙 - Q01 to Q15)
      // ==========================================
      {
        order_num: 1,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q01.jpg',
        audio_url: null,
        option_a: 'さる',
        option_b: 'パンダ',
        option_c: 'うさぎ',
        option_d: '',
        correct_option: 'C',
        marks: 1,
        explanation: 'うさぎ (Rabbit / හාවා).'
      },
      {
        order_num: 2,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/images/jft08_q02.png',
        audio_url: null,
        option_a: '日本',
        option_b: 'ドイツ',
        option_c: 'ニュージーランド',
        option_d: '',
        correct_option: 'B',
        marks: 1,
        explanation: 'ドイツ (Germany / ජර්මනිය).'
      },
      {
        order_num: 3,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/images/jft08_q03.png',
        audio_url: null,
        option_a: 'ぎゅうにゅう',
        option_b: 'ぎゅうにく',
        option_c: 'ぶたにく',
        option_d: '',
        correct_option: 'A',
        marks: 1,
        explanation: 'ぎゅうにゅう (Milk / කිරි).'
      },
      {
        order_num: 4,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q04.jpg',
        audio_url: null,
        option_a: 'さんぽします',
        option_b: 'ふります',
        option_c: 'やすみます',
        option_d: '',
        correct_option: 'A',
        marks: 1,
        explanation: 'さんぽします (Walk / ඇවිදිනවා).'
      },
      {
        order_num: 5,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q05.jpg',
        audio_url: null,
        option_a: 'さとうをいれます',
        option_b: 'さとうをはいります',
        option_c: 'さとうをあげます',
        option_d: '',
        correct_option: 'A',
        marks: 1,
        explanation: 'さとうをいれます (Put in sugar / සීනි දමනවා).'
      },
      {
        order_num: 6,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q06.jpg',
        audio_url: null,
        option_a: 'パンをきります',
        option_b: 'パンをかきます',
        option_c: 'パンをあげます',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: 'パンをきります (Cut bread / පාන් කපනවා).'
      },
      {
        order_num: 7,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q07.jpg',
        audio_url: null,
        option_a: 'おこります',
        option_b: 'すわります',
        option_c: 'たちます',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: 'たちます (Stand up / නැගිටිනවා).'
      },
      {
        order_num: 8,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q08.jpg',
        audio_url: null,
        option_a: 'バナナ',
        option_b: 'きゅうり',
        option_c: 'キャベツ',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: 'きゅうり (Cucumber / පිපිඤ්ඤා).'
      },
      {
        order_num: 9,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q09.jpg',
        audio_url: null,
        option_a: 'ぶどう',
        option_b: 'すいか',
        option_c: 'バナナ',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: 'ぶどう (Grapes / මිදි).'
      },
      {
        order_num: 10,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。(Look at the illustration and choose the correct word.)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q10.jpg',
        audio_url: null,
        option_a: 'せんたっき',
        option_b: 'せんたくき',
        option_c: 'そうじき',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: 'せんたっき (Washing machine / රෙදි සෝදන යන්ත්‍රය).'
      },
      {
        order_num: 11,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined hiragana word in kanji.? Choose the correct one.\n\nあの【にんぎょう】はだれのですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '人系',
        option_b: '人形',
        option_c: '入形',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '人形 (にんぎょう - Doll / බෝනික්කා).'
      },
      {
        order_num: 12,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined hiragana word in kanji.? Choose the correct one.\n\nきむら【せんせい】は今どこにいますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '先先',
        option_b: '先生',
        option_c: '制生',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '先生 (せんせい - Teacher / ගුරුවරයා).'
      },
      {
        order_num: 13,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined hiragana word in kanji.? Choose the correct one.\n\n【やおや】はみなみにあります。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '八百屋',
        option_b: '八百家',
        option_c: '八千屋',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '八百屋 (やおや - Greengrocer / එළවළු කඩය).'
      },
      {
        order_num: 14,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined hiragana word in kanji.? Choose the correct one.\n\n【こんしゅう】の日曜日学校は休みです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '来週',
        option_b: '先週',
        option_c: '今週',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '今週 (こんしゅう - This week / මේ සතිය).'
      },
      {
        order_num: 15,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'How do you write the underlined hiragana word in kanji.? Choose the correct one.\n\n日本で【はなび】を見たことがありますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '花美',
        option_b: '花火',
        option_c: '花日',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '花火 (はなび - Fireworks / ගිනිකෙළි).'
      },

      // ==========================================
      // SECTION 2: Conversation & Expression (会話・表現 - Q16 to Q30)
      // ==========================================
      {
        order_num: 16,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\n公園に子供たちが＿＿＿＿いました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ろくさつ',
        option_b: 'ろくまい',
        option_c: 'ろくにん',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ろくにん (6 people / ළමුන් 6 දෙනෙක්. 人の数え方は「〜人」).'
      },
      {
        order_num: 17,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\n昨日友達とえいがを＿＿に行きました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '見',
        option_b: '見た',
        option_c: '見ます',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '動詞マス形＋に行きました -> 見に行きました (Went to watch / බලන්න ගියා).'
      },
      {
        order_num: 18,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\n昨日の夜 9時半＿＿テレビでテニスのしあいを見ました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'あまり',
        option_b: 'まで',
        option_c: 'で',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '9時半まで (Until 9:30 / 9:30 තෙක්).'
      },
      {
        order_num: 19,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '文を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the sentence and choose the word that fits the blank the most.)\n\nあれ＿＿中国語＿＿新聞ではありません。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'は・の',
        option_b: 'か・か',
        option_c: 'の・の',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'あれは中国語の新聞ではありません (That is not a Chinese newspaper / එය චීන භාෂා පුවත්පතක් නොවේ).'
      },
      {
        order_num: 20,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the phrase that fits the most.)\n\nりえ: トムさんのお姉さんはどんな人ですか。\nトム: かのじょは、せが＿＿＿＿、ちょっとふとい人です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'たかくて',
        option_b: 'たかい',
        option_c: 'たかく',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'せがたかくて (Tall and... / උස සහ...).'
      },
      {
        order_num: 21,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the phrase that fits the most.)\n\nA: ひろしさん、何時＿＿帰ります＿＿。\nB: 5時ごろ、帰ります。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'か・か',
        option_b: 'に・か',
        option_c: 'へ・が',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '何時に帰りますか (What time will you return? / කීයටද ආපසු එන්නේ?).'
      },
      {
        order_num: 22,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the phrase that fits the most.)\n\nA: お父さんの会社はどこに＿＿＿＿か。\nB: 父の会社は、しんじゅくにあります。\nA: お母さんもしごとを＿＿＿＿か。\nB: ええ、母は学校の先生です。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'あります・します',
        option_b: 'します・あります',
        option_c: 'います・します',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '会社はあります・しごとをします (Company exists / Does work).'
      },
      {
        order_num: 23,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the phrase that fits the most.)\n\nA: あそこにだれがいますか。\nB: ポールさんのお姉さんがいます。\nA: スージーさんは＿＿にいますか。\nB: 木のそばにたっています。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'だれ',
        option_b: 'いつ',
        option_c: 'どこ',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'どこにいますか (Where is Suzie? / සූසි කොහේද ඉන්නේ?).'
      },
      {
        order_num: 24,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄 (24) に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the best phrase for 24.)\n\nひろし: 毎朝、何時のバスにのりますか。\nリサ: 8時のバスです。\nひろし: バスていまで、歩いて(24)＿＿＿＿かかりますか。\nリサ: 10分ぐらいですよ。だから、7時45分にうちを出ます。\nひろし: そうですか。学校(25)＿＿＿＿、何分かかりますか。\nリサ: そうですね。20分ぐらいですね。\nひろし: そうですか。じゃ、学校は8時半からはじまるんですか。\nリサ: ええ、そうです。\nひろし: 毎朝、はやいですね。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'どのぐらい',
        option_b: 'いつ',
        option_c: 'いくつ',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'どのぐらいかかりますか (How long does it take? / කොපමණ වේලාවක් ගතවේද?).'
      },
      {
        order_num: 25,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄 (25) に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the best phrase for 25.)\n\nひろし: 毎朝、何時のバスにのりますか。\nリサ: 8時のバスです。\nひろし: バスていまで、歩いて(24)どのぐらいかかりますか。\nリサ: 10分ぐらいですよ。だから、7時45分にうちを出ます。\nひろし: そうですか。学校(25)＿＿＿＿、何分かかりますか。\nリサ: そうですね。20分ぐらいですね。\nひろし: そうですか。じゃ、学校は8時半からはじまるんですか。\nリサ: ええ、そうです。\nひろし: 毎朝、はやいですね。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'まで',
        option_b: 'ぐらい',
        option_c: 'ごろ',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '学校まで (To/until school / පාසල දක්වා).'
      },
      {
        order_num: 26,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄 (26) に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the best phrase for 26.)\n\nA: こんどの日曜日、友達とつりに行きます。いっしょに(26)＿＿＿＿。\nB: ええ、行きましょう。どこで会いましょうか。\nC: じゃ、6時にぼくの家に来て(27)＿＿＿＿。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '行きますか',
        option_b: '行きませんか',
        option_c: '行きましたか',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'いっしょに行きませんか (Won\'t you come with us? / අපිත් එක්ක යමුද?).'
      },
      {
        order_num: 27,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄 (27) に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the best phrase for 27.)\n\nA: こんどの日曜日、友達とつりに行きます。いっしょに(26)行きませんか。\nB: ええ、行きましょう。どこで会いましょうか。\nC: じゃ、6時にぼくの家に来て(27)＿＿＿＿。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ます',
        option_b: 'くれます',
        option_c: 'ください',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '来てください (Please come / එන්න).'
      },
      {
        order_num: 28,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄 (28) に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the best phrase for 28.)\n\nめぐみ: 昨日デパートに行きましたか。\nマイク: デパートへシャツを(28)＿＿＿＿行きました。\nめぐみ: (29)＿＿＿＿デパートへ行きましたか。\nマイク: ぎんざのデパートへ行きました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '売るに',
        option_b: '買いに',
        option_c: '着るに',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'シャツを買いに行きました (Went to buy a shirt / කමිසයක් මිලදී ගැනීමට ගියා).'
      },
      {
        order_num: 29,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄 (29) に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the best phrase for 29.)\n\nめぐみ: 昨日デパートに行きましたか。\nマイク: デパートへシャツを(28)買いに行きました。\nめぐみ: (29)＿＿＿＿デパートへ行きましたか。\nマイク: ぎんざのデパートへ行きました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'どこで',
        option_b: 'どこに',
        option_c: 'どこの',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'どこのデパート (Which department store / කොහේ තියෙන ඩිපාර්ට්මන්ට් ස්ටෝර් එකටද?).'
      },
      {
        order_num: 30,
        section_name: 'Section 2: Conversation & Expression (会話・表現)',
        question_text: '対話を読んで、空欄に入る最も適切な言葉を一つ選んでください。(Read the dialog and choose the phrase that fits the most.)\n\nA: あの木のそばに子供＿＿＿＿いますね。\nB: ええ、あの大きな木のそばですね。\nA: そうです。あの子＿＿＿＿ゆきちゃんですよ。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'が・は',
        option_b: 'の・が',
        option_c: 'に・に',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '子供がいますね・あの子はゆきちゃんですよ。'
      },

      // ==========================================
      // SECTION 3: LISTENING COMPREHENSION (聴解 - Choukai - Q31 to Q45)
      // ==========================================
      {
        order_num: 31,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、書類を戻すべき場所 (a, b, c) を選んでください。\n\nChoose the place the woman should put the documents back.\n(女性が書類を戻す場所はどこですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q31.jpg',
        audio_url: '/uploads/audio/jft08_q31.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '指示されたキャビネットの場所（c）を選びます。'
      },
      {
        order_num: 32,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、ナインさん (Nain) は誰か選んでください。\n\nWhich person is Nain?\n(ナインさんはどの人ですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q32.jpg',
        audio_url: '/uploads/audio/jft08_q32.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '畑で作業しているナインさんの特徴（b）を選びます。'
      },
      {
        order_num: 33,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、男性が遅れる理由を選んでください。\n\nChoose the reason why the man will be late.\n(男性が遅れる理由は何ですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q33.jpg',
        audio_url: '/uploads/audio/jft08_q33.mp3',
        option_a: 'a (病院 / Hospital)',
        option_b: 'b (渋滞 / Traffic jam)',
        option_c: 'c (腰痛 / Back pain)',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '男性が遅刻する理由（b: 交通渋滞）を選びます。'
      },
      {
        order_num: 34,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、原さん (Hara) はどの人か選んでください。\n\nWhich person is Hara?\n(原さんはどの人ですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q34.jpg',
        audio_url: '/uploads/audio/jft08_q34.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '特徴に合致する原さん（a）を選びます。'
      },
      {
        order_num: 35,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しい部屋のレイアウト (a, b, c) を選んでください。\n\nChoose the correct room layout.\n(正しい部屋の配置はどれですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q35.jpg',
        audio_url: '/uploads/audio/jft08_q35.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '音声で指示された部屋のレイアウト（a）を選びます。'
      },
      {
        order_num: 36,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、井口さん (Iguchi) はどの人か選んでください。\n\nWhich person is Iguchi?\n(井口さんはどの人ですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q36.jpg',
        audio_url: '/uploads/audio/jft08_q36.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '井口さんの特徴（b）を選びます。'
      },
      {
        order_num: 37,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題 - 37/38共通】音声を聞いて、薬を飲む正しい順番を選んでください。\n\nWhich of the following is the correct order to take medicine?\n(薬を飲む正しい順番はどれですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q37.jpg',
        audio_url: '/uploads/audio/jft08_q37.mp3',
        option_a: 'a (寝る前 / Before sleep)',
        option_b: 'b (食前 / Before meal)',
        option_c: 'c (食後 / After meal)',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '薬を飲むタイミング（c: 食後）が正解です。'
      },
      {
        order_num: 38,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題 - 37/38共通】音声を聞いて、服薬後にしてはいけないことを選んでください。\n\nWhat should the patient not do after taking medicine?\n(薬を飲んだ後にしてはいけないことは何ですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q38.jpg',
        audio_url: '/uploads/audio/jft08_q38.mp3',
        option_a: 'a (車の運転 / Driving)',
        option_b: 'b (飲酒 / Drinking alcohol)',
        option_c: 'c (激しい運動 / Running)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '薬を飲んだ後に禁止されていること（a: 運転）を選びます。'
      },
      {
        order_num: 39,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題 - 39/40共通】音声を聞いて、アリさんが準備するものを選んでください。\n\nWhat will Mr. Ari prepare?\n(アリさんは何を準備しますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q39.jpg',
        audio_url: '/uploads/audio/jft08_q39.mp3',
        option_a: 'a (飲み物 / Drinks)',
        option_b: 'b (コピー / Handouts)',
        option_c: 'c (机・椅子の準備 / Tables)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'アリさんが担当する準備（a: 飲み物の用意）を選びます。'
      },
      {
        order_num: 40,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題 - 39/40共通】音声を聞いて、西村さんが準備するものを選んでください。\n\nWhat will Mr. Nishimura prepare?\n(西村さんは何を準備しますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q40.jpg',
        audio_url: '/uploads/audio/jft08_q40.mp3',
        option_a: '1 (資料の配布 / Handouts on table)',
        option_b: '2 (プロジェクター / Laptop & Projector)',
        option_c: '3 (机の移動 / Tables)',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '西村さんが担当する準備（2: パソコン・機器の接続）を選びます。'
      },
      {
        order_num: 41,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、女性のコート (1, 2, 3, 4) を選んでください。\n\nWhat is the woman\'s coat?\n(女性のコートはどれですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q41.jpg',
        audio_url: '/uploads/audio/jft08_q41.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '特徴（丈の長さ、ボタン、ベルト）に合致するコート（1番）を選びます。'
      },
      {
        order_num: 42,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、正しいテーブルのセット (1, 2, 3, 4) を選んでください。\n\nHow is the table?\n(正しいテーブルの並べ方はどれですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q42.jpg',
        audio_url: '/uploads/audio/jft08_q42.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '指示通りのカトラリーの並び（1番）を選びます。'
      },
      {
        order_num: 43,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、女性の家 (1, 2, 3, 4) を選んでください。\n\nWhere is the woman\'s house?\n(女性の家はどこですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q43.jpg',
        audio_url: '/uploads/audio/jft08_q43.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '道案内に従った女性の家の位置（2番）を選びます。'
      },
      {
        order_num: 44,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、女性が買い物に行く日 (1, 2, 3, 4) を選んでください。\n\nWhen is the woman going shopping?\n(女性はいつ買い物に行きますか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q44.jpg',
        audio_url: '/uploads/audio/jft08_q44.mp3',
        option_a: '1 (2日)',
        option_b: '2 (4日)',
        option_c: '3 (6日)',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'カレンダー上で指定された日（3番: 6日）を選びます。'
      },
      {
        order_num: 45,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【リスニング問題】音声を聞いて、女性の部屋 (1, 2, 3, 4) を選んでください。\n\nWhat is the woman\'s room?\n(女性の部屋はどこですか。)',
        question_type: 'multiple_choice',
        image_url: '/uploads/images/jft08_q45.jpg',
        audio_url: '/uploads/audio/jft08_q45.mp3',
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '指定された階と部屋の位置（1番）を選びます。'
      },

      // ==========================================
      // SECTION 4: READING COMPREHENSION (読解 - Dokkai - Q46 to Q60)
      // ==========================================
      {
        order_num: 46,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【46/47/48 共通問題】\n私の友達はおとしよりに世話をするボランティアをしています。彼女は 1 か月に 2,3 回、女性のかみをきれいにしたり、けしょうをしたりします。彼女はおばあちゃんといっしょに住んでいて、おとしよりと話すのが、好きだから、このボランティアをしています。しょうらいは人をたすける仕事をしたいと言っていました。彼女によると女性はけしょうをしたときと、していないときでは、ずいぶんかわるそうです。けしょうをするとよく笑うようになるし、相手の目を見て大きい声で話すようになるそうです。日本では男性より女性のほうが元気で長生きです。理由はいろいろあると思います。けしょうが理由の一つかもしれません。\n\n友達はどうしてボランティアをしていますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft08_passage_46_48.png',
        audio_url: null,
        option_a: 'おとしよりと話すのが好きだから',
        option_b: '人とたすける仕事をしたいから',
        option_c: '女性のかみをきれいにするのが好きだから',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '「おとしよりと話すのが、好きだから、このボランティアをしています」とあります。(Because she likes talking to elderly people / වැඩිහිටියන් සමඟ කතාබස් කිරීමට කැමති නිසා).'
      },
      {
        order_num: 47,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'けしょうをしたとき女性はどうなりますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft08_passage_46_48.png',
        audio_url: null,
        option_a: '話す声が小さくなる',
        option_b: 'えがおがふえる',
        option_c: '長生きになる',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '「けしょうをするとよく笑うようになるし（笑顔が増える）」とあります。(Smiles and laughs more / සිනහව වැඩි වේ).'
      },
      {
        order_num: 48,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'ここにあっているものはどれか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft08_passage_46_48.png',
        audio_url: null,
        option_a: '私の友達は1か月に5回もボランティアをします',
        option_b: '彼女はしょうらいは人をたすける仕事をしたいと言います',
        option_c: '女性はけしょうするのがきらいです',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '「しょうらいは人をたすける仕事をしたいと言っていました」と一致します。(She wants to do a job helping people in the future / අනාගතයේදී මිනිසුන්ට උපකාර වන රැකියාවක් කිරීමට කැමතියි).'
      },
      {
        order_num: 49,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【49/50 共通問題】\nリサ\nみなさん、誕生日のメッセージありがとうございました。たくさんのあたたかいメッセージをもらって、ほんとうにうれしいです。\n日本に来てはじめて誕生日。そして、私もとうとう 30 代です。誕生日の夜は友達の山田さん、チンさんといっしょにカラオケへ行きました。歌って、おどってすごくたのしかった。二人からプレゼントをもらいました。山田さんはスマートフォンカワ―とチンさんはかわいいキーホルダーをくれました。\nありがとう。\nケーキはお店からのサービスでした。\n\n何について書いたメールですか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft08_passage_49_50.png',
        audio_url: null,
        option_a: '誕生日だったこと',
        option_b: 'プレゼントをもらったこと',
        option_c: 'ケーキを食べたこと',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '誕生日のメッセージへのお礼と誕生日の様子について書かれています。(About her birthday / උපන්දිනය පිළිබඳව).'
      },
      {
        order_num: 50,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'ここにあっているものはどれか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft08_passage_49_50.png',
        audio_url: null,
        option_a: 'ケーキは山田さんからもらいました',
        option_b: '私は今35才です',
        option_c: '山田さんはスマートフォンカバーとチンさんはかわいいキーホルダーをくれました',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '「山田さんはスマートフォンカワ―とチンさんはかわいいキーホルダーをくれました」と一致します。(Yamada gave a phone case and Chin gave a keyholder).'
      },
      {
        order_num: 51,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【51〜54 共通問題】\nゆみさん、\nお元気ですか。サンフランシスコは、毎日いいてんきです。昨日、テレビのニュースで「東京でじしんがありました。しんかんせんがとまりました。」と言いました。じしんは、どうでしたか。ゆみさんは、だいじょうぶでしたか。東京とサンフランシスコはとおいですが、テレビやインターネットなどがありますから、東京のニュースがすぐわかります。\n私は、明日から来週の木曜日まで、ヨセミテ公園でキャンプをします。アジアやヨーロッパの国の学生が来ます。でも、私のグループには、問題があります。バングラデシュのアリフさんは、ぶた肉を食べません。かんこくのシンさんは、とり肉を食べません。私は、魚がきらいです。そして、みんな料理があまり好きではありません。私はちょっとしんぱいです。\n明日の朝は 5 時におきます。ヨセミテ公園まで車で 6 時間かかります。金曜日の夜はいつも友達とダンスをしますが、今晩はダンスをしません。10 時にねます。\nでは、また手紙を書きます。さようなら。\n8月10日　ケン\n\nケンさんはどこにいますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft08_passage_51_54.png',
        audio_url: null,
        option_a: '東京',
        option_b: 'サンフランシスコ',
        option_c: 'おおさか',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '「サンフランシスコは、毎日いいてんきです」とあり、ケンはサンフランシスコにいます。(Ken is in San Francisco / කෙන් සැන් ෆ්‍රැන්සිස්කෝ හි සිටී).'
      },
      {
        order_num: 52,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'ゆみさんはどこにいますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft08_passage_51_54.png',
        audio_url: null,
        option_a: 'オーストラリア',
        option_b: 'アメリカ',
        option_c: '日本 (東京)',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '東京の地震を心配して手紙を書いているため、ゆみさんは日本（東京）にいます。(Yumi is in Tokyo, Japan / යුමි ජපානයේ ටෝකියෝ හි සිටී).'
      },
      {
        order_num: 53,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'ケンさんはどうやってとうきょうのニュースがわかりますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft08_passage_51_54.png',
        audio_url: null,
        option_a: 'ゆみさんから',
        option_b: 'テレビやインターネットなどで',
        option_c: '友達から',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '「テレビやインターネットなどがありますから、東京のニュースがすぐわかります」とあります。(Via TV and the Internet / රූපවාහිනිය සහ අන්තර්ජාලය මඟින්).'
      },
      {
        order_num: 54,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'ここにあっているものはどれか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft08_passage_51_54.png',
        audio_url: null,
        option_a: '明日から来週の木曜日まで、ヨセミテ公園でキャンプをします',
        option_b: 'バングラデシュのアリフさんは、ぶた肉を食べます',
        option_c: '昨日、テレビのニュースで「サンフランシスコでじしんがありました。」と言いました',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '「明日から来週の木曜日まで、ヨセミテ公園でキャンプをします」と一致します。(Camping at Yosemite National Park until next Thursday).'
      },
      {
        order_num: 55,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【55/56 共通問題】\nゆめで見たうち\n私の部屋のかべにまるくて、あおい月の写真がはってあります。いつもベッドに入るまえに、写真を見ます。\nある晩ゆめを見ました。私は広い部屋にいました。窓のそとにちきゅうが見えました。「ここは月のうちだ」と思いました。うれしかったです。でも、よく見ると、かべには何もかけてありません。テーブルやいすもありません。何もかざってありません。私は「こんなうちはらいやだ」と大きい声で言いました。\nすると、目がさめました。私のへやにはベッドや机がおいてあります。かべにカレンダーもかけてあります。本だなに好きな本がいろいろならべてあります。ゆめで見たうちよりいいと思いました。\n\nこの人の部屋のかべに何をはってありますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft08_passage_55_56.png',
        audio_url: null,
        option_a: '太陽の写真',
        option_b: '月の写真',
        option_c: '風の写真',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '「私の部屋のかべにまるくて、あおい月の写真がはってあります」とあります。(Photo of the blue moon on the wall).'
      },
      {
        order_num: 56,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'ここにあっているものはどれか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft08_passage_55_56.png',
        audio_url: null,
        option_a: 'この人の部屋にはベッドや机がおいてあります',
        option_b: 'この人の部屋から窓のそとにちきゅうが見えます',
        option_c: 'この人の部屋は月にあります',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '「私のへやにはベッドや机がおいてあります」とあります。(The actual room has a bed and desk).'
      },
      {
        order_num: 57,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【57/58 共通問題】\n今朝こうべで大きいじしんがありました。今私はさんのみや駅の前にいます。駅の建物はこわれて、かべの時計はとまっています。時計のはりは 5 時 46 分をさしています。じしんがあった時間です。電車はうごいていません。\n古いビルが駅前の広いみちにたおれています。たおれていないビルも窓のガラスがわれています。ビルの中を見ると、いろいろなものがこわれています。あぶないですから、入ることができません。\n\nじしんがあった時間は何時でしたか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '5時45分',
        option_b: '5時46分',
        option_c: '5時47分',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '「時計のはりは 5 時 46 分をさしています。じしんがあった時間です」とあります。(The earthquake occurred at 5:46 / භූමිකම්පාව සිදු වූ වේලාව 5:46 යි).'
      },
      {
        order_num: 58,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: 'ここにあっているものはどれか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'こうべで大きいつなみがありました',
        option_b: 'じしんのために電車はうごいていません',
        option_c: '今私はこわれているビルの中にいます',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '「じしんがあった時間です。電車はうごいていません」と一致します。(Trains are not running due to the earthquake / භූමිකම්පාව නිසා දුම්රිය ධාවනය නොවේ).'
      },
      {
        order_num: 59,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【59/60 共通問題】\n田中: 山田さん、今、何かがっきをならっていますか。\n山田: ええ、フルートをならっています。\n田中: そうですか。私はピアノをならっています。\n山田: あら、私、中学校のときに、ピアノをならっていました。でも、今フルートのほうが好きです。\n田中: もうどのくらいフルートをならっていますか。\n山田: まだ 2 年です。だから、あまりじょうずじゃないです。\n田中: 何曜日に練習していますか。\n山田: 月曜日と水曜日に先生のうちで練習しています。\n田中: フルートはピアノよりやさしいですか。\n山田: いいえ、りょうほうもむずかしいです。あなたのきょうだいも何かがっきができますか。\n田中: ええ、兄がバイオリンをひきます。ところで、今度の土曜日にうちでパーティーがあります。そのとき、私がピアノをひきますから、あなたはフルートをふきませんか。\n山田: ああ、いいですね。そうしましょう。\n\n山田さんはどのぐらいフルートをならっていますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft08_passage_59_60.png',
        audio_url: null,
        option_a: '2年間',
        option_b: '3年間',
        option_c: '4年間',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '「まだ 2 年です」とあります。(Learning flute for 2 years / වසර 2ක් පුරා ෆ්ලූට් වාදනය ඉගෙන ගනී).'
      },
      {
        order_num: 60,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '田中さんは山田さんにどうしようとていあんしていますか。',
        question_type: 'multiple_choice',
        image_url: '/images/jft08_passage_59_60.png',
        audio_url: null,
        option_a: '土曜日のパーティーでフルートをふくこと',
        option_b: 'いっしょに練習すること',
        option_c: '山田さんのうちでピアノをひくこと',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '「今度の土曜日にうちでパーティーがあります。そのとき、私がピアノをひきますから、あなたはフルートをふきませんか」と提案しています。(Invited to play flute at the Saturday party / සෙනසුරාදා සාදයේදී ෆ්ලූට් වාදනය කිරීමට ආරාධනා කරයි).'
      }
    ];

    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, order_num, section_name, question_text, question_type, 
          image_url, audio_url, option_a, option_b, option_c, option_d, 
          correct_option, marks, explanation
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId, q.order_num, q.section_name, q.question_text, q.question_type,
        q.image_url, q.audio_url, q.option_a, q.option_b, q.option_c, q.option_d,
        q.correct_option, q.marks, q.explanation
      ]);
    }

    console.log(`Successfully inserted all 60 questions for JFT Model Paper 08 (Exam ID: ${examId})`);
  } catch (err) {
    console.error('seedJftModelPaper08 error:', err);
  }
}

module.exports = { seedJftModelPaper08 };
