const { query } = require('../config/database');

async function seedJftModelPaper17() {
  console.log('Seeding JFT-Basic Official Model Paper 17 (60 Questions, Pass 200/250)...');
  const title = 'JFT-Basic Official Model Paper 17 (60 Minutes)';

  try {
    let exam = await query.get("SELECT id FROM exams WHERE title = ? OR title LIKE '%Paper 17%'", [title]);
    let examId;

    if (exam) {
      examId = exam.id;
      console.log(`Found existing Exam ID: ${examId}, resetting questions...`);
      await query.run('DELETE FROM questions WHERE exam_id = ?', [examId]);
      await query.run(`
        UPDATE exams 
        SET course_id = 1,
            title = ?,
            description = 'Official JFT-Basic Prometric Computer-Based Examination Paper 17 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Listening Audio Tracks and Sinhala Explanations)',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [title, examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (
          1,
          ?,
          'Official JFT-Basic Prometric Computer-Based Examination Paper 17 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Listening Audio Tracks and Sinhala Explanations)',
          60,
          200,
          1
        )
      `, [title]);
      examId = res.id;
      console.log(`Created new Exam ID: ${examId}`);
    }

    const questions = [
  {
    "order_num": 1,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n日本料理や寿司を作る料理人は何ですか。",
    "image_url": "/images/jft_paper17/p17_page_01_img_1.png",
    "audio_url": null,
    "option_a": "いたのえ",
    "option_b": "いたくえ",
    "option_c": "いたまえ",
    "option_d": "",
    "correct_option": "C",
    "marks": 1,
    "explanation": "ජපන් ආහාර හා සුෂි සකසන ප්‍රවීණ සූපවේදියා හඳුන්වන්නේ \"いたまえ\" (板前 - Itamae) යනුවෙනි."
  },
  {
    "order_num": 2,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n建物や部屋をきれいにする人は何ですか。",
    "image_url": "/images/jft_paper17/p17_page_01_img_2.png",
    "audio_url": null,
    "option_a": "いたまえ",
    "option_b": "せいそうにん",
    "option_c": "せいそういん",
    "option_d": "",
    "correct_option": "C",
    "marks": 1,
    "explanation": "පිරිසිදු කිරීම් සිදු කරන සේවකයා හඳුන්වන්නේ \"せいそういん\" (清掃員 - Seisouin) යනුවෙනි."
  },
  {
    "order_num": 3,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n鉄板で焼いてソースとマヨネーズをかける料理は何ですか。",
    "image_url": "/images/jft_paper17/p17_page_02_img_1.png",
    "audio_url": null,
    "option_a": "おこのみやき",
    "option_b": "ケーキ",
    "option_c": "ピザ",
    "option_d": "",
    "correct_option": "A",
    "marks": 1,
    "explanation": "පින්තූරයේ දැක්වෙන්නේ ජපන් සාම්ප්‍රදායික කෑමක් වන \"おこのみやき\" (お好み焼き - Okonomiyaki) ය."
  },
  {
    "order_num": 4,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n網の上で肉を焼いて食べる料理は何ですか。",
    "image_url": "/images/jft_paper17/p17_page_02_img_2.png",
    "audio_url": null,
    "option_a": "とりにく",
    "option_b": "やきにく",
    "option_c": "やさい",
    "option_d": "",
    "correct_option": "B",
    "marks": 1,
    "explanation": "දැලක් මත මස් පුළුස්සන ක්‍රමය හඳුන්වන්නේ \"やきにく\" (焼肉 - Yakiniku) යනුවෙනි."
  },
  {
    "order_num": 5,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\nのりでご飯や具を手で巻いて食べる寿司は何ですか。",
    "image_url": "/images/jft_paper17/p17_page_03_img_1.png",
    "audio_url": null,
    "option_a": "焼き魚",
    "option_b": "てまきずし",
    "option_c": "やきずし",
    "option_d": "",
    "correct_option": "B",
    "marks": 1,
    "explanation": "අතින් ඔතන ලද කේතු හැඩැති සුෂි හඳුන්වන්නේ \"てまきずし\" (手巻き寿司 - Temakizushi) යනුවෙනි."
  },
  {
    "order_num": 6,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n富士山が見える周りを陸に囲まれた水域は何ですか。",
    "image_url": "/images/jft_paper17/p17_page_03_img_2.png",
    "audio_url": null,
    "option_a": "みずうみ",
    "option_b": "みなと",
    "option_c": "うみ",
    "option_d": "",
    "correct_option": "A",
    "marks": 2,
    "explanation": "පින්තූරයේ දැක්වෙන්නේ ෆුජි කන්ද පාමුල පිහිටි විලක් (みずうみ - 湖) වේ."
  },
  {
    "order_num": 7,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n木がたくさん生い茂っている場所は何ですか。",
    "image_url": "/images/jft_paper17/p17_page_04_img_1.png",
    "audio_url": null,
    "option_a": "木",
    "option_b": "森",
    "option_c": "山",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "ගස් විශාල සංඛ්‍යාවක් එකට පිහිටි වනාන්තරය හඳුන්වන්නේ \"森\" (もり - Mori) යනුවෙනි."
  },
  {
    "order_num": 8,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n山の間を水が流れている自然の水路は何ですか。",
    "image_url": "/images/jft_paper17/p17_page_04_img_2.png",
    "audio_url": null,
    "option_a": "みなと",
    "option_b": "みずうみ",
    "option_c": "かわ",
    "option_d": "",
    "correct_option": "C",
    "marks": 2,
    "explanation": "පින්තූරයේ ගලා බසින ගංගාවක් (かわ - 川) දැක්වේ."
  },
  {
    "order_num": 9,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n風によってできた砂の丘は何ですか。",
    "image_url": "/images/jft_paper17/p17_page_05_img_1.png",
    "audio_url": null,
    "option_a": "やきゅう",
    "option_b": "さきゅう",
    "option_c": "あきゅう",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "වැලි කඳු (තොත්තරී වැලි කඳු) හඳුන්වන්නේ \"さきゅう\" (砂丘 - Sakyuu) යනුවෙනි."
  },
  {
    "order_num": 10,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n高い所から水が勢いよく落ちている場所は何ですか。",
    "image_url": "/images/jft_paper17/p17_page_05_img_2.png",
    "audio_url": null,
    "option_a": "かわ",
    "option_b": "たき",
    "option_c": "みずうみ",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "දිය ඇල්ල හඳුන්වන්නේ \"たき\" (滝 - Taki) යනුවෙනි."
  },
  {
    "order_num": 11,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【下線の漢字の正しいひらがなを選んでください】\n海からつよい<u>風</u>がふきます。",
    "image_url": null,
    "audio_url": null,
    "option_a": "あめ",
    "option_b": "ゆき",
    "option_c": "かぜ",
    "option_d": "",
    "correct_option": "C",
    "marks": 2,
    "explanation": "「風」කන්ජිය හි නිරවද්‍ය කියවීම \"かぜ\" (සුළඟ) වේ."
  },
  {
    "order_num": 12,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【下線の漢字の正しいひらがなを選んでください】\n日本の<u>文化</u>にきょうみがあります。",
    "image_url": null,
    "audio_url": null,
    "option_a": "ぶんがく",
    "option_b": "ぶんぽう",
    "option_c": "ぶんか",
    "option_d": "",
    "correct_option": "C",
    "marks": 2,
    "explanation": "「文化」කන්ජිය හි නිරවද්‍ය කියවීම \"ぶんか\" (සංස්කෘතිය) වේ."
  },
  {
    "order_num": 13,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【下線の漢字の正しいひらがなを選んでください】\n韓国の<u>音楽</u>をよく聞きます。",
    "image_url": null,
    "audio_url": null,
    "option_a": "おどり",
    "option_b": "おんがく",
    "option_c": "えいが",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "「音楽」කන්ජිය හි නිරවද්‍ය කියවීම \"おんがく\" (සංගීතය) වේ."
  },
  {
    "order_num": 14,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【下線の漢字の正しいひらがなを選んでください】\n去年スペインに旅行に行きました。とても<u>楽しかった</u>です。",
    "image_url": null,
    "audio_url": null,
    "option_a": "たのしかった",
    "option_b": "うれしかった",
    "option_c": "うつくしかった",
    "option_d": "",
    "correct_option": "A",
    "marks": 2,
    "explanation": "「楽しかった」කන්ජිය හි නිරවද්‍ය කියවීම \"たのしかった\" (විනෝදජනක විය) වේ."
  },
  {
    "order_num": 15,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【下線の漢字の正しいひらがなを選んでください】\n週に１<u>回</u>フランス料理を食べます。",
    "image_url": null,
    "audio_url": null,
    "option_a": "まい",
    "option_b": "かい",
    "option_c": "だい",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "වාර ගණන දැක්වෙන「回」කන්ජිය හි නිරවද්‍ය කියවීම \"かい\" (1回 = いっかい - එක් වරක්) වේ."
  },
  {
    "order_num": 16,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【文章の空欄をうめなさい】\n最近、南アメリカや東南アジアで森 (16) ＿＿＿ 少なくなってきています。\nきかいで木をきる (17) ＿＿＿ かんたんです。しかし、木をうえて森 (18) ＿＿＿ 作るのはかんたんではありません。小さな木が大きくなって、また、森ができる (19) ＿＿＿ 何十年 (20) ＿＿＿ かかるのです。",
    "image_url": "/images/jft_paper17/p17_page_07_img_1.png",
    "audio_url": null,
    "option_a": "を",
    "option_b": "に",
    "option_c": "が",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ස්වාභාවික තත්ව වෙනසක් සිදුවන ප්‍රධාන නාම පදය දැක්වීමට \"が\" නිපාතය යෙදේ (森が少なくなって)."
  },
  {
    "order_num": 17,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【文章の空欄をうめなさい】\nきかいで木をきる (17) ＿＿＿ かんたんです。",
    "image_url": "/images/jft_paper17/p17_page_07_img_1.png",
    "audio_url": null,
    "option_a": "のを",
    "option_b": "のは",
    "option_c": "のに",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ක්‍රියාවක් නාම පදයක් කර (Noun clause) වාක්‍යයේ මාතෘකාව දැක්වීමට \"のは\" යෙදේ (木を切るのは簡単です)."
  },
  {
    "order_num": 18,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【文章の空欄をうめなさい】\nしかし、木をうえて森 (18) ＿＿＿ 作るのはかんたんではありません。",
    "image_url": "/images/jft_paper17/p17_page_07_img_1.png",
    "audio_url": null,
    "option_a": "に",
    "option_b": "を",
    "option_c": "で",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "කර්මය (Direct object) දැක්වීමට \"を\" නිපාතය යෙදේ (森を作るのは)."
  },
  {
    "order_num": 19,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【文章の空欄をうめなさい】\n小さな木が大きくなって、また、森ができる (19) ＿＿＿ 何十年 (20) ＿＿＿ かかるのです。",
    "image_url": "/images/jft_paper17/p17_page_07_img_1.png",
    "audio_url": null,
    "option_a": "から",
    "option_b": "ので",
    "option_c": "まで",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "යම් නිශ්චිත අවස්ථාවක් දක්වා කාලය ගතවීම දැක්වීමට \"まで\" (දක්වා) යෙදේ (森ができるまで)."
  },
  {
    "order_num": 20,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【文章の空欄をうめなさい】\n森ができるまで 何十年 (20) ＿＿＿ かかるのです。",
    "image_url": "/images/jft_paper17/p17_page_07_img_1.png",
    "audio_url": null,
    "option_a": "も",
    "option_b": "が",
    "option_c": "で",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "කාලය හෝ ප්‍රමාණය අධික බව අවධාරණය කිරීමට සංඛ්‍යා පදයක් අගට \"も\" යෙදේ (何十年も = දශක ගණනාවක් තරම් දිගු කලක්)."
  },
  {
    "order_num": 21,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで最も適切なものを選びなさい】\n\nA : 誰（　）スキーに行く人（　）いませんか。\nB : 山田さんが行きたい（　）言っていました。",
    "image_url": null,
    "audio_url": null,
    "option_a": "か・が・と",
    "option_b": "も・も・に",
    "option_c": "か・も・が",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "නොදන්නා අයෙකු ඇසීමට \"誰か\" (යමෙක්), විෂය දැක්වීමට \"人はいませんか / 人がいませんか\", සහ අදහස ප්‍රකාශ කිරීමට \"〜と言っていました\" යෙදේ. නිවැරදි එකතුව: か・が・と."
  },
  {
    "order_num": 22,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで最も適切なものを選びなさい】\n\nA : 試合は....................。\nB : はい、もう終わりました。",
    "image_url": null,
    "audio_url": null,
    "option_a": "終わりますか",
    "option_b": "終わりましょうか",
    "option_c": "終わりましたか",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "පිළිතුර \"はい、もう終わりました\" (ඔව්, දැනටමත් අවසන් විය) වන බැවින්, අතීත කාල ප්‍රශ්නය \"終わりましたか\" විය යුතුය."
  },
  {
    "order_num": 23,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで最も適切なものを選びなさい】\n\nA : おじいさん、いらっしゃいますか。\nB : 祖父は....................出かけています。",
    "image_url": null,
    "audio_url": null,
    "option_a": "昨日",
    "option_b": "今",
    "option_c": "近く",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "වර්තමානයේ බැහැරව සිටින බව දැක්වීමට \"今出かけています\" (දැන් බැහැරව ගොස් ඇත) යෙදේ."
  },
  {
    "order_num": 24,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話とイラストを見て最も適切なものを選びなさい】\n\nA : すみません、レストランの中で(24)....................。\nB : そうですか。(25)....................。",
    "image_url": "/images/jft_paper17/p17_page_09_img_1.png",
    "audio_url": null,
    "option_a": "たばこをすったほうがいいです",
    "option_b": "たばこをすってはいけません",
    "option_c": "たばこをすわなければなりません",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "දුම්පානය තහනම් සංකේතය අනුව තහනමක් ප්‍රකාශ කරන \"たばこをすってはいけません\" (දුම්පානය නොකළ යුතුය) නිවැරදි වේ."
  },
  {
    "order_num": 25,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話とイラストを見て最も適切なものを選びなさい】\n\nA : すみません、レストランの中でたばこをすってはいけません。\nB : そうですか。(25)....................。",
    "image_url": "/images/jft_paper17/p17_page_09_img_1.png",
    "audio_url": null,
    "option_a": "ありがとう",
    "option_b": "ようこそ",
    "option_c": "すみません",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "තහනම දැනුම් දුන් විට සමාව අයැද පිළිතුරු දීමට \"すみません\" (සමාවෙන්න) යෙදේ."
  },
  {
    "order_num": 26,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで最も適切なものを選びなさい】\n\nA : 今まで、イギリスへ(26)....................ことがありますか。\nB : ええ、去年(27)....................。",
    "image_url": "/images/jft_paper17/p17_page_09_img_2.png",
    "audio_url": null,
    "option_a": "行く",
    "option_b": "行った",
    "option_c": "行かない",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "පෙර අත්දැකීමක් විමසන \"〜たことがありますか\" ව්‍යාකරණය අනුව \"行ったことがありますか\" වේ."
  },
  {
    "order_num": 27,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで最も適切なものを選びなさい】\n\nA : 今まで、イギリスへ行ったことがありますか。\nB : ええ、去年(27)....................。",
    "image_url": "/images/jft_paper17/p17_page_09_img_2.png",
    "audio_url": null,
    "option_a": "行った",
    "option_b": "行きましょう",
    "option_c": "行かないです",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "පසුගිය වසරේ (去年) සිදු වූ අතීත ක්‍රියාවක් බැවින් අතීත කාල \"行った\" (ගියා) නිවැරදි වේ."
  },
  {
    "order_num": 28,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで最も適切なものを選びなさい】\nA : きむらさんに誕生日のケーキをあげたいんですが、どうでしょう。\nB : ケーキですか。きむらさんはあまり甘いものが好きじゃないと言っていましたね。\nA : そうですか。じゃ、ケーキは(28)....................ほうがいいですね。",
    "image_url": "/images/jft_paper17/p17_page_10_img_1.png",
    "audio_url": null,
    "option_a": "出た",
    "option_b": "もらった",
    "option_c": "あげない",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "කිමුරා මහතා පැණිරස අකමැති බැවින් කේක් නොදී සිටීම සුදුසුය (ケーキはあげないほうがいいですね)."
  },
  {
    "order_num": 29,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで最も適切なものを選びなさい】\nB : 今、6時半だから(29)....................ほうがいいですよ。7時になったら、店が閉まるから。",
    "image_url": "/images/jft_paper17/p17_page_10_img_1.png",
    "audio_url": null,
    "option_a": "いそぐ",
    "option_b": "いそいだ",
    "option_c": "いそがない",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "යෝජනාවක් / උපදෙසක් දෙන \"〜たほうがいい\" ව්‍යාකරණය අනුව \"いそいだほうがいい\" (ඉක්මන් කළහොත් හොඳයි) නිවැරදි වේ."
  },
  {
    "order_num": 30,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【会話を読んで最も適切なものを選びなさい】\nA : じゃ、タクシーで(30)....................ほうがいいですね。",
    "image_url": "/images/jft_paper17/p17_page_10_img_1.png",
    "audio_url": null,
    "option_a": "行く",
    "option_b": "行かない",
    "option_c": "行った",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "උපදෙසක් පිළිගනිමින් \"〜たほうがいい\" ව්‍යාකරණය අනුව \"タクシーで行ったほうがいいですね\" (ටැක්සියකින් ගියොත් හොඳයි) නිවැරදි වේ."
  },
  {
    "order_num": 31,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\n正しくないのはどれですか。",
    "image_url": null,
    "audio_url": "/audio/jft_paper17/jft17_q31.mp3",
    "option_a": "今はしゅふで、かいごを勉強しています",
    "option_b": "来年からかんごしのしごとします",
    "option_c": "来年から病院へ入院します",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩය අනුව ඇය ලබන වසරේ රෝහලක හෙදියක ලෙස වැඩ කිරීමට නියමිත අතර රෝහල් ගත වීමක් (入院) සිදු නොවේ."
  },
  {
    "order_num": 32,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\n正しいのはどれですか。",
    "image_url": null,
    "audio_url": "/audio/jft_paper17/jft17_q32.mp3",
    "option_a": "家族は主人と夫です",
    "option_b": "オーストリアで日本語をべんきょうしています",
    "option_c": "オーストリア人だけど家族と東京に住んでいます",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ඔස්ට්‍රියානු ජාතිකයෙකු වන නමුත් පවුලේ අය සමඟ ටෝකියෝවේ ජීවත් වන බව ශ්‍රව්‍ය පටයේ සඳහන් වේ."
  },
  {
    "order_num": 33,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\nシンさんは会社までどうやって行きますか。",
    "image_url": "/images/jft_paper17/p17_page_11_img_1.png",
    "audio_url": "/audio/jft_paper17/jft17_q33_q40.mp3",
    "option_a": "自転車",
    "option_b": "歩いて",
    "option_c": "電車",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "ශින් මහතා සමාගමට යන්නේ පාපැදියෙනි (自転車 - Jitensha)."
  },
  {
    "order_num": 34,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\nシンさんは会社までどのぐらいかかりますか。",
    "image_url": "/images/jft_paper17/p17_page_11_img_1.png",
    "audio_url": "/audio/jft_paper17/jft17_q33_q40.mp3",
    "option_a": "10分",
    "option_b": "25分",
    "option_c": "15分",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "සමාගමට යාමට විනාඩි 15ක් ගතවේ (15分 - Juugofun)."
  },
  {
    "order_num": 35,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\nジョイさんは日本語の学校までどうやって行きますか。",
    "image_url": "/images/jft_paper17/p17_page_12_img_1.png",
    "audio_url": "/audio/jft_paper17/jft17_q33_q40.mp3",
    "option_a": "自転車",
    "option_b": "自動車",
    "option_c": "車",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ජෝයි මහතා පාසලට යන්නේ මෝටර් රථයෙනි (車 - Kuruma)."
  },
  {
    "order_num": 36,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\nジョイさんは日本語の学校までどのぐらいかかりますか。",
    "image_url": "/images/jft_paper17/p17_page_12_img_1.png",
    "audio_url": "/audio/jft_paper17/jft17_q33_q40.mp3",
    "option_a": "20分",
    "option_b": "45分",
    "option_c": "40分",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ජපන් භාෂා පාසලට යාමට විනාඩි 40ක් ගතවේ (40分 - Yonjuppun)."
  },
  {
    "order_num": 37,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\nさとうさんは会社までどうやって行きますか。",
    "image_url": "/images/jft_paper17/p17_page_12_img_2.png",
    "audio_url": "/audio/jft_paper17/jft17_q33_q40.mp3",
    "option_a": "自転車",
    "option_b": "車",
    "option_c": "電車",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "සතෝ මහත්මිය රැකියාවට යන්නේ මෝටර් රථයෙනි (車)."
  },
  {
    "order_num": 38,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\nさとうさんは会社までどのぐらいかかりますか。",
    "image_url": "/images/jft_paper17/p17_page_12_img_2.png",
    "audio_url": "/audio/jft_paper17/jft17_q33_q40.mp3",
    "option_a": "1時間半",
    "option_b": "1時間",
    "option_c": "2時間",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "සතෝ මහත්මියට රැකියාවට යාමට පැය එකහමාරක් (1時間半 - Ichijikan-han) ගතවේ."
  },
  {
    "order_num": 39,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\n吉田さんは会社までどうやって行きますか。",
    "image_url": "/images/jft_paper17/p17_page_14_img_1.png",
    "audio_url": "/audio/jft_paper17/jft17_q33_q40.mp3",
    "option_a": "電車",
    "option_b": "車",
    "option_c": "自転車",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "යොෂිඩා මහතා රැකියාවට යන්නේ දුම්රියෙනි (電車 - Densha)."
  },
  {
    "order_num": 40,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\n吉田さんは会社までどのぐらいかかりますか。",
    "image_url": "/images/jft_paper17/p17_page_14_img_1.png",
    "audio_url": "/audio/jft_paper17/jft17_q33_q40.mp3",
    "option_a": "35分",
    "option_b": "30分",
    "option_c": "40分",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "යොෂිඩා මහතාට විනාඩි 30ක් (30分 - Sanjuppun) ගතවේ."
  },
  {
    "order_num": 41,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて、ワークシートの①にあてはまる組み合わせを選びなさい】\n① (　) を つくります。",
    "image_url": "/images/jft_paper17/p17_page_15_img_1.png",
    "audio_url": "/audio/jft_paper17/jft17_q41_q43.mp3",
    "option_a": "a・b",
    "option_b": "a・c",
    "option_c": "a・d",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "සාදන ද්‍රව්‍ය (つくります) වන්නේ කැවිලි (a: おかし) සහ බෝනික්කන් (d: にんぎょう) වේ (a・d)."
  },
  {
    "order_num": 42,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて、ワークシートの②にあてはまる組み合わせを選びなさい】\n② (　) を あつめます。",
    "image_url": "/images/jft_paper17/p17_page_15_img_1.png",
    "audio_url": "/audio/jft_paper17/jft17_q41_q43.mp3",
    "option_a": "c・b",
    "option_b": "c・e",
    "option_c": "b・d",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "එකතු කරන ද්‍රව්‍ය (あつめます) වන්නේ කාසි (b: コイン) සහ බෝනික්කන් (d: にんぎょう) වේ (b・d)."
  },
  {
    "order_num": 43,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて、ワークシートの③にあてはまる組み合わせを選びなさい】\n③ ホールで (　) を 見ます。",
    "image_url": "/images/jft_paper17/p17_page_15_img_1.png",
    "audio_url": "/audio/jft_paper17/jft17_q41_q43.mp3",
    "option_a": "c・b",
    "option_b": "c・d",
    "option_c": "c・e",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ශාලාවේ නරඹන්නේ ඔපෙරා (c: オペラ) සහ නාට්‍ය (e: えんげき) වේ (c・e)."
  },
  {
    "order_num": 44,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて正しいこたえを選びなさい】\nカーラさんの趣味は何ですか。\n(a: 外国のコインをあつめること / b: サッカーのしあいを見ること / c: おかしをつくること / d: 外国語をべんきょうすること)",
    "image_url": "/images/jft_paper17/p17_page_17_img_2.png",
    "audio_url": "/audio/jft_paper17/jft17_q44_q45.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "d",
    "correct_option": "C",
    "marks": 5,
    "explanation": "කාර්ලා මහත්මියගේ විනෝදාංශය කැවිලි සෑදීමයි (c: おかしをつくること)."
  },
  {
    "order_num": 45,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて正しいこたえを選びなさい】\nキムさんの趣味は何ですか。\n(a: 外国のコインをあつめること / b: サッカーのしあいを見ること / c: おかしをつくること / d: 外国語をべんきょうすること)",
    "image_url": "/images/jft_paper17/p17_page_17_img_2.png",
    "audio_url": "/audio/jft_paper17/jft17_q44_q45.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "d",
    "correct_option": "A",
    "marks": 5,
    "explanation": "කිම් මහතාගේ විනෝදාංශය විදේශීය කාසි එකතු කිරීමයි (a: 外国のコインをあつめること)."
  },
  {
    "order_num": 46,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【カプセルホテルの文章を読んで答えなさい】\nカプセルホテルがある場所はどこですか。",
    "image_url": "/images/jft_paper17/p17_page_19_img_1.png",
    "audio_url": null,
    "option_a": "東京",
    "option_b": "ちほう（地方）",
    "option_c": "",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "ඡේදයේ පළමු වාක්‍යය අනුව කැප්සියුල් හෝටල් බහුලව පිහිටා ඇත්තේ ටෝකියෝ නගරයේය (東京)."
  },
  {
    "order_num": 47,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【カプセルホテルの文章を読んで答えなさい】\nカプセルホテルのかたちはどんなかたちですか。",
    "image_url": "/images/jft_paper17/p17_page_19_img_1.png",
    "audio_url": null,
    "option_a": "ふつうのホテルとおなじ",
    "option_b": "小さい部屋がたくさんある",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "බෙහෙත් කැප්සියුලයක හැඩය ගත් කුඩා කාමර රාශියක් මී වදයක ආකාරයෙන් පේළියට පිහිටා ඇත (小さい部屋がたくさんある)."
  },
  {
    "order_num": 48,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【カプセルホテルの文章を読んで答えなさい】\nカプセルホテルの部屋の中はどうですか。",
    "image_url": "/images/jft_paper17/p17_page_19_img_1.png",
    "audio_url": null,
    "option_a": "せまい",
    "option_b": "ひろい",
    "option_c": "",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "කාමරය ඉතා පටු වන අතර (せまい), ඇඳෙන් බැස කෙළින් සිට ගැනීමට පවා නොහැකි තරම් කුඩාය."
  },
  {
    "order_num": 49,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【カプセルホテルの文章を読んで答えなさい】\nカプセルホテルをよく利用する人はだれですか。",
    "image_url": "/images/jft_paper17/p17_page_19_img_1.png",
    "audio_url": null,
    "option_a": "かんこうきゃく（観光客）",
    "option_b": "サラリーマン",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ටෝකියෝවේ සේවය කරන රැකියාලාභීන් (サラリーマン - වැටුප් ලබන සේවකයන්) මෙම හෝටල් නිතර භාවිත කරයි."
  },
  {
    "order_num": 50,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【カプセルホテルの文章を読んで答えなさい】\nこの文の「ハチのす」は何のことですか。",
    "image_url": "/images/jft_paper17/p17_page_19_img_1.png",
    "audio_url": null,
    "option_a": "会社",
    "option_b": "ハチの家",
    "option_c": "ホテル",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "කුඩා කාමර පේළි පිටින් පිරුණු හෝටලය උපමාවකින් හඳුන්වා ඇත්තේ \"ハチのす\" (මී වදය = ホテル) ලෙසයි."
  },
  {
    "order_num": 51,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【カプセルホテルの文章を読んで答えなさい】\nこの文の「たくさんの働きバチ」は何のことですか。",
    "image_url": "/images/jft_paper17/p17_page_19_img_1.png",
    "audio_url": null,
    "option_a": "むし（虫）",
    "option_b": "ホテルの人",
    "option_c": "サラリーマン",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "උදෑසන වැඩට පිටත්ව යන සේවකයන්ව \"働きバチ\" (වැඩකාර මී මැස්සන් = サラリーマン) ලෙස රූපකයෙන් දක්වා ඇත."
  },
  {
    "order_num": 52,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【カプセルホテルの文章を読んで答えなさい】\nどうしてカプセルホテルができましたか。",
    "image_url": "/images/jft_paper17/p17_page_19_img_1.png",
    "audio_url": null,
    "option_a": "夜遅くまで、趣味を楽しみたいから",
    "option_b": "夜遅くまで仕事をして、家に帰れないから",
    "option_c": "家族といっしょに食事をしたり、話したりしたくないから",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "රැකියාවේ රාත්‍රී කාලය වන තෙක් අතිකාල වැඩ කර දුර බැහැර පිහිටි නිවෙස් වලට යාමට නොහැකි සේවකයන් වෙනුවෙන් කැප්සියුල් හෝටල් බිහිවිය."
  },
  {
    "order_num": 53,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【アルバイトの文章を読んで答えなさい】\nやまもとさんは、両親から毎月送ってもらうお金はどうしていますか。",
    "image_url": "/images/jft_paper17/p17_page_20_img_1.png",
    "audio_url": null,
    "option_a": "大学にはらっています。",
    "option_b": "生活や旅行、あそびのために使っています。",
    "option_c": "きっさてんにはらっています。",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "විශ්වවිද්‍යාල ගාස්තු දෙමාපියන් කෙලින්ම ගෙවන අතර, එවන රුපියල් ලක්ෂයක මුදල ජීවන වියදම් හා විනෝද චාරිකා සඳහා යොදා ගනී."
  },
  {
    "order_num": 54,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【アルバイトの文章を読んで答えなさい】\nやまもとさんは今アルバイトをどう思っていますか。",
    "image_url": "/images/jft_paper17/p17_page_20_img_1.png",
    "audio_url": null,
    "option_a": "今の仕事は早くやめてもっと勉強する時間を作りたいです",
    "option_b": "仕事がいそがしくて大学に行けないのでやめたいです",
    "option_c": "仕事もあまり大変ではないし、もらえるお金も悪くないです",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "කැෆේ රැකියාව එතරම් වෙහෙසකර නොවන අතර ලැබෙන වැටුපද සතුටුදායක බව යමමොතෝ පවසයි (仕事もあまり大変ではないし、もらうお金も悪くない)."
  },
  {
    "order_num": 55,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【アルバイトの文章を読んで答えなさい】\nアルバイトのことを正しく説明しているのはどれですか。",
    "image_url": "/images/jft_paper17/p17_page_20_img_1.png",
    "audio_url": null,
    "option_a": "学生はきっさてんのアルバイトは1日1時間しかできません",
    "option_b": "図書館で本を貸す手伝いをするアルバイトはもらえるお金が少ないです",
    "option_c": "両親から10万円おくってもらえるとアルバイトをしなくてもいいです",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "පුස්තකාලයේ වාඩිවී කරන පහසු රැකියාවට පැයකට ලැබෙන්නේ යෙන් 600ක් වැනි අඩු මුදලකි (もらえるお金が少ないです)."
  },
  {
    "order_num": 56,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【日本まつりボランティアカードを読んで答えなさい】\nタイラー・モスさんがしたい仕事は何ですか。",
    "image_url": "/images/jft_paper17/p17_page_21_img_1.png",
    "audio_url": null,
    "option_a": "あんない・うけつけ",
    "option_b": "しかい・うけつけ",
    "option_c": "さつえい・うけつけ",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "කාඩ්පතේ \"したい仕事\" (කැමති කාර්යයන්) ලෙස ඔහු රවුම් කර ඇත්තේ \"さつえい\" (ඡායාරූප ගැනීම) සහ \"うけつけ\" (පිළිගැනීමේ කටයුතු) ය."
  },
  {
    "order_num": 57,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【日本まつりボランティアカードを読んで答えなさい】\nタイラー・モスさんは何ができますか。",
    "image_url": "/images/jft_paper17/p17_page_21_img_1.png",
    "audio_url": null,
    "option_a": "日本語と韓国語がはなすことができます",
    "option_b": "パソコンの使い方がわかります",
    "option_c": "日本語でコンピューターでタイプすることができます",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "කාඩ්පතේ \"できること\" (හැකියාවන්) හි \"コンピューターがつかえます\" (පරිගණක භාවිතය දනී) සඳහන් වේ."
  },
  {
    "order_num": 58,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【日本まつりカラオケコンテストのおしらせを読んで、正しいものに〇、ちがうものに×を選んでください】\nこの会場で食事をしてもいいです。",
    "image_url": "/images/jft_paper17/p17_page_22_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "නිවේදනයේ \"飲食はご遠慮ください\" (කෑම බීම ගැනීමෙන් වළකින්න) ලෙස තහනම් කර ඇති බැවින් ප්‍රකාශය වැරදිය (×)."
  },
  {
    "order_num": 59,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【日本まつりカラオケコンテストのおしらせを読んで、正しいものに〇、ちがうものに×を選んでください】\nこれは歌を歌うコンテストです。",
    "image_url": "/images/jft_paper17/p17_page_22_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "මෙය කැරෝකී ගායන තරඟයක් (カラオケコンテスト = 歌を歌うコンテスト) බැවින් ප්‍රකාශය නිවැරදිය (〇)."
  },
  {
    "order_num": 60,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【日本まつりカラオケコンテストのおしらせを読んで、正しいものに〇、ちがうものに×を選んでください】\nこの会場で映画を見ることもできます。",
    "image_url": "/images/jft_paper17/p17_page_22_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "මෙම උත්සවයේ චිත්‍රපට නැරඹීමක් පිළිබඳව සඳහන් නොවන බැවින් ප්‍රකාශය වැරදිය (×)."
  }
];

    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, section_name, order_num, question_text, question_type,
          option_a, option_b, option_c, option_d, correct_option, marks, explanation,
          image_url, audio_url
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId,
        q.section_name,
        q.order_num,
        q.question_text,
        'multiple_choice',
        q.option_a,
        q.option_b,
        q.option_c,
        q.option_d || '',
        q.correct_option,
        q.marks,
        q.explanation,
        q.image_url,
        q.audio_url
      ]);
    }

    console.log(`Successfully seeded ${questions.length} questions for Paper 17 (Exam ${examId})`);
  } catch (err) {
    console.error('Error seeding JFT Paper 17:', err);
  }
}

module.exports = { seedJftModelPaper17 };
