const { query } = require('../config/database');

async function seedJLPTN5Paper02() {
  try {
    console.log('====================================================');
    console.log('Seeding JLPT N5 Official Examination - July 2024 (Paper 02)...');
    console.log('====================================================');

    const course = await query.get("SELECT id, code, name FROM courses WHERE id = 2 OR code = 'JLPT-N5'");
    if (!course) {
      throw new Error("Course JLPT-N5 (ID: 2) not found in database.");
    }
    const courseId = course.id;
    console.log(`Target Course: ${course.name} (ID: ${courseId})`);

    const title = 'JLPT N5 Official Examination - July 2024 (Paper 02)';
    const description = 'Official JLPT N5 Examination from July 2024 (Paper 02). Features all 3 sections: Language Knowledge (Vocabulary), Language Knowledge (Grammar) & Reading, and Listening Comprehension with authentic audio and high-resolution diagrams.';

    // Check if exam record already exists
    let exam = await query.get("SELECT * FROM exams WHERE course_id = ? AND title = ?", [courseId, title]);

    let examId;
    if (exam) {
      examId = exam.id;
      console.log(`Found existing Exam record with ID: ${examId}`);
      await query.run(`
        UPDATE exams
        SET title = ?,
            course_id = ?,
            duration_minutes = 105,
            passing_score = 50,
            total_marks = 180,
            description = ?,
            category = 'JLPT-N5',
            is_active = 1
        WHERE id = ?
      `, [title, courseId, description, examId]);
    } else {
      console.log('Creating new Exam record for Paper 02...');
      const insertResult = await query.run(`
        INSERT INTO exams (course_id, title, duration_minutes, passing_score, total_marks, description, category, is_active)
        VALUES (?, ?, 105, 50, 180, ?, 'JLPT-N5', 1)
      `, [courseId, title, description]);
      examId = insertResult.id;
      console.log(`Created Exam record with ID: ${examId}`);
    }

    const audioTrackUrl = '/audio/n5_paper2_listening.mp3';

    const questionsData = [
      // =========================================================================
      // SECTION 1: 言語知識（文字・語彙） (Q01 to Q21, 1 mark each = 21 marks)
      // =========================================================================
      {
        order_num: 1,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題１　＿＿＿の　ことばは　どう　よみますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nいま 店の まえにいます。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'いえ',
        option_b: 'えき',
        option_c: 'みせ',
        option_d: 'へや',
        correct_option: 'C',
        marks: 1,
        explanation: '「店」の読み方は「みせ」です。「いま みせの まえにいます。」（I am currently in front of the store.）',
        explanation_sin: '「店」කියවන්නේ「みせ」(මිසෙ - කඩය/සාප්පුව) ලෙසයි. දැන් කඩය ඉදිරිපිට සිටිමි.'
      },
      {
        order_num: 2,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題１　＿＿＿の　ことばは　どう　よみますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nたなかさんは いま 外国に います。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'がいしゃ',
        option_b: 'かいしゃ',
        option_c: 'かいこく',
        option_d: 'がいこく',
        correct_option: 'D',
        marks: 1,
        explanation: '「外国」の読み方は「がいこく」です。「たなかさんは いま がいこくに います。」（Tanaka is currently in a foreign country.）',
        explanation_sin: '「外国」කියවන්නේ「がいこく」(ගයිකොකු - විදේශ රට) ලෙසයි. තනකා මහතා දැන් විදේශ රටක සිටී.'
      },
      {
        order_num: 3,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題１　＿＿＿の　ことばは　どう　よみますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nさとうさんは 話が じょうずです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'うた',
        option_b: 'はなし',
        option_c: 'え',
        option_d: 'じ',
        correct_option: 'B',
        marks: 1,
        explanation: '「話」の読み方は「はなし」です。「さとうさんは はなしが じょうずです。」（Sato is good at talking/storytelling.）',
        explanation_sin: '「話」කියවන්නේ「はなし」(හනශි - කතාව/දෙබස) ලෙසයි. සාතෝ මහතා කතාවට දක්ෂයි.'
      },
      {
        order_num: 4,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題１　＿＿＿の　ことばは　どう　よみますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nはやしさんも 読んで ください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'あそんで',
        option_b: 'ならんで',
        option_c: 'よんで',
        option_d: 'えらんで',
        correct_option: 'C',
        marks: 1,
        explanation: '「読んで」の読み方は「よんで」です（動詞：読む）。「はやしさんも よんで ください。」（Hayashi, please read too.）',
        explanation_sin: '「読んで」කියවන්නේ「よんで」(යොන්දෙ - කියවන්න) ලෙසයි. හයාෂි මහතාත් කියවන්න.'
      },
      {
        order_num: 5,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題１　＿＿＿の　ことばは　どう　よみますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nあたらしい こうえんは まちの 北がわに あります。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ひがしがわ',
        option_b: 'みなみがわ',
        option_c: 'にしがわ',
        option_d: 'きたがわ',
        correct_option: 'D',
        marks: 1,
        explanation: '「北がわ」の読み方は「きたがわ」です。「北（きた）＋ 側（がわ）」＝ 北側（north side / north side of the town）。',
        explanation_sin: '「北がわ」කියවන්නේ「きたがわ」(කිතගාවා - උතුරු පැත්ත) ලෙසයි. අලුත් උද්‍යානය නගරයේ උතුරු පැත්තේ පිහිටා ඇත.'
      },
      {
        order_num: 6,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題１　＿＿＿の　ことばは　どう　よみますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nわたしは 九月に けっこんします。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'くがつ',
        option_b: 'きゅうがつ',
        option_c: 'くげつ',
        option_d: 'きゅうげつ',
        correct_option: 'A',
        marks: 1,
        explanation: '「九月」の読み方は「くがつ」です（September）。きゅうがつとは読みません。',
        explanation_sin: '「九月」කියවන්නේ විශේෂිතව「くがつ」(කුගත්සු - සැප්තැම්බර් මාසය) ලෙසයි.'
      },
      {
        order_num: 7,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題１　＿＿＿の　ことばは　どう　よみますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nきのう 来なかった ひとは だれですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'きなかった',
        option_b: 'こなかった',
        option_c: 'いなかった',
        option_d: 'ねなかった',
        correct_option: 'B',
        marks: 1,
        explanation: '「来る（くる）」のカ変動詞の過去否定形「来なかった」は「こなかった」と読みます（person who did not come）。',
        explanation_sin: '「来る(くる)」ක්‍රියාපදයේ අතීත සෘණ රූපය「来なかった」කියවන්නේ「こなかった」(කොනකත්තා - ආවේ නැති) ලෙසයි.'
      },
      {
        order_num: 8,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題２　＿＿＿の　ことばは　どう　かきますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nてんきが わるいですから、うちに いましょう。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '天汽',
        option_b: '矢気',
        option_c: '天気',
        option_d: '矢汽',
        correct_option: 'C',
        marks: 1,
        explanation: '「てんき」の正しい漢字表記は「天気」です（weather）。',
        explanation_sin: '「てんき」(කාලගුණය) සඳහා නිවැරදි කන්ජි අක්ෂර වන්නේ「天気」වේ.'
      },
      {
        order_num: 9,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題２　＿＿＿の　ことばは　どう　かきますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nあちらの そらを みてください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '犬',
        option_b: '花',
        option_c: '山',
        option_d: '空',
        correct_option: 'D',
        marks: 1,
        explanation: '「そら」の漢字表記は「空」です（sky）。（犬＝いぬ、花＝はな、山＝やま）。',
        explanation_sin: '「そら」(අහස) සඳහා නිවැරදි කන්ජි අක්ෂරය වන්නේ「空」(සොරා) වේ.'
      },
      {
        order_num: 10,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題２　＿＿＿の　ことばは　どう　かきますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nさとうさんも たってください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '立って',
        option_b: '食って',
        option_c: '位って',
        option_d: '喰って',
        correct_option: 'A',
        marks: 1,
        explanation: '「たつ（立つ）」のテ形は「立って」です（Please stand up）。',
        explanation_sin: '「たって」(නැගිටින්න) සඳහා නිවැරදි කන්ජි අක්ෂරය「立って」වේ.'
      },
      {
        order_num: 11,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題２　＿＿＿の　ことばは　どう　かきますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nがくせいは なんにん いますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '先生',
        option_b: '学生',
        option_c: '学主',
        option_d: '先主',
        correct_option: 'B',
        marks: 1,
        explanation: '「がくせい」の正しい漢字表記は「学生」です（student）。先生は「せんせい」です。',
        explanation_sin: '「がくせい」(ශිෂ්‍යයා) සඳහා නිවැරදි කන්ජි වන්නේ「学生」වේ.'
      },
      {
        order_num: 12,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題２　＿＿＿の　ことばは　どう　かきますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nかいだんを おりて ください。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '上りて',
        option_b: '止りて',
        option_c: '不りて',
        option_d: '下りて',
        correct_option: 'D',
        marks: 1,
        explanation: '階段を「おりる」の漢字は「下りる」で、「下りて」となります（Please go down the stairs）。',
        explanation_sin: '「おりて」(පහළට බහින්න) සඳහා නිවැරදි කන්ජි වන්නේ「下りて」වේ.'
      },
      {
        order_num: 13,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題３　（　）に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nえいがの（　）を ２まい かいました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ケーキ',
        option_b: 'チケット',
        option_c: 'ギター',
        option_d: 'タクシー',
        correct_option: 'B',
        marks: 1,
        explanation: '薄い紙や券を数える助数詞「まい（枚）」を使い、映画を見るためのものは「チケット（ticket）」です。',
        explanation_sin: 'චිත්‍රපට නැරඹීම සඳහා මිලදී ගන්නේ「チケット」(ප්‍රවේශ පත්‍ර / tickets) ය.'
      },
      {
        order_num: 14,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題３　（　）に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nびょういんは うちから（　）ですから、バスで いきます。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ながい',
        option_b: 'おおい',
        option_c: 'おそい',
        option_d: 'とおい',
        correct_option: 'D',
        marks: 1,
        explanation: 'バスで行く理由として、家から距離があることを表す形容詞「とおい（遠い / far）」が入ります。',
        explanation_sin: 'නිවසේ සිට රෝහල දුර බැවින්「とおい」(දුරයි) යන්න නිවැරදියි.'
      },
      {
        order_num: 15,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題３　（　）に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nきょうは いもうとの 12（　）のたんじょうびです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ねん',
        option_b: 'さい',
        option_c: 'だい',
        option_d: 'えん',
        correct_option: 'B',
        marks: 1,
        explanation: '年齢を数える助数詞は「さい（歳/才）」です。「12さいのたんじょうび（12th birthday）」。',
        explanation_sin: 'වයස ප්‍රකාශ කිරීමට යොදන නිපාතය「さい」(වයස / years old) වේ.'
      },
      {
        order_num: 16,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題３　（　）に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n（　）を わすれましたから、おかねを もって いません。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'かぎ',
        option_b: 'とけい',
        option_c: 'さいふ',
        option_d: 'かさ',
        correct_option: 'C',
        marks: 1,
        explanation: 'お金を入れて持ち歩くものは「さいふ（財布 / wallet）」です。財布を忘れたからお金を持っていません。',
        explanation_sin: 'මුදල් දමන පසුම්බිය හඳුන්වන්නේ「さいふ」(පසුම්බිය / wallet) ලෙසයි.'
      },
      {
        order_num: 17,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題３　（　）に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nりょこうの ときは くろい くつを（　）。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'はきます',
        option_b: 'つけます',
        option_c: 'かけます',
        option_d: 'かぶります',
        correct_option: 'A',
        marks: 1,
        explanation: '靴やズボンなど足・下半身に身につける動詞は「はきます（履きます）」です（wear shoes）。',
        explanation_sin: 'සපත්තු, මේස්, කලිසම් පැළඳීමට යොදන ක්‍රියාපදය「はきます」(පළඳිනවා) වේ.'
      },
      {
        order_num: 18,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題３　（　）に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nきょうは じゅぎょうの あと、すぐ いえに（　）。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'かえります',
        option_b: 'すみます',
        option_c: 'あるきます',
        option_d: 'でかけます',
        correct_option: 'A',
        marks: 1,
        explanation: '授業のあと自分の家へ戻る動作は「かえります（帰ります / return home）」です。',
        explanation_sin: 'පන්තිය අවසන් වූ පසු ආපසු නිවසට යන බැවින්「かえります」(ආපසු යනවා) නිවැරදිය.'
      },
      {
        order_num: 19,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題４　＿＿＿の　ぶんと　だいたい　おなじ　いみの　ぶんが　あります。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nけさ、はやしさんに あいました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'きのうの あさ、はやしさんに あいました。',
        option_b: 'きょうの ひる、はやしさんに あいました。',
        option_c: 'きょうの あさ、はやしさんに あいました。',
        option_d: 'きのうの ひる、はやしさんに あいました。',
        correct_option: 'C',
        marks: 1,
        explanation: '「けさ（今朝）」は「きょうの あさ（this morning）」と同義です。',
        explanation_sin: '「けさ」(අද උදෑසන) යනු「きょうの あさ」(අද උදේ) යන අර්ථයම ලබාදෙයි.'
      },
      {
        order_num: 20,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題４　＿＿＿の　ぶんと　だいたい　おなじ　いみの　ぶんが　あります。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nこの かんじは かんたんです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'この かんじは やさしいです。',
        option_b: 'この かんじは むずかしいです。',
        option_c: 'この かんじは おもしろいです。',
        option_d: 'この かんじは つまらないです。',
        correct_option: 'A',
        marks: 1,
        explanation: '「かんたん（簡単）」は「やさしい（easy / simple）」と同じ意味です。',
        explanation_sin: '「かんたん」(පහසු/සරල) යන්නට සමාන අර්ථය「やさしい」ලබාදෙයි.'
      },
      {
        order_num: 21,
        section_name: '言語知識（文字・語彙） - Language Knowledge (Vocabulary)',
        question_text: '問題４　＿＿＿の　ぶんと　だいたい　おなじ　いみの　ぶんが　あります。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nたなかさんは リーさんに さくぶんを おしえました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'リーさんは たなかさんに さくぶんを わたしました。',
        option_b: 'たなかさんは リーさんに さくぶんを ならいました。',
        option_c: 'たなかさんは リーさんに さくぶんを わたしました。',
        option_d: 'リーさんは たなかさんに さくぶんを ならいました。',
        correct_option: 'D',
        marks: 1,
        explanation: '「Aが Bに 教える（A teaches B）」は、視点を変えると「Bが Aに 習う（B learns from A）」と同じ意味になります。田中さんが教えたので、リーさんは田中さんに習いました。',
        explanation_sin: 'තනකා මහතා ලී ට ඉගැන්වූවා යන්නෙහි සමාන අර්ථය වන්නේ "ලී, තනකා මහතාගෙන් ඉගෙන ගත්තා" (リーさんは たなかさんに さくぶんを ならいました) යන්නයි.'
      },

      // =========================================================================
      // SECTION 2: 言語知識（文法）・読解 (Q22 to Q43, 2 marks each = 44 marks)
      // =========================================================================
      {
        order_num: 22,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　（　）に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n私は 一か月（　）２回、ギターを 習っています。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'も',
        option_b: 'が',
        option_c: 'を',
        option_d: 'に',
        correct_option: 'D',
        marks: 2,
        explanation: 'ある期間に対する頻度を表す助詞は「に」を用います：「一か月に２回（twice a month）」。',
        explanation_sin: 'කාල සීමාවක සංඛ්‍යාතය (frequency) දැක්වීමට「〜に〜回」ලෙස「に」නිපාතය යොදයි.'
      },
      {
        order_num: 23,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　（　）に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n日曜日に買い物（　）さんぽをします。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'へ',
        option_b: 'も',
        option_c: 'や',
        option_d: 'ぐらい',
        correct_option: 'C',
        marks: 2,
        explanation: '名詞の代表例を並列する助詞は「や」です：「買い物や さんぽ（shopping and walking, etc.）」。',
        explanation_sin: 'නාමපද ලැයිස්තුගත කර උදාහරණ දැක්වීමට「や」(සහ / ආදිය) නිපාතය යොදා ගැනේ.'
      },
      {
        order_num: 24,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　（　）に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n私の 母は 銀行（　）はたらいています。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'が',
        option_b: 'で',
        option_c: 'へ',
        option_d: 'に',
        correct_option: 'B',
        marks: 2,
        explanation: '動作・勤務が行われる場所を示す助詞「で」が適切です。「銀行ではたらいています（works at a bank）」。',
        explanation_sin: 'යම් ස්ථානයක ක්‍රියාවක් හෝ රැකියාවක් කරන බව දැක්වීමට ස්ථාන නිපාතය「で」යොදයි.'
      },
      {
        order_num: 25,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　（　）に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n私は 新しい カメラ（　）ほしいです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'で',
        option_b: 'か',
        option_c: 'に',
        option_d: 'が',
        correct_option: 'D',
        marks: 2,
        explanation: '願望を表すイ形容詞「ほしい」の対象は助詞「が」で表します：「カメラが ほしい（want a camera）」。',
        explanation_sin: '「ほしい」(අවශ්‍යයි/ඕනෑ) සමඟ අවශ්‍ය වන වස්තුව දැක්වීමට「が」නිපාතය යොදා ගනී.'
      },
      {
        order_num: 26,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　（　）に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nきのう 私は デパートに 行きましたが、（　）買いませんでした。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '何を',
        option_b: '何も',
        option_c: '何か',
        option_d: '何に',
        correct_option: 'B',
        marks: 2,
        explanation: '疑問詞＋「も」＋否定形で全面否定を表します：「何も 買いませんでした（didn\'t buy anything）」。',
        explanation_sin: 'සම්පූර්ණ සෘණාර්ථය (කිසිවක් මිලදී ගත්තේ නෑ) දැක්වීමට「何も」(කිසිවක්) සමඟ「〜ませんでした」යෙදේ.'
      },
      {
        order_num: 27,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　（　）に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nＡ食堂の ラーメンは、大学の 食堂の ラーメンより（　）おいしいです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'あまり',
        option_b: 'すぐ',
        option_c: 'ずっと',
        option_d: 'いちばん',
        correct_option: 'C',
        marks: 2,
        explanation: '２つのものを比較して差が大きいことを強調する副詞は「ずっと」です：「〜より ずっと おいしい（much more delicious than...）」。',
        explanation_sin: 'සංසන්දනයකදී වඩාත් වැඩි බව දැක්වීමට「ずっと」(වඩා බෙහෙවින්/much more) යෙදේ.'
      },
      {
        order_num: 28,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　（　）に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n（店で）\nＡ「このペンは（　）ですか。」\nＢ「100円です。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'いくら',
        option_b: 'いくつ',
        option_c: 'どれ',
        option_d: 'どうして',
        correct_option: 'A',
        marks: 2,
        explanation: '値段（100円）を聞く疑問詞は「いくら（How much?）」です。いくつ＝個数、どれ＝選択、どうして＝理由。',
        explanation_sin: 'මිල ගණන් ඇසීමට යොදන ප්‍රශ්න වචනය「いくら」(කීයද / how much) වේ.'
      },
      {
        order_num: 29,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　（　）に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nきのうの夜、（　）前に 本を 読みました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'ねる',
        option_b: 'ねて',
        option_c: 'ねた',
        option_d: 'ねている',
        correct_option: 'A',
        marks: 2,
        explanation: '「動詞辞書形 ＋ 前に（before doing ...）」の文法規則に従い、辞書形「ねる」が入ります。「ねる まえに（before sleeping）」。',
        explanation_sin: '「〜前に」(පෙර) යෙදීමේදී ක්‍රියාපදයේ මූලික ශබ්දකෝෂ ස්වරූපය (Dictionary Form)「ねる」යෙදේ.'
      },
      {
        order_num: 30,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題１　（　）に　なにを　いれますか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nリー「林さん、にもつが多いですね。少し（　）。」\n林「あ、すみません。おねがいします。」',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '持っていませんか',
        option_b: '持たないでください',
        option_c: 'もちましたね',
        option_d: '持ちましょうか。',
        correct_option: 'D',
        marks: 2,
        explanation: '相手を手伝う申し出の表現は「〜ましょうか（Shall I ...?）」です。「少し持ちましょうか（Shall I carry some of it?）」。',
        explanation_sin: 'අන් අයට උදව් කිරීමට යෝජනා කරන විට「〜ましょうか」(මම අල්ලා ගන්නද?) ස්වරූපය යොදයි.'
      },
      {
        order_num: 31,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題２　★に　入る　ものは　どれですか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n私は たんじょうびに ____ ____ ★ ____ 使って います。\n１：くれた　２：毎日　３：カメラを　４：そふが',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'くれた',
        option_b: '毎日',
        option_c: 'カメラを',
        option_d: 'そふが',
        correct_option: 'A',
        marks: 2,
        explanation: '正しい文の組み立て：私は たんじょうびに 【２：毎日】 【４：そふが】 ★【１：くれた】 【３：カメラを】 使っています。（毎日祖父がくれたカメラを使っています）。★の位置に入るのは「１：くれた」です。',
        explanation_sin: 'නිවැරදි වාක්‍ය සැකැස්ම:「毎日(2) そふが(4) ★くれた(1) カメラを(3)」වේ. ★ ස්ථානයට 1 (くれた) ලැබේ.'
      },
      {
        order_num: 32,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題２　★に　入る　ものは　どれですか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nこうえん ____ ____ ★ ____ たくさんいます。\n１：鳥　２：に　３：は　４：が',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '鳥',
        option_b: 'に',
        option_c: 'は',
        option_d: 'が',
        correct_option: 'A',
        marks: 2,
        explanation: '正しい文の組み立て：こうえん 【２：に】 【３：は】 ★【１：鳥】 【４：が】 たくさんいます。（公園には鳥がたくさんいます）。★の位置に入るのは「１：鳥」です。',
        explanation_sin: 'නිවැරදි වාක්‍ය සැකැස්ම:「公園 に(2) は(3) ★鳥(1) が(4) たくさんいます」වේ. ★ ස්ථානයට 1 (鳥) ලැබේ.'
      },
      {
        order_num: 33,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題２　★に　入る　ものは　どれですか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n今年の夏 ____ ____ ★ ____ 山に行きます。\n１：海　２：では　３：は　４：なくて',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '海',
        option_b: 'では',
        option_c: 'は',
        option_d: 'なくて',
        correct_option: 'B',
        marks: 2,
        explanation: '正しい文の組み立て：今年の夏 【３：は】 【１：海】 ★【２：では】 【４：なくて】 山に行きます。（今年の夏は海ではなくて山に行きます）。★の位置に入るのは「２：では」です。',
        explanation_sin: 'නිවැරදි වාක්‍ය සැකැස්ම:「今年の夏 は(3) 海(1) ★では(2) なくて(4) 山に行きます」වේ. ★ ස්ථානයට 2 (では) ලැබේ.'
      },
      {
        order_num: 34,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題２　★に　入る　ものは　どれですか。１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n私は 毎朝 へやを ____ ____ ★ ____ 出ます。\n１：を　２：から　３：家　４：そうじして',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'を',
        option_b: 'から',
        option_c: '家',
        option_d: 'そうじして',
        correct_option: 'C',
        marks: 2,
        explanation: '正しい文の組み立て：私は 毎朝 へやを 【４：そうじして】 【２：から】 ★【３：家】 【１：を】 出ます。（部屋をそうじしてから家を出ます）。★の位置に入るのは「３：家」です。',
        explanation_sin: 'නිවැරදි වාක්‍ය සැකැස්ම:「へやを そうじして(4) から(2) ★家(3) を(1) 出ます」වේ. ★ ස්ථානයට 3 (家) ලැබේ.'
      },
      {
        order_num: 35,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題３　つぎの　ぶんしょうを　読んで、14から 17の　なかに　入る　いちばん　いい　ものを、１・２・３・４から　ひとつ　えらんで　ください。\n\nきのう、友だちと えいがを 見ました。\n駅の近く（14）新しい えいがかん で 見ました。とても 大きい えいがかんでした。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'も',
        option_b: 'は',
        option_c: 'の',
        option_d: 'と',
        correct_option: 'C',
        marks: 2,
        explanation: '「駅の近く（名詞）」と「新しいえいがかん（名詞）」をつなぐ助詞は「の」です（a new movie theater near the station）。',
        explanation_sin: 'නාමපද දෙකක් සම්බන්ධ කිරීමට「の」නිපාතය යෙදේ (駅の近くの 新しい えいがかん).'
      },
      {
        order_num: 36,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題３　つぎの　ぶんしょうを　読んで、14から 17の　なかに　入る　いちばん　いい　ものを、１・２・３・４から　ひとつ　えらんで　ください。\n\nえいがかんは 広くて、とても きれいでした。\nまた（15）。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '行ってください',
        option_b: '行きたいです',
        option_c: '来てください',
        option_d: '来たいです',
        correct_option: 'B',
        marks: 2,
        explanation: '映画館がとても綺麗だったという感想に続き、筆者自身の希望を述べる文脈なので「行きたいです（I want to go again）」が最も適切です。',
        explanation_sin: 'තමන් නැවත එහි යාමට කැමති බව ප්‍රකාශ කිරීමට「また 行きたいです」(නැවත යන්න ඕනෑ) යොදයි.'
      },
      {
        order_num: 37,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題３　つぎの　ぶんしょうを　読んで、14から 17の　なかに　入る　いちばん　いい　ものを、１・２・３・４から　ひとつ　えらんで　ください。\n\n日曜日に 日本りょうりの クラスに 行きました。\nはじめは、おにぎりを 作りました。（16）、やさいの みそしるを 作りました。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'いつも',
        option_b: 'もう',
        option_c: 'しかし',
        option_d: 'それから',
        correct_option: 'D',
        marks: 2,
        explanation: '「はじめは（at first）」と対応し、次の動作・順序を繋ぐ接続詞は「それから（and then / after that）」です。',
        explanation_sin: 'ක්‍රියා පිළිවෙළ දැක්වීමේදී මුලින්ම (はじめは) කළ දෙයට පසු ඊළඟට කළ දේ දැක්වීමට「それから」(ඊට පස්සේ / and then) යෙදේ.'
      },
      {
        order_num: 38,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題３　つぎの　ぶんしょうを　読んで、14から 17の　なかに　入る　いちばん　いい　ものを、１・２・３・４から　ひとつ　えらんで　ください。\n\nおにぎりは 少し むずかしかったです。でも、みそしるは（17）。\nクラスは とても たのしかったです。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'かんたんでした',
        option_b: 'かんたんだったからです',
        option_c: 'かんたんではありませんでした',
        option_d: 'かんたんではなかったからです',
        correct_option: 'A',
        marks: 2,
        explanation: '逆接の接続詞「でも（but）」で対比されているため、「おにぎりは むずかしかった（difficult）↔ みそしるは かんたんでした（easy）」が文脈として完璧に成立します。',
        explanation_sin: '「でも」(නමුත්) ඇති බැවින්, ඔනිගිරි අමාරු වුවත් මිසොශිරු ලේසි විය යන ප්‍රතිවිරුද්ධ අර්ථය දැක්වීමට「かんたんでした」යෙදේ.'
      },
      {
        order_num: 39,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題４　つぎの　ぶんを　読んで、しつもんに　こたえて　ください。こたえは、１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n大友さん\nこんにちは、ムムです。\nつくえの上に おいしい おかしが ありました。\n旅行の おみやげですね。\nありがとうございました。\n\n【しつもん】このメールで、ムムさんは 大友さんに 何が言いたいですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'おかしを ありがとうございます。',
        option_b: 'わたしも 旅行に 行きたいです。',
        option_c: '今、大友さんは どこに いますか。',
        option_d: 'わたしも おかしが 好きです。',
        correct_option: 'A',
        marks: 2,
        explanation: 'ムムさんは大友さんが机に置いてくれた旅行土産のお菓子について「ありがとうございました」とお礼を伝えています（Thank you for the sweets）。',
        explanation_sin: 'මෙම කෙටි පණිවිඩයෙන් මුමු පවසන්නේ සංචාරක තිළිණය ලෙස තැබූ රසකැවිලි වලට ස්තූතියි「おかしを ありがとうございます」යන්නයි.'
      },
      {
        order_num: 40,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題４　つぎの　ぶんを　読んで、しつもんに　こたえて　ください。こたえは、１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\n学生の ときは、電車の中で 友だちと よく 話しました。でも、会社の人になってからは、電車の中で 一人で 本を 読んで います。電車の中は しずかで、本を 読むのに いい 時間です。\n\n【しつもん】「私」は今、電車の中で何をしますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: '友だちと話します。',
        option_b: '友だちと本を読みます。',
        option_c: '一人で本を読みます。',
        option_d: '会社の人と話します。',
        correct_option: 'C',
        marks: 2,
        explanation: '本文に「会社の人になってからは、電車の中で 一人で 本を 読んで います」と明記されているため、「一人で本を読みます」が正解です。',
        explanation_sin: 'පෙළෙහි පැහැදිලිවම "දැන් සමාගමේ සේවකයෙකු වූ පසු තනිවම දුම්රිය තුළ පොත් කියවනවා" (一人で本を読みます) ලෙස සඳහන් වේ.'
      },
      {
        order_num: 41,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題５　つぎの　ぶんしょうを　読んで、しつもんに　こたえて　ください。こたえは、１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nきのう、はじめて 青木山に 行きました。駅の前から バスで 30分でした。山を のぼりはじめると、山から おりてくる 人たちが「こんにちは。」と 言ってくれました。私は ①うれしかったです。私も「こんにちは。」と 言いました。\n山の上で おべんとうを 食べました。とても おいしかったです。山の上で 会った 女の人が「来月は さくらの 花が さいて、もっと きれいです。」と 教えてくれました。私は ②来月また行きたいです。\n\n【しつもん１】どうして ①うれしかったですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'はじめて 青木山に のぼったから。',
        option_b: '山で ぜんぜん つかれなかったから。',
        option_c: '山で 会った 人たちと いっしょに 山に のぼったから。',
        option_d: '山で 会った 人たちが「私」に「こんにちは。」と 言ったから。',
        correct_option: 'D',
        marks: 2,
        explanation: '「山から おりてくる 人たちが『こんにちは。』と 言ってくれました。私は うれしかったです。」とあるので、山で出会った人たちが挨拶してくれたことが理由です。',
        explanation_sin: 'කන්දෙන් බැස එන මිනිසුන් "කොන්නිචිවා" කියා ආචාර කළ නිසා සතුටු වූ බව පෙළෙහි පැහැදිලිව දක්වා ඇත.'
      },
      {
        order_num: 42,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題５　つぎの　ぶんしょうを　読んで、しつもんに　こたえて　ください。こたえは、１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nきのう、はじめて 青木山に 行きました。駅の前から バスで 30分でした。山を のぼりはじめると、山から おりてくる 人たちが「こんにちは。」と 言ってくれました。私は ①うれしかったです。私も「こんにちは。」と 言いました。\n山の上で おべんとうを 食べました。とても おいしかったです。山の上で 会った 女の人が「来月は さくらの 花が さいて、もっと きれいです。」と 教えてくれました。私は ②来月また行きたいです。\n\n【しつもん２】どうして ②来月また行きたいですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: null,
        option_a: 'さくらの 花が 見たいから。',
        option_b: 'さくらではない ほかの花も 見たいから。',
        option_c: '山で 会った 女の人に また会いたいから。',
        option_d: '山で もっと たくさんの人と 話したいから。',
        correct_option: 'A',
        marks: 2,
        explanation: '山の上で会った女の人から「来月は さくらの 花が さいて、もっと きれいです」と教えられ、その桜の花が見たいためです。',
        explanation_sin: 'ලබන මස සකුරා මල් පිපී තවත් ලස්සන වන බව පැවසූ බැවින් සකුරා මල් නැරඹීමට නැවත යාමට අවශ්‍ය විය.'
      },
      {
        order_num: 43,
        section_name: '言語知識（文法）・読解 - Language Knowledge (Grammar) & Reading',
        question_text: '問題６　右の　チラシを　見て、しつもんに　こたえて　ください。こたえは、１・２・３・４から　いちばん　いい　ものを　ひとつ　えらんで　ください。\n\nダトさんは、たまごと りんごを 安い日に 買いたいです。いつ どの店へ 行きますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper2/reading_q22_flyer.jpg',
        audio_url: null,
        option_a: '13日に④、14日に②',
        option_b: '13日に④、15日に①',
        option_c: '14日に②、15日に①',
        option_d: '14日に②、15日に④',
        correct_option: 'A',
        marks: 2,
        explanation: 'チラシの特売条件：たまごの特売最安値は13日の④番の店（1パック100円）、りんごの特売最安値は14日の②番の店（1個80円）です。したがって「13日に④、14日に②」が正解です。',
        explanation_sin: 'පත්‍රිකාවට අනුව, බිත්තර වඩාත්ම ලාභ වන්නේ 13 වන දින 4 වන වෙළඳසැලෙන් වන අතර, ඇපල් වඩාත්ම ලාභ වන්නේ 14 වන දින 2 වන වෙළඳසැලෙන් වේ. එබැවින් නිවැරදි පිළිතුර A වේ.'
      },

      // =========================================================================
      // SECTION 3: 聴解 (Listening Comprehension - Q44 to Q67, 2 marks each = 48 marks)
      // =========================================================================
      {
        order_num: 44,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題１　問題１では、まず しつもんを 聞いて ください。それから 話を 聞いて、問題用紙の １から ４の 中から、いちばん いい ものを ひとつ えらんで ください。\n\n１番：男の人と 女の人が 話しています。二人は 何を 注文しますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper2/listening_m1_q1.jpg',
        audio_url: audioTrackUrl,
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'B',
        marks: 2,
        explanation: '男の人と女の人のカフェでの注文内容：女の人はコーヒーとケーキ、男の人は温かい紅茶を注文します。この組み合わせは２番のイラストです。',
        explanation_sin: 'පිරිමි පුද්ගලයා සහ කාන්තාව ඇණවුම් කරන්නේ 2 වන රූපයේ දැක්වෙන සංයෝජනයයි (කෝපි + කේක් සහ තේ).'
      },
      {
        order_num: 45,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題１\n\n２番：男の学生と 女の学生が 話しています。女の学生は 何色の ペンを 使いますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'みどり',
        option_b: 'あお',
        option_c: 'きいろ',
        option_d: 'ちゃいろ',
        correct_option: 'A',
        marks: 2,
        explanation: '男の学生が持っているペンの中から、女の学生はノートを目立たせるために「みどり（緑）」のペンを選んで使います。',
        explanation_sin: 'ශිෂ්‍යාව භාවිතා කිරීමට තෝරාගන්නේ කොළ පැහැති「みどり」(හරිත) පෑනයි.'
      },
      {
        order_num: 46,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題１\n\n３番：男の人と 女の人が 話しています。二人は 何曜日に 会いますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'かようび',
        option_b: 'すいようび',
        option_c: 'もくようび',
        option_d: 'きんようび',
        correct_option: 'B',
        marks: 2,
        explanation: '会う曜日の相談：火曜日は男の人の都合が悪く、木曜日以降も予定があるため、二人の都合が合う「すいようび（水曜日 / Wednesday）」に決定します。',
        explanation_sin: 'දෙදෙනාගේම වේලාව ගැලපෙන පරිදි හමුවීමට තීරණය කරන්නේ බදාදා「すいようび」දිනයි.'
      },
      {
        order_num: 47,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題１\n\n４番：男の人が 話しています。学生は いくら 払いますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '300えん',
        option_b: '500えん',
        option_c: '600えん',
        option_d: '800えん',
        correct_option: 'B',
        marks: 2,
        explanation: '案内によると一般料金は800円ですが、学生証の提示により学生料金は「500えん（500円）」となります。',
        explanation_sin: 'සාමාන්‍ය අය කිරීම යෙන් 800 වුවත්, ශිෂ්‍යයන් ගෙවිය යුතු මුදල වන්නේ යෙන් 500「500えん」වේ.'
      },
      {
        order_num: 48,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題１\n\n５番：男の人と 女の人が 話しています。女の人は どこへ 行きますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper2/listening_m1_q5.jpg',
        audio_url: audioTrackUrl,
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'C',
        marks: 2,
        explanation: '地図を用いた道案内：まっすぐ進んで二つ目の角を曲がり、銀行の隣にある目的地の「3番」へ向かいます。',
        explanation_sin: 'සංවාදයේ ලබාදුන් උපදෙස් අනුව කාන්තාව යන්නේ 3 වන ස්ථානය වෙතයි.'
      },
      {
        order_num: 49,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題１\n\n６番：男の先生が 話しています。学生は 明日 何を 持ってきますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'ノートとペン',
        option_b: 'ノートとのみもの',
        option_c: 'ペンとのみもの',
        option_d: 'のみものだけ',
        correct_option: 'C',
        marks: 2,
        explanation: '先生の持ち物の指示：ノートやプリント類は教室で配るため不要ですが、メモを取るための筆記用具（ペン）と水分補給の飲み物は持参する必要があるため「ペンとのみもの」が正解です。',
        explanation_sin: 'ගුරුවරයාගේ උපදෙස් පරිදි සිසුන් හෙට රැගෙන ආ යුත්තේ පෑන සහ පානයන්「ペンとのみもの」වේ.'
      },
      {
        order_num: 50,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題１\n\n７番：女の人と 男の人が 話しています。鍵は どうやって 開けますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper2/listening_m1_q7.jpg',
        audio_url: audioTrackUrl,
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'D',
        marks: 2,
        explanation: '電子錠の開け方の説明：暗証番号を入力した後にレバーを右に回す操作手順を示しているのは「4番」のイラストです。',
        explanation_sin: 'යතුර විවෘත කරන නිවැරදි පියවර අනුපිළිවෙළ 4 වන රූප සටහනින් දැක්වේ.'
      },
      {
        order_num: 51,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題２　問題２では、まず しつもんを 聞いて ください。そのあと、問題用紙の せんたくしを 読んで ください。読む 時間が あります。それから 話を 聞いて、問題用紙の １から ４の 中から、いちばん いい ものを ひとつ えらんで ください。\n\n１番：男の人と 女の人が 話しています。男の人は 今週末 どの スポーツを しますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper2/listening_m2_q1.jpg',
        audio_url: audioTrackUrl,
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'A',
        marks: 2,
        explanation: '今週末にするスポーツの会話：サッカーや野球の誘いもありますが、男の人は友人と約束しているテニス（1番）をします。',
        explanation_sin: 'පිරිමි පුද්ගලයා මෙම සති අන්තයේ මිතුරන් සමඟ කරන්නේ 1 වන ක්‍රීඩාව (ටෙනිස්) වේ.'
      },
      {
        order_num: 52,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題２\n\n２番：男の人と 女の人が 絵を 見て 話しています。女の人が 好きな 絵は どれですか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper2/listening_m2_q2.jpg',
        audio_url: audioTrackUrl,
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'D',
        marks: 2,
        explanation: '絵の好みの会話：海や山だけの絵ではなく、動物が描かれている自然の絵が好きだと言っており、条件に合致するのは「4番」の絵です。',
        explanation_sin: 'කාන්තාව වඩාත්ම ප්‍රිය කරන චිත්‍රය වන්නේ 4 වන පින්තූරයයි.'
      },
      {
        order_num: 53,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題２\n\n３番：男の人と 女の人が 話しています。女の人は どれを 買いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper2/listening_m2_q3.jpg',
        audio_url: audioTrackUrl,
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'D',
        marks: 2,
        explanation: '商品の選択：サイズが大きくポケットが付いているデザインを希望し、最終的に「4番」の商品を購入することに決めました。',
        explanation_sin: 'කාන්තාව මිලදී ගැනීමට තෝරාගන්නේ 4 වන අයිතමයයි.'
      },
      {
        order_num: 54,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題２\n\n４番：男の人と 女の人が 話しています。二人は お昼ご飯に 何を 食べますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'ラーメン',
        option_b: 'カレー',
        option_c: 'うどん',
        option_d: 'そば',
        correct_option: 'C',
        marks: 2,
        explanation: '昼食の相談：ラーメン屋は行列でカレーの気分でもないため、すぐ近くにある店で「うどん」を食べることに合意しました。',
        explanation_sin: 'දෙදෙනා සාකච්ඡා කර දවල් ආහාරය සඳහා තෝරාගන්නේ「うどん」(උදොන් නූඩ්ල්ස්) ය.'
      },
      {
        order_num: 55,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題２\n\n５番：男の人と 女の人が 話しています。二人は どこで 会いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper2/listening_m2_q5.jpg',
        audio_url: audioTrackUrl,
        option_a: '1',
        option_b: '2',
        option_c: '3',
        option_d: '4',
        correct_option: 'B',
        marks: 2,
        explanation: '待ち合わせ場所の確認：北口の改札を出たすぐ右手にある本屋の前（2番）で待ち合わせることにしました。',
        explanation_sin: 'දෙදෙනා හමුවීමට තීරණය කරන්නේ 2 වන ස්ථානයේදීය.'
      },
      {
        order_num: 56,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題２\n\n６番：男の人と 女の人が 話しています。会議室は 何階ですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '2階',
        option_b: '3階',
        option_c: '5階',
        option_d: '7階',
        correct_option: 'D',
        marks: 2,
        explanation: '社内での会議室の確認：いつも使う3階や5階ではなく、本日の大会議室は「7階（ななかい）」に設定されています。',
        explanation_sin: 'අද දින රැස්වීම් කාමරය පිහිටා ඇත්තේ 7 වන මහලේ「7階」(නනකායි) ය.'
      },
      {
        order_num: 57,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題３　問題３では、絵を 見ながら 質問を 聞いて ください。矢印（➡）の 人は 何と 言いますか。１から ３の 中から、いちばん いい ものを ひとつ えらんで ください。\n\n１番：時計を 見ながら 何と 言いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper2/listening_m3_q1.jpg',
        audio_url: audioTrackUrl,
        option_a: '今、何時？',
        option_b: '時計、ある？',
        option_c: '何時に行く？',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '時計を見ながら相手に現在時刻を尋ねる適切な表現は「今、何時？（What time is it now?）」です。',
        explanation_sin: 'වේලාව විමසීමට යෝග්‍ය ප්‍රකාශය「今、何時？」(දැන් වෙලාව කීයද?) වේ.'
      },
      {
        order_num: 58,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題３\n\n２番：友達の 誕生日に プレゼントを 渡します。何と 言いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper2/listening_m3_q2.jpg',
        audio_url: audioTrackUrl,
        option_a: 'おめでとう。',
        option_b: 'ありがとう。',
        option_c: 'いただきます。',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '誕生日のプレゼントを渡す際、相手を祝う言葉は「おめでとう。（Happy Birthday / Congratulations）」です。',
        explanation_sin: 'උපන්දිනයකට සුබ පතමින් තෑග්ගක් දෙන විට පවසන්නේ「おめでとう」(සුබ පැතුම්) ය.'
      },
      {
        order_num: 59,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題３\n\n３番：漢字の 読み方が 分かりません。何と 言いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper2/listening_m3_q3.jpg',
        audio_url: audioTrackUrl,
        option_a: 'これは、誰の漢字ですか。',
        option_b: 'これは、何と読みますか。',
        option_c: 'これは、どう書きますか。',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '漢字の読み方を質問する表現は「これは、何と読みますか。（How do you read this?）」です。',
        explanation_sin: 'කන්ජිය කියවන ආකාරය අන් අයගෙන් ඇසීමට「これは、何と読みますか」(මෙය කියවන්නේ කෙසේද?) යැයි අසයි.'
      },
      {
        order_num: 60,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題３\n\n４番：雨が 降ってきました。傘を 持っていない 人に 何と 言いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper2/listening_m3_q4.jpg',
        audio_url: audioTrackUrl,
        option_a: '傘を買いましたか。',
        option_b: '傘を持っていきますか。',
        option_c: 'この傘を使ってください。',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '雨の中で傘がなくて困っている人に自分の傘を貸す表現は「この傘を使ってください。（Please use this umbrella）」です。',
        explanation_sin: 'කුඩයක් නැති කෙනෙකුට තම කුඩය පිරිනමමින් පවසන්නේ「この傘を使ってください」(මෙම කුඩය භාවිතා කරන්න) යන්නයි.'
      },
      {
        order_num: 61,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題３\n\n５番：交番で 道を 聞きます。何と 言いますか。',
        question_type: 'multiple_choice',
        image_url: '/images/n5_paper2/listening_m3_q5.jpg',
        audio_url: audioTrackUrl,
        option_a: 'すみません、駅はどこですか。',
        option_b: '駅に行きますか。',
        option_c: '駅は遠いですか。',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '交番（警察署）で駅への道を尋ねる丁寧な切り出しは「すみません、駅はどこですか。（Excuse me, where is the station?）」です。',
        explanation_sin: 'පොලිස් මුරපොළකදී පාර අසන විට「すみません、駅はどこですか」(සමාවෙන්න, දුම්රිය ස්ථානය කොහේද?) යැයි විමසයි.'
      },
      {
        order_num: 62,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題４　問題４は、絵などが ありません。文を 聞いて、１から ３の 中から、いちばん いい ものを ひとつ えらんで ください。\n\n１番：大学まで 何で 来ますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'はい、行きます。',
        option_b: '自転車です。',
        option_c: '9時です。',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '交通手段（何で）を尋ねられているので、手段を答える「自転車です。（By bicycle）」が適切です。',
        explanation_sin: 'පැමිණි ප්‍රවාහන මාධ්‍යය (何で) අසන බැවින්「自転車です」(පාපැදියෙන්) යන්න නිවැරදි පිළිතුරයි.'
      },
      {
        order_num: 63,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題４\n\n２番：本屋は どこですか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '本を買いました。',
        option_b: 'いいえ、違います。',
        option_c: 'デパートの前ですよ。',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '場所（どこ）を尋ねられているので、位置を説明する「デパートの前ですよ。（In front of the department store）」が適切です。',
        explanation_sin: 'ස්ථානය (どこ) අසන බැවින්「デパートの前ですよ」(දෙපාර්තමේන්තු වෙළඳසැල ඉදිරිපිට) යන්න නිවැරදිය.'
      },
      {
        order_num: 64,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題４\n\n３番：誰と 旅行に 行きましたか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '京都です。',
        option_b: '昨日です。',
        option_c: '田中さんです。',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '一緒に行った人物（誰と）を尋ねられているので、「田中さんです。（With Tanaka）」が適切です。',
        explanation_sin: 'ගියේ කා සමඟද (誰と) යන්නට නිවැරදි පිළිතුර පුද්ගලයා දැක්වෙන「田中さんです」(තනකා මහතා සමග) වේ.'
      },
      {
        order_num: 65,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題４\n\n４番：お菓子を どうぞ。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'どういたしまして。',
        option_b: 'ありがとう、いただきます。',
        option_c: 'ごちそうさまでした。',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '食べ物を勧められた時の挨拶は「ありがとう、いただきます。（Thank you, I will have some）」です。ごちそうさまでしたは食後の挨拶です。',
        explanation_sin: 'යමක් පිරිනැමූ විට දෙන නිවැරදි ප්‍රතිචාරය「ありがとう、いただきます」(ස්තූතියි, මම භාරගන්නවා/කනවා) වේ.'
      },
      {
        order_num: 66,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題４\n\n５番：日本に どのくらい いますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: 'ちょうど １年です。',
        option_b: '来年行きます。',
        option_c: '友達といます。',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '滞在期間（どのくらい）を問われているので、「ちょうど １年です。（Exactly one year）」が適切です。',
        explanation_sin: 'කාල සීමාව (කොපමණ කල්ද) අසන බැවින්「ちょうど １年です」(හරියටම අවුරුද්දක්) යන්න නිවැරදිය.'
      },
      {
        order_num: 67,
        section_name: '聴解 - Listening Comprehension',
        question_text: '問題４\n\n６番：お仕事は 何を して いますか。',
        question_type: 'multiple_choice',
        image_url: null,
        audio_url: audioTrackUrl,
        option_a: '元気です。',
        option_b: '仕事が好きです。',
        option_c: '銀行に 勤めて います。',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '仕事内容・職業を尋ねられているので、「銀行に 勤めて います。（I work at a bank）」が適切です。',
        explanation_sin: 'කරන රැකියාව කුමක්දැයි විමසන බැවින්「銀行に 勤めて います」(බැංකුවක සේවය කරනවා) යන්න නිවැරදිය.'
      }
    ];

    console.log(`Prepared ${questionsData.length} questions for Paper 02.`);

    // Delete existing questions for this exam to ensure fresh, idempotent state
    await query.run("DELETE FROM questions WHERE exam_id = ?", [examId]);
    console.log(`Cleared existing questions for exam ID ${examId}.`);

    // Insert all 67 questions
    for (const q of questionsData) {
      await query.run(`
        INSERT INTO questions (
          exam_id, section_name, question_text, question_type,
          image_url, audio_url,
          option_a, option_b, option_c, option_d,
          correct_option, marks, explanation, explanation_sin, order_num, difficulty_level
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId,
        q.section_name,
        q.question_text,
        q.question_type,
        q.image_url,
        q.audio_url,
        q.option_a,
        q.option_b,
        q.option_c,
        q.option_d,
        q.correct_option,
        q.marks,
        q.explanation,
        q.explanation_sin,
        q.order_num,
        'N5'
      ]);
    }

    console.log(`✅ Successfully seeded all ${questionsData.length} questions for "${title}" (Exam ID: ${examId})!`);

    // Verification check
    const countCheck = await query.get("SELECT COUNT(*) as count FROM questions WHERE exam_id = ?", [examId]);
    console.log(`Verification: Exam ID ${examId} now has ${countCheck.count} questions.`);

    // Check Exam ID 2 intact
    const exam2Check = await query.get("SELECT COUNT(*) as count FROM questions WHERE exam_id = 2");
    console.log(`Safety Check: Original Mock Exam ID 2 question count = ${exam2Check.count} (Must be exactly 8).`);

    return { examId, totalQuestions: countCheck.count };
  } catch (err) {
    console.error('Error in seedJLPTN5Paper02:', err);
    throw err;
  }
}

module.exports = { seedJLPTN5Paper02 };

if (require.main === module) {
  seedJLPTN5Paper02()
    .then((result) => {
      console.log('Seeding completed successfully:', result);
      process.exit(0);
    })
    .catch((err) => {
      console.error('Seeding failed:', err);
      process.exit(1);
    });
}
