const { query } = require('../config/database');

async function seedJftModelPaper21() {
  console.log('Seeding JFT-Basic Official Model Paper 21 (60 Questions, Pass 200/250)...');
  const title = 'JFT-Basic Official Model Paper 21 (60 Minutes)';

  try {
    let exam = await query.get("SELECT id FROM exams WHERE title = ? OR title LIKE '%Paper 21%'", [title]);
    let examId;

    if (exam) {
      examId = exam.id;
      console.log(`Found existing Exam ID: ${examId}, resetting questions...`);
      await query.run('DELETE FROM questions WHERE exam_id = ?', [examId]);
      await query.run(`
        UPDATE exams 
        SET course_id = 1,
            title = ?,
            description = 'Official JFT-Basic Prometric Computer-Based Examination Paper 21 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Authentic Extracted Images, Listening Audio Tracks and Sinhala Explanations)',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [title, examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (
          1,
          ?,
          'Official JFT-Basic Prometric Computer-Based Examination Paper 21 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Authentic Extracted Images, Listening Audio Tracks and Sinhala Explanations)',
          60,
          200,
          1
        )
      `, [title]);
      examId = res.id;
      console.log(`Created new Exam ID: ${examId}`);
    }

    const questions = [
      // ================= SECTION 1: Script & Vocabulary (文字・語彙 - Q01 to Q15) =================
      {
        order_num: 1,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft20/jft20_img_1.jpg',
        audio_url: null,
        option_a: 'おじさん',
        option_b: 'おじいさん',
        option_c: 'おばあさん',
        option_d: '',
        correct_option: 'B',
        marks: 1,
        explanation: 'පින්තූරයේ දැක්වෙන්නේ සීයා (おじいさん - Grandfather) ය. おじさん = මාමා, おばあさん = ආච්චී.'
      },
      {
        order_num: 2,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft20/jft20_img_2.jpg',
        audio_url: null,
        option_a: 'がっこう',
        option_b: 'かっこお',
        option_c: 'がっこ',
        option_d: '',
        correct_option: 'A',
        marks: 1,
        explanation: 'පාසල හඳුන්වන්නේ "がっこう" (学校 - Gakkou) යනුවෙනි.'
      },
      {
        order_num: 3,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft20/jft20_img_3.jpg',
        audio_url: null,
        option_a: 'こうり',
        option_b: 'とおり',
        option_c: 'こおり',
        option_d: '',
        correct_option: 'C',
        marks: 1,
        explanation: 'දියවන අයිස් කැටය හඳුන්වන්නේ "こおり" (氷 - Koori) යනුවෙනි.'
      },
      {
        order_num: 4,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい動詞を選んでください。\n(Look at the illustration and choose the correct verb.)',
        image_url: '/uploads/images/jft20/jft20_img_4.jpg',
        audio_url: null,
        option_a: 'わすれます',
        option_b: 'わてます',
        option_c: 'わたります',
        option_d: '',
        correct_option: 'C',
        marks: 1,
        explanation: 'පාර මාරු වීම හඳුන්වන්නේ "わたります" (渡ります - Watarimasu) යනුවෙනි.'
      },
      {
        order_num: 5,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい動詞を選んでください。\n(Look at the illustration and choose the correct verb.)',
        image_url: '/uploads/images/jft20/jft20_img_5.jpg',
        audio_url: null,
        option_a: 'おしえます',
        option_b: 'しかります',
        option_c: 'つくります',
        option_d: '',
        correct_option: 'A',
        marks: 1,
        explanation: 'ගුරුවරියක් දරුවන්ට උගන්වන ක්‍රියාව "おしえます" (教えます - Oshiemasu) වේ.'
      },
      {
        order_num: 6,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）のひらがなの漢字はどう書きますか。\n彼は【あかい】車がほしいです。',
        image_url: null,
        audio_url: null,
        option_a: '青い',
        option_b: '赤い',
        option_c: '歩い',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '「あかい」යන වචනයට අදාළ නිවැරදි කන්ජිය වන්නේ "赤い" (රතු) ය.'
      },
      {
        order_num: 7,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）のひらがなの漢字はどう書きますか。\nバスより【でんしゃ】のほうが早いです。',
        image_url: null,
        audio_url: null,
        option_a: '雪車',
        option_b: '電気',
        option_c: '電車',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '「でんしゃ」යන වචනයට අදාළ නිවැරදි කන්ජිය වන්නේ "電車" (විදුලි දුම්රිය) ය.'
      },
      {
        order_num: 8,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）のひらがなの漢字はどう書きますか。\nコロンボは【べんり】なまちです。',
        image_url: null,
        audio_url: null,
        option_a: '便利な',
        option_b: '吏利な',
        option_c: '吏理な',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '「べんり」යන වචනයට අදාළ නිවැරදි කන්ජිය වන්නේ "便利な" (පහසු/ප්‍රයෝජනවත්) ය.'
      },
      {
        order_num: 9,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線の言葉はどう書きますか。\nA：ぜんぶでいくらですか。\nB：【はっぴゃくじゅうなな】ルピーです。',
        image_url: null,
        audio_url: null,
        option_a: '六百十七',
        option_b: '八百十七',
        option_c: '八十百七',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '「はっぴゃくじゅうなな (817)」යනු "八百十七" වේ.'
      },
      {
        order_num: 10,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）のひらがなの漢字はどう書きますか。\n私の【かぞく】はよにんです。',
        image_url: null,
        audio_url: null,
        option_a: '家族',
        option_b: '家旅',
        option_c: '火',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '「かぞく」යන වචනයට අදාළ නිවැරදි කන්ජිය වන්නේ "家族" (පවුල) ය.'
      },
      {
        order_num: 11,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄に最もあてはまるものを選びなさい。\n公園に人が__________います。',
        image_url: '/uploads/images/jft20/jft20_img_6.jpg',
        audio_url: null,
        option_a: 'あまり',
        option_b: 'おおぜい',
        option_c: 'おおぜ',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: 'උද්‍යානයේ බොහෝ පිරිසක් සිටින බව පැවසීමට "おおぜい" (大勢 - විශාල පිරිසක්) යෙදේ.'
      },
      {
        order_num: 12,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄に最もあてはまるものを選びなさい。\n父は毎朝しんぶんを__________よみます。',
        image_url: '/uploads/images/jft20/jft20_img_7.jpg',
        audio_url: null,
        option_a: 'にさつ',
        option_b: 'にだい',
        option_c: 'にまい',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: 'පුවත්පත්, කොළ වැනි පැතලි ද්‍රව්‍ය ගණනය කිරීමේ ඒකකය වන්නේ "〜まい (枚)" බැවින් "にまい (පිටු/කොළ 2ක්)" නිවැරදි වේ.'
      },
      {
        order_num: 13,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄(13)に最もあてはまるものを選びなさい。\n私のかぞくはみんなテレビドラマとえいがをみる (13)__________ 好きです。',
        image_url: null,
        audio_url: null,
        option_a: 'のが',
        option_b: 'のを',
        option_c: 'の',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: 'කැමැත්ත දැක්වීමේදී ක්‍රියා පදය නාම පදයක් බවට පත් කර "〜のが好きです" (බැලීමට කැමතිය) ලෙස යෙදේ.'
      },
      {
        order_num: 14,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄(14)に最もあてはまるものを選びなさい。\n父はホラーえいががいちばん好きで、母は外国のテレビドラマが好きです。(14)__________、サブタイトルがなかったらこまるといっていますが、',
        image_url: null,
        audio_url: null,
        option_a: 'だから',
        option_b: 'しかし',
        option_c: 'でも',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: 'පෙර වාක්‍යයට ප්‍රතිවිරුද්ධ අදහසක් සම්බන්ධ කිරීමට "でも" (නමුත්) යෙදේ.'
      },
      {
        order_num: 15,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、空欄(15)に最もあてはまるものを選びなさい。\nあってもなくても何 (15)__________ 見ています。',
        image_url: null,
        audio_url: null,
        option_a: 'だから',
        option_b: 'でも',
        option_c: 'しかし',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '"何でも" (ඕනෑම දෙයක්) = කෙසේ වෙතත් ඕනෑම දෙයක් නරඹයි.'
      },

      // ================= SECTION 2: Conversation & Grammar (会話・文法 - Q16 to Q30) =================
      {
        order_num: 16,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文を読んで、空欄に最もあてはまるものを選びなさい。\nじしょを__________英語の勉強をします。',
        image_url: '/uploads/images/jft20/jft20_img_8.jpg',
        audio_url: null,
        option_a: 'つかって',
        option_b: 'つくって',
        option_c: 'しかって',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ශබ්දකෝෂය භාවිතා කරමින් ඉගෙනීමට "つかって" (使って - භාවිතා කර) යෙදේ.'
      },
      {
        order_num: 17,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '対話を読んで、空欄に最もあてはまるものを選びなさい。\nA：「おなかがいたいですから、今日仕事休みます。」\nB：「__________。」',
        image_url: '/uploads/images/jft20/jft20_img_9.jpg',
        audio_url: null,
        option_a: 'おめでとう',
        option_b: 'おだいじに',
        option_c: 'ありがとう',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'අසනීප වූ කෙනෙකුට සුවය ප්‍රාර්ථනා කිරීමට "おだいじに" (ඉක්මන් සුවය ලැබේවා / පරිස්සම් වන්න) යෙදේ.'
      },
      {
        order_num: 18,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文を読んで、空欄に最もあてはまるものを選びなさい。\nあの学校に学生が三千人__________いません。',
        image_url: null,
        audio_url: null,
        option_a: 'あまり',
        option_b: 'とても',
        option_c: 'しか',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'සෘණ ක්‍රියා පදයක් (〜いません) සමඟ සීමාවක් දැක්වීමට "〜しか" (පමණක්) යෙදේ: 三千人しかいません (3000ක් පමණි).'
      },
      {
        order_num: 19,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文を読んで、空欄に最もあてはまるものを選びなさい。\n公園でしゃしんを__________。',
        image_url: '/uploads/images/jft20/jft20_img_10.jpg',
        audio_url: null,
        option_a: 'とりました',
        option_b: 'しました',
        option_c: 'ありました',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ඡායාරූප ගැනීම හඳුන්වන්නේ "しゃしんをとります" (写真を撮る) බැවින් "とりました" නිවැරදි වේ.'
      },
      {
        order_num: 20,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '対話を読んで、空欄に最もあてはまるものを選びなさい。\nA：アベさん日本語のべんきょうは__________はじめましたか。\nB：一年前はじめました。',
        image_url: null,
        audio_url: null,
        option_a: 'いくつ',
        option_b: 'いつ',
        option_c: 'いくら',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'කාලය විමසීමට "いつ" (කවදාද) යෙදේ: いつはじめましたか (කවදාද පටන් ගත්තේ?).'
      },
      {
        order_num: 21,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '対話を読んで、空欄に最もあてはまる助詞を選びなさい。\nリサ：山田さん、パリスにはいつ行きますか。\n山田：来月に行きます。\nリサ：だれ__________行きますか。\n山田：かぞくと行きます。',
        image_url: '/uploads/images/jft20/jft20_img_11.jpg',
        audio_url: null,
        option_a: 'か',
        option_b: 'に',
        option_c: 'と',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'සමඟ යන පුද්ගලයා විමසීමට "〜と" (සමඟ) නිපාතය යෙදේ: だれと行きますか (කා සමඟද යන්නේ?).'
      },
      {
        order_num: 22,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '対話を読んで、空欄(22)に最もあてはまる助詞を選びなさい。\nきゃく：あのメロン (22)__________ 三つください。\nてんいん：はい、一つ850円です。三つ2550円になります。',
        image_url: '/uploads/images/jft20/jft20_img_12.jpg',
        audio_url: null,
        option_a: 'が',
        option_b: 'の',
        option_c: 'を',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ඉල්ලීමක් කිරීමේදී කර්මය දැක්වීමට "〜を" නිපාතය යෙදේ: メロンを三つください.'
      },
      {
        order_num: 23,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '対話を読んで、空欄(23)に最もあてはまる助詞を選びなさい。\nきゃく：ぜんぶ (23)__________ いくらですか。\nてんいん：2910円です。',
        image_url: '/uploads/images/jft20/jft20_img_13.jpg',
        audio_url: null,
        option_a: 'が',
        option_b: 'の',
        option_c: 'で',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'මුළු එකතුව දැක්වීමේදී "ぜんぶで" (සමස්තය එකතුව) යෙදේ.'
      },
      {
        order_num: 24,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '対話を読んで、空欄に最もあてはまるものを選びなさい。\nポール：ねえ、明日しんじゅくへあのえいがを見に__________。\nようこ：ああ、すみません。それは先週見てしまいました。',
        image_url: '/uploads/images/jft20/jft20_img_14.jpg',
        audio_url: null,
        option_a: '行きますか',
        option_b: '行きませんか',
        option_c: '行きましたか',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ආරාධනා කිරීමට "〜ませんか" යෙදේ: えいがを見に行きませんか (චිත්‍රපටය නැරඹීමට යමුද?).'
      },
      {
        order_num: 25,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '対話を読んで、空欄(25)に最もあてはまるものを選びなさい。\nひろし：リサさんは日本語のほかに何を (25)__________ いますか。\nリサ：私はれきし、えいご、すうがく、びじゅつをべんきょうしています。',
        image_url: '/uploads/images/jft20/jft20_img_15.jpg',
        audio_url: null,
        option_a: 'おしえて',
        option_b: 'べんきょうして',
        option_c: 'しらべて',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ඉගෙන ගන්නා විෂයයන් ගැන විමසීමට "何をべんきょうしていますか" යෙදේ.'
      },
      {
        order_num: 26,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '対話を読んで、空欄(26)に最もあてはまるものを選びなさい。\nリサ：そうですか。じゅぎょうがおわってから、(26)__________ しますか。\nひろし：ええ、そうです。',
        image_url: '/uploads/images/jft20/jft20_img_15.jpg',
        audio_url: null,
        option_a: 'べんきょ',
        option_b: 'およぎ',
        option_c: 'れんしゅう',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ක්‍රීඩා සමාජයේ පුහුණුවීම් දැක්වීමට "れんしゅう" (පුහුණුවීම් / Practice) යෙදේ.'
      },
      {
        order_num: 27,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '対話を読んで、空欄(27)に最もあてはまるものを選びなさい。\nひろし：それから、やきゅうぶでは じゅぎょうがはじまる前にもします。\nリサ：へえー。(27)__________。',
        image_url: '/uploads/images/jft20/jft20_img_15.jpg',
        audio_url: null,
        option_a: 'たいへんですね',
        option_b: 'あついですね',
        option_c: 'ひろいですね',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'උදේ සහ හවස දෙකේදීම පුහුණුවීම් කරන බැවින් එය අපහසු/වෙහෙසකර බව පැවසීමට "たいへんですね" (අමාරු වැඩක්නේ) යෙදේ.'
      },
      {
        order_num: 28,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '対話を読んで、空欄に最もあてはまるものを選びなさい。\nサリ：れいぞうこの中に何がありますか。\nシン：ぎゅうにゅうやたまごややさいなどがあります。\nサリ：ビールもありますか。\nシン：いいえ、__________。',
        image_url: '/uploads/images/jft20/jft20_img_16.jpg',
        audio_url: null,
        option_a: 'ビールはあります',
        option_b: 'ビールはありません',
        option_c: 'ビールはありますか',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'නැත (いいえ) යැයි පවසන බැවින් "ビールはありません" (බියර් නැත) නිවැරදි වේ.'
      },
      {
        order_num: 29,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '対話を読んで、空欄(29)に最もあてはまるものを選びなさい。\nA：なつ休みに (29)__________ へ行きましたか。\nB：きょうとへ行きました。',
        image_url: '/uploads/images/jft20/jft20_img_17.jpg',
        audio_url: null,
        option_a: 'どこ',
        option_b: 'これ',
        option_c: 'どれ',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ස්ථානය විමසීමට "どこ" (කොහේද) යෙදේ: どこへ行きましたか (කොහේද ගියේ?).'
      },
      {
        order_num: 30,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '対話を読んで、空欄(30)に最もあてはまるものを選びなさい。\nB：おてらがおおぜい見ました。とても (30)__________ ですよ。',
        image_url: '/uploads/images/jft20/jft20_img_17.jpg',
        audio_url: null,
        option_a: 'やすみました',
        option_b: 'あついでした',
        option_c: 'たのしかった',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'සංචාරය විනෝදජනක වූ බව අතීත කාලයෙන් පැවසීමට "とてもたのしかったですよ" (ගොඩක් විනෝදජනක වුණා) යෙදේ.'
      },

      // ================= SECTION 3: Listening Comprehension (聴解 - Q31 to Q45) =================
      {
        order_num: 31,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【音声を聴いて答えなさい】\nA man is looking for a birthday present for his wife at a jewelry shop. Which necklace is he going to buy?',
        image_url: '/uploads/images/jft20/jft20_img_18.jpg',
        audio_url: '/uploads/audio/jft20_q31.mp3',
        option_a: 'A (Star necklace)',
        option_b: 'B (Flower / Cross necklace)',
        option_c: 'C (Heart necklace)',
        option_d: 'D (Pearl necklace)',
        correct_option: 'C',
        marks: 5,
        explanation: 'ශ්‍රව්‍ය ඛණ්ඩය අනුව ඔහු බිරිඳට තෝරාගන්නේ හෘදයාකාර (Heart necklace - C) මාලයයි.'
      },
      {
        order_num: 32,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【音声を聴いて答えなさい】\nA man is talking with his wife on the phone. What is he going to buy?',
        image_url: '/uploads/images/jft20/jft20_img_22.jpg',
        audio_url: '/uploads/audio/jft20_q32.mp3',
        option_a: 'A (Bread, Beer, Milk)',
        option_b: 'B (Bread, Milk, Butter)',
        option_c: 'C (Bread, Milk)',
        option_d: 'D (Bread, Beer, Milk, Butter)',
        correct_option: 'A',
        marks: 5,
        explanation: 'ශ්‍රව්‍ය ඛණ්ඩය අනුව ඔහු මිලදී ගැනීමට යන්නේ පාන්, බියර් සහ කිරි (A) ය.'
      },
      {
        order_num: 33,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【音声を聴いて答えなさい】\nYou are listening to the weather forecast. What is the forecast?',
        image_url: '/uploads/images/jft20/jft20_img_26.jpg',
        audio_url: '/uploads/audio/jft20_q33.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c',
        option_d: 'd',
        correct_option: 'C',
        marks: 5,
        explanation: 'කාලගුණ අනාවැකිය අනුව නිවැරදි කාලගුණ සටහන C වේ.'
      },
      {
        order_num: 34,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【音声を聴いて答えなさい】\nA man and a woman are talking about the design of the company business card. Which design did they decide on?',
        image_url: '/uploads/images/jft20/jft20_img_27.jpg',
        audio_url: '/uploads/audio/jft20_q34.mp3',
        option_a: 'A (Top Left)',
        option_b: 'B (Top Right)',
        option_c: 'C (Bottom Left)',
        option_d: 'D (Bottom Right)',
        correct_option: 'D',
        marks: 5,
        explanation: 'ඔවුන් තීරණය කරන්නේ දකුණු පස පහළ පිහිටි D ව්‍යාපාරික කාඩ්පත් මෝස්තරයයි.'
      },
      {
        order_num: 35,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【音声を聴いて答えなさい】\nA woman is in a department store. Which floor is she going to?',
        image_url: '/uploads/images/jft20/jft20_img_31.jpg',
        audio_url: '/uploads/audio/jft20_q35.mp3',
        option_a: '5th Floor',
        option_b: '6th Floor',
        option_c: '7th Floor',
        option_d: '8th Floor',
        correct_option: 'C',
        marks: 5,
        explanation: 'ඇය යාමට බලාපොරොත්තු වන්නේ 7 වන මහලට (7th floor - C) ය.'
      },
      {
        order_num: 36,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【音声を聴いて答えなさい】\nA man and a woman are talking. How old is the man now?',
        image_url: '/uploads/images/jft20/jft20_img_35.jpg',
        audio_url: '/uploads/audio/jft20_q36.mp3',
        option_a: '16',
        option_b: '59',
        option_c: '50',
        option_d: '60',
        correct_option: 'D',
        marks: 5,
        explanation: 'පිරිමි පුද්ගලයාගේ වර්තමාන වයස අවුරුදු 60 (D: 60) වේ.'
      },
      {
        order_num: 37,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【音声を聴いて答えなさい】\nA woman is looking at clothes in a boutique. What is she going to buy?',
        image_url: '/uploads/images/jft20/jft20_img_39.jpg',
        audio_url: '/uploads/audio/jft20_q37.mp3',
        option_a: 'White skirt',
        option_b: 'White pants',
        option_c: 'Blue skirt',
        option_d: 'Blue pants',
        correct_option: 'C',
        marks: 5,
        explanation: 'ඇය මිලදී ගන්නේ නිල් පැහැති සායයි (Blue skirt - C).'
      },
      {
        order_num: 38,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【音声を聴いて答えなさい】\nA man and a woman are talking. How many people in total are coming to the party?',
        image_url: '/uploads/images/jft20/jft20_img_43.jpg',
        audio_url: '/uploads/audio/jft20_q38.mp3',
        option_a: 'A (2 people)',
        option_b: 'B (3 people)',
        option_c: 'C (4 people)',
        option_d: 'D (5 people)',
        correct_option: 'C',
        marks: 5,
        explanation: 'සාදයට සහභාගී වන මුළු පිරිස 4 දෙනෙකි (C: 4 people).'
      },
      {
        order_num: 39,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【音声を聴いて答えなさい】\nA woman bought a bed. Where is she going to put it?',
        image_url: '/uploads/images/jft20/jft20_img_47.jpg',
        audio_url: '/uploads/audio/jft20_q39.mp3',
        option_a: 'A (Top left under window)',
        option_b: 'B (Top right beside door)',
        option_c: 'C (Bottom left)',
        option_d: 'D (Bottom right)',
        correct_option: 'A',
        marks: 5,
        explanation: 'ඇඳ තැබීමට තීරණය කරන්නේ කාමරයේ කවුළුව යට වම්පස කොටසේ (A) ය.'
      },
      {
        order_num: 40,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【音声を聴いて答えなさい】\nStudents are talking. What will the man do from now on?',
        image_url: '/uploads/images/jft20/jft20_img_51.jpg',
        audio_url: '/uploads/audio/jft20_q40.mp3',
        option_a: 'A (Study alone at desk)',
        option_b: 'B (Study with friends)',
        option_c: 'C (Read newspaper on floor)',
        option_d: 'D (Talk with friend)',
        correct_option: 'A',
        marks: 5,
        explanation: 'ඔහු මේ මොහොතේ සිට තනිවම මේසය අසල හිඳ පාඩම් කරනු ඇත (A).'
      },
      {
        order_num: 41,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【音声を聴いて答えなさい】\nA man and a woman are talking. What will the woman do now on?',
        image_url: '/uploads/images/jft20/jft20_img_55.jpg',
        audio_url: '/uploads/audio/jft20_q41.mp3',
        option_a: 'A (Sleep in bed)',
        option_b: 'B (Eat with family)',
        option_c: 'C (Talk on phone)',
        option_d: 'D (Talk in office)',
        correct_option: 'C',
        marks: 5,
        explanation: 'කාන්තාව දැන් දුරකථන ඇමතුමක් ලබා ගනු ඇත (C: Phone call).'
      },
      {
        order_num: 42,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【音声を聴いて答えなさい】\nStudents are talking. What will the female student do now on?',
        image_url: '/uploads/images/jft20/jft20_img_59.jpg',
        audio_url: '/uploads/audio/jft20_q42.mp3',
        option_a: 'A (Read book then eat)',
        option_b: 'B (Eat then read book)',
        option_c: 'C (Sleep then study)',
        option_d: 'D (Study then sleep)',
        correct_option: 'B',
        marks: 5,
        explanation: 'ශිෂ්‍යාව පළමුව ආහාර ගෙන ඉන්පසු පොත කියවනු ඇත (B).'
      },
      {
        order_num: 43,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【音声を聴いて答えなさい】\nDoctor is talking. What does the sick person do first?',
        image_url: '/uploads/images/jft20/jft20_img_63.jpg',
        audio_url: '/uploads/audio/jft20_q43.mp3',
        option_a: 'A (Go to Room 1 first)',
        option_b: 'B (Go to Room 2 first)',
        option_c: 'C (Sit in waiting room)',
        option_d: 'D (Talk at counter)',
        correct_option: 'A',
        marks: 5,
        explanation: 'වෛද්‍යවරයාගේ උපදෙස් අනුව රෝගියා පළමුව 1 වන කාමරයට යා යුතුය (A).'
      },
      {
        order_num: 44,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【音声を聴いて答えなさい】\nMother and son are talking. What will the son do first?',
        image_url: null,
        audio_url: '/uploads/audio/jft20_q44.mp3',
        option_a: 'ドアのかぎをしめます',
        option_b: 'てをあらいます',
        option_c: 'おかしを食べます',
        option_d: 'テーブルをあらいます',
        correct_option: 'B',
        marks: 5,
        explanation: 'මවගේ උපදෙස් අනුව පුතා පළමුව දෑත් සෝදාගත යුතුය (てをあらいます).'
      },
      {
        order_num: 45,
        section_name: 'Section 3: Listening Comprehension (聴解)',
        question_text: '【音声を聴いて答えなさい】\nA man and a woman are talking. What are they going to do now on?',
        image_url: null,
        audio_url: '/uploads/audio/jft20_q45.mp3',
        option_a: 'りょこうがいしゃへ行きます',
        option_b: 'りょこうへ行きます',
        option_c: 'インターネットを見ます',
        option_d: 'でんしゃにのります',
        correct_option: 'C',
        marks: 5,
        explanation: 'ඔවුන් දැන් අන්තර්ජාලය පරීක්ෂා කරනු ඇත (インターネットを見ます).'
      },

      // ================= SECTION 4: Reading Comprehension (読解 - Q46 to Q60) =================
      {
        order_num: 46,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【メッセージを読んで答えなさい】\nキムさん、\n私は今日時間がありません。\n明日もいそがしいです。\nしゅくだいがたくさんあります。\n月曜日にあいましょう。\nスミス\n\n46. かれらはいつあいますか。',
        image_url: '/uploads/images/jft20/jft20_img_67.jpg',
        audio_url: null,
        option_a: '月曜日',
        option_b: '今日',
        option_c: 'あわない',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ලිපියේ අවසානයේ "月曜日にあいましょう" (සඳුදා හමුවෙමු) යනුවෙන් සඳහන් වේ.'
      },
      {
        order_num: 47,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【お知らせを読んで答えなさい】\nアパートのみなさんへ、\n来週の土曜日と日曜日の午前7時から午後5時までもんだいがありますから、エレベーターをつかわないでかいだんをつかってください。\n\n47. 何時間エレベーターをつかうことができませんか。',
        image_url: '/uploads/images/jft20/jft20_img_68.jpg',
        audio_url: null,
        option_a: '12時間',
        option_b: '10時間',
        option_c: '08時間',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'උදෑසන 7 සිට සවස 5 දක්වා කාලය පැය 10 කි (10時間).'
      },
      {
        order_num: 48,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【メモを読んで答えなさい】\n「日本語1」と「日本語2」のみなさんへ、\n今日、やまだ先生はおひるまでお休みです。午前の「日本語1」のクラスはありません。午後の「日本語2」のクラスはあります。「日本語1」のしゅくだいは来週出してください。\n\n48. メモには何がありますか。',
        image_url: null,
        audio_url: null,
        option_a: '「日本語1」と「日本語2」のクラスは今日ありません',
        option_b: '「日本語1」クラスは今日あります。でも「日本語2」クラスは今日ありません',
        option_c: '「日本語2」クラスは今日あります。でも「日本語1」クラスは今日ありません',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'සටහන අනුව සවස පැවැත්වෙන නිහොංගෝ 2 පන්තිය අද පවතින අතර, උදෑසන නිහොංගෝ 1 පන්තිය නොපැවැත්වේ (C).'
      },
      {
        order_num: 49,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【文を読んで答えなさい】\n昨日夜10時に友達の家にでんわをしましたが、友達はいませんでした。1時間あとでもういちどでんわをしました。でも彼はかえっていませんでした。それから、私はねました。\n\n49. 私は何時にねましたか。',
        image_url: null,
        audio_url: null,
        option_a: '10時',
        option_b: '11時',
        option_c: '12時',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'රාත්‍රී 10 ට ඇමතුමක් දී පැයකට පසු (11 ට) නැවත ඇමතුමක් ලබාදී නිදාගත් බැවින් වේලාව රාත්‍රී 11 (11時 - B) වේ.'
      },
      {
        order_num: 50,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【日記を読んで答えなさい】\n私のなまえはきむらいずみです。去年フランスへ行きました。そこでいろいろな人とあいました。だから、とてもうれしかったです。フランス人のせいかつはとてもいそがしいです。フランスりょうりはとてもおいしいです。とくにぎょうざがとても好きでした。さかなもとてもおいしかったです。\n\n50. きむらさんはどうしてうれしかったですか。',
        image_url: '/uploads/images/jft20/jft20_img_69.jpg',
        audio_url: null,
        option_a: 'さかなはとてもおいしかったですから',
        option_b: 'ぎょうざがとても好きだから',
        option_c: 'いろいろなフランス人とあいましたから',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ප්‍රංශයේදී විවිධ පුද්ගලයින් හමුවූ නිසා ඇය සතුටු වූවාය (そこでいろいろな人とあいました。だから、とてもうれしかったです).'
      },
      {
        order_num: 51,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【文を読んで答えなさい】\n昨日あたらしいかさを買ったんです。明日の母のたんじょうびのプレゼントです。このかさはかるくていいです。去年もあたらしいかさをあげました。そのかさはあかくておもかったです。昨日よりとてもやすかったです。\n\n51. 去年は母にどんなかさをあげましたか。',
        image_url: '/uploads/images/jft20/jft20_img_70.jpg',
        audio_url: null,
        option_a: 'おもくてやすいかさです',
        option_b: 'かるくておもいかさです',
        option_c: 'あかくてたかいかさです',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'ගිය වසරේ මවට දුන්නේ බරින් වැඩි හා ලාභදායී කුඩයකි (おもくてやすいかさです).'
      },
      {
        order_num: 52,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【手紙を読んで答えなさい】\nアリさん、\nお元気ですか。日本に来てからもう3か月になりました。今、私はやまださんと言うかぞくでホームステイをしながら大学で日本語をべんきょうしています。やまださんの家はお父さんとお母さんとむすこさんの3人かぞくです。むすこさんのなまえはよしこです。彼は大学生で1週間に3日アルバイトをしています。日本の大学生はアメリカの大学生ほどよくべんきょうしません。週末だけでなく、ふつうの日でもお酒をのんだり、カラオケへ行ったりします。よしこさんの話では、日本人は大学のしけんのためによくべんきょうしますし、かいしゃに入ったら、よくしごとをしますから、大学の4年間はあそぶんだそうです。\nジョン・スミス\n\n52. これはだれが書いたてがみですか。',
        image_url: '/uploads/images/jft20/jft20_img_71.jpg',
        audio_url: null,
        option_a: 'アリさん',
        option_b: 'よしこさん',
        option_c: 'ジョン・スミスさん',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ලිපිය ලියා අවසන් කර අත්සන් තබා ඇත්තේ ජෝන් ස්මිත් මහතාය (ジョン・スミスさん).'
      },
      {
        order_num: 53,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '53. どうして日本の大学生はアメリカの大学生よりべんきょうしませんか。',
        image_url: '/uploads/images/jft20/jft20_img_71.jpg',
        audio_url: null,
        option_a: 'お酒をのむのが好きだから',
        option_b: 'かいしゃでよくはたらくようになるから',
        option_c: 'カラオケへ行ってあそびたいから',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'සමාගමකට බැඳුණු පසු දැඩිව වෙහෙසී වැඩ කිරීමට සිදුවන බැවිනි (かいしゃに入ったら、よくしごとをしますから).'
      },
      {
        order_num: 54,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【対話を読んで答えなさい】\n学生：すみません、この本をやりたいです。\nとしょかんの人：このがっこうの学生ですか。\n学生：はい。\nとしょかんの人：では、はじめにこの紙になまえとじゅうしょとでんわばんごうを書いてください。\n学生：はい。\nとしょかんの人：書きましたか。\n学生：はい。\nとしょかんの人：これは辞書ですね。辞書はとしょかんの中でつかってください。\n学生：はい、わかりました。では、この7さつをかしてください。\nとしょかんの人：ああ、学生は4さつまでです。\n学生：そうですか。では、この3さつはかりません。\nとしょかんの人：わかりました。では、こちらの本は2週間、ざっしは1週間でかえしてください。今日は15日ですから、[　　　　]。\n学生：はい、わかりました。\n\n54. はこ [　　] に何を入れますか。',
        image_url: '/uploads/images/jft20/jft20_img_72.jpg',
        audio_url: null,
        option_a: '本は29日、ざっしは22日です',
        option_b: '本は22日、ざっしは29日です',
        option_c: '本もざっしも22日です',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'අද 15 වනදා බැවින්, සති 2 කින් (15+14=29) පොත් ද, සතියකින් (15+7=22) සඟරා ද ආපසු දිය යුතුය.'
      },
      {
        order_num: 55,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '55. この学生は何さつかりましたか。',
        image_url: '/uploads/images/jft20/jft20_img_72.jpg',
        audio_url: null,
        option_a: '3さつ',
        option_b: '4さつ',
        option_c: '5さつ',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'පුස්තකාලයෙන් සිසුන්ට ලබාගත හැක්කේ උපරිම පොත් 4ක් පමණි (学生は4さつまでです).'
      },
      {
        order_num: 56,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '56. この学生はとしょかんで何をしましたか。',
        image_url: '/uploads/images/jft20/jft20_img_72.jpg',
        audio_url: null,
        option_a: '本になまえを書きました',
        option_b: '辞書をかりました',
        option_c: '本とざっしをかりました',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ශිෂ්‍යයා පුස්තකාලයෙන් පොත් සහ සඟරා ණයට ගත්තේය (本とざっしをかりました).'
      },
      {
        order_num: 57,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '57. このとしょかんで学生ができることは何ですか。',
        image_url: '/uploads/images/jft20/jft20_img_72.jpg',
        audio_url: null,
        option_a: '本と辞書を1週間かりること',
        option_b: '本やざっしを4さつまでかりること',
        option_c: 'ざっしを2週間かりること',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'සිසුන්ට පොත් හෝ සඟරා 4 ක් දක්වා ණයට ගත හැකිය (本やざっしを4さつまでかりること).'
      },
      {
        order_num: 58,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '【文章を読んで答えなさい】\nリン：時間がたいから、タクシーで行きませんか。\n田中：タクシーよりちかてつのほうがはやいですよ。\n\nリンさんと田中さんはちかてつにのりました。東京のどうろはいつもくるまでこんでいます。\n\nリン：どこでのりかえますか。\n田中：ちょっとまってください。ちずを見ますから。つぎの駅でのりかえます。それから三つめの駅でおります。\n\n田中さんは20年東京に住んでいますが、今でもちかてつはよくわかりません。たくさんあるからです。のりかえる駅もいろいろあります。\n\nABCデパートの前の駅につきました。この駅はとてもふかいところにあります。ちか37mです。エスカレーターが15だいあります。二人はエスカレーターを3かいのりかえてちかから明るい外へ出ました。\n\n58. どうしてリンさんと田中さんはちかてつにのりましたか。',
        image_url: null,
        audio_url: null,
        option_a: 'タクシーのお金がないからです',
        option_b: 'タクシーはときどきおそいからです',
        option_c: 'ちかてつの駅のなまえをおぼえたいからです',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'මාර්ග තදබදය නිසා ටැක්සි ගමනාගමනය ප්‍රමාද විය හැකි බැවින් භූගත දුම්රිය වේගවත් යැයි තනකා මහතා පැවසීය (タクシーよりちかてつのほうがはやいですよ).'
      },
      {
        order_num: 59,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '59. 田中さんはどうしてちかてつがよくわかりませんか。',
        image_url: null,
        audio_url: null,
        option_a: 'ちかてつがたくさんあるからです',
        option_b: 'あたまがわるいからです',
        option_c: 'いつもタクシーにのるからです',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'භූගත දුම්රිය මාර්ග සහ දුම්රිය ස්ථාන විශාල සංඛ්‍යාවක් පවතින බැවිනි (たくさんあるからです).'
      },
      {
        order_num: 60,
        section_name: 'Section 4: Reading Comprehension (読解)',
        question_text: '60. リンさんと田中さんはどの駅でおおりましたか。1・2の中からいちばんいいものをえらびなさい。',
        image_url: '/uploads/images/jft20/jft20_img_73.jpg',
        audio_url: null,
        option_a: '1 (Change at next station, then 3rd station)',
        option_b: '2 (Change at next station, then 2nd station)',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'මීළඟ නැවතුමෙන් දුම්රිය මාරු කර ඉන්පසු 3 වන දුම්රිය නැවතුමෙන් බැස ගත් බැවින් සටහන් 1 (A) නිවැරදි වේ (それから三つめの駅でおります).'
      }
    ];

    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, section_name, question_text, question_type,
          image_url, audio_url,
          option_a, option_b, option_c, option_d,
          correct_option, marks, explanation, order_num
        ) VALUES (?, ?, ?, 'multiple_choice', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId, q.section_name, q.question_text,
        q.image_url, q.audio_url,
        q.option_a, q.option_b, q.option_c, q.option_d,
        q.correct_option, q.marks, q.explanation, q.order_num
      ]);
    }

    console.log(`🎉 SUCCESS: Seeded ${questions.length} questions for JFT Model Paper 21 (Exam ID: ${examId})`);
    return { success: true, examId, count: questions.length };
  } catch (err) {
    console.error('Error seeding JFT Model Paper 21:', err);
    throw err;
  }
}

module.exports = { seedJftModelPaper21 };
