const { query } = require('../config/database');

async function seedJftModelPaper14() {
  console.log('Seeding JFT-Basic Official Model Paper 14 (60 Questions, 250 Marks, Pass 200)...');
  const title = 'JFT-Basic Official Model Paper 14 (60 Minutes)';

  try {
    let exam = await query.get("SELECT id FROM exams WHERE title = ? OR title LIKE '%Paper 14%'", [title]);
    let examId;

    if (exam) {
      examId = exam.id;
      console.log(`Found existing Exam ID: ${examId}, resetting questions...`);
      await query.run('DELETE FROM questions WHERE exam_id = ?', [examId]);
      await query.run(`
        UPDATE exams 
        SET course_id = 1,
            title = ?,
            description = 'Official JFT-Basic Prometric Computer-Based Examination Paper 14 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Listening Audio Tracks and Sinhala Explanations)',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [title, examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (
          1,
          ?,
          'Official JFT-Basic Prometric Computer-Based Examination Paper 14 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Listening Audio Tracks and Sinhala Explanations)',
          60,
          200,
          1
        )
      `, [title]);
      examId = res.id;
      console.log(`Created new Exam ID: ${examId}`);
    }

    const questions = [
      // ================= SECTION 1: Script & Vocabulary (文字・語彙 - Q01 to Q15) =================
      {
        order_num: 1,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft14/jft14_img_1.jpg',
        audio_url: null,
        option_a: 'はなみ',
        option_b: 'はなび',
        option_c: 'はな',
        option_d: '',
        correct_option: 'A',
        marks: 1,
        explanation: 'はなみ (花見) = මල් නැරඹීම / Cherry blossom viewing picnic. はなび = ගිනිකෙළි. はな = මල්.'
      },
      {
        order_num: 2,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft14/jft14_img_2.jpg',
        audio_url: null,
        option_a: 'まんじゅう',
        option_b: 'パン',
        option_c: 'りんご',
        option_d: '',
        correct_option: 'A',
        marks: 1,
        explanation: 'まんじゅう (饅頭) = ජපන් සම්ප්‍රදායික පැණි බනිස් / Steamed bean-jam bun.'
      },
      {
        order_num: 3,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft14/jft14_img_3.jpg',
        audio_url: null,
        option_a: 'トマド',
        option_b: 'トマート',
        option_c: 'トマト',
        option_d: '',
        correct_option: 'C',
        marks: 1,
        explanation: 'トマト (Tomato) = තක්කාලි.'
      },
      {
        order_num: 4,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft14/jft14_img_4.jpg',
        audio_url: null,
        option_a: 'しんかんせん',
        option_b: 'でんしゃ',
        option_c: 'きしゃ',
        option_d: '',
        correct_option: 'A',
        marks: 1,
        explanation: 'しんかんせん (新幹線) = බුලට් දුම්රිය / Bullet train. でんしゃ = සාමාන්‍ය විදුලි දුම්රිය.'
      },
      {
        order_num: 5,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: 'イラストを見て正しい言葉を選んでください。\n(Look at the illustration and choose the correct word.)',
        image_url: '/uploads/images/jft14/jft14_img_5.jpg',
        audio_url: null,
        option_a: 'ジャンプ',
        option_b: 'ジョギングをします',
        option_c: 'たいそうをします',
        option_d: '',
        correct_option: 'A',
        marks: 1,
        explanation: 'ジャンプ (Jump) = පැනීම / Gymnastics flip jump.'
      },
      {
        order_num: 6,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\n彼はお金が（　　）でしょう。',
        image_url: null,
        audio_url: null,
        option_a: 'あります',
        option_b: 'ある',
        option_c: 'ありません',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '「〜でしょう」ඉදිරියෙන් ක්‍රියාපදයේ සාමාන්‍ය ස්වරූපය (Plain form: ある) යෙදේ.'
      },
      {
        order_num: 7,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\n母の大切なかびんを（　　）しまいました。',
        image_url: null,
        audio_url: null,
        option_a: 'こわしました',
        option_b: 'こわす',
        option_c: 'こわして',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: 'අතපසුවීමකින් හෝ කනගාටුදායක දෙයක් සිදුවූ විට 「V-て しまいました」භාවිතා වේ. こわして + しまいました.'
      },
      {
        order_num: 8,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\n来月のはじめに家を出て、一人で（　　）つもりです。',
        image_url: null,
        audio_url: null,
        option_a: '住みます',
        option_b: '住む',
        option_c: '住んでいます',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: 'අභිප්‍රාය ප්‍රකාශ කිරීමට 「V-(Dictionary form) + つもりです」යෙදේ. 住む + つもりです.'
      },
      {
        order_num: 9,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\n７月には北海道へ（　　）よていです。',
        image_url: null,
        audio_url: null,
        option_a: '行きます',
        option_b: '行きました',
        option_c: '行く',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: 'සැලසුම් ප්‍රකාශ කිරීමේදී 「V-(Dictionary form) + よていです」භාවිතා වේ. 行く + よていです.'
      },
      {
        order_num: 10,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\n明日からスキーに行きます。１週間（　　）んです。',
        image_url: null,
        audio_url: null,
        option_a: '休み',
        option_b: '休みな',
        option_c: '休みます',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '休み (නාම පදය) + なんです හෝ 休みなんです. නිවාඩුවක් බව පැහැදිලි කරයි.'
      },
      {
        order_num: 11,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）の言葉のひらがなはどう書きますか。\n【右と左】をよく見て道をわたりましょう。',
        image_url: null,
        audio_url: null,
        option_a: 'ひだり・みぎ',
        option_b: 'くち・みぎ',
        option_c: 'みぎ・ひだり',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '右 = みぎ (දකුණ), 左 = ひだり (වම). 右と左 = みぎ・ひだり.'
      },
      {
        order_num: 12,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）の言葉のひらがなはどう書きますか。\nひとつめのかどをまがります。【赤い】はしがあります。',
        image_url: null,
        audio_url: null,
        option_a: 'あおい',
        option_b: 'あかい',
        option_c: 'しろい',
        option_d: '',
        correct_option: 'B',
        marks: 2,
        explanation: '赤 = あか (රතු), 赤い = あかい.'
      },
      {
        order_num: 13,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）の言葉のひらがなはどう書きますか。\nこの【通り】に白いビルが二つあります。',
        image_url: null,
        audio_url: null,
        option_a: 'とおり',
        option_b: 'みち',
        option_c: 'どうろ',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '通り = とおり (වීදිය / Avenue).'
      },
      {
        order_num: 14,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）の言葉のひらがなはどう書きますか。\n【青い】ビルの前でアイスクリームを食べました。',
        image_url: null,
        audio_url: null,
        option_a: 'あかい',
        option_b: 'しろい',
        option_c: 'あおい',
        option_d: '',
        correct_option: 'C',
        marks: 2,
        explanation: '青 = あお (නිල්), 青い = あおい.'
      },
      {
        order_num: 15,
        section_name: 'Section 1: Script & Vocabulary (文字・語彙)',
        question_text: '下線（____）の言葉のひらがなはどう書きますか。\n【黒い】タクシーにのりました。',
        image_url: null,
        audio_url: null,
        option_a: 'くろい',
        option_b: 'くらい',
        option_c: 'しろい',
        option_d: '',
        correct_option: 'A',
        marks: 2,
        explanation: '黒 = くろ (කළු), 黒い = くろい.'
      },

      // ================= SECTION 2: Conversation & Grammar (会話・文法 - Q16 to Q30) =================
      {
        order_num: 16,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\nあそこにきれいなたてものが＿＿＿＿＿。',
        image_url: null,
        audio_url: null,
        option_a: '見せます',
        option_b: '見て',
        option_c: '見えます',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ස්වභාවිකව ඇසට පෙනෙන විට 「〜が見えます」භාවිතා වේ.'
      },
      {
        order_num: 17,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文を読んで、(17)に入る一番いいものを一つ選んでください。\nふじさんはとても(17)＿＿＿＿、ここからちょっと(18)＿＿＿＿。',
        image_url: null,
        audio_url: null,
        option_a: 'きれいな',
        option_b: 'きれいに',
        option_c: 'きれいだけど',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '「きれいだけど」(ලස්සන වුවත්) යන්න පසුව එන දුරයි යන්න සමග ප්‍රතිවිරුද්ධ අර්ථය දක්වයි.'
      },
      {
        order_num: 18,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文を読んで、(18)に入る一番いいものを一つ選んでください。\nふじさんはとても(17)＿＿＿＿、ここからちょっと(18)＿＿＿＿。',
        image_url: null,
        audio_url: null,
        option_a: 'とおい',
        option_b: 'とおく',
        option_c: 'とおき',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'වාක්‍ය අවසානයේ නාමවිශේෂණය සාමාන්‍ය ස්වරූපයෙන් 「とおい」(දුරයි) ලෙස යෙදේ.'
      },
      {
        order_num: 19,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\nこのとおりはいい店がおおいけど夜＿＿＿＿。私はあまり行きたくないです。',
        image_url: null,
        audio_url: null,
        option_a: 'あかるいです',
        option_b: 'くらいです',
        option_c: 'くろいです',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'රාත්‍රිය අඳුරු (くらい) නිසා යාමට අකමැති බව පවසයි.'
      },
      {
        order_num: 20,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '文を読んで、（　　）に一番いいものを一つ選んでください。\n東京のうえの＿＿＿しんじゅくなど大きい町がたくさんあります。',
        image_url: null,
        audio_url: null,
        option_a: 'に',
        option_b: 'や',
        option_c: 'が',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'උදාහරණ ලැයිස්තුගත කිරීමට 「〜や〜など」භාවිතා වේ.'
      },
      {
        order_num: 21,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(21)に入る一番いいものを一つ選んでください。\nA：すみません、サクラぎんこうは(21)＿＿＿＿。\nB：サクラぎんこうはこの通りをまっすぐ行って、ひとつめのしんごうを右にまがってください。',
        image_url: null,
        audio_url: null,
        option_a: 'どうろですか',
        option_b: 'どのですか',
        option_c: 'どこですか',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ස්ථානයක් විමසීමට 「どこですか」(කොහේද?) භාවිතා වේ.'
      },
      {
        order_num: 22,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(22)に入る一番いいものを一つ選んでください。\nA：(22)＿＿＿＿、右ですね。\nB：はい そうです。まっすぐ行って右にまがります。\nA：どうもありがとうございます。',
        image_url: null,
        audio_url: null,
        option_a: 'まっすぐ行く',
        option_b: 'まっすぐ行かないで',
        option_c: 'まっすぐ行って',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ක්‍රියා දෙකක් සම්බන්ධ කිරීමට て-form: まっすぐ行って.'
      },
      {
        order_num: 23,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(23)に入る一番いいものを一つ選んでください。\nカーラ：金曜日の食事、まちあわせの時間はどうしますか。\nやまだ：６時はどうですか。\nカーラ：すみません、(23)＿＿＿＿。。。６時半でもいいですか。',
        image_url: null,
        audio_url: null,
        option_a: '6時はだいじょうぶです',
        option_b: '6時はいいです',
        option_c: '6時はちょっと',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'යෝජනාවක් ආචාරශීලීව ප්‍රතික්ෂේප කර වෙනත් වේලාවක් ඉල්ලීමට 「〜はちょっと」භාවිතා වේ.'
      },
      {
        order_num: 24,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(24)に入る一番いいものを一つ選んでください。\nやまだ：ええ、いいですよ。じゃ、６時半にレストランの入り口で(24)＿＿＿＿。',
        image_url: null,
        audio_url: null,
        option_a: 'あいましょう',
        option_b: 'あいます',
        option_c: 'あいません',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'එකට හමුවෙමු යැයි යෝජනා කිරීමට 「〜ましょう」(あいましょう) භාවිතා වේ.'
      },
      {
        order_num: 25,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(25)に入る一番いいものを一つ選んでください。\nカーラ：ああ、服はジーンズでもいいですか。\nやまだ：ええ、(25)＿＿＿＿。',
        image_url: null,
        audio_url: null,
        option_a: 'たいへんです',
        option_b: 'わるいです',
        option_c: 'だいじょうぶです',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'ජීන්ස් ඇඳීම ගැටලුවක් නැති බව පැවසීමට 「だいじょうぶです」භාවිතා වේ.'
      },
      {
        order_num: 26,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '電話の会話を読んで、(26)に入る一番いいものを一つ選んでください。\nA：(26)＿＿＿＿、田中さんですか。\nB：はい、ああ、カーラさん。',
        image_url: '/uploads/images/jft14/jft14_img_19.jpg',
        audio_url: null,
        option_a: 'もうしもうし',
        option_b: 'もうしわけもし',
        option_c: 'もしもし',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'දුරකථනයට පිළිතුරු දීමේදී හෝ ඇමතීමේදී 「もしもし」(හෙලෝ) භාවිතා කරයි.'
      },
      {
        order_num: 27,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '電話の会話を読んで、(27)に入る一番いいものを一つ選んでください。\nA：すみません。15分ぐらいおくれます。ちょっと(27)＿＿＿＿。\nB：だいじょうぶですか。じゃ、またあとで。',
        image_url: '/uploads/images/jft14/jft14_img_19.jpg',
        audio_url: null,
        option_a: '道にわたります',
        option_b: '道にまよって',
        option_c: '道にいます',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'මග මුලාවීම හේතුවක් ලෙස දැක්වීමට て-form: 「道にまよって」(පාර අතරමං වී).'
      },
      {
        order_num: 28,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(28)に入る一番いいものを一つ選んでください。\nA：キムさん、もうびじゅつかんに行きましたか。\nB：はい、(28)＿＿＿＿。',
        image_url: null,
        audio_url: null,
        option_a: '行きません',
        option_b: '行きました',
        option_c: '行きます',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: '「はい」සමග අතීත ප්‍රකාශය: 「行きました」(ගියා).'
      },
      {
        order_num: 29,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(29)に入る一番いいものを一つ選んでください。\nA：どうでしたか。\nB：山の絵がとても(29)＿＿＿＿。',
        image_url: null,
        audio_url: null,
        option_a: 'よくないです',
        option_b: 'よくなかったです',
        option_c: 'よかったです',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'අතීත අත්දැකීමක් හොඳ බව පැවසීමට 「よかったです」(හොඳයි / විශිෂ්ටයි).'
      },
      {
        order_num: 30,
        section_name: 'Section 2: Conversation & Grammar (会話・文法)',
        question_text: '会話を読んで、(30)に入る一番いいものを一つ選んでください。\nA：そうですか。ホセさんはもう行きましたか。\nC：いいえ、(30)＿＿＿＿。私も行ってみたいです。',
        image_url: null,
        audio_url: null,
        option_a: 'まだです',
        option_b: 'もうです',
        option_c: 'いいです',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'තවම සිදුවී නොමැති බව පැවසීමට 「いいえ、まだです」(නැත, තවම නැත).'
      },

      // ================= SECTION 3: Listening Comprehension (聴解 - Choukai - Q31 to Q45) =================
      {
        order_num: 31,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、質問に答えてください。\nエドワードさんはだれですか。',
        image_url: '/uploads/images/jft14/jft14_img_7.jpg',
        audio_url: '/uploads/audio/jft14_q31.mp3',
        option_a: 'ひしょ',
        option_b: 'じむのスタッフ',
        option_c: 'しゃちょう',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'සංවාදයේදී එඩ්වර්ඩ් මහතා කාර්යාල කාර්ය මණ්ඩලයේ (じむのスタッフ) අයෙකු ලෙස හඳුන්වා දෙයි.'
      },
      {
        order_num: 32,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、質問に答えてください。\nナターリヤさんはだれですか。',
        image_url: '/uploads/images/jft14/jft14_img_8.jpg',
        audio_url: '/uploads/audio/jft14_q32.mp3',
        option_a: 'ひしょ',
        option_b: 'しゃちょう',
        option_c: 'うけつけの人',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'නටාලියා මෙනවිය ලේකම්වරිය (ひしょ) වේ.'
      },
      {
        order_num: 33,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、質問に答えてください。\nハリードさんはだれですか。',
        image_url: '/uploads/images/jft14/jft14_img_10.jpg',
        audio_url: '/uploads/audio/jft14_q33.mp3',
        option_a: 'しゃちょう',
        option_b: 'じむのスタッフ',
        option_c: 'ドライバー',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'හලීඩ් මහතා රියදුරු (ドライバー) වේ.'
      },
      {
        order_num: 34,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、正しい絵（a, b, c, d）を選んでください。',
        image_url: '/uploads/images/jft14/jft14_img_16.jpg',
        audio_url: '/uploads/audio/jft14_q34.mp3',
        option_a: 'a (パソコン)',
        option_b: 'b (ファクス)',
        option_c: 'c (コピー機)',
        option_d: 'd (電話)',
        correct_option: 'A',
        marks: 5,
        explanation: 'සංවාදයේ සඳහන් උපකරණය පරිගණකය (a - パソコン) වේ.'
      },
      {
        order_num: 35,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、正しい絵（a, b, c, d）を選んでください。',
        image_url: '/uploads/images/jft14/jft14_img_16.jpg',
        audio_url: '/uploads/audio/jft14_q35.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c',
        option_d: 'd',
        correct_option: 'B',
        marks: 5,
        explanation: 'සංවාදයේ සඳහන් වන්නේ b (ෆැක්ස් යන්ත්‍රය) වේ.'
      },
      {
        order_num: 36,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、正しい絵（a, b, c, d）を選んでください。',
        image_url: '/uploads/images/jft14/jft14_img_16.jpg',
        audio_url: '/uploads/audio/jft14_q36.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c',
        option_d: 'd',
        correct_option: 'C',
        marks: 5,
        explanation: 'සංවාදයේ සඳහන් වන්නේ c (ෆොටෝකොපි යන්ත්‍රය) වේ.'
      },
      {
        order_num: 37,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、正しい絵（a, b, c, d）を選んでください。',
        image_url: '/uploads/images/jft14/jft14_img_16.jpg',
        audio_url: '/uploads/audio/jft14_q37.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c',
        option_d: 'd',
        correct_option: 'D',
        marks: 5,
        explanation: 'සංවාදයේ සඳහන් වන්නේ d (දුරකථනය) වේ.'
      },
      {
        order_num: 38,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、まりさんの正しいイラスト（a, b, c, d）を選びなさい。',
        image_url: '/uploads/images/jft14/jft14_img_9.jpg',
        audio_url: '/uploads/audio/jft14_q38.mp3',
        option_a: 'a (あたま)',
        option_b: 'b (かた)',
        option_c: 'c (こし)',
        option_d: 'd (くび)',
        correct_option: 'A',
        marks: 5,
        explanation: 'මාරිගේ හිස (あたま - a) වේදනා දෙන බව පවසයි.'
      },
      {
        order_num: 39,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、のださんの正しいイラスト（a, b, c, d）を選びなさい。',
        image_url: '/uploads/images/jft14/jft14_img_11.jpg',
        audio_url: '/uploads/audio/jft14_q38.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c',
        option_d: 'd',
        correct_option: 'C',
        marks: 5,
        explanation: 'නොඩා මහතාගේ ඉණ (こし - c) රිදෙන බව සඳහන් වේ.'
      },
      {
        order_num: 40,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、たなかさんの正しいイラスト（a, b, c, d）を選びなさい。',
        image_url: '/uploads/images/jft14/jft14_img_12.jpg',
        audio_url: '/uploads/audio/jft14_q38.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c',
        option_d: 'd',
        correct_option: 'B',
        marks: 5,
        explanation: 'තනකා මහතාගේ උරහිස (かた - b) සම්බන්ධ වේ.'
      },
      {
        order_num: 41,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、正しい絵（a, b, c）を選びなさい。',
        image_url: '/uploads/images/jft14/jft14_img_13.jpg',
        audio_url: '/uploads/audio/jft14_q41.mp3',
        option_a: 'a (おなかが痛い)',
        option_b: 'b (ねられません)',
        option_c: 'c (つかれています)',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'බඩේ අමාරුවක් (おなかが痛い - a) ඇති බව පවසයි.'
      },
      {
        order_num: 42,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、正しい絵（a, b, c）を選びなさい。',
        image_url: '/uploads/images/jft14/jft14_img_14.jpg',
        audio_url: '/uploads/audio/jft14_q42.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'නින්ද නොයන බව (ねられません - b) පවසයි.'
      },
      {
        order_num: 43,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、正しい絵（a, b, c）を選びなさい。',
        image_url: '/uploads/images/jft14/jft14_img_15.jpg',
        audio_url: '/uploads/audio/jft14_q43.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'වෙහෙසට පත්ව ඇති බව (つかれています - c) සඳහන් කරයි.'
      },
      {
        order_num: 44,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて、正しい絵を選びなさい。',
        image_url: '/uploads/images/jft14/jft14_img_17.jpg',
        audio_url: '/uploads/audio/jft14_q44_45.mp3',
        option_a: 'a',
        option_b: 'b',
        option_c: 'c',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'නෑම / ස්නානය කිරීම (お風呂に入る - b) සුදුසු බව පවසයි.'
      },
      {
        order_num: 45,
        section_name: 'Section 3: Listening Comprehension (聴解 - Choukai)',
        question_text: '音声を聞いて質問に答えてください。\nつかれているとき何をしたほうがいいですか。',
        image_url: null,
        audio_url: '/uploads/audio/jft14_q44_45.mp3',
        option_a: '薬をのむ',
        option_b: 'お風呂に入る',
        option_c: 'おんがくを聞く',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'වෙහෙස වූ විට උණු වතුරෙන් ස්නානය කිරීම (お風呂に入る) වඩාත් සුදුසු බව උපදෙස් දෙයි.'
      },

      // ================= SECTION 4: Reading Comprehension (読解 - Dokkai - Q46 to Q60) =================
      {
        order_num: 46,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: 'メッセージを読んで質問に答えてください。\nなぜ彼女は遅れるのですか。',
        image_url: '/uploads/images/jft14/jft14_img_18.jpg',
        audio_url: null,
        option_a: 'じこがあったので',
        option_b: 'じゅうたいので',
        option_c: '道にまよいたから',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'පණිවිඩයේ 「じゅうたいです」(මාර්ග තදබදයකි) ලෙස පැහැදිලිව දක්වා ඇත.'
      },
      {
        order_num: 47,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '案内を見て答えてください。\nダンスを見たい人たちは何時にステージの前に行ったほうがいいですか。',
        image_url: '/uploads/images/jft14/jft14_img_6.jpg',
        audio_url: null,
        option_a: '10時',
        option_b: '11時',
        option_c: '2時',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: 'වේදිකා වැඩසටහනේ 「10:00〜10:30 タイのダンス」ලෙස සඳහන් වේ.'
      },
      {
        order_num: 48,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '案内を見て答えてください。\nマレーシア料理はどこにありますか。',
        image_url: '/uploads/images/jft14/jft14_img_6.jpg',
        audio_url: null,
        option_a: '2',
        option_b: '3',
        option_c: '4',
        option_d: '5',
        correct_option: 'D',
        marks: 5,
        explanation: 'ලැයිස්තුවේ 5 වන කුටිය 「マレーシア料理」ලෙස සටහන් කර ඇත.'
      },
      {
        order_num: 49,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '案内を見て答えてください。\n木に作ったにんぎょうを買いたいです。どこにいきますか。',
        image_url: '/uploads/images/jft14/jft14_img_6.jpg',
        audio_url: null,
        option_a: '6',
        option_b: '7',
        option_c: '8',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: '8 වන කුටිය 「フィリピン民芸品・アクセサリー」(පිලිපීන සාම්ප්‍රදායික අත්කම් සහ බෝනික්කන්) වේ.'
      },
      {
        order_num: 50,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '案内を見て答えてください。\n日本語を学びたいです。どこへ行きますか。',
        image_url: '/uploads/images/jft14/jft14_img_6.jpg',
        audio_url: null,
        option_a: '7のストール',
        option_b: '2時にステージの前',
        option_c: '10時にステージの前',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'වේදිකාවේ 「14:00〜14:30 (දවල් 2ට) 日本語ミニレッスン」පැවැත්වේ.'
      },
      {
        order_num: 51,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '説明を読んで、合う写真を選んでください。\n「からくて、おいしいです。色は少し赤いです。きゅうりなどの野菜の食べ物です。韓国の食べ物です。日本でとても人気があります。」',
        image_url: '/uploads/images/jft14/jft14_img_20.jpg',
        audio_url: null,
        option_a: 'トマト',
        option_b: 'さしみ',
        option_c: 'キムチ',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'කොරියානු සැර කෑමක් වන කිම්චි (キムチ) විස්තර කරයි.'
      },
      {
        order_num: 52,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、この人はどんなきもちでしたか。\n私がはじめてマリオさんに会った時。',
        image_url: null,
        audio_url: null,
        option_a: 'A: 何も話したくないと思っていました。',
        option_b: 'B: 何か話したいと思っていました。',
        option_c: 'C: グッドモーニングと言いれんしゅうをしましたが、朝ではなかったので困りました。',
        option_d: 'D: いっしょにかいものに行きたいと思っていました。',
        correct_option: 'B',
        marks: 5,
        explanation: '「私はその人と友達になりたいと思いました」(මම ඔහු සමග කතාබහ කර මිතුරු වීමට සිතුවෙමි).'
      },
      {
        order_num: 53,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで、この人はどんなきもちでしたか。\n私が夜マリオさんに会った時。',
        image_url: null,
        audio_url: null,
        option_a: 'A: 何も話したくないと思っていました。',
        option_b: 'B: 何か話したいと思っていました。',
        option_c: 'C: グッドモーニングと言いれんしゅうをしましたが、朝ではなかったので困りました。',
        option_d: 'D: いっしょにかいものに行きたいと思っていました。',
        correct_option: 'C',
        marks: 5,
        explanation: 'උදෑසන නොවන නිසා "Good Morning" කීමට පුරුදු වී සිටි බැවින් කුමක් කිව යුතු දැයි නොදැන සිටියේය.'
      },
      {
        order_num: 54,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章を読んで答えてください。\nこの人がどうして小さい声で「グッドモーニング」と言いましたか。',
        image_url: null,
        audio_url: null,
        option_a: 'アパートがしずかだったからです',
        option_b: 'かいものに行きたくなかったからです',
        option_c: '外国の人がなんと言うかしんぱいだったからです',
        option_d: '',
        correct_option: 'C',
        marks: 5,
        explanation: 'විදේශිකයා කුමක් පවසනු ඇත්දැයි බියෙන් හා චකිතයෙන් සිටි නිසාය.'
      },
      {
        order_num: 55,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '手紙を読んで、内容が正しければ〇、ちがっていれば×を選んでください。\nかずこさんは私のペンフレンドです。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'පෑන මිතුරා වන්නේ සුසුකි මහතාය (かずこさんは私の友達).'
      },
      {
        order_num: 56,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '手紙を読んで、内容が正しければ〇、ちがっていれば×を選んでください。\nかずこさんと私のペンフレンドは高校3年生です。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ලියුම්කරු සහ කසුකෝ 1 වන වසරේ වන අතර, සුසුකි පමණක් 3 වන වසරේ වේ.'
      },
      {
        order_num: 57,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '手紙を読んで、内容が正しければ〇、ちがっていれば×を選んでください。\n私の趣味はピアノとテニスです。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'කසුකෝගේ විනෝදාංශය පියානෝ වන අතර, මගේ විනෝදාංශය ටෙනිස් වේ.'
      },
      {
        order_num: 58,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '手紙を読んで、内容が正しければ〇、ちがっていれば×を選んでください。\nすずきさんは手紙に写真がほしいと書きました。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'A',
        marks: 5,
        explanation: '「あなたの写真を送ってください」(ඔබේ ඡායාරූපයක් එවන්න) යැයි ලියා තිබුණි.'
      },
      {
        order_num: 59,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '手紙を読んで、内容が正しければ〇、ちがっていれば×を選んでください。\n私たちは東京でペンフレンドを会いました。',
        image_url: null,
        audio_url: null,
        option_a: '〇 (正しい)',
        option_b: '× (まちがい)',
        option_c: '',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'ඔවුන් කිසිදා ටෝකියෝවේදී පෞද්ගලිකව හමුවී නොමැත.'
      },
      {
        order_num: 60,
        section_name: 'Section 4: Reading Comprehension (読解 - Dokkai)',
        question_text: '文章の [ ] の中に入る一番いいものを選びなさい。\n「私たちはへんじを出せませんでした。[　　]」',
        image_url: null,
        audio_url: null,
        option_a: 'そして、二人の写真を送りました',
        option_b: '写真も送りませんでした。',
        option_c: '「東京で会いましょう。」と書きました。',
        option_d: '',
        correct_option: 'B',
        marks: 5,
        explanation: 'පිළිතුරු නොයැවූ බැවින් ඡායාරූපයක්ද යැවීමට නොහැකි විය (写真も送りませんでした).'
      }
    ];

    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, section_name, question_text, question_type,
          image_url, audio_url,
          option_a, option_b, option_c, option_d,
          correct_option, marks, explanation, order_num
        ) VALUES (?, ?, ?, 'multiple_choice', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId, q.section_name, q.question_text,
        q.image_url, q.audio_url,
        q.option_a, q.option_b, q.option_c, q.option_d,
        q.correct_option, q.marks, q.explanation, q.order_num
      ]);
    }

    console.log(`🎉 SUCCESS: Seeded ${questions.length} questions for JFT Model Paper 14 (Exam ID: ${examId})`);
    return { success: true, examId, count: questions.length };
  } catch (err) {
    console.error('Error seeding JFT Model Paper 14:', err);
    throw err;
  }
}

module.exports = { seedJftModelPaper14 };
