const { query } = require('../config/database');

async function seedJftModelPaper16() {
  console.log('Seeding JFT-Basic Official Model Paper 16 (60 Questions, Pass 200/250)...');

  try {
    let exam = await query.get("SELECT * FROM exams WHERE id = 155 OR title LIKE '%Model Paper 16%'");
    let examId = 155;

    if (exam) {
      examId = exam.id;
      const countRes = await query.get("SELECT COUNT(*) as count FROM questions WHERE exam_id = ?", [examId]);
      if (countRes && countRes.count >= 60) {
        await query.run('UPDATE exams SET duration_minutes = 60, passing_score = 200, is_active = 1 WHERE id = ?', [examId]);
        await query.run('UPDATE questions SET marks = 1 WHERE exam_id = ? AND order_num >= 1 AND order_num <= 5', [examId]);
        await query.run('UPDATE questions SET marks = 2 WHERE exam_id = ? AND order_num >= 6 AND order_num <= 15', [examId]);
        await query.run('UPDATE questions SET marks = 5 WHERE exam_id = ? AND order_num >= 16 AND order_num <= 60', [examId]);
        return;
      }
      console.log(`Found existing Exam ID: ${examId}, resetting questions...`);
      await query.run('DELETE FROM questions WHERE exam_id = ?', [examId]);
      await query.run(`
        UPDATE exams 
        SET course_id = 1,
            title = 'JFT-Basic Official Model Paper 16 (60 Minutes)',
            description = 'Official JFT-Basic Prometric Computer-Based Examination Paper 16 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Listening Audio Tracks and Sinhala Explanations)',
            duration_minutes = 60,
            passing_score = 200,
            is_active = 1
        WHERE id = ?
      `, [examId]);
    } else {
      const res = await query.run(`
        INSERT INTO exams (id, course_id, title, description, duration_minutes, passing_score, is_active)
        VALUES (
          155,
          1,
          'JFT-Basic Official Model Paper 16 (60 Minutes)',
          'Official JFT-Basic Prometric Computer-Based Examination Paper 16 (Full 60 Questions, 250 Total Marks, 200 Passing Marks, Complete Listening Audio Tracks and Sinhala Explanations)',
          60,
          200,
          1
        )
      `);
      examId = res.id;
      console.log(`Created new Exam ID: ${examId}`);
    }

    const questions = [
  {
    "order_num": 1,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n飛行機が発着する場所は何ですか。",
    "image_url": "/images/jft_paper16/p16_page_01_img_1.png",
    "audio_url": null,
    "option_a": "ひこうき",
    "option_b": "くうこう",
    "option_c": "駅",
    "option_d": "",
    "correct_option": "B",
    "marks": 1,
    "explanation": "පින්තූරයේ දැක්වෙන්නේ ගුවන් තොටුපළකි (くうこう - 空港 - Kuukou)."
  },
  {
    "order_num": 2,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n電車が発着する場所は何ですか。",
    "image_url": "/images/jft_paper16/p16_page_01_img_2.png",
    "audio_url": null,
    "option_a": "くうこう",
    "option_b": "ひこうき",
    "option_c": "駅",
    "option_d": "",
    "correct_option": "C",
    "marks": 1,
    "explanation": "පින්තූරයේ දැක්වෙන්නේ දුම්රිය ස්ථානයකි (駅 - えき - Eki)."
  },
  {
    "order_num": 3,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\nバスを待つ場所は何ですか。",
    "image_url": "/images/jft_paper16/p16_page_02_img_1.png",
    "audio_url": null,
    "option_a": "バス",
    "option_b": "バスてい",
    "option_c": "駅",
    "option_d": "",
    "correct_option": "B",
    "marks": 1,
    "explanation": "බස් නැවතුම්පොළ හඳුන්වන්නේ \"バスてい\" (バス停 - Basutei) යනුවෙනි."
  },
  {
    "order_num": 4,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n病気やけがのときに診察を受ける建物は何ですか。",
    "image_url": "/images/jft_paper16/p16_page_02_img_2.png",
    "audio_url": null,
    "option_a": "病気",
    "option_b": "病院",
    "option_c": "ホテル",
    "option_d": "",
    "correct_option": "B",
    "marks": 1,
    "explanation": "රෝහල හඳුන්වන්නේ \"病院\" (びょういん - Byouin) යනුවෙනි."
  },
  {
    "order_num": 5,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【イラストを見て正しい言葉を選びなさい】\n子どもたちが遊具で遊んでいる緑の場所は何ですか。",
    "image_url": "/images/jft_paper16/p16_page_03_img_1.png",
    "audio_url": null,
    "option_a": "学校",
    "option_b": "庭",
    "option_c": "公園",
    "option_d": "",
    "correct_option": "C",
    "marks": 1,
    "explanation": "ළමුන් සෙල්ලම් කරන උද්‍යානය හඳුන්වන්නේ \"公園\" (こうえん - Kouen) යනුවෙනි."
  },
  {
    "order_num": 6,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【文を読んで空欄に最も適当なものを選びなさい】\n友達（　）やくそく（　）しました。",
    "image_url": null,
    "audio_url": null,
    "option_a": "が・が",
    "option_b": "と・と",
    "option_c": "と・を",
    "option_d": "",
    "correct_option": "C",
    "marks": 2,
    "explanation": "මිතුරෙකු සමඟ පොරොන්දු වීම දැක්වීමට \"友達と約束をしました\" (と・を) යෙදේ."
  },
  {
    "order_num": 7,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【文を読んで空欄に最も適当なものを選びなさい】\nこの料理は味（　）うすいですから、もっとしお（　）入れてください。",
    "image_url": null,
    "audio_url": null,
    "option_a": "が・に",
    "option_b": "が・が",
    "option_c": "が・を",
    "option_d": "",
    "correct_option": "C",
    "marks": 2,
    "explanation": "රස ලා බව දැක්වීමට \"味がうすい\", ලුණු දැමීමට \"しおを入れてください\" (が・を) යෙදේ."
  },
  {
    "order_num": 8,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【文を読んで空欄に最も適当なものを選びなさい】\nあの歌手はとても人気（　）あります。",
    "image_url": null,
    "audio_url": null,
    "option_a": "に",
    "option_b": "が",
    "option_c": "を",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "ජනප්‍රියතාවය ඇති බව දැක්වීමට \"人気がある\" (が) යෙදේ."
  },
  {
    "order_num": 9,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【文を読んで空欄に最も適当なものを選びなさい】\n子供は公園の中（　）走りまわっています。",
    "image_url": null,
    "audio_url": null,
    "option_a": "に",
    "option_b": "を",
    "option_c": "が",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "යම් ප්‍රදේශයක් තුළ එහා මෙහා දිවීම/ඇවිදීම දැක්වීමට මාර්ගය/ප්‍රදේශය අගට \"を\" නිපාතය යෙදේ (中を走り回る)."
  },
  {
    "order_num": 10,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【文を読んで空欄に最も適当なものを選びなさい】\n母（　）作ったケーキ（　）これです。",
    "image_url": null,
    "audio_url": null,
    "option_a": "の・を",
    "option_b": "が・は",
    "option_c": "の・も",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "විශේෂණ වාක්‍ය ඛණ්ඩයේ කර්තෘ \"母が\" සහ ප්‍රධාන මාතෘකාව \"ケーキは\" (が・は) වේ."
  },
  {
    "order_num": 11,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【下線の漢字の正しいひらがなを選んでください】\n私は<u>西洋</u>の文学が好きです。",
    "image_url": null,
    "audio_url": null,
    "option_a": "せいゆう",
    "option_b": "とうよう",
    "option_c": "せいよう",
    "option_d": "",
    "correct_option": "C",
    "marks": 2,
    "explanation": "「西洋」හි නිවැරදි කියවීම \"せいよう\" (බටහිර රටවල්) වේ."
  },
  {
    "order_num": 12,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【下線の漢字の正しいひらがなを選んでください】\n妹の(12)<u>代わり</u>に(13)手紙を書きました。",
    "image_url": null,
    "audio_url": null,
    "option_a": "わかり",
    "option_b": "かわり",
    "option_c": "まわり",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "「代わり」හි නිවැරදි කියවීම \"かわり\" (වෙනුවට) වේ."
  },
  {
    "order_num": 13,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【下線の漢字の正しいひらがなを選んでください】\n妹の(12)代わりに(13)<u>手紙</u>を書きました。",
    "image_url": null,
    "audio_url": null,
    "option_a": "てがみ",
    "option_b": "はがき",
    "option_c": "ふうとう",
    "option_d": "",
    "correct_option": "A",
    "marks": 2,
    "explanation": "「手紙」හි නිවැරදි කියවීම \"てがみ\" (ලිපිය) වේ."
  },
  {
    "order_num": 14,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【下線の漢字の正しいひらがなを選んでください】\nもう少し(14)<u>低い</u>いすを(15)貸してください。",
    "image_url": null,
    "audio_url": null,
    "option_a": "たかい",
    "option_b": "ひくい",
    "option_c": "ながい",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "「低い」හි නිවැරදි කියවීම \"ひくい\" (මිටි / පහත්) වේ."
  },
  {
    "order_num": 15,
    "section_name": "Section 1: Script and Vocabulary (文字・語彙 - Moji & Goi)",
    "question_text": "【下線の漢字の正しいひらがなを選んでください】\nもう少し(14)低いいすを(15)<u>貸して</u>ください。",
    "image_url": null,
    "audio_url": null,
    "option_a": "かりて",
    "option_b": "かして",
    "option_c": "かいて",
    "option_d": "",
    "correct_option": "B",
    "marks": 2,
    "explanation": "「貸して」හි නිවැරදි කියවීම \"かして\" (ණයට / භාවිතයට දෙන්න) වේ."
  },
  {
    "order_num": 16,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【文と同じ意味の文を選びなさい】\nてつだいましょうか。",
    "image_url": null,
    "audio_url": null,
    "option_a": "てつだえますか",
    "option_b": "てつだってあげます",
    "option_c": "てつだってください",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "\"てつだいましょうか\" (මම උදව් කරන්නද?) යනු තමා අනෙකාට උදව් කිරීමට ඉදිරිපත් වීමකි (\"てつだってあげます\" = මම උදව් කර දෙන්නම්)."
  },
  {
    "order_num": 17,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【文と同じ意味の文を選びなさい】\nブラウンさんは留学生です。ドイツから来ました。",
    "image_url": null,
    "audio_url": null,
    "option_a": "ブラウンさんはドイツからりょこうに来ました。",
    "option_b": "ブラウンさんはドイツから働きに来ました。",
    "option_c": "ブラウンさんはドイツから勉強に来ました。",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "留学生 (විදේශීය ශිෂ්‍යයා) යනු ඉගෙනුම සඳහා පැමිණි අයෙකි (勉強に来ました)."
  },
  {
    "order_num": 18,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【文と同じ意味の文を選びなさい】\n田中さんは35さいです。どくしんです。",
    "image_url": null,
    "audio_url": null,
    "option_a": "田中さんは35さいです。けっこんしていません。",
    "option_b": "田中さんは35さいです。しごとをしていません。",
    "option_c": "田中さんは35さいです。子供がいません。",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "どくしん (独身 - අවිවාහක) යනු විවාහ වී නොමැති බවයි (けっこんしていません)."
  },
  {
    "order_num": 19,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【文と同じ意味の文を選びなさい】\nこんやのパーティーは何時からですか。",
    "image_url": null,
    "audio_url": null,
    "option_a": "こんどのパーティーは何時からですか。",
    "option_b": "今日の夜のパーティーは何時からですか。",
    "option_c": "今週のパーティーは何時からですか。",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "こんや (今夜) යනු අද රාත්‍රියයි (今日の夜)."
  },
  {
    "order_num": 20,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【文と同じ意味の文を選びなさい】\nひまなとき、うちでおんがくを聞きます。",
    "image_url": null,
    "audio_url": null,
    "option_a": "いそがしくないとき、うちでおんがくをききます。",
    "option_b": "うるさくないとき、うちでおんがくをききます。",
    "option_c": "たのしくないとき、うちでおんがくをききます。",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "ひまなとき (විවේක වේලාවට) යනු කාර්යබහුල නොවන අවස්ථාවයි (いそがしくないとき)."
  },
  {
    "order_num": 21,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【対話の空欄に最も適当なものを選びなさい】\nA : 明日、どこ（　）出かけますか。\nB : いいえ、どこも行きません。",
    "image_url": null,
    "audio_url": null,
    "option_a": "かへ",
    "option_b": "も",
    "option_c": "が",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "කිසියම් ස්ථානයකට යනවාදැයි විමසීමට \"どこかへ\" යෙදේ."
  },
  {
    "order_num": 22,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【対話の空欄に最も適当なものを選びなさい】\nA : 明日(22)....................といいなあ。\nB : どうして。\nA : 明日(23)....................、パパといっしょにゆうえんちに行く予定なんだ。",
    "image_url": null,
    "audio_url": null,
    "option_a": "晴れる",
    "option_b": "晴れます",
    "option_c": "晴れました",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "පැතුමක් ප්‍රකාශ කරන \"〜といいなあ\" සමඟ ක්‍රියාපදයේ සාමාන්‍ය වර්තමාන කාලය (Dictionary form) \"晴れる\" යෙදේ."
  },
  {
    "order_num": 23,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【対話の空欄に最も適当なものを選びなさい】\nA : 明日(23)....................、パパといっしょにゆうえんちに行く予定なんだ。",
    "image_url": null,
    "audio_url": null,
    "option_a": "晴れました",
    "option_b": "晴れたら",
    "option_c": "晴れたとき",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "කොන්දේසියක් (පෑවුවහොත්) දක්වන \"〜たら\" ආකෘතිය \"晴れたら\" නිවැරදි වේ."
  },
  {
    "order_num": 24,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【対話の空欄に最も適当なものを選びなさい】\nA : 富士山に(24)....................ことがありますか。\nB : いいえ、ありません。ぜひ(25)....................みたいです。",
    "image_url": null,
    "audio_url": null,
    "option_a": "登った",
    "option_b": "登りました",
    "option_c": "登る",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "අත්දැකීම් විමසන \"〜たことがありますか\" අනුව \"登ったことがありますか\" වේ."
  },
  {
    "order_num": 25,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【対話の空欄に最も適当なものを選びなさい】\nB : いいえ、ありません。ぜひ(25)....................みたいです。",
    "image_url": null,
    "audio_url": null,
    "option_a": "登ります",
    "option_b": "登った",
    "option_c": "登って",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "උත්සාහ කර බැලීමට කැමැත්ත පළ කරන \"〜てみたい\" අනුව \"登ってみたい\" (නැග බැලීමට කැමතියි) වේ."
  },
  {
    "order_num": 26,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【対話の空欄に最も適当なものを選びなさい】\nA : 何を飲むか、決めましたか。\nB : 私はビールを....................しました。",
    "image_url": null,
    "audio_url": null,
    "option_a": "飲むに",
    "option_b": "飲みに",
    "option_c": "飲みすぎ",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "තෝරා ගැනීම ප්‍රකාශ කිරීමේදී \"ビールにしました\" හෝ ක්‍රියාවක් ලෙස \"飲みにしました\" (බියර් බීමට තීරණය කළා) යෙදේ."
  },
  {
    "order_num": 27,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【対話の空欄に最も適当なものを選びなさい】\nA : このカメラは以前のより、ずっと使い方が(27)....................ですね。\nB : こんなにかんたんと、みんな使えますね。\nA : そうです。お年よりも、子供も(28)....................よ。",
    "image_url": null,
    "audio_url": null,
    "option_a": "かんたんな",
    "option_b": "かんたん",
    "option_c": "かんたんに",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "විශේෂණ පදය කෙලින්ම \"ですね\" සමඟ සම්බන්ධ වන විට \"かんたんですね\" වේ."
  },
  {
    "order_num": 28,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【対話の空欄に最も適当なものを選びなさい】\nA : そうです。お年よりも、子供も(28)....................よ。",
    "image_url": null,
    "audio_url": null,
    "option_a": "使う",
    "option_b": "使えます",
    "option_c": "使って",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "හැකියාව ප්‍රකාශ කරන විභව රූපය (Potential form) \"使えますよ\" (භාවිතා කළ හැකියි) වේ."
  },
  {
    "order_num": 29,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【対話の空欄に最も適当なものを選びなさい】\n客 : すみません、この服を(29)....................みたいんです。\n店員 : ええ、どうぞ。あちらで(30)....................ください。",
    "image_url": "/images/jft_paper16/p16_page_08_img_1.png",
    "audio_url": null,
    "option_a": "しちゃくする",
    "option_b": "しちゃく",
    "option_c": "しちゃくし",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ඇඳුමක් ඇඳ බැලීමට (Try on) \"しちゃくしてみたい\" (試着) යෙදේ."
  },
  {
    "order_num": 30,
    "section_name": "Section 2: Conversation and Grammar (会話・文法 - Kaiwa & Bunpou)",
    "question_text": "【対話の空欄に最も適当なものを選びなさい】\n店員 : ええ、どうぞ。あちらで(30)....................ください。",
    "image_url": "/images/jft_paper16/p16_page_08_img_1.png",
    "audio_url": null,
    "option_a": "しちゃくして",
    "option_b": "しちゃくし",
    "option_c": "しちゃくに",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "ආචාරශීලී ඉල්ලීමක් කරන \"〜てください\" සමඟ \"しちゃくしてください\" (ඇඳ බලන්න) වේ."
  },
  {
    "order_num": 31,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\n話にあう絵はどれですか。",
    "image_url": "/images/jft_paper16/p16_q31_grid.png",
    "audio_url": "/audio/jft_paper16/jft16_q31.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "d",
    "correct_option": "A",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩයේ විස්තරය ගැලපෙන නිවැරදි රූපය a වේ."
  },
  {
    "order_num": 32,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\n話にあう絵はどれですか。",
    "image_url": "/images/jft_paper16/p16_page_10_img_2.png",
    "audio_url": "/audio/jft_paper16/jft16_q32.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "d",
    "correct_option": "A",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩයේ විස්තරය ගැලපෙන නිවැරදි රූපය a වේ."
  },
  {
    "order_num": 33,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\n話にあう絵はどれですか。",
    "image_url": "/images/jft_paper16/p16_page_12_img_1.png",
    "audio_url": "/audio/jft_paper16/jft16_q33.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "d",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩයේ විස්තරය ගැලපෙන නිවැරදි රූපය b වේ."
  },
  {
    "order_num": 34,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\n話にあう絵はどれですか。",
    "image_url": "/images/jft_paper16/p16_page_13_img_3.png",
    "audio_url": "/audio/jft_paper16/jft16_q34.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "d",
    "correct_option": "A",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩයේ විස්තරය ගැලපෙන නිවැරදි රූපය a වේ."
  },
  {
    "order_num": 35,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\n話にあう絵はどれですか。",
    "image_url": "/images/jft_paper16/p16_situations_abcd.png",
    "audio_url": "/audio/jft_paper16/jft16_q35_q36.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "d",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩයේ විස්තරය ගැලපෙන නිවැරදි රූපය c වේ."
  },
  {
    "order_num": 36,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\nけっこんのおいわいのために何をしますか。",
    "image_url": "/images/jft_paper16/p16_actions_efgh.png",
    "audio_url": "/audio/jft_paper16/jft16_q35_q36.mp3",
    "option_a": "e : 花をプレゼントします",
    "option_b": "f : 時計をプレゼントします",
    "option_c": "g : ネクタイをプレゼントします",
    "option_d": "h : 食事に招待します",
    "correct_option": "A",
    "marks": 5,
    "explanation": "විවාහ උත්සවය වෙනුවෙන් මල් කළඹක් තෑගි කරයි (e)."
  },
  {
    "order_num": 37,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\n話にあう絵はどれですか。",
    "image_url": "/images/jft_paper16/p16_situations_abcd.png",
    "audio_url": "/audio/jft_paper16/jft16_q37_q38.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "d",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩය අනුව ගැලපෙන නිවැරදි රූපය b වේ."
  },
  {
    "order_num": 38,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\nカーラさんのひっこしのおいわいに何をしますか。",
    "image_url": "/images/jft_paper16/p16_actions_efgh.png",
    "audio_url": "/audio/jft_paper16/jft16_q37_q38.mp3",
    "option_a": "e : 時計をあげます",
    "option_b": "f : お皿をあげます",
    "option_c": "g : 手伝いに行きます",
    "option_d": "h : パーティーをします",
    "correct_option": "A",
    "marks": 5,
    "explanation": "නව නිවසට යාමේ සුබපැතුමක් ලෙස ඔරලෝසුවක් ලබා දෙයි (e)."
  },
  {
    "order_num": 39,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\n話にあう絵はどれですか。",
    "image_url": "/images/jft_paper16/p16_situations_abcd.png",
    "audio_url": "/audio/jft_paper16/jft16_q39_q40.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "d",
    "correct_option": "A",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩයේ විස්තරය ගැලපෙන නිවැරදි රූපය a වේ."
  },
  {
    "order_num": 40,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\nパクさんのしゅうしょくおいわいに何をしますか。",
    "image_url": "/images/jft_paper16/p16_actions_efgh.png",
    "audio_url": "/audio/jft_paper16/jft16_q39_q40.mp3",
    "option_a": "e : ネクタイをあげます",
    "option_b": "f : かばんをあげます",
    "option_c": "g : 靴をあげます",
    "option_d": "h : 本をあげます",
    "correct_option": "A",
    "marks": 5,
    "explanation": "නව රැකියාවට සුබපැතුමක් ලෙස ටයි පටියක් (ネクタイ) ලබා දෙයි."
  },
  {
    "order_num": 41,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\n話にあう絵はどれですか。",
    "image_url": "/images/jft_paper16/p16_situations_abcd.png",
    "audio_url": "/audio/jft_paper16/jft16_q41_q42.mp3",
    "option_a": "a",
    "option_b": "b",
    "option_c": "c",
    "option_d": "d",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ශ්‍රව්‍ය ඛණ්ඩයේ විස්තරය ගැලපෙන නිවැරදි රූපය c වේ."
  },
  {
    "order_num": 42,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\nキルスティナさんのしゅっさんに何をしますか。",
    "image_url": "/images/jft_paper16/p16_actions_efgh.png",
    "audio_url": "/audio/jft_paper16/jft16_q41_q42.mp3",
    "option_a": "e : 赤ちゃんの服をあげます",
    "option_b": "f : おもちゃをあげます",
    "option_c": "g : お金をあげます",
    "option_d": "h : 写真をとります",
    "correct_option": "A",
    "marks": 5,
    "explanation": "දරුවා ඉපදීම නිමිත්තෙන් බිළිඳු ඇඳුම් (赤ちゃんの服) තෑගි කරයි."
  },
  {
    "order_num": 43,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\nなかむらさんはいつ来ますか。",
    "image_url": "/images/jft_paper16/p16_page_27_img_1.png",
    "audio_url": "/audio/jft_paper16/jft16_q43_q44.mp3",
    "option_a": "18日",
    "option_b": "28日",
    "option_c": "27日",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "නකමුරා මහතා පැමිණෙන්නේ 28 වන දිනයි (28日 - Nijuuhachinichi)."
  },
  {
    "order_num": 44,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\nなかむらさんはどこで働いていますか。",
    "image_url": "/images/jft_paper16/p16_page_27_img_1.png",
    "audio_url": "/audio/jft_paper16/jft16_q43_q44.mp3",
    "option_a": "東京の支社で",
    "option_b": "大阪の支社で",
    "option_c": "東京の本社で",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "නකමුරා මහතා සේවය කරන්නේ ටෝකියෝ ප්‍රධාන කාර්යාලයේය (東京の本社で)."
  },
  {
    "order_num": 45,
    "section_name": "Section 3: Listening Comprehension (聴解 - Choukai)",
    "question_text": "【音声を聴いて答えなさい】\n正しいものはどれですか。",
    "image_url": "/images/jft_paper16/p16_page_27_img_2.png",
    "audio_url": "/audio/jft_paper16/jft16_q45.mp3",
    "option_a": "いしかわさんは21日に来ます",
    "option_b": "いしかわさんは朝9時のひこうきで来ます",
    "option_c": "いしかわさんはシドニー支社で働いています",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "ඉශිකාවා මහතා 21 වන දින පැමිණේ (いしかわさんは21日に来ます)."
  },
  {
    "order_num": 46,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【アランさんの文章を読んで、内容に合っているものに○、ちがっているものに×を答えなさい】\nアランさんは日本人とときどき英語で話します。",
    "image_url": "/images/jft_paper16/p16_page_28_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ඡේදය අනුව ඇලන් ජපාන මිතුරන් හා සාමාන්‍ය වැසියන් සමඟ සැමවිටම ජපන් බසින් කතා කරයි (いつも日本語で話します)."
  },
  {
    "order_num": 47,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【アランさんの文章を読んで、内容に合っているものに○、ちがっているものに×を答えなさい】\nアランさんは日本語がわかりませんから、日本人は英語で話します。",
    "image_url": "/images/jft_paper16/p16_page_28_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ඇලන්ට ජපන් භාෂාව තේරෙන නමුත් ජපන් ජාතිකයන් ඔහුව දුටු පමණින් ඉංග්‍රීසියෙන් කතා කරයි."
  },
  {
    "order_num": 48,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【アランさんの文章を読んで、内容に合っているものに○、ちがっているものに×を答えなさい】\n駅の前で日本人と話した時、女の人は男の人より親切でした。",
    "image_url": "/images/jft_paper16/p16_page_28_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "පිරිමි පුද්ගලයා \"だめ、だめ\" කියා මගහැරියද, කාන්තාව බොහෝ වේලාවක් වැය කර ඉංග්‍රීසියෙන් මග කියාදීමට උත්සාහ කළාය (女の人は男の人より親切でした)."
  },
  {
    "order_num": 49,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【アランさんの文章を読んで、内容に合っているものに○、ちがっているものに×を答えなさい】\nアランさんが図書館へ行った時、図書館は休みでした。",
    "image_url": "/images/jft_paper16/p16_page_28_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "පුස්තකාලය නිවාඩු නොවූ අතර, කාන්තාව කියාදුන් මග ඔස්සේ ගිය විට පුස්තකාලයක් හමු නොවීය (図書館はありませんでした)."
  },
  {
    "order_num": 50,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【アランさんの文章を読んで、内容に合っているものに○、ちがっているものに×を答えなさい】\nアランさんはアメリカ人です。",
    "image_url": "/images/jft_paper16/p16_page_28_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ඇලන් ප්‍රංශ ජාතිකයෙකි (おおさかに住んでいるフランス人です)."
  },
  {
    "order_num": 51,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【アランさんの文章を読んで答えなさい】\nアランさんはどうして「日本人のみなさん、日本語でお願いします」と言いましたか。",
    "image_url": "/images/jft_paper16/p16_page_28_img_1.png",
    "audio_url": null,
    "option_a": "英語がきらいですから",
    "option_b": "日本語を覚えたいですから",
    "option_c": "日本人の英語より日本語のほうがよくわかりますから",
    "option_d": "",
    "correct_option": "C",
    "marks": 5,
    "explanation": "ජපන් ජාතිකයන් කතා කරන අසීරු ඉංග්‍රීසියට වඩා ජපන් බසින් කතා කරන විට ඇලන්ට හොඳින් තේරුම් ගත හැකි බැවිනි."
  },
  {
    "order_num": 52,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【よしこさんの手紙を読んで答えなさい】\nよしこさんが困っていることはどれですか。",
    "image_url": "/images/jft_paper16/p16_page_29_img_1.png",
    "audio_url": null,
    "option_a": "大学の授業が始まったから",
    "option_b": "大学の学費（りょうきん）が高いから",
    "option_c": "地理学の勉強がきらいだから",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "යොෂිකෝ පවසන්නේ විශ්වවිද්‍යාල අධ්‍යයන ගාස්තු ඉතා ඉහළ බැවින් ඇය දැඩි කනස්සල්ලෙන් පසුවන බවයි (大学の学費もとても高いですから心配です)."
  },
  {
    "order_num": 53,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【あきらさんとジョンの会話を読んで答えなさい】\nあきらさんはどんな絵を書きましたか。一番いいものを一つ選びなさい。\n(人: 横を向いている形 / 大: 手足を広げて立っている形 / 立: 地面の上に立っている形)",
    "image_url": "/images/jft_paper16/p16_page_30_img_1.png",
    "audio_url": null,
    "option_a": "1",
    "option_b": "2",
    "option_c": "3",
    "option_d": "4",
    "correct_option": "A",
    "marks": 5,
    "explanation": "සංවාදය අනුව 人 (පැත්ත බලා සිටින මිනිසා), 大 (අත් පා විහිදා සිටින මිනිසා), 立 (පොළොව මත සිටින මිනිසා) නිවැරදිව නිරූපණය වන චිත්‍රය අංක 1 වේ."
  },
  {
    "order_num": 54,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【ドラえもんの文章を読んで、内容に合っているものに○、ちがっているものに×を答えなさい】\nドラえもんは動物です。",
    "image_url": "/images/jft_paper16/p16_page_31_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ඩොරෙමොන් සතෙකු නොව බළල් හැඩැති රොබෝවෙකි (ねこのかたちのロボットです)."
  },
  {
    "order_num": 55,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【ドラえもんの文章を読んで、内容に合っているものに○、ちがっているものに×を答えなさい】\nドラえもんはポケットから便利なものを出します。",
    "image_url": "/images/jft_paper16/p16_page_31_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "ඩොරෙමොන්ගේ මායා සාක්කුවෙන් ප්‍රයෝජනවත් ගැජට් එළියට ගනී (ふしぎなポケットを持っていて、いろいろなものが出せます)."
  },
  {
    "order_num": 56,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【ドラえもんの文章を読んで、内容に合っているものに○、ちがっているものに×を答えなさい】\n空をとびたいとき「タケコプター」に乗ります。",
    "image_url": "/images/jft_paper16/p16_page_31_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ටකෙකොප්ටර් මත නගින්නේ නැත, එය හිස මත සවි කර ගනී (タケコプターをあたまにつけると、じゆうに空をとべます)."
  },
  {
    "order_num": 57,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【ドラえもんの文章を読んで、内容に合っているものに○、ちがっているものに×を答えなさい】\n「どこでもドア」があったらどこでも行けます。",
    "image_url": "/images/jft_paper16/p16_page_31_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "දොර ඇරීමෙන් කැමති ඕනෑම තැනකට ක්ෂණිකව යා හැකිය (このドアを開けると、どこでも行きたいところへ行けます)."
  },
  {
    "order_num": 58,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【電子メールを読んで、内容に合っているものに○、ちがっているものに×を答えなさい】\n田中さんはうちゅうひこうしです。",
    "image_url": "/images/jft_paper16/p16_page_32_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "A",
    "marks": 5,
    "explanation": "තනකා මහතා අභ්‍යවකාශයට ගොස් පැමිණි ගගනගාමියෙකි (ぼくもうちゅうひこうしになりたいんですが)."
  },
  {
    "order_num": 59,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【電子メールを読んで、内容に合っているものに○、ちがっているものに×を答えなさい】\n田中さんはうちゅうへ行って、うちゅうせんの外へでました。",
    "image_url": "/images/jft_paper16/p16_page_32_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ඊමේල් පණිවිඩයේ තනකා අභ්‍යවකාශ යානයෙන් පිටතට පැමිණි බවක් සඳහන් නොවේ."
  },
  {
    "order_num": 60,
    "section_name": "Section 4: Reading Comprehension (読解 - Dokkai)",
    "question_text": "【電子メールを読んで、内容に合っているものに○、ちがっているものに×を答えなさい】\nでんしメールを送った人はうちゅうについてけんきゅうしています。",
    "image_url": "/images/jft_paper16/p16_page_32_img_1.png",
    "audio_url": null,
    "option_a": "〇",
    "option_b": "×",
    "option_c": "",
    "option_d": "",
    "correct_option": "B",
    "marks": 5,
    "explanation": "ඊමේලය එවූ පුද්ගලයා පර්යේෂකයෙකු නොව අනාගතයේ ගගනගාමියෙකු වීමට කැමති ශිෂ්‍යයෙකි (ぼくもうちゅうひこうしになりたいんですが、どんな勉強をしたらいいですか)."
  }
];

    for (const q of questions) {
      await query.run(`
        INSERT INTO questions (
          exam_id, section_name, order_num, question_text, question_type,
          option_a, option_b, option_c, option_d, correct_option, marks, explanation,
          image_url, audio_url
        ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
      `, [
        examId,
        q.section_name,
        q.order_num,
        q.question_text,
        'multiple_choice',
        q.option_a,
        q.option_b,
        q.option_c,
        q.option_d || '',
        q.correct_option,
        q.marks,
        q.explanation,
        q.image_url,
        q.audio_url
      ]);
    }

    console.log(`Successfully seeded ${questions.length} questions for Paper 16 (Exam ${examId})`);
  } catch (err) {
    console.error('Error seeding JFT Paper 16:', err);
  }
}

module.exports = { seedJftModelPaper16 };
